Repository Kong/kubernetes-ingress-controller, pull requests merged in 2020-07, with the labels that each got.

#664 Proposal/Feature add flag --skip-empty-annotation to honor only annotated resources.
  cli/ingress-controller/flags.go
  cli/ingress-controller/main.go
  cli/ingress-controller/main_test.go
  internal/ingress/annotations/annotations.go
  internal/ingress/annotations/annotations_test.go
  internal/ingress/controller/parser/parser_test.go
  internal/ingress/store/fake_store.go
  internal/ingress/store/store.go
Labels: changes requested, trello

#751 Remove support for global KongPlugins
  docs/guides/prometheus-grafana.md
  docs/guides/redis-rate-limiting.md
  docs/guides/using-kongplugin-resource.md
  docs/references/custom-resources.md
  internal/ingress/controller/parser/parser.go
  internal/ingress/controller/parser/parser_test.go
  internal/ingress/store/fake_store_test.go
  internal/ingress/store/store.go
Labels: please review

#768 docs: fix the building part in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: please review

#771 fix: solve the restart caused by kong not starting
  cli/ingress-controller/main.go
Labels: changes requested

#745 Added functions and testcases to handle ingress.kubernetes.io/force-s…
  internal/ingress/annotations/annotations.go
  internal/ingress/annotations/annotations_test.go
  internal/ingress/controller/parser/parser.go
  internal/ingress/controller/parser/parser_test.go
Labels: changes requested
