Repository Kong/kubernetes-ingress-controller, pull requests merged in 2020-11, with the labels that each got.

#928 Udate CONTRIBUTING Golang version
  CONTRIBUTING.md
Labels: docs, pr/please review

#949 Add CI check for untidy go modules
  Makefile
  hack/verify-tidy.sh
Labels: area/ci, pr/please review

#957 chore(deploy) update default worker count to 2
  deploy/manifests/base/kong-ingress-dbless.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  hack/dev/dbless/base/kong.yaml
Labels: pr/please review

#908 Add override support for Knative Services
  internal/ingress/controller/parser/parser_test.go
  internal/ingress/controller/parser/translate.go
Labels: pr/changes requested

#964 Fix invalid tag generation in CI
  .github/workflows/build-test.yaml
Labels: pr/please review

#944 feat(consumer) validate credential secret fields
  internal/ingress/controller/parser/kongstate/consumer.go
  internal/ingress/controller/parser/kongstate/consumer_test.go
Labels: pr/changes requested
