Repository Kong/kubernetes-ingress-controller, pull requests merged in 2020-04, with the labels that each got.

#583 Update the title https redirect
  docs/guides/configuring-https-redirect.md
Labels: changes requested

#591 Add new konghq.com/regex-priority annotation
  internal/ingress/annotations/annotations.go
  internal/ingress/annotations/annotations_test.go
  internal/ingress/controller/parser/parser.go
  internal/ingress/controller/parser/parser_test.go
Labels: changes requested

#555 docs: add guide for jwt and acl plugin use
  docs/guides/README.md
  docs/guides/configure-acl-plugin.md
Labels: changes requested

#578 Restart Ingress status leader election cycle after premature exit
  cli/ingress-controller/main.go
  cli/ingress-controller/main_test.go
  go.mod
  internal/ingress/controller/controller.go
  internal/ingress/election/election.go
  internal/ingress/status/status.go
Labels: please review

#597 Add host_header annotation for Services
  internal/ingress/annotations/annotations.go
  internal/ingress/annotations/annotations_test.go
  internal/ingress/controller/parser/parser.go
  internal/ingress/controller/parser/parser_test.go
Labels: please review

#609 Add methods annotation
  internal/ingress/annotations/annotations.go
  internal/ingress/annotations/annotations_test.go
  internal/ingress/controller/parser/parser.go
  internal/ingress/controller/parser/parser_test.go
Labels: please review

#615 Fix preserve client ip docs: ExternalTrafficPolicy setting
  docs/guides/preserve-client-ip.md
Labels: changes requested

#627 docs: Further adjust guides to new strip_path default
  docs/guides/prometheus-grafana.md
  docs/guides/using-kongingress-resource.md
Labels: docs

#628 Add flags to provide certificate PEM string
  cli/ingress-controller/flag_test.go
  cli/ingress-controller/flags.go
  cli/ingress-controller/main.go
Labels: please review
