Repository Kong/kubernetes-ingress-controller, pull requests merged in 2020-09, with the labels that each got.

#828 fix(controller): remove a no-op sort of ingresses
  internal/ingress/controller/controller.go
Labels: please review

#826 Ingress V1: apiversion negotiation and flags, support in store, parser-k8s decoupling, ingress parsing refactor
  .gitignore
  cli/ingress-controller/flag_test.go
  cli/ingress-controller/flags.go
  cli/ingress-controller/main.go
  cli/ingress-controller/util.go
  cli/ingress-controller/util_test.go
  internal/ingress/controller/controller.go
  internal/ingress/controller/parser/kongstate/kongstate.go
  internal/ingress/controller/parser/kongstate/kongstate_test.go
  internal/ingress/controller/parser/kongstate/route.go
  internal/ingress/controller/parser/kongstate/route_test.go
  internal/ingress/controller/parser/kongstate/util.go
  internal/ingress/controller/parser/parser.go
  internal/ingress/controller/parser/parser_test.go
  internal/ingress/controller/parser/translate.go
  internal/ingress/controller/parser/translate_test.go
  internal/ingress/controller/parser/util/objectmeta.go
  internal/ingress/controller/parser/util/objectmeta_test.go
  internal/ingress/status/status.go
  internal/ingress/status/status_test.go
  internal/ingress/store/fake_store.go
  internal/ingress/store/fake_store_test.go
  internal/ingress/store/store.go
  internal/ingress/utils/ingressapi.go
  internal/ingress/utils/ingressapi_test.go
Labels: please review

#811 Add ingress class docs
  docs/README.md
  docs/concepts/custom-resources.md
  docs/concepts/ingress-classes.md
  docs/deployment/admission-webhook.md
  docs/guides/cert-manager.md
  docs/guides/configure-acl-plugin.md
  docs/guides/configuring-fallback-service.md
  docs/guides/configuring-health-checks.md
  docs/guides/configuring-https-redirect.md
  docs/guides/getting-started.md
  docs/guides/prometheus-grafana.md
  docs/guides/redis-rate-limiting.md
  docs/guides/using-consumer-credential-resource.md
  docs/guides/using-external-service.md
  docs/guides/using-ingress-with-grpc.md
  docs/guides/using-kongclusterplugin-resource.md
  docs/guides/using-kongingress-resource.md
  docs/guides/using-kongplugin-resource.md
  docs/guides/using-mtls-auth-plugin.md
  docs/guides/using-oidc-plugin.md
  docs/guides/using-rewrites.md
  docs/guides/using-tcpingress.md
  docs/references/annotations.md
  docs/references/custom-resources.md
Labels: pr/changes requested

#832 Ingress V1: Parse Ingress V1 entries from Store.
  internal/ingress/controller/parser/ingressrules.go
  internal/ingress/controller/parser/ingressrules_test.go
  internal/ingress/controller/parser/parser.go
  internal/ingress/controller/parser/translate.go
  internal/ingress/controller/parser/translate_test.go
Labels: pr/please review

#843 Handle Ingress v1 class
  cli/ingress-controller/flags.go
  cli/ingress-controller/main.go
  cli/ingress-controller/main_test.go
  internal/ingress/annotations/annotations.go
  internal/ingress/annotations/annotations_test.go
  internal/ingress/store/fake_store.go
  internal/ingress/store/fake_store_test.go
  internal/ingress/store/store.go
Labels: pr/please review

#818 Add 0.10.0 changelog
  CHANGELOG.md
Labels: pr/please review

#864 docs: update cli args for logging
  docs/references/cli-arguments.md
Labels: pr/please review

#866 chore(flags) remove deprecated flags
  cli/ingress-controller/flag_test.go
  cli/ingress-controller/flags.go
  docs/concepts/security.md
  docs/references/cli-arguments.md
Labels: pr/changes requested

#871 Document (and add!) new flags for 1.0.0
  cli/ingress-controller/flags.go
  docs/references/cli-arguments.md
Labels: pr/please review

#873 Remove deprecated annotations
  docs/guides/upstream-mtls.md
  docs/references/annotations.md
  internal/ingress/annotations/annotations.go
  internal/ingress/annotations/annotations_test.go
  internal/ingress/controller/parser/kongstate/kongstate_test.go
  internal/ingress/controller/parser/kongstate/route_test.go
  internal/ingress/controller/parser/kongstate/service_test.go
  internal/ingress/controller/parser/parser_test.go
Labels: pr/please review

#877 Use EKS-like status
  docs/deployment/eks.md
Labels: pr/please review
