Repository Kong/kubernetes-ingress-controller, pull requests merged in 2021-09, with the labels that each got.

#1784 docs: some cleanup for the Gateway APIs KEP
  keps/0002-kong-gateway-api.md
Labels: severity/low, area/kep, ci/license/unchanged

#1801 Rename roles
  CHANGELOG.md
  Makefile
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  deploy/single-v2/all-in-one-dbless.yaml
  deploy/single-v2/all-in-one-enterprise-dbless.yaml
  deploy/single-v2/all-in-one-enterprise-postgres.yaml
  deploy/single-v2/all-in-one-postgres.yaml
Labels: ci/license/unchanged

#1742 docs: add unreferenced object filtration KEP
  keps/0008-unreferenced-object-filtration.md
Labels: severity/low, area/kep, ci/license/unchanged

#1816 fix: e2e tests
  test/e2e/all_in_one_test.go
Labels: bug, area/ci, ci/license/unchanged

#1851 doc(*) point back to main doc site
  README.md
Labels: do not merge, pr/please review, ci/license/unchanged

#1869 chore: updates for indirect containerd dep
  go.mod
  go.sum
Labels: severity/low, area/cleanup

#1870 Revert "chore(deps): bump actions/github-script from 4.1 to 5 (#1863)"
  .github/workflows/license.yaml
Labels: ci/license/unchanged

#1878 fix: timing flake in istio e2e tests
  test/e2e/istio_test.go
Labels: severity/low, ci/license/unchanged, area/cleanup

#1848 KEP: minor updates to the Gateway APIs KEP
  keps/0002-kong-gateway-api.md
Labels: severity/medium, area/kep, ci/license/unchanged
