Repository Kong/kubernetes-ingress-controller, pull requests merged in 2021-12, with the labels that each got.

#2029 fix(test) add delay in webhook test
  test/integration/webhook_test.go
Labels: ci/license/unchanged

#2057 fix: innappropriate object cache removal
  CHANGELOG.md
  hack/generators/controllers/networking/main.go
  internal/controllers/configuration/zz_generated_controllers.go
  internal/ctrlutils/utils.go
Labels: bug, severity/low, ci/license/unchanged

#2066 fix: gateway integration test wait times
  test/integration/gateway_test.go
Labels: severity/medium, area/ci, ci/license/unchanged

#2073 fix: reduce gh actions job resource contention for istio e2e
  .github/workflows/e2e.yaml
Labels: severity/medium, area/ci, ci/license/unchanged

#2070 fix(manager) lock client creation
  CHANGELOG.md
  internal/adminapi/client.go
Labels: bug, severity/medium, ci/license/unchanged

#2076 fix: test gateway integrations sequentially
  test/integration/gateway_test.go
Labels: severity/medium, area/ci, ci/license/unchanged

#1971 Add KongIngress types for generated CRDs
  CHANGELOG.md
  Makefile
  config/crd/bases/configuration.konghq.com_kongclusterplugins.yaml
  config/crd/bases/configuration.konghq.com_kongconsumers.yaml
  config/crd/bases/configuration.konghq.com_kongingresses.yaml
  config/crd/bases/configuration.konghq.com_kongplugins.yaml
  config/crd/bases/configuration.konghq.com_tcpingresses.yaml
  config/crd/bases/configuration.konghq.com_udpingresses.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  go.mod
  go.sum
  hack/generators/manifests/main.go
  internal/admission/validator.go
  internal/kongstate/route.go
  internal/kongstate/route_test.go
  internal/kongstate/service_test.go
  internal/kongstate/upstream.go
  internal/kongstate/upstream_test.go
  internal/kongstate/util.go
  internal/kongstate/util_test.go
  internal/parser/parser_test.go
  internal/parser/translate.go
  internal/parser/translate_test.go
  internal/store/store.go
  pkg/apis/configuration/v1/configsource.go
  pkg/apis/configuration/v1/kongclusterplugin_types.go
  pkg/apis/configuration/v1/kongingress_types.go
  pkg/apis/configuration/v1/kongplugin_types.go
  pkg/apis/configuration/v1/kongprotocol_types.go
  pkg/apis/configuration/v1/zz_generated.deepcopy.go
  test/e2e/all_in_one_test.go
  test/integration/knative_test.go
  test/integration/kongingress_test.go
Labels: ci/license/unchanged

#2103 feat(deploy) add KONG_KIC to manifests
  config/base/kong-ingress-dbless.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
Labels: ci/license/unchanged

#2089 Change reporting to TLS
  CHANGELOG.md
  internal/util/reports.go
  internal/util/reports_test.go
Labels: ci/license/changed

#2109 fix: de-parallelize gw webhook test
  test/integration/gateway_webhook_test.go
Labels: severity/low, ci/license/unchanged, test-flake

#2041 Add support for TLS Passthrough
  go.sum
  internal/parser/translate_test.go
  internal/util/protocol.go
  internal/util/protocol_test.go
  test/integration/tcpingress_test.go
  test/integration/utils_test.go
Labels: ci/license/changed
