Repository Kong/kubernetes-ingress-controller, pull requests merged in 2021-07, with the labels that each got.

#1475 Remove unused code - package configsecret
  go.mod
  railgun/pkg/configsecret/common.go
  railgun/pkg/configsecret/decoder.go
  railgun/pkg/configsecret/encoder.go
Labels: ci/license/unchanged

#1494 Make duplicate log suppressing a setting in config
  .github/workflows/2x-integration-test.yaml
  railgun/manager/run.go
  railgun/pkg/config/config.go
  railgun/test/integration/suite_test.go
Labels: ci/license/unchanged

#1501 Merge/main to next
  .github/workflows/1x-docker-build-push.yaml
  .github/workflows/1x-integration-test.yaml
  .github/workflows/2x-docker-build-push.yaml
  .github/workflows/2x-integration-test.yaml
  .github/workflows/common-test.yaml
  .gitignore
  Makefile
  pkg/annotations/annotations_test.go
  pkg/kongstate/upstream_test.go
  pkg/util/ingressapi_test.go
  pkg/util/secretgetter_test.go
  railgun/Makefile
Labels: ci/license/unchanged

#1451 KIC-2.0 Update Ingress Status/Condition after sync to Kong successfully
  internal/ingress/controller/kong.go
  pkg/sendconfig/common_workflows.go
  pkg/sendconfig/kong.go
  pkg/sendconfig/sendconfig.go
  railgun/internal/ctrlutils/ingress-status.go
  railgun/internal/proxy/clientgo_cached_proxy_resolver_test.go
  railgun/manager/run.go
  railgun/pkg/config/config.go
  railgun/test/integration/knative_test.go
  railgun/test/integration/suite_test.go
  railgun/test/integration/tcpingress_test.go
  railgun/test/integration/udpingress_test.go
Labels: area/feature, ci/license/changed, severity/high, size/small

#1502 fix: timing issue in proxy tests
  railgun/internal/proxy/clientgo_cached_proxy_resolver_test.go
Labels: bug, ci/license/unchanged, severity/medium

#1510 chore: update go-kong to v0.20.0
  go.mod
  go.sum
  pkg/adminapi/client.go
Labels: bug, ci/license/unchanged

#1512 chore: deprecate klog stderrthreshold flag
  CHANGELOG.md
  railgun/pkg/config/config.go
Labels: area/cleanup, ci/license/unchanged

#1506 fix: add back the --sync-period flag
  railgun/manager/run.go
  railgun/pkg/config/config.go
Labels: area/cleanup, bug, ci/license/unchanged, severity/medium

#1496 Use a StringSlice flag type in `--watch-namespace`
  railgun/manager/run.go
  railgun/pkg/config/config.go
Labels: ci/license/unchanged

#1511 fix: ensure flagset set validation is called
  railgun/cmd/rootcmd/env.go
  railgun/cmd/rootcmd/env_test.go
  railgun/cmd/rootcmd/rootcmd.go
Labels: bug, ci/license/unchanged, severity/low

#1514 fix: re-implement status update flags
  CHANGELOG.md
  railgun/manager/run.go
  railgun/pkg/config/config.go
Labels: area/cleanup, area/debt, ci/license/unchanged, severity/low

#1518 fix: datarace in datarace test
  pkg/util/debug_logging_test.go
Labels: bug, ci/license/unchanged, severity/low

#1488 [KIC-2.0] performance test cases and data collection
  railgun/test/performance/perf_ingress_test.go
  railgun/test/performance/perf_knative_test.go
  railgun/test/performance/perf_tcpingress_test.go
  railgun/test/performance/perf_udpingress_test.go
  railgun/test/performance/suite_test.go
Labels: area/perf, ci/license/unchanged, severity/high, severity/medium, size/small

#1528 fix: update kubernetes version for legacy tests
  Makefile
Labels: area/ci, bug, ci/license/unchanged, severity/high

#1530 cherry-pick #1528 (bump kind node version) to main
  Makefile
  railgun/scripts/setup-integration-tests.sh
  test/integration/test.sh
Labels: ci/license/unchanged

#1531 fix: dont run ci twice for branch
  .github/workflows/1x-integration-test.yaml
  .github/workflows/2x-integration-test.yaml
Labels: area/ci, ci/license/unchanged, severity/medium

#1526 docs: create SECURITY.md
  SECURITY.md
Labels: area/security, ci/license/unchanged, docs, severity/medium

#1525 chore: refactor manager.Run function
  railgun/manager/controllerdef.go
  railgun/manager/ingressapi.go
  railgun/manager/run.go
  railgun/manager/setup.go
  railgun/manager/vars.go
Labels: area/cleanup, ci/license/unchanged, severity/medium

#1539 [KIC2.0] fix typo and log footprint
  pkg/sendconfig/sendconfig.go
  railgun/test/performance/suite_test.go
Labels: area/cleanup, bug, ci/license/unchanged, severity/high, size/small

#1527 chore: add codeql analysis
  .github/workflows/common-codeql-analysis.yaml
Labels: area/ci, area/security, ci/license/changed, severity/medium

#1537 chore: nonfunctional fixes for lint errors
  .golangci.yaml
  railgun/cmd/rootcmd/rootcmd.go
  railgun/hack/generators/controllers/networking/main.go
  railgun/internal/ctrlutils/ingress-status.go
  railgun/internal/ctrlutils/utils.go
  railgun/internal/mgrutils/reports.go
  railgun/internal/proxy/clientgo_cached_proxy_resolver.go
  railgun/internal/proxy/clientgo_cached_proxy_resolver_test.go
  railgun/manager/controllerdef.go
  railgun/manager/run.go
  railgun/pkg/config/config.go
  railgun/test/integration/consts.go
  railgun/test/integration/ingress_https_test.go
  railgun/test/integration/ingress_test.go
  railgun/test/integration/knative_test.go
  railgun/test/integration/plugin_test.go
  railgun/test/integration/suite_test.go
  railgun/test/integration/tcpingress_test.go
  railgun/test/integration/udpingress_test.go
  railgun/test/integration/utils_test.go
  railgun/test/integration/webhook_test.go
Labels: area/ci, area/cleanup, ci/license/unchanged, severity/medium

#1545 chore(process): issue template forms
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/enhancement.yaml
Labels: ci/license/unchanged

#1523 [chore] re-organize railgun manager
  railgun/Makefile
  railgun/examples/tcpingress.yaml
  railgun/examples/udpingress.yaml
  railgun/hack/generators/controllers/networking/main.go
  railgun/internal/cmd/rootcmd/env.go
  railgun/internal/cmd/rootcmd/env_test.go
  railgun/internal/cmd/rootcmd/rootcmd.go
  railgun/internal/cmd/rootcmd/run.go
  railgun/internal/cmd/rootcmd/servers.go
  railgun/internal/controllers/configuration/doc.go
  railgun/internal/controllers/configuration/zz_generated_controllers.go
  railgun/internal/diagnostics/server.go
  railgun/internal/manager/config.go
  railgun/internal/manager/consts.go
  railgun/internal/manager/controllerdef.go
  railgun/internal/manager/flagset.go
  railgun/internal/manager/ingressapi.go
  railgun/internal/manager/run.go
  railgun/internal/manager/setup.go
  railgun/internal/manager/vars.go
  railgun/main.go
  railgun/scripts/check-container-environment.sh
  railgun/scripts/setup-integration-tests.sh
  railgun/test/integration/controller_test.go
  railgun/test/integration/ingress_test.go
  railgun/test/integration/suite_test.go
Labels: area/cleanup, ci/license/unchanged, severity/medium

#1554 fix: adjust docker image build paths
  .github/workflows/2x-image-build-test.yaml
  Dockerfile.railgun
Labels: area/ci, bug, ci/license/unchanged, severity/high

#1551 fix(parser) reject oauth2s without name
  pkg/kongstate/consumer_test.go
  pkg/kongstate/credentials.go
Labels: ci/license/unchanged, pr/please review

#1555 docs(change) add breaking finalizer change info
  CHANGELOG.md
Labels: ci/license/unchanged

#1565 chore(build) update RG tag
  Makefile
Labels: ci/license/unchanged, pr/please review

#1571 chore: temporarily disable auto ctrl loading
  railgun/internal/manager/run.go
Labels: area/cleanup, ci/license/unchanged, severity/medium

#1568 [chore][quality] fix - ingress_https_test check points; multiple routes update; only throw error if err is not nil
  railgun/internal/ctrlutils/ingress-status.go
  railgun/test/integration/ingress_https_test.go
Labels: ci/license/unchanged

#1550 [chore] alignment - enablement indicating feature support
  railgun/internal/manager/controllerdef.go
Labels: area/cleanup, ci/license/changed

#1570 [feat] legacy CRD compatibility
  CHANGELOG.md
  railgun/Makefile
  railgun/config/crd/bases/configuration.konghq.com_kongclusterplugins.yaml
  railgun/config/crd/bases/configuration.konghq.com_kongconsumers.yaml
  railgun/config/crd/bases/configuration.konghq.com_kongingresses.yaml
  railgun/config/crd/bases/configuration.konghq.com_kongplugins.yaml
  railgun/config/crd/bases/configuration.konghq.com_tcpingresses.yaml
  railgun/config/crd/bases/configuration.konghq.com_udpingresses.yaml
  railgun/config/crd/patches/upgrade_compat.yaml
  railgun/hack/generators/manifests/main.go
Labels: area/cleanup, ci/license/unchanged, severity/medium

#1556 feat: add some bulk ingress testing
  railgun/test/integration/ingress_bulk_test.go
  railgun/test/integration/suite_test.go
  railgun/test/integration/utils_test.go
Labels: area/ci, ci/license/unchanged, severity/low

#1558 [feat] CI testing kubernetes version matrix
  .github/workflows/2x-kubernetes-version-matrix-test.yaml
  RELEASE.md
  pkg/sendconfig/sendconfig.go
  railgun/test/integration/suite_test.go
  railgun/test/integration/utils_test.go
Labels: area/ci, ci/license/unchanged, pr/please review, severity/medium

#1563 Add kustomizations and tooling to create 2.x manifests
  CHANGELOG.md
  deploy/single
  deploy/single-v1/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single-v1/all-in-one-dbless.yaml
  deploy/single-v1/all-in-one-postgres-enterprise.yaml
  deploy/single-v1/all-in-one-postgres.yaml
  deploy/single-v2/all-in-one-dbless.yaml
  deploy/single-v2/all-in-one-enterprise-dbless.yaml
  deploy/single-v2/all-in-one-enterprise-postgres.yaml
  deploy/single-v2/all-in-one-postgres.yaml
  hack/build-single-manifests.sh
  hack/verify-manifests.sh
  railgun/Makefile
  railgun/config/base/kong-ingress-2x.yaml
  railgun/config/base/kong-ingress-dbless.yaml
  railgun/config/base/kustomization.yaml
  railgun/config/base/namespace.yaml
  railgun/config/base/service.yaml
  railgun/config/base/serviceaccount.yaml
  railgun/config/base/validation-service.yaml
  railgun/config/crd/kustomization.yaml
  railgun/config/rbac/leader_election_role_binding.yaml
  railgun/config/rbac/role_binding.yaml
  railgun/config/variants/enterprise-postgres/enterprise-resources.yaml
  railgun/config/variants/enterprise-postgres/kong-enterprise.yaml
  railgun/config/variants/enterprise-postgres/kustomization.yaml
  railgun/config/variants/enterprise/kong-enterprise.yaml
  railgun/config/variants/enterprise/kustomization.yaml
  railgun/config/variants/postgres/kong-ingress-postgres.yaml
  railgun/config/variants/postgres/kustomization.yaml
  railgun/config/variants/postgres/migration.yaml
  railgun/config/variants/postgres/postgres.yaml
  railgun/hack/deploy/build-single-manifests.sh
Labels: ci/license/unchanged, pr/please review

#1578 [chore] Fix enablement variable setting priority
  railgun/internal/ctrlutils/ingress-status.go
  railgun/internal/manager/controllerdef.go
  railgun/internal/manager/run.go
Labels: area/cleanup, bug, ci/license/changed

#1557 fix: reduce deckgen calls from proxy cache server
  railgun/internal/proxy/clientgo_cached_proxy_resolver.go
  railgun/internal/proxy/clientgo_cached_proxy_resolver_test.go
  railgun/internal/proxy/suite_test.go
Labels: area/cleanup, ci/license/unchanged, severity/low

#1584 Fix Ingress v1beta1 API resource group
  CHANGELOG.md
  deploy/single-v2/all-in-one-dbless.yaml
  deploy/single-v2/all-in-one-enterprise-dbless.yaml
  deploy/single-v2/all-in-one-enterprise-postgres.yaml
  deploy/single-v2/all-in-one-postgres.yaml
  railgun/config/rbac/role.yaml
  railgun/hack/generators/controllers/networking/main.go
  railgun/internal/controllers/configuration/zz_generated_controllers.go
Labels: ci/license/unchanged

#1589 Add configuration dumps for 2.x
  CHANGELOG.md
  internal/cmd/rootcmd/run.go
  internal/cmd/rootcmd/servers.go
  internal/diagnostics/server.go
  internal/manager/config.go
  internal/manager/run.go
  internal/manager/setup.go
  internal/proxy/clientgo_cached_proxy_resolver.go
  internal/proxy/clientgo_cached_proxy_resolver_test.go
  internal/proxy/proxy.go
  internal/proxy/suite_test.go
  internal/sendconfig/common_workflows.go
  internal/util/configdiag.go
  test/integration/controller_test.go
  test/integration/suite_test.go
Labels: ci/license/unchanged, pr/please review

#1600 Clean frequently flooded messages during load tests
  internal/ctrlutils/ingress-status.go
Labels: area/cleanup, ci/license/unchanged

#1611 chore: clean up coverage
  Makefile
Labels: area/ci, ci/license/unchanged, severity/low

#1610 fix: increase the default for proxy requests
  CHANGELOG.md
  internal/manager/config.go
  internal/proxy/proxy.go
Labels: bug, ci/license/unchanged, severity/high

#1620 [fix] stop status updates on 404
  internal/ctrlutils/ingress-status.go
Labels: bug, ci/license/unchanged, severity/medium

#1621 chore: seperate latest k8s release tests
  .github/workflows/release.yaml
Labels: area/ci, area/cleanup, ci/license/unchanged
