Repository Kong/kubernetes-ingress-controller, pull requests merged in 2021-05, with the labels that each got.

#1231 chore: gitignore the railgun executable
  railgun/.gitignore
Labels: ci/license/changed

#1274 KIC 2.0 - Proxy interface and Async Cache Resolution Server
  pkg/store/store.go
  railgun/controllers/configuration/zz_generated_controllers.go
  railgun/controllers/corev1/endpoints_controller.go
  railgun/controllers/corev1/service_controller.go
  railgun/hack/generators/controllers/networking/main.go
  railgun/internal/ctrlutils/kong.go
  railgun/internal/ctrlutils/utils.go
  railgun/internal/ctrlutils/vars.go
  railgun/internal/mgrutils/store.go
  railgun/internal/proxy/clientgo_cached_proxy_resolver.go
  railgun/internal/proxy/proxy.go
  railgun/manager/manager.go
Labels: area/perf, ci/license/changed, priority/high

#1282 fix: add kong update sha checks
  pkg/sendconfig/sendconfig.go
  railgun/internal/proxy/clientgo_cached_proxy_resolver.go
Labels: area/perf, ci/license/unchanged

#1281 Add workspace flag to Railgun manager
  go.mod
  go.sum
  pkg/adminapi/client.go
  railgun/manager/manager.go
  railgun/test/integration/suite_test.go
Labels: ci/license/unchanged, pr/please review

#1294 logr backend: replace zap with logrus
  cli/ingress-controller/main.go
  go.mod
  go.sum
  pkg/util/logging.go
  railgun/internal/proxy/clientgo_cached_proxy_resolver.go
  railgun/manager/manager.go
  railgun/test/integration/suite_test.go
Labels: ci/license/changed

#1303 Fix: typo need to be corrected
  cli/ingress-controller/flags.go
Labels: docs

#1295 Add apiserver-host flag to Railgun
  railgun/manager/manager.go
Labels: ci/license/unchanged, pr/please review

#1296 Add kong-admin-token flag to Railgun
  railgun/manager/manager.go
Labels: ci/license/unchanged

#1285 fix: plug ingressclass into ctrls
  railgun/controllers/configuration/zz_generated_controllers.go
  railgun/hack/generators/controllers/networking/main.go
  railgun/internal/ctrlutils/utils.go
  railgun/manager/manager.go
  railgun/test/integration/ingress_test.go
  railgun/test/integration/kongingress_test.go
  railgun/test/integration/tcpingress_test.go
  railgun/test/integration/udpingress_test.go
  railgun/test/integration/utils_test.go
Labels: area/testing, bug, ci/license/unchanged, pr/please review

#1314 chore: manager code re-organization
  railgun/cmd/rootcmd/rootcmd.go
  railgun/manager/config.go
  railgun/manager/controllerdef.go
  railgun/manager/flagset.go
  railgun/manager/manager.go
  railgun/manager/run.go
  railgun/manager/vars.go
  railgun/test/integration/suite_test.go
Labels: area/debt, ci/license/unchanged

#1313 feat: add postgres support to KIC 2.0
  .github/workflows/integration_test.yaml
  go.mod
  go.sum
  railgun/Makefile
  railgun/internal/proxy/clientgo_cached_proxy_resolver.go
  railgun/manager/config.go
  railgun/manager/run.go
  railgun/test/integration/suite_test.go
  railgun/test/integration/udpingress_test.go
Labels: area/debt, ci/license/unchanged, pr/please review

#1323 Clean up unused railgun variables
  railgun/Makefile
  railgun/internal/ctrlutils/utils.go
  railgun/internal/ctrlutils/vars.go
  railgun/manager/run.go
  railgun/test/integration/suite_test.go
Labels: ci/license/unchanged

#1322 Add github-actions versions checking with dependabot
  .github/dependabot.yml
Labels: area/ci

#1317 Implement --watch-namespace flag for Railgun
  railgun/manager/config.go
  railgun/manager/run.go
  railgun/test/integration/ingress_test.go
  railgun/test/integration/suite_test.go
Labels: ci/license/unchanged, pr/please review

#1336 feat: add --proxy-sync-seconds mgr cli flag
  CHANGELOG.md
  railgun/internal/proxy/clientgo_cached_proxy_resolver.go
  railgun/internal/proxy/proxy.go
  railgun/manager/config.go
  railgun/manager/run.go
  railgun/test/integration/suite_test.go
Labels: area/debt, area/perf, ci/license/unchanged, pr/please review

#1341 Pull from remote PR repos
  .github/workflows/license.yaml
Labels: area/ci, ci/license/changed, pr/please review

#1316 Admission webhook in Railgun
  cli/ingress-controller/flags.go
  cli/ingress-controller/main.go
  pkg/admission/errors.go
  pkg/admission/server.go
  pkg/admission/server_test.go
  pkg/admission/validator.go
  pkg/admission/validator_test.go
  pkg/kongstate/util.go
  pkg/util/secretgetter.go
  railgun/cmd/rootcmd/admission.go
  railgun/cmd/rootcmd/rootcmd.go
  railgun/cmd/rootcmd/run.go
  railgun/manager/run.go
  railgun/manager/vars.go
  railgun/pkg/config/config.go
  railgun/pkg/config/consts.go
  railgun/pkg/config/flagset.go
  railgun/test/integration/consts.go
  railgun/test/integration/controller_test.go
  railgun/test/integration/suite_test.go
  railgun/test/integration/webhook_test.go
Labels: ci/license/changed

#1351 chore(*) remove outdated comment
  railgun/internal/proxy/suite_test.go
  railgun/pkg/config/config.go
Labels: ci/license/changed, pr/please review

#1339 Support custom entities in Railgun
  railgun/internal/proxy/clientgo_cached_proxy_resolver.go
  railgun/internal/proxy/clientgo_cached_proxy_resolver_test.go
  railgun/pkg/config/config.go
Labels: ci/license/unchanged, pr/please review

#1347 feat: implement environment variable substitution
  railgun/cmd/rootcmd/env.go
  railgun/cmd/rootcmd/env_test.go
  railgun/cmd/rootcmd/rootcmd.go
Labels: ci/license/changed

#1357 Fix apiGroup in core objects: services and endpoints
  railgun/config/crd/bases/configuration.konghq.com_kongclusterplugins.yaml
  railgun/config/crd/bases/configuration.konghq.com_kongingresses.yaml
  railgun/config/rbac/role.yaml
  railgun/controllers/configuration/zz_generated_controllers.go
  railgun/hack/generators/controllers/networking/main.go
Labels: ci/license/changed

#1359 chore(mgr) enable most controllers
  railgun/pkg/config/config.go
Labels: ci/license/unchanged, pr/please review

#1360 Add tooling necessary for KongPlugin support
  pkg/sendconfig/common_workflows.go
  pkg/sendconfig/kong.go
  railgun/manager/run.go
  railgun/test/integration/plugin_test.go
  railgun/test/integration/suite_test.go
Labels: ci/license/unchanged

#1362 v2.0.0-alpha.1 changelog and makefile version bump
  CHANGELOG.md
  Makefile
Labels: ci/license/unchanged

#1156 Automatically build Docker images for branch and tag pushes
  .github/workflows/build-test.yaml
  .github/workflows/docker-build-push.yaml
  Dockerfile
  Makefile
  README.md
Labels: ci/license-status-unchanged, ci/license/changed, pr/please review

#1367 Merge main into next
  .github/workflows/build-test.yaml
  .github/workflows/docker-build-push.yaml
  .github/workflows/license.yaml
  .github/workflows/master-mirrors-main.yaml
  Dockerfile
  Makefile
  README.md
  cli/ingress-controller/flags.go
  cli/ingress-controller/util.go
  deploy/manifests/enterprise-k8s/kustomization.yaml
  deploy/manifests/enterprise/kustomization.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  pkg/parser/parser.go
  pkg/parser/parser_test.go
  pkg/store/store.go
  test/integration/sut/kustomization.yaml
Labels: ci/license/changed

#1368 Update 2.0.0-alpha.1 and 1.3 changelogs for release
  CHANGELOG.md
Labels: ci/license/changed

#1374 chore: upgrade gh action uses
  .github/workflows/docker-build-push.yaml
Labels: area/ci, ci/license/changed

#1375 Merge next into main
  .github/workflows/build-test.yaml
  .github/workflows/docker-build-push.yaml
  .github/workflows/integration_test.yaml
  .github/workflows/license.yaml
  .github/workflows/test.yaml
Labels: area/ci, ci/license/changed, pr/please review

#1376 Add release instructions
  RELEASE.md
Labels: ci/license/changed, docs, pr/please review

#1378 Bump KIC and Kong versions in manifest
  .github/workflows/test.yaml
  deploy/manifests/base/kong-ingress-dbless.yaml
  deploy/manifests/enterprise-k8s/kustomization.yaml
  deploy/manifests/enterprise/kustomization.yaml
  deploy/manifests/postgres/kong-ingress-postgres.yaml
  deploy/manifests/postgres/migration.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
Labels: ci/license/changed, pr/please review

#1381 fix(build) separate 1.x and 2.x build tags
  Makefile
Labels: ci/license/changed

#1377 ci(license) fix filter
  .github/workflows/license.yaml
Labels: area/ci, ci/license/unchanged, pr/please review

#1382 Merge main into next
  .github/workflows/license.yaml
  .github/workflows/test.yaml
  Makefile
  RELEASE.md
  deploy/manifests/base/kong-ingress-dbless.yaml
  deploy/manifests/enterprise-k8s/kustomization.yaml
  deploy/manifests/enterprise/kustomization.yaml
  deploy/manifests/postgres/kong-ingress-postgres.yaml
  deploy/manifests/postgres/migration.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
Labels: ci/license/unchanged

#1383 hack(github): GH Actions log scraper
  hack/get-github-actions-logs.sh
Labels: ci/license/unchanged
