Repository Kong/kubernetes-ingress-controller, pull requests merged in 2021-11, with the labels that each got.

#1984 fix(creds) coerce oauth hash_secret to bool
  CHANGELOG.md
  internal/kongstate/kongstate.go
  internal/kongstate/kongstate_test.go
Labels: ci/license/unchanged

#1979 feat(build) add debug image targets
  Dockerfile
  Makefile
Labels: ci/license/unchanged

#1989 Update 2.0.x with 2.0.5 changes
  .github/workflows/release.yaml
  CHANGELOG.md
  Dockerfile
  Makefile
  README.md
  go.mod
  go.sum
  internal/admission/errors.go
  internal/admission/validator.go
  internal/admission/validator_test.go
  internal/kongstate/kongstate.go
  internal/kongstate/kongstate_test.go
  test/integration/webhook_test.go
Labels: ci/license/unchanged

#1995 fix(status) update non-http upstream Ingresses
  internal/ctrlutils/ingress-status.go
  test/integration/ingress_test.go
Labels: ci/license/unchanged

#1997 chore(changelog) change date format
  CHANGELOG.md
Labels: ci/license/unchanged

#2000 fix(admission) add KongClusterPlugin config
  CHANGELOG.md
  hack/deploy-admission-controller.sh
Labels: ci/license/unchanged

#1998 feat: gateway controller
  CHANGELOG.md
  FEATURE_GATES.md
  PROJECT
  config/rbac/role.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  go.mod
  go.sum
  internal/annotations/annotations.go
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gateway_controller_test.go
  internal/controllers/gateway/gateway_controller_utils.go
  internal/manager/controllerdef.go
  internal/manager/feature_gates.go
  internal/manager/run.go
  internal/manager/setup.go
  internal/proxy/clientgo_cached_proxy_resolver.go
  internal/proxy/proxy.go
  internal/test/util/controller_manager.go
  internal/test/util/crds.go
  keps/0002-kong-gateway-api.md
  test/e2e/istio_test.go
  test/integration/gateway_test.go
  test/integration/suite_test.go
Labels: severity/medium, area/gateway-api, ci/license/changed

#2013 fix: status updates for svc with > 1 ingress
  CHANGELOG.md
  internal/ctrlutils/ingress-status.go
  test/integration/ingress_test.go
Labels: bug, severity/medium, ci/license/unchanged

#2022 chore(deps) update containerd and image-spec
  go.mod
  go.sum
Labels: ci/license/changed

#2024 Release 2.0.6
  .github/workflows/e2e.yaml
  .github/workflows/test.yaml
  CHANGELOG.md
  Makefile
  go.mod
  go.sum
  hack/deploy-admission-controller.sh
  internal/ctrlutils/ingress-status.go
  test/e2e/all_in_one_test.go
  test/integration/ingress_test.go
  test/integration/suite_test.go
  test/integration/utils_test.go
  test/utils/controller_manager.go
Labels: ci/license/changed

#2026 chore(deps): go mod tidy and fix test errors following #2025
  go.mod
  go.sum
  test/integration/webhook_test.go
Labels: ci/license/changed

#2032 feat(make) determine the tag automatically
  Makefile
Labels: ci/license/unchanged

#2039 fix: credentials validation for required data
  CHANGELOG.md
  internal/adminapi/validators/consumer/credentials/validation.go
  test/integration/webhook_test.go
Labels: bug, severity/medium, ci/license/unchanged
