Repository Kong/kubernetes-ingress-controller, pull requests merged in 2021-01, with the labels that each got.

#997 Prune extra subresource block in TCPIngress CRD
  deploy/manifests/base/custom-types.yaml
  hack/dev/common/custom-types.yaml
Labels: pr/please review

#993 remove Get started about Helm 2
  README.md
Labels: docs

#1008 feat(ci) codecoverage
  .github/workflows/test.yaml
  .gitignore
  Makefile
  README.md
Labels: area/ci, area/testing, feature

#1016 request response buffering options
  .gitignore
  deploy/manifests/base/custom-types.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  go.mod
  go.sum
  hack/dev/common/custom-types.yaml
  internal/ingress/annotations/annotations.go
  internal/ingress/annotations/annotations_test.go
  internal/ingress/controller/parser/kongstate/route.go
  internal/ingress/controller/parser/kongstate/route_test.go
  internal/ingress/controller/parser/parser_test.go
Labels: area/kong, area/testing, feature, priority/medium

#1020 fix(docs): add missing contributing docs related to PR base branches
  CONTRIBUTING.md
Labels: docs
