Repository Kong/kubernetes-ingress-controller, pull requests merged in 2021-06, with the labels that each got.

#1391 Update CHANGELOG.md
  CHANGELOG.md
Labels: ci/license/unchanged

#1397 Sendconfig update improvements
  CHANGELOG.md
  pkg/sendconfig/common_workflows.go
  pkg/sendconfig/sendconfig.go
  pkg/sendconfig/sendconfig_test.go
  railgun/internal/proxy/proxy.go
  railgun/test/integration/suite_test.go
Labels: bug, ci/license/unchanged, priority/high, size/small

#1407 Fix incorrect link in changelog
  CHANGELOG.md
Labels: ci/license/unchanged, pr/please review

#1405 feat: add BYOK to integration tests
  .github/workflows/test.yaml
  railgun/test/integration/suite_test.go
Labels: area/testing, ci/license/unchanged, priority/low, size/small

#1409 Build and push Railgun images
  .github/workflows/1x-docker-build-push.yaml
  .github/workflows/2x-docker-build-push.yaml
Labels: area/ci, ci/license/unchanged, pr/please review

#1410 Group CI tests by version
  .github/workflows/1x-integration-test.yaml
  .github/workflows/2x-integration-test.yaml
  .github/workflows/common-test.yaml
Labels: blocked, ci/license/unchanged, pr/please review

#1422 Set the GH Actions environment on docker push workflows
  .github/workflows/1x-docker-build-push.yaml
  .github/workflows/2x-docker-build-push.yaml
Labels: ci/license/unchanged

#1401 feat(config) make timeout configurable for the kong client
  CHANGELOG.md
  railgun/internal/proxy/clientgo_cached_proxy_resolver.go
  railgun/internal/proxy/clientgo_cached_proxy_resolver_test.go
  railgun/manager/run.go
  railgun/pkg/config/config.go
Labels: area/debt, pending author feedback, size/small

#1423 KIC 2.0 Alpha.1 KEP Updates
  railgun/keps/0003-kic-kubebuilder-re-architecture.md
  railgun/keps/0004-kong-kubernetes-testing.md
Labels: area/kep, ci/license/unchanged, priority/medium, size/small

#1431 feat: add redudancy reducing debug logr
  .github/workflows/2x-integration-test.yaml
  pkg/util/debug_logging.go
  pkg/util/debug_logging_test.go
  railgun/manager/run.go
Labels: area/ci, ci/license/unchanged, priority/high, size/medium

#1321 Use Plugins (GetSchema), Workspaces (Exists,Create), Tags (Exists) me…
  cli/ingress-controller/main.go
  cli/ingress-controller/util.go
  pkg/util/plugin_schema_helper.go
Labels: area/cleanup, bug, pending author feedback

#1396 [KIC 2.0] Add knative Ingress support
  CHANGELOG.md
  go.mod
  go.sum
  pkg/annotations/annotations.go
  pkg/store/store.go
  railgun/Makefile
  railgun/config/rbac/role.yaml
  railgun/controllers/configuration/zz_generated_controllers.go
  railgun/hack/generators/controllers/networking/main.go
  railgun/internal/ctrlutils/utils.go
  railgun/manager/run.go
  railgun/pkg/config/config.go
  railgun/test/integration/knative_test.go
  railgun/test/integration/suite_test.go
Labels: area/feature, ci/license/unchanged, pr/please review, priority/high, size/small

#1439 Fix Ingresses with certificates in 2.x
  CHANGELOG.md
  railgun/config/rbac/role.yaml
  railgun/controllers/configuration/zz_generated_controllers.go
  railgun/hack/generators/controllers/networking/main.go
  railgun/manager/run.go
  railgun/pkg/clientset/fake/clientset_generated.go
  railgun/test/integration/ingress_test.go
  railgun/test/integration/suite_test.go
Labels: ci/license/unchanged, pr/please review

#1457 Rework 2.x RBAC generators
  CHANGELOG.md
  go.mod
  go.sum
  railgun/config/crd/bases/configuration.konghq.com_tcpingresses.yaml
  railgun/config/rbac/role.yaml
  railgun/controllers/configuration/zz_generated_controllers.go
  railgun/hack/generators/controllers/networking/main.go
Labels: ci/license/changed

#1462 chore: update kind to v0.11.1
  railgun/scripts/setup-integration-tests.sh
Labels: area/ci, ci/license/unchanged, size/small

#1463 [docs] Update CONTRIBUTING.md for recent KIC 2.0 tooling
  CONTRIBUTING.md
Labels: ci/license/unchanged, docs, size/small

#1473 chore: bump kind version for legacy int tests
  test/integration/test.sh
Labels: area/ci, bug, ci/license/unchanged, priority/high
