Repository Kong/kubernetes-ingress-controller, pull requests merged in 2021-10, with the labels that each got.

#1887 Release 1.3.3
  .github/workflows/common-test.yaml
  CHANGELOG.md
  go.mod
  go.sum
  pkg/deckgen/generate.go
Labels: ci/license/unchanged

#1882 docs: CHANGELOG entry for 2.0.0
  CHANGELOG.md
Labels: area/docs, severity/high, ci/license/unchanged

#1880 docs: update RELEASE.md for gh workflows test matrices
  RELEASE.md
Labels: area/docs, severity/low, ci/license/unchanged

#1889 chore: extra defensive http checks in istio e2e tests
  test/e2e/istio_test.go
Labels: bug, severity/medium, area/ci, ci/license/unchanged

#1885 [KEP] Gruduation Criteria and initial implementability for Gateway APIs
  keps/0002-kong-gateway-api.md
Labels: do not merge, severity/medium, area/kep, ci/license/unchanged

#1899 Prometheus metrics regression test
  test/integration/controller_test.go
  test/integration/metrics_test.go
Labels: ci/license/unchanged

#1898 chore: update containerd to v1.5.7
  go.mod
  go.sum
Labels: severity/medium, area/security, ci/license/unchanged
