Repository Kong/kubernetes-ingress-controller, pull requests merged in 2021-08, with the labels that each got.

#1625 Add Docker build and push workflow
  .github/workflows/release.yaml
Labels: ci/license/unchanged

#1633 fix: knative tests on gke
  test/integration/knative_test.go
Labels: area/ci, bug, ci/license/unchanged

#1635 Release/v2.0.0 alpha.3
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/enhancement.yaml
  .github/workflows/common-codeql-analysis.yaml
  .github/workflows/release.yaml
  CHANGELOG.md
  SECURITY.md
  internal/kongstate/consumer_test.go
  internal/kongstate/credentials.go
  internal/manager/controllerdef.go
  test/integration/knative_test.go
Labels: area/ci, ci/license/unchanged

#1622 [chore] add controller functional prometheus format metrics
  CHANGELOG.md
  go.mod
  internal/metrics/prometheus.go
  internal/proxy/clientgo_cached_proxy_resolver.go
  internal/proxy/proxy.go
  internal/proxy/suite_test.go
  internal/sendconfig/common_workflows.go
  internal/sendconfig/sendconfig.go
Labels: area/cleanup, bug, ci/license/changed, severity/high

#1638 Booleanize the controller flags
  internal/manager/config.go
  internal/manager/controllerdef.go
  internal/manager/flagset.go
  internal/manager/ingressapi.go
  internal/manager/vars.go
  internal/util/enablementstatus.go
  internal/util/enablementstatus_test.go
  test/integration/controller_test.go
  test/integration/suite_test.go
Labels: ci/license/unchanged

#1645 docs: fix alpha changelog for flag breaks
  CHANGELOG.md
  internal/manager/config.go
Labels: area/cleanup, ci/license/unchanged, severity/high

#1644 fix(deploy) dereference single symlink
  deploy/single
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
Labels: ci/license/unchanged

#1641 fix: tcp ingress status updates
  internal/ctrlutils/ingress-status.go
Labels: bug, ci/license/unchanged, severity/medium

#1658 fix: panic in consumer sort func
  CHANGELOG.md
  internal/deckgen/generate.go
Labels: bug, ci/license/unchanged, severity/medium

#1665 fix: de-duplicate codeql runs on PRs
  .github/workflows/codeql.yaml
Labels: severity/low, area/ci, ci/license/unchanged, area/cleanup

#1668 doc(release) note manifest version bump
  RELEASE.md
Labels: pr/please review, ci/license/unchanged

#1585 use AutoHandlers instead of custom enablement logic
  internal/manager/config.go
  internal/manager/controllerdef.go
  internal/manager/flagset.go
  internal/manager/ingressapi.go
  internal/manager/run.go
  internal/manager/vars.go
  internal/util/enablementstatus.go
  internal/util/enablementstatus_test.go
  test/integration/suite_test.go
Labels: ci/license/unchanged

#1671 fix: support minimum TLS v1.2 for webhook admission server
  CHANGELOG.md
  internal/admission/server.go
Labels: severity/medium, area/security, ci/license/unchanged

#1672 fix: combine coverage and CI workflow
  .github/workflows/test.yaml
  Makefile
Labels: area/ci, ci/license/unchanged, area/cleanup

#1657 expose both controller and proxy prometheus format metrics for scrape
  CHANGELOG.md
  config/base/kong-ingress-2x.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/monitor.yaml
  deploy/single-v2/all-in-one-dbless.yaml
  deploy/single-v2/all-in-one-enterprise-dbless.yaml
  deploy/single-v2/all-in-one-enterprise-postgres.yaml
  deploy/single-v2/all-in-one-postgres.yaml
Labels: bug, do not merge, ci/license/changed, area/cleanup

#1673 Release 2.0.0-beta.1
  CHANGELOG.md
  Makefile
  RELEASE.md
  config/base/kong-ingress-2x.yaml
  deploy/single
  deploy/single-v2/all-in-one-dbless.yaml
  deploy/single-v2/all-in-one-enterprise-dbless.yaml
  deploy/single-v2/all-in-one-enterprise-postgres.yaml
  deploy/single-v2/all-in-one-postgres.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
Labels: ci/license/unchanged

#1677 Merge next to main for 2.0.0-beta.1
  .github/workflows/codeql.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  CHANGELOG.md
  Makefile
  config/base/kong-ingress-2x.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/monitor.yaml
  deploy/single-v2/all-in-one-dbless.yaml
  deploy/single-v2/all-in-one-enterprise-dbless.yaml
  deploy/single-v2/all-in-one-enterprise-postgres.yaml
  deploy/single-v2/all-in-one-postgres.yaml
  go.mod
  go.sum
  hack/e2e/run-tests.sh
  internal/admission/server.go
  internal/ctrlutils/ingress-status.go
  internal/deckgen/generate.go
  internal/manager/config.go
  internal/manager/controllerdef.go
  internal/manager/flagset.go
  internal/manager/ingressapi.go
  internal/manager/run.go
  internal/manager/vars.go
  internal/metrics/prometheus.go
  internal/proxy/clientgo_cached_proxy_resolver.go
  internal/proxy/proxy.go
  internal/proxy/suite_test.go
  internal/sendconfig/common_workflows.go
  internal/sendconfig/sendconfig.go
  internal/util/enablementstatus.go
  internal/util/enablementstatus_test.go
  test/integration/controller_test.go
  test/integration/ingress_https_test.go
  test/integration/ingress_test.go
  test/integration/knative_test.go
  test/integration/kongingress_test.go
  test/integration/plugin_test.go
  test/integration/suite_test.go
  test/integration/tcpingress_test.go
  test/integration/udpingress_test.go
  test/integration/utils_test.go
  test/integration/webhook_test.go
  test/performance/ingress_bulk_test.go
  test/performance/suite_test.go
Labels: ci/license/changed

#1680 [kep] performance tests
  keps/0007-kic-performance-test.md
Labels: area/debt, ci/license/unchanged, area/perf

#1681 updating docs associated to release and github workflow process
  README.md
  RELEASE.md
Labels: ci/license/unchanged

#1689 only global registry publisize data through controller-runtime metrics ports
  internal/metrics/prometheus.go
Labels: bug, pr/please review

#1682 Consolidate kustomize sources
  config/base/kong-ingress-2x.yaml
  config/base/kong-ingress-dbless.yaml
  config/base/kustomization.yaml
  config/base/namespace.yaml
  config/base/service.yaml
  config/base/validation-service.yaml
  config/rbac/kustomization.yaml
  config/rbac/role.yaml
  config/variants/enterprise-postgres/enterprise-resources.yaml
  config/variants/enterprise-postgres/kong-enterprise.yaml
  config/variants/enterprise/kong-enterprise.yaml
  config/variants/postgres/kong-ingress-postgres.yaml
  config/variants/postgres/migration.yaml
  config/variants/postgres/postgres.yaml
  deploy/manifests/base/custom-types.yaml
  deploy/manifests/base/kong-ingress-dbless.yaml
  deploy/manifests/base/kustomization.yaml
  deploy/manifests/base/namespace.yaml
  deploy/manifests/base/rbac.yaml
  deploy/manifests/base/service.yaml
  deploy/manifests/base/validation-service.yaml
  deploy/manifests/enterprise-k8s/kong-enterprise-k8s.yaml
  deploy/manifests/enterprise-k8s/kustomization.yaml
  deploy/manifests/enterprise/enterprise-resources.yaml
  deploy/manifests/enterprise/kong-enterprise.yaml
  deploy/manifests/enterprise/kustomization.yaml
  deploy/manifests/postgres/kong-ingress-postgres.yaml
  deploy/manifests/postgres/kustomization.yaml
  deploy/manifests/postgres/migration.yaml
  deploy/manifests/postgres/postgres.yaml
  deploy/single-v2/all-in-one-dbless.yaml
  deploy/single-v2/all-in-one-enterprise-dbless.yaml
  deploy/single-v2/all-in-one-enterprise-postgres.yaml
  deploy/single-v2/all-in-one-postgres.yaml
  hack/deploy/build-single-manifests.sh
  hack/generators/controllers/networking/main.go
  internal/controllers/configuration/zz_generated_controllers.go
Labels: pr/please review, ci/license/unchanged

#1696 Release 1.3.2
  CHANGELOG.md
  Makefile
  deploy/manifests/base/kong-ingress-dbless.yaml
  deploy/manifests/enterprise-k8s/kustomization.yaml
  deploy/manifests/enterprise/kustomization.yaml
  deploy/manifests/postgres/kong-ingress-postgres.yaml
  deploy/manifests/postgres/migration.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
Labels: pr/please review, ci/license/unchanged

#1686 upgrade gateway from 2.4 to 2.5
  CHANGELOG.md
  config/base/kong-ingress-dbless.yaml
  config/variants/enterprise-postgres/kustomization.yaml
  config/variants/enterprise/kustomization.yaml
  config/variants/postgres/kong-ingress-postgres.yaml
  config/variants/postgres/migration.yaml
  deploy/single-v2/all-in-one-dbless.yaml
  deploy/single-v2/all-in-one-enterprise-dbless.yaml
  deploy/single-v2/all-in-one-enterprise-postgres.yaml
  deploy/single-v2/all-in-one-postgres.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
Labels: pr/please review, ci/license/unchanged, area/release

#1705 Re-add pushing to dockerhub on pushes to `main`
  .github/workflows/release.yaml
Labels: ci/license/unchanged

#1701 Add 1.3.2 content to main
  CHANGELOG.md
Labels: pr/please review, ci/license/unchanged

#1706 README header for KIC 2.0 public beta
  README.md
Labels: do not merge, ci/license/unchanged

#1702 Address TCPIngress and UDPIngress collision
  CHANGELOG.md
  go.mod
  go.sum
  internal/parser/parser.go
  test/integration/tcpingress_test.go
  test/integration/udpingress_test.go
Labels: ci/license/unchanged

#1707 beta change log update
  CHANGELOG.md
Labels: ci/license/unchanged

#1715 release: bump KIC to 2.0.0-beta.2 in deploy-v2 manifests
  config/base/kong-ingress-dbless.yaml
  deploy/single-v2/all-in-one-dbless.yaml
  deploy/single-v2/all-in-one-enterprise-dbless.yaml
  deploy/single-v2/all-in-one-enterprise-postgres.yaml
  deploy/single-v2/all-in-one-postgres.yaml
Labels: ci/license/unchanged

#1717 chore: fix changelog formatting
  CHANGELOG.md
Labels: ci/license/unchanged

#1721 Restore webhook script
  deploy/manifests/validation-webhook-configuration.yaml
  hack/deploy-admission-controller.sh
Labels: ci/license/unchanged

#1726 [bug] add namespace selector into PodMonitor
  config/prometheus/monitor.yaml
Labels: bug, ci/license/unchanged

#1729 fix: remove credentials constraint violation dropping
  CHANGELOG.md
  internal/kongstate/kongstate.go
Labels: bug, severity/medium, ci/license/unchanged

#1731 Fix 1.22 test compatibility
  test/integration/knative_test.go
  test/integration/webhook_test.go
  test/performance/perf_knative_test.go
Labels: ci/license/unchanged

#1727 chore: enable k8s v1.22.0 release testing
  .github/workflows/release.yaml
Labels: severity/high, area/ci, ci/license/unchanged

#1741 docs: KEP updates for KIC v2.0.0-beta release
  keps/0003-kic-kubebuilder-re-architecture.md
  keps/0004-kong-kubernetes-testing.md
  keps/0006-officially-supported-platforms.md
  keps/0007-kic-performance-test.md
Labels: severity/low, area/kep, ci/license/unchanged
