Repository Kong/kubernetes-ingress-controller, pull requests merged in 2021-04, with the labels that each got.

#1158 Add storageversion tags to Railgun versions of CRD types
  railgun/apis/configuration/v1/kongclusterplugin_types.go
  railgun/apis/configuration/v1/kongconsumer_types.go
  railgun/apis/configuration/v1/kongingress_types.go
  railgun/apis/configuration/v1/kongplugin_types.go
  railgun/apis/configuration/v1alpha1/udpingress_types.go
  railgun/config/crd/bases/configuration.konghq.com_kongclusterplugins.yaml
  railgun/config/crd/bases/configuration.konghq.com_kongconsumers.yaml
  railgun/config/crd/bases/configuration.konghq.com_kongingresses.yaml
Labels: do not merge

#1162 Use Docker Hub KIC repo in manifests
  deploy/manifests/base/kong-ingress-dbless.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
Labels: pr/please review

#1157 Add TCPIngress to Railgun
  go.mod
  go.sum
  railgun/Makefile
  railgun/PROJECT
  railgun/apis/configuration/v1beta1/groupversion_info.go
  railgun/apis/configuration/v1beta1/tcpingress_types.go
  railgun/apis/configuration/v1beta1/zz_generated.deepcopy.go
  railgun/cmd/generators/controllers/networking/main.go
  railgun/config/crd/bases/configuration.konghq.com_tcpingresses.yaml
  railgun/config/crd/kustomization.yaml
  railgun/config/crd/kustomizeconfig.yaml
  railgun/config/crd/patches/cainjection_in_tcpingresses.yaml
  railgun/config/crd/patches/webhook_in_tcpingresses.yaml
  railgun/config/rbac/role.yaml
  railgun/config/rbac/tcpingress_editor_role.yaml
  railgun/config/rbac/tcpingress_viewer_role.yaml
  railgun/config/samples/configuration.konghq.com_v1beta1_tcpingress.yaml
  railgun/controllers/configuration/zz_generated_controllers.go
  railgun/main.go
  railgun/pkg/clientset/clientset.go
  railgun/pkg/clientset/fake/clientset_generated.go
  railgun/pkg/clientset/fake/register.go
  railgun/pkg/clientset/scheme/register.go
  railgun/pkg/clientset/typed/configuration/v1beta1/configuration_client.go
  railgun/pkg/clientset/typed/configuration/v1beta1/doc.go
  railgun/pkg/clientset/typed/configuration/v1beta1/fake/doc.go
  railgun/pkg/clientset/typed/configuration/v1beta1/fake/fake_configuration_client.go
  railgun/pkg/clientset/typed/configuration/v1beta1/fake/fake_tcpingress.go
  railgun/pkg/clientset/typed/configuration/v1beta1/generated_expansion.go
  railgun/pkg/clientset/typed/configuration/v1beta1/tcpingress.go
  railgun/test/integration/ingress_test.go
  railgun/test/integration/suite_test.go
  railgun/test/integration/tcpingress_test.go
  railgun/test/integration/udpingress_test.go
  railgun/test/integration/utils_test.go
Labels: area/ci, area/testing, feature, priority/high

#1166 Refactor validation server and improve test coverage/consistency
  cli/ingress-controller/main.go
  cli/ingress-controller/util.go
  go.mod
  go.sum
  internal/admission/errors.go
  internal/admission/server.go
  internal/admission/server_test.go
  internal/admission/validator.go
  internal/admission/validator_test.go
  pkg/kongstate/consumer.go
  pkg/kongstate/consumer_test.go
  pkg/kongstate/kongstate.go
  pkg/kongstate/kongstate_test.go
  pkg/sendconfig/kong.go
Labels: pr/please review

#1138 ci(*) report if a PR results in a license change
  .github/workflows/license.yaml
Labels: ci/license-status-unchanged, ci/license/unchanged

#1183 docs: add controller management to non-goals
  railgun/keps/0003-kic-kubebuilder-re-architecture.md
Labels: kep, pr/please review

#1163 ClientGo Storer Implementation for Railgun
  pkg/apis/configuration/v1beta1/types.go
  pkg/store/store.go
  railgun/config/samples/configuration.konghq.com_v1beta1_tcpingress.yaml
  railgun/controllers/configuration/secret_controller.go
  railgun/controllers/configuration/secret_utils.go
  railgun/keps/0004-kong-kubernetes-testing.md
  railgun/pkg/store/store.go
Labels: area/debt, pr/please review, priority/high

#1193 ci(license) ignore unsuccessful label removal
  .github/workflows/license.yaml
Labels: ci/license-status-unchanged

#1190 docs: small updates for KEPs
  railgun/keps/0003-kic-kubebuilder-re-architecture.md
  railgun/keps/0005-definition-of-done.md
Labels: docs

#1196 Merge main into next
  .github/stale.yml
  .github/workflows/license.yaml
  .github/workflows/test.yaml
  CHANGELOG.md
  CONTRIBUTING.md
  deploy/manifests/base/kong-ingress-dbless.yaml
  deploy/manifests/postgres/kong-ingress-postgres.yaml
  deploy/manifests/postgres/migration.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  railgun/keps/0005-definition-of-done.md
Labels: ci/license-status-unchanged

#1192 docs: add kep README
  railgun/keps/README.md
Labels: ci/license-status-unchanged, docs

#1198 fix(ci) use the correct steps when license changes
  .github/workflows/license.yaml
Labels: ci/license-status-unchanged

#1200 Merge main into next
  .github/workflows/license.yaml
Labels: ci/license-status-unchanged

#1184 Kubernetes Clientset Generation for V1 APIs
  railgun/Makefile
  railgun/TODO.md
  railgun/apis/configuration/v1/groupversion_info.go
  railgun/apis/configuration/v1/kongclusterplugin_types.go
  railgun/apis/configuration/v1/kongconsumer_types.go
  railgun/apis/configuration/v1/kongingress_types.go
  railgun/apis/configuration/v1/kongplugin_types.go
  railgun/pkg/clientset/clientset.go
  railgun/pkg/clientset/fake/clientset_generated.go
  railgun/pkg/clientset/fake/register.go
  railgun/pkg/clientset/scheme/register.go
  railgun/pkg/clientset/typed/configuration/v1/configuration_client.go
  railgun/pkg/clientset/typed/configuration/v1/doc.go
  railgun/pkg/clientset/typed/configuration/v1/fake/doc.go
  railgun/pkg/clientset/typed/configuration/v1/fake/fake_configuration_client.go
  railgun/pkg/clientset/typed/configuration/v1/fake/fake_kongclusterplugin.go
  railgun/pkg/clientset/typed/configuration/v1/fake/fake_kongconsumer.go
  railgun/pkg/clientset/typed/configuration/v1/fake/fake_kongingress.go
  railgun/pkg/clientset/typed/configuration/v1/fake/fake_kongplugin.go
  railgun/pkg/clientset/typed/configuration/v1/generated_expansion.go
  railgun/pkg/clientset/typed/configuration/v1/kongclusterplugin.go
  railgun/pkg/clientset/typed/configuration/v1/kongconsumer.go
  railgun/pkg/clientset/typed/configuration/v1/kongingress.go
  railgun/pkg/clientset/typed/configuration/v1/kongplugin.go
  railgun/test/integration/ingress_test.go
Labels: pr/please review, priority/high

#1185 Implement {enabled,disabled,auto} flags for each controller
  pkg/util/enablementstatus.go
  pkg/util/enablementstatus_test.go
  railgun/cmd/rootcmd/rootcmd.go
  railgun/manager/flagset.go
  railgun/manager/manager.go
  railgun/test/integration/suite_test.go
Labels: ci/license-status-unchanged

#1208 fix(ci) correct license label
  .github/workflows/license.yaml
Labels: ci/license/unchanged

#1211 Merge main into next
  .github/workflows/license.yaml
Labels: ci/license/changed

#1206 fix: expand udp integration tests
  railgun/test/integration/udpingress_test.go
Labels: area/ci, area/testing, ci/license-status-unchanged, ci/license/unchanged

#1228 chore: remove unused controllers
  railgun/controllers/configuration/kongclusterplugin_controller.go
  railgun/controllers/configuration/kongconsumer_controller.go
  railgun/controllers/configuration/kongingress_controller.go
  railgun/controllers/configuration/kongplugin_controller.go
  railgun/manager/manager.go
Labels: area/debt, ci/license/unchanged, pr/please review

#1213 TCPIngress Tests
  go.mod
  go.sum
  pkg/store/store.go
  railgun/Makefile
  railgun/PROJECT
  railgun/apis/configuration/v1beta1/groupversion_info.go
  railgun/apis/configuration/v1beta1/tcpingress_types.go
  railgun/config/crd/bases/configuration.konghq.com_kongclusterplugins.yaml
  railgun/config/crd/bases/configuration.konghq.com_kongingresses.yaml
  railgun/config/crd/bases/configuration.konghq.com_tcpingresses.yaml
  railgun/config/crd/kustomization.yaml
  railgun/config/crd/patches/cainjection_in_tcpingresses.yaml
  railgun/config/crd/patches/webhook_in_tcpingresses.yaml
  railgun/config/rbac/tcpingress_editor_role.yaml
  railgun/config/rbac/tcpingress_viewer_role.yaml
  railgun/config/samples/configuration_v1beta1_tcpingress.yaml
  railgun/controllers/configuration/secret_utils.go
  railgun/test/integration/suite_test.go
  railgun/test/integration/tcpingress_test.go
Labels: area/ci, area/testing, ci/license/changed, feature, pr/please review

#1227 chore: move ctrl generators to hack dir
  railgun/hack/generators/controllers/networking/main.go
  railgun/main.go
Labels: area/debt, ci/license/changed, pr/please review

#1232 KIC 2.0: introduce Admin API mtls and headers. Refactor and reuse KIC 1.x logic.
  cli/ingress-controller/main.go
  pkg/adminapi/client.go
  pkg/adminapi/header_roundtripper.go
  pkg/util/enablementstatus.go
  railgun/cmd/rootcmd/rootcmd.go
  railgun/manager/flagset.go
  railgun/manager/manager.go
Labels: ci/license/changed

#1243 deploy(*) update Gateway/Enterprise repo and tags
  deploy/manifests/enterprise-k8s/kustomization.yaml
  deploy/manifests/enterprise/kustomization.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  test/integration/sut/kustomization.yaml
Labels: ci/license/unchanged, pr/please review

#1248 chore: drop master branch tracking
  .github/workflows/master-mirrors-main.yaml
Labels: ci/license/unchanged

#1216 [KEP] Context Updates for KIC 2.0 KEP
  railgun/keps/0003-kic-kubebuilder-re-architecture.md
Labels: ci/license/unchanged, kep

#1252 ci(licenses) ignore Kong repos
  .github/workflows/license.yaml
Labels: ci/license/unchanged

#1202 docs: kep for new platform support
  railgun/keps/0006-officially-supported-platforms.md
Labels: ci/license-status-unchanged, ci/license/unchanged, docs, kep

#1255 KIC 2.0: TODO cleanup
  railgun/Makefile
  railgun/hack/generators/controllers/networking/main.go
  railgun/keps/0001-single-kic-multi-gateway.md
  railgun/scripts/setup-integration-tests.sh
  railgun/test/integration/suite_test.go
Labels: area/debt, ci/license/unchanged

#1257 fix: enable leader election ID override
  railgun/manager/manager.go
  railgun/test/integration/suite_test.go
Labels: area/debt, ci/license/unchanged, pr/please review

#1264 feat: use httpbin as stardard http test tooling
  railgun/examples/httpbin.yaml
  railgun/test/integration/ingress_test.go
  railgun/test/integration/kongingress_test.go
  railgun/test/integration/suite_test.go
  railgun/test/integration/tcpingress_test.go
Labels: area/ci, area/testing, ci/license/unchanged

#1265 fix: add a kb shim to work around Dockerfile validation
  railgun/Dockerfile
Labels: bug, ci/license/unchanged, pr/please review

#1262 feat: add ingress.class override for mgr
  railgun/cmd/rootcmd/rootcmd.go
  railgun/controllers/configuration/zz_generated_controllers.go
  railgun/controllers/corev1/endpoints_controller.go
  railgun/controllers/corev1/service_controller.go
  railgun/hack/generators/controllers/networking/main.go
  railgun/internal/ctrlutils/kong.go
  railgun/internal/ctrlutils/utils.go
  railgun/manager/manager.go
  railgun/pkg/constants/constants.go
  railgun/test/integration/ingress_test.go
  railgun/test/integration/kongingress_test.go
  railgun/test/integration/suite_test.go
  railgun/test/integration/tcpingress_test.go
  railgun/test/integration/udpingress_test.go
Labels: ci/license/changed, pr/please review, priority/high
