Repository Kong/kubernetes-ingress-controller, pull requests merged in 2022-09, with the labels that each got.

#2889 chore: bump Gateway API's GatewayClass from v1alpha2 to v1beta1
  CHANGELOG.md
  Makefile
  PROJECT
  internal/admission/validator.go
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gateway_controller_test.go
  internal/controllers/gateway/gateway_utils.go
  internal/controllers/gateway/gatewayclass_controller.go
  internal/controllers/gateway/gatewayclass_controller_test.go
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/route_utils.go
  internal/controllers/gateway/tcproute_controller.go
  internal/controllers/gateway/tlsroute_controller.go
  internal/controllers/gateway/udproute_controller.go
  internal/dataplane/sendconfig/sendconfig.go
  internal/manager/controllerdef.go
  internal/manager/run.go
  pkg/apis/configuration/v1/configsource.go
  pkg/apis/configuration/v1/kongingress_types.go
  pkg/apis/configuration/v1/kongprotocol_types.go
  pkg/apis/configuration/v1beta1/groupversion_info.go
  test/conformance/gateway_conformance_test.go
  test/e2e/helpers_gateway_test.go
  test/integration/gateway_test.go
  test/integration/helpers_test.go
  test/integration/httproute_webhook_test.go
Labels: area/gateway-api, area/maintenance

#2894 chore: bump Gateway API's HTTPRoute from v1alpha2 to v1beta1
  .golangci.yaml
  CHANGELOG.md
  internal/admission/server.go
  internal/admission/server_test.go
  internal/admission/validator.go
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gateway_controller_test.go
  internal/controllers/gateway/gateway_utils.go
  internal/controllers/gateway/gatewayclass_controller.go
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/route_utils.go
  internal/controllers/gateway/route_utils_test.go
  internal/controllers/gateway/tcproute_controller.go
  internal/controllers/gateway/tlsroute_controller.go
  internal/controllers/gateway/udproute_controller.go
  internal/dataplane/kongstate/util_test.go
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/translate_httproute.go
  internal/dataplane/parser/translate_httproute_test.go
  internal/dataplane/parser/translate_tcproute.go
  internal/dataplane/parser/translate_tlsroute.go
  internal/dataplane/parser/translate_udproute.go
  internal/dataplane/parser/translate_utils.go
  internal/dataplane/parser/translate_utils_test.go
  internal/dataplane/parser/wrappers_backendref.go
  internal/dataplane/parser/wrappers_refchecker.go
  internal/store/fake_store.go
  internal/store/fake_store_test.go
  internal/store/store.go
  internal/types/types.go
  internal/util/conversions.go
  internal/util/hostname.go
  internal/util/k8s.go
  internal/validation/gateway/httproute.go
  internal/validation/gateway/httproute_test.go
  test/conformance/gateway_conformance_test.go
  test/e2e/helpers_gateway_test.go
  test/integration/gateway_test.go
  test/integration/helpers_test.go
  test/integration/httproute_test.go
  test/integration/httproute_webhook_test.go
Labels: area/gateway-api

#2902 chore: pin k8s to v1.24.4 in integration tests
  test/integration/suite_test.go
Labels: area/testing

#2900 chore: bump Gateway API's Gateway from v1alpha2 to v1beta1
  CHANGELOG.md
  internal/admission/server.go
  internal/admission/server_test.go
  internal/admission/validator.go
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gateway_controller_test.go
  internal/controllers/gateway/gateway_utils.go
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/route_utils.go
  internal/controllers/gateway/route_utils_test.go
  internal/controllers/gateway/tcproute_controller.go
  internal/controllers/gateway/tlsroute_controller.go
  internal/controllers/gateway/types.go
  internal/controllers/gateway/udproute_controller.go
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/translate_httproute_test.go
  internal/dataplane/parser/wrappers_refchecker.go
  internal/store/fake_store.go
  internal/store/fake_store_test.go
  internal/store/store.go
  internal/types/types.go
  internal/util/conversions.go
  internal/validation/gateway/httproute.go
  internal/validation/gateway/httproute_test.go
  test/e2e/features_test.go
  test/e2e/helpers_gateway_test.go
  test/integration/examples_test.go
  test/integration/gateway_test.go
  test/integration/gateway_webhook_test.go
  test/integration/helpers_test.go
  test/integration/httproute_test.go
  test/integration/httproute_webhook_test.go
  test/integration/tcproute_test.go
  test/integration/tlsroute_test.go
  test/integration/udproute_test.go
Labels: area/gateway-api

#2903 test: add e2e tests in kong 3.0 compatibility test action
  .github/workflows/kong3.0_compatibility.yaml
Labels: area/testing, area/maintenance

#2883 Handle 3.x regex prefixes
  .github/workflows/test_nightly.yaml
  CHANGELOG.md
  PROJECT
  config/crd/bases/configuration.konghq.com_ingressclassparameterses.yaml
  config/crd/kustomization.yaml
  config/rbac/role.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  go.mod
  go.sum
  hack/generators/controllers/networking/main.go
  internal/controllers/configuration/zz_generated_controllers.go
  internal/dataplane/kong_client.go
  internal/dataplane/kongstate/consumer.go
  internal/dataplane/kongstate/consumer_test.go
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/translate.go
  internal/dataplane/parser/translate_httproute.go
  internal/dataplane/parser/translate_httproute_test.go
  internal/dataplane/parser/translate_ingress.go
  internal/dataplane/parser/translate_ingress_test.go
  internal/dataplane/parser/translate_knative.go
  internal/dataplane/parser/translate_test.go
  internal/dataplane/parser/translate_utils.go
  internal/dataplane/parser/translate_utils_test.go
  internal/dataplane/parser/translate_vars.go
  internal/dataplane/parser/translators/ingress.go
  internal/dataplane/parser/translators/ingress_test.go
  internal/dataplane/parser/translators/translator_vars.go
  internal/manager/config.go
  internal/manager/controllerdef.go
  internal/manager/feature_gates.go
  internal/manager/run.go
  internal/store/store.go
  internal/util/kongversion.go
  internal/versions/versions.go
  pkg/apis/configuration/v1alpha1/ingress_class_param_types.go
  test/e2e/features_test.go
  test/e2e/helpers_test.go
  test/integration/httproute_test.go
  test/integration/ingress_https_test.go
  test/integration/ingress_test.go
  test/integration/plugin_test.go
  test/integration/suite_test.go
  test/integration/utils_test.go
Labels: ci/run-nightly

#2925 fix: adapt admission webhook tests to run in colima host
  internal/util/test/webhooks.go
  test/integration/suite_test.go
Labels: area/debt, area/ci

#2929 chore: remove cron based jobs
  .github/workflows/cleanup.yaml
  .github/workflows/codeql.yaml
  .github/workflows/e2e.yaml
  .github/workflows/kong3.0_compatibility.yaml
  .github/workflows/license.yaml
  .github/workflows/nightly.yaml
Labels: area/ci

#2937 chore(tests): improve TestUDPIngressTCPIngressCollision stability
  test/integration/udpingress_test.go
Labels: area/debt, area/testing, area/maintenance

#2952 chore: introduce CheckCondition helper
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gateway_controller_test.go
  internal/controllers/gateway/gateway_utils.go
  internal/controllers/gateway/gatewayclass_controller.go
  internal/dataplane/parser/parser.go
  internal/util/conditions.go
  internal/util/conditions_test.go
  test/e2e/features_test.go
  test/e2e/helpers_gateway_test.go
  test/integration/gateway_test.go
  test/integration/helpers_test.go
  test/integration/tlsroute_test.go
Labels: area/debt, area/maintenance

#2938 chore: update k8s versions in nightly workflow
  .github/workflows/nightly.yaml
Labels: area/ci

#2965 feat(metrics): Add failure_reason label to ingress_controller_configuration_push_count metric
  CHANGELOG.md
  grafana.json
  internal/dataplane/sendconfig/sendconfig.go
  internal/dataplane/sendconfig/sendconfig_test.go
  internal/metrics/prometheus.go
Labels: area/metrics

#2996 chore: bump istio version
  .github/workflows/e2e.yaml
  .github/workflows/e2e_targeted.yaml
Labels: area/ci, area/testing

#3005 chore: remove cron workflows
  .github/workflows/cleanup.yaml
  .github/workflows/codeql.yaml
  .github/workflows/e2e.yaml
  .github/workflows/kong3.0_compatibility.yaml
  .github/workflows/license.yaml
  .github/workflows/nightly.yaml
Labels: area/ci

#3007 chore: don't send telemetry from integration and conformance tests
  test/conformance/suite_test.go
  test/integration/suite_test.go
Labels: area/debt, area/telemetry
