Repository Kong/kubernetes-ingress-controller, pull requests merged in 2022-08, with the labels that each got.

#2708 refactor: add generic Gateway Routes to kong.Route translation functions
  go.mod
  internal/dataplane/parser/translate_routes_helpers.go
  internal/dataplane/parser/translate_routes_helpers_test.go
  internal/dataplane/parser/translate_tcproute.go
  internal/dataplane/parser/translate_tlsroute.go
  internal/dataplane/parser/translate_udproute.go
Labels: area/maintenance

#2716 ci: add labels checker
  .github/workflows/check_pr_labels.yaml
Labels: area/ci

#2765 chore(ci): don't review code for labels checker
  .github/workflows/check_pr_labels.yaml
Labels: area/ci

#2771 chore(ci) make nightly tests conditional
  .github/workflows/test.yaml
  .github/workflows/test_nightly.yaml
Labels: ci/run-nightly

#2781 feat: promote Gateway feature gate to beta
  .github/workflows/test.yaml
  CHANGELOG.md
  FEATURE_GATES.md
  Makefile
  internal/manager/controllerdef.go
  internal/manager/feature_gates.go
  internal/manager/feature_gates_test.go
  test/conformance/suite_test.go
  test/e2e/features_test.go
  test/integration/utils_test.go
Labels: area/gateway-api

#2801 ci: store gateway API version only in go.mod
  Makefile
Labels: area/ci

#2804 chore: remove unsupported golint linter
  .golangci.yaml
Labels: area/ci

#2821 fix: info log missing service endpoints
  CHANGELOG.md
  internal/dataplane/parser/parser.go
Labels: bug, area/maintenance

#2825 fix: info instead of warn for no targets
  CHANGELOG.md
  internal/dataplane/parser/parser.go
Labels: bug

#2827 fix(gateway) handle NodePort addresses
  internal/controllers/gateway/gateway_controller.go
  test/e2e/features_test.go
  test/e2e/helpers_test.go
Labels: bug

#2857 chore: replace broken link in TODO
  Makefile
Labels: area/maintenance

#2858 fix(build): don't use temp dir for clien-gen
  Makefile
Labels: area/maintenance

#2854 ci: add build tag to go generate invocation for gateway API URLs
  Makefile
  test/internal/cmd/generate-gateway-api-urls/main.go
Labels: area/ci

#2869 chore(manifests) add KONG_ROUTER_FLAVOR env var to set kong router mode to traditional
  config/base/kong-ingress-dbless.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
Labels: area/kong, ci/run-nightly

#2879 build: use third_party build tag for dependencies
  Makefile
  third_party/client-gen.go
  third_party/controller-gen.go
  third_party/golangci-lint.go
  third_party/gotestfmt.go
  third_party/kustomize.go
  third_party/pkg.go
Labels: dependencies
