Repository Kong/kubernetes-ingress-controller, pull requests merged in 2022-03, with the labels that each got.

#2292 feat(controllers) add IngressClass v1
  CHANGELOG.md
  config/base/ingressclass.yaml
  config/base/kustomization.yaml
  config/rbac/role.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  hack/generators/controllers/networking/main.go
  internal/controllers/configuration/zz_generated_controllers.go
  internal/manager/config.go
  internal/manager/controllerdef.go
  internal/store/fake_store.go
  internal/store/fake_store_test.go
  internal/store/store.go
Labels: ci/license/unchanged

#2303 chore: refactor dp obj deletion ensure
  hack/generators/controllers/networking/main.go
  internal/controllers/configuration/zz_generated_controllers.go
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/utils/utils.go
  internal/dataplane/kong_client.go
Labels: severity/medium, ci/license/unchanged, area/cleanup

#2314 chore: update CHANGELOG.md for mtls flags from #1958
  CHANGELOG.md
Labels: area/docs, severity/medium, ci/license/unchanged

#2330 chore(docs) move changelog item
  CHANGELOG.md
Labels: ci/license/unchanged

#2351 chore: delete .ci directory
  .ci/build-main.sh
Labels: severity/low, ci/license/unchanged, area/maintenance

#2352 chore: delete old unneeded doc redir
  deploy/README.md
Labels: severity/low, ci/license/unchanged, area/maintenance

#2350 docs: README.md cleanup
  README.md
Labels: severity/low, ci/license/unchanged, area/maintenance

#2353 chore: cleanup httproute example
  examples/gateway-httproute.yaml
Labels: severity/low, ci/license/unchanged, area/maintenance

#2354 chore: remove old ing types from httpbin example
  examples/ingress.yaml
Labels: severity/low, ci/license/unchanged, area/maintenance

#2355 chore: cleanup the unused legacy tests
  hack/legacy/test/README.md
  hack/legacy/test/cases/00-ingress-match-type/ingress.yaml
  hack/legacy/test/cases/00-ingress-match-type/verify.sh
  hack/legacy/test/cases/01-https/ingress.yaml
  hack/legacy/test/cases/01-https/verify.sh
  hack/legacy/test/cases/02-ingress-apiversions/ingress.yaml
  hack/legacy/test/cases/02-ingress-apiversions/verify.sh
  hack/legacy/test/cases/03-plugin-correlation-id/ingress.yaml
  hack/legacy/test/cases/03-plugin-correlation-id/verify.sh
  hack/legacy/test/cases/04-plugin-key-auth/ingress.yaml
  hack/legacy/test/cases/04-plugin-key-auth/verify.sh
  hack/legacy/test/cases/05-ingress-override/ingress.yaml
  hack/legacy/test/cases/05-ingress-override/verify.sh
  hack/legacy/test/cases/06-default-backend/ingress.yaml
  hack/legacy/test/cases/06-default-backend/verify.sh
  hack/legacy/test/cases/07-sni-route/ingress.yaml
  hack/legacy/test/cases/07-sni-route/verify.sh
  hack/legacy/test/cases/08-externalname/ingress.yaml
  hack/legacy/test/cases/08-externalname/verify.sh
  hack/legacy/test/sut/kustomization.yaml
  hack/legacy/test/sut/patch-deployment.yaml
  hack/legacy/test/test.sh
  hack/legacy/test/util/create-cluster.sh
  hack/legacy/test/util/install-sut.sh
  hack/legacy/test/util/run-all-tests.sh
  hack/legacy/test/util/run-one-test.sh
  hack/legacy/test/util/teardown-cluster.sh
Labels: severity/low, ci/license/unchanged, area/maintenance

#2358 chore: move fipscmd to internal/cmd
  Dockerfile
  internal/cmd/fips/main.go
Labels: severity/low, ci/license/unchanged, area/maintenance

#2359 chore: move test utils under internal/utils/test
  internal/util/test/controller_manager.go
  internal/util/test/crds.go
  internal/util/test/webhooks.go
  test/conformance/suite_test.go
  test/e2e/istio_test.go
  test/integration/suite_test.go
  test/integration/webhook_test.go
Labels: severity/low, ci/license/unchanged, area/maintenance

#2361 chore: move k8s utils under internal/util
  hack/generators/controllers/networking/main.go
  internal/controllers/configuration/zz_generated_controllers.go
  internal/dataplane/kong_client.go
  internal/manager/controllerdef.go
  internal/manager/run.go
  internal/util/kubernetes/object/set.go
  internal/util/kubernetes/object/set_test.go
  internal/util/kubernetes/object/status/queue.go
  internal/util/kubernetes/object/status/queue_test.go
Labels: severity/low, ci/license/unchanged, area/maintenance

#2366 chore: update daysUntilStale as 7
  .github/stale.yml
Labels: severity/medium, area/ci, ci/license/unchanged

#2378 fix: remove redundant copy in Dockerfile
  Dockerfile
Labels: severity/low, ci/license/unchanged, area/maintenance

#2379 fix: serialize fgs in reports
  internal/util/reports.go
  internal/util/reports_test.go
Labels: bug, severity/medium, ci/license/unchanged
