Repository Kong/kubernetes-ingress-controller, pull requests merged in 2022-10, with the labels that each got.

#3021 chore(tests): Add BuildPulse reporting
  .github/workflows/e2e.yaml
  .github/workflows/nightly.yaml
  .github/workflows/test.yaml
  Makefile
  third_party/go.mod
  third_party/go.sum
  third_party/gotestfmt.go
  third_party/gotestsum.go
Labels: area/testing

#3025 chore(tests): buildpulse-report step requires repo checkout
  .github/workflows/e2e.yaml
  .github/workflows/nightly.yaml
  .github/workflows/test.yaml
Labels: area/testing

#3023 fix(tests): move schema changes to before running controller to fix a data race in conformance tests
  test/conformance/gateway_conformance_test.go
  test/conformance/suite_test.go
Labels: area/testing, area/maintenance

#2995 chore(tests) refactor E2E kustomize handling
  test/e2e/kustomizations.go
  test/e2e/utils_test.go
Labels: area/testing

#3030 chore(tests): make e2e junit results names unique
  .github/workflows/e2e.yaml
Labels: area/testing

#3031 chore(tests): collect proper junit reports from e2e tests
  .github/workflows/e2e.yaml
Labels: area/testing

#3024 Gateway API updated to 0.5.1
  CHANGELOG.md
  go.mod
  go.sum
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gateway_controller_test.go
  internal/controllers/gateway/gateway_utils.go
  test/consts/zz_generated_gateway.go
  test/integration/tlsroute_test.go
Labels: area/gateway-api

#3033 chore(ci): run buildpulse reporting on all branches
  .github/workflows/test.yaml
Labels: area/ci

#3022 chore(ci) split E2E into a job per test
  .github/workflows/e2e.yaml
  Makefile
Labels: area/ci, area/testing

#3048 fix(tests): fix istio tests
  .golangci.yaml
  test/e2e/istio_test.go
  test/e2e/kustomizations.go
Labels: area/testing

#3013 fix: Handle lack of CRDs gracefully for every controller
  CHANGELOG.md
  go.mod
  go.sum
  hack/generators/controllers/networking/main.go
  internal/controllers/configuration/zz_generated_controllers.go
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gatewayclass_controller.go
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/referencegrant_controller.go
  internal/controllers/gateway/tcproute_controller.go
  internal/controllers/gateway/tlsroute_controller.go
  internal/controllers/gateway/udproute_controller.go
  internal/controllers/knative/knative.go
  internal/controllers/utils/utils.go
  internal/manager/conditions.go
  internal/manager/conditions_test.go
  internal/manager/config.go
  internal/manager/controllerdef.go
  internal/manager/ingressapi.go
  internal/manager/run.go
  test/e2e/features_test.go
  test/e2e/helpers_test.go
  test/e2e/kustomizations.go
  test/e2e/utils_test.go
Labels: area/maintenance

#3050 chore(lint): remove some of the nolint directives
  internal/admission/server.go
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gatewayclass_controller.go
  internal/util/reports.go
  test/integration/suite_test.go
Labels: area/debt, area/maintenance

#3008 fix(parser): add HTTPRoute combined services routes
  CHANGELOG.md
  internal/dataplane/parser/translate_httproute.go
  internal/dataplane/parser/translate_httproute_test.go
  internal/dataplane/parser/translators/httproute.go
Labels: area/gateway-api

#3059 chore(tests): dump diagnostics for e2e kuma test
  test/e2e/kuma_test.go
Labels: area/testing

#3065 chore(tests): remove hardcoded v1.24 version for tests
  test/conformance/suite_test.go
  test/integration/suite_test.go
Labels: area/tests

#3077 chore: make sure the generated code is properly formatted
  Makefile
  internal/controllers/configuration/zz_generated_controllers.go
Labels: area/maintenance, size/L

#3078 chore: use .gitattributes to annotate generated files for pull-request-size bot
  .gitattributes
Labels: size/XS

#3074 chore: add more options to Makefile for running KIC locally
  Makefile
Labels: area/maintenance, size/M

#3079 chore: remove unneded DeleteObject() on gateway
  internal/controllers/gateway/gateway_controller.go
Labels: size/XS

#3082 chore: update HTTPRoute controller version in logs
  internal/controllers/gateway/httproute_controller.go
Labels: size/XS

#3084 chore: install experimental Gateway API CRDs as well as standard ones
  Makefile
Labels: area/maintenance, size/XS

#3081 fix: fill in gateway namespace and name when failed to find it in k8s
  internal/controllers/gateway/gateway_controller.go
Labels: size/XS

#3085 chore(ci): change the redhat registry backend to quay
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
Labels: size/M

#3090 fix(ci): fix use of wrong docker registry in preflight scan
  .github/actions/redhat-opdev-preflight-action/entrypoint.sh
Labels: size/XS

#3089 refactor(parser): extract functions to be used in HTTPRouteMatch consolidation
  internal/dataplane/parser/translate_httproute.go
  internal/dataplane/parser/translate_tcproute.go
  internal/dataplane/parser/translate_tlsroute.go
  internal/dataplane/parser/translate_udproute.go
  internal/dataplane/parser/translate_utils.go
  internal/dataplane/parser/translate_utils_test.go
Labels: size/L

#3047 feat: store only secrets that are possible to be used in object cache of dataplane
  CHANGELOG.md
  hack/generators/controllers/networking/main.go
  internal/controllers/configuration/object_references.go
  internal/controllers/configuration/object_references_test.go
  internal/controllers/configuration/secret_controller.go
  internal/controllers/configuration/zz_generated_controllers.go
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gateway_utils.go
  internal/controllers/knative/knative.go
  internal/controllers/reference/indexer.go
  internal/controllers/reference/indexer_test.go
  internal/controllers/reference/reference.go
  internal/manager/controllerdef.go
  internal/store/store.go
  test/integration/ingress_https_test.go
  test/integration/utils_test.go
Labels: size/XXL

#3105 chore(ci): exclude generated files from pr size calculations using globbing
  .gitattributes
Labels: area/ci, size/XS

#3103 chore(tests): add backend builder utility to reduce parser tests lengths
  internal/dataplane/parser/translate_httproute_test.go
  internal/util/builder/httpbackendref.go
  internal/util/builder/kongstateservicebackend.go
Labels: size/L

#3104 chore(tests): add k8s obj info utility to reduce parser tests lengths
  internal/dataplane/parser/translate_httproute_test.go
Labels: size/L

#3109 chore(tests): add CommonRouteSpec mock to reduce parser tests length
  internal/dataplane/parser/translate_httproute_test.go
Labels: size/M

#3108 chore(tests): add httproutematch builder utility to reduce parser tests
  internal/dataplane/parser/translate_httproute_test.go
  internal/util/builder/httproutematch.go
Labels: size/L

#3107 chore(tests) replace duplicate objects def with existing obeject ref in parser tests
  internal/dataplane/parser/translate_httproute_test.go
Labels: size/L

#3111 feat(#3097): use TranslationFailureCollector in Parser
  internal/dataplane/kong_client.go
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/parser_test.go
  internal/dataplane/parser/translate_httproute_test.go
  internal/dataplane/parser/translate_ingress_test.go
  internal/dataplane/parser/translate_knative_test.go
  internal/dataplane/parser/translate_kong_l4_test.go
  internal/dataplane/parser/translate_utils_test.go
  internal/metrics/prometheus.go
Labels: size/L

#3060 feature(parser): consolidation of multiple `HTTPRouteMatch` objects into single `kong.Route`
  CHANGELOG.md
  internal/dataplane/parser/translate_httproute.go
  internal/dataplane/parser/translate_httproute_test.go
  internal/dataplane/parser/translators/httproute.go
  internal/util/builder/httproutematch.go
Labels: area/feature, size/XXL

#3117 tests: fix the missing controller logs
  internal/cmd/rootcmd/run.go
  internal/manager/run.go
  internal/manager/setup.go
  internal/util/test/controller_manager.go
  test/conformance/gateway_conformance_test.go
  test/conformance/suite_test.go
  test/e2e/istio_test.go
  test/integration/suite_test.go
  test/integration/utils_test.go
Labels: size/L

#3116 Use modern plugin schema retrieval and delegate default filling to go-kong
  go.mod
  internal/dataplane/deckgen/deckgen.go
  internal/dataplane/deckgen/deckgen_test.go
  internal/dataplane/deckgen/generate.go
  internal/util/plugin_schema_helper.go
Labels: size/XL
