Repository Kong/kubernetes-ingress-controller, pull requests merged in 2022-01, with the labels that each got.

#2035 feat(metrics) add Grafana dashboard
  grafana.json
Labels: ci/license/unchanged

#2125 deps: upgrade deck to v1.10.0, update the affected deck calls in `sendconfig`
  go.mod
  go.sum
  internal/sendconfig/sendconfig.go
Labels: ci/license/changed

#2134 chore(deploy) rebuild manifests
  config/base/kong-ingress-dbless.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
Labels: ci/license/unchanged

#2135 doc(changelog) add missing KCP 2.x breaking change
  CHANGELOG.md
Labels: ci/license/unchanged

#2140 chore: update containerd
  go.mod
  go.sum
Labels: severity/medium, area/security, ci/license/unchanged, area/cleanup

#2136 feat: implement matching support for HTTPRoute in parser
  internal/parser/translate.go
  internal/parser/translate_test.go
Labels: severity/medium, area/gateway-api, ci/license/unchanged, area/cleanup

#2144 Add and test nightly builds
  .github/workflows/e2e.yaml
  .github/workflows/nightly.yaml
  test/e2e/all_in_one_test.go
Labels: ci/license/unchanged

#2178 chore: add extra validation for supported httproute features
  internal/validation/gateway/httproute.go
  internal/validation/gateway/httproute_test.go
Labels: severity/medium, area/gateway-api, ci/license/unchanged

#2182 Release 1.3.4
  CHANGELOG.md
  pkg/util/reports.go
  pkg/util/reports_test.go
Labels: ci/license/unchanged

#2181 Release 2.0.7
  CHANGELOG.md
  internal/util/reports.go
  internal/util/reports_test.go
  test/e2e/all_in_one_test.go
  test/e2e/istio_test.go
  test/integration/consts.go
  test/integration/suite_test.go
  test/integration/webhook_test.go
Labels: ci/license/changed

#2193 chore(*) update controller version
  Makefile
Labels: ci/license/unchanged

#2183 doc(changelog) add 1.3.4
  CHANGELOG.md
Labels: ci/license/unchanged

#2180 doc(changelog) add 2.0.7
  CHANGELOG.md
Labels: ci/license/unchanged

#2191 fix: validation for update-in-place unique constrained credentials
  CHANGELOG.md
  internal/admission/utils.go
  internal/admission/validator.go
  internal/validation/consumers/credentials/validation.go
  test/integration/webhook_test.go
Labels: bug, severity/high, ci/license/unchanged

#2192 Chore/replace goimports with gci
  .golangci.yaml
  Makefile
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/httproute_controller.go
  internal/parser/translate_httproute_test.go
  internal/proxy/clientgo_cached_proxy_resolver_test.go
  internal/proxy/proxy.go
Labels: severity/low, area/ci, size/small

#2189 fix(ci) rename nightly build
  .github/workflows/nightly.yaml
Labels: ci/license/unchanged

#2202 KEP - reword unmanaged gateways mode
  keps/0002-kong-gateway-api.md
Labels: area/docs, area/gateway-api, ci/license/unchanged, area/cleanup

#2196 ci(*) add E2E workflow with user-chosen versions
  .github/workflows/e2e_targeted.yaml
  test/e2e/all_in_one_test.go
  test/e2e/istio_test.go
Labels: ci/license/unchanged

#2179 docs: preview/experimental docs in README.md
  README.md
Labels: area/docs, severity/low, ci/license/unchanged

#2206 test(knative) update to latest version
  go.mod
  go.sum
  test/integration/suite_test.go
Labels: ci/license/unchanged

#2184 fix(status) retry updates if LB is pending
  internal/ctrlutils/ingress-status.go
  internal/manager/setup.go
  internal/sendconfig/kong.go
  internal/sendconfig/sendconfig.go
Labels: ci/license/changed

#2216 ci(*) add integration test to targeted job
  .github/workflows/e2e_targeted.yaml
Labels: ci/license/unchanged

#2220 chore: cleanup Makefile
  .github/workflows/test.yaml
  Makefile
Labels: severity/low, ci/license/unchanged, area/cleanup

#2223 test(*) re-enable integration race detection
  Makefile
Labels: ci/license/unchanged
