Repository Kong/kubernetes-ingress-controller, pull requests merged in 2022-12, with the labels that each got.

#3203 fix(ci): use correct redhat standard tags in nightly CI
  .github/workflows/nightly.yaml
Labels: area/ci, size/XS

#3208 fix(ci): use correct junit file name in nightly CI
  .github/workflows/nightly.yaml
Labels: area/ci, size/XS

#3211 chore(docs): display exported kinds first in the API reference
  config/crd/bases/configuration.konghq.com_kongclusterplugins.yaml
  config/crd/bases/configuration.konghq.com_kongplugins.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  docs/api-reference.md
  pkg/apis/configuration/v1/configsource.go
  scripts/apidocs-gen/template/gv_details.tpl
Labels: area/docs, size/L

#3219 chore(docs): remove top-level CRD extensive godocs
  config/crd/bases/configuration.konghq.com_ingressclassparameterses.yaml
  config/crd/bases/configuration.konghq.com_kongclusterplugins.yaml
  config/crd/bases/configuration.konghq.com_kongconsumers.yaml
  config/crd/bases/configuration.konghq.com_kongingresses.yaml
  config/crd/bases/configuration.konghq.com_kongplugins.yaml
  config/crd/bases/configuration.konghq.com_tcpingresses.yaml
  config/crd/bases/configuration.konghq.com_udpingresses.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  docs/api-reference.md
  pkg/apis/configuration/v1/kongclusterplugin_types.go
  pkg/apis/configuration/v1/kongconsumer_types.go
  pkg/apis/configuration/v1/kongingress_types.go
  pkg/apis/configuration/v1/kongplugin_types.go
  pkg/apis/configuration/v1alpha1/ingress_class_param_types.go
  pkg/apis/configuration/v1beta1/tcpingress_types.go
  pkg/apis/configuration/v1beta1/udpingress_types.go
  scripts/apidocs-gen/post-process-for-konghq.sh
Labels: area/docs, size/L

#3224 chore(deps) use consistent YAML lib
  .golangci.yaml
  go.mod
  internal/dataplane/kongstate/util.go
  test/e2e/utils_test.go
Labels: size/M

#3227 test(gateway-api): cover L4 routes in getSupportedGatewayForRoute tests
  internal/controllers/gateway/route_utils_test.go
  internal/controllers/gateway/types.go
  internal/util/builder/backendref.go
  internal/util/builder/listener.go
  internal/util/builder/routegroupkind.go
  internal/util/conversions.go
Labels: area/tests, area/gateway-api, size/XXL

#3226 fix(gateway-api): verify TLS/TCPRoute is accepted before pushing to Gateway
  CHANGELOG.md
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gateway_utils.go
  internal/controllers/gateway/gateway_utils_test.go
  internal/controllers/gateway/tcproute_controller.go
  internal/controllers/gateway/tlsroute_controller.go
  internal/controllers/gateway/udproute_controller.go
  test/integration/tcproute_test.go
  test/integration/tlsroute_test.go
Labels: bug, area/gateway-api, size/L

#3232 refactor: use one version of getting address to a variable
  internal/controllers/gateway/gateway_controller_test.go
  internal/controllers/gateway/gateway_utils_test.go
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/route_utils_test.go
  internal/dataplane/parser/ingressrules_test.go
  internal/dataplane/parser/translate_httproute_test.go
  internal/dataplane/parser/translate_routes_helpers_test.go
  internal/util/address/of.go
  internal/util/builder/address.go
  internal/util/builder/httpbackendref.go
  internal/util/builder/kongstateservicebackend.go
  internal/util/builder/listener.go
  internal/util/builder/routegroupkind.go
  internal/util/builder/routenamespaces.go
  internal/util/conversions.go
Labels: refactor, size/L

#3233 ci: don't run tests when license unavailable
  .github/workflows/test.yaml
Labels: area/ci, size/S

#3216 chore(deps): bump github.com/Masterminds/sprig to 3.2.3
  go.mod
  go.sum
  hack/generators/controllers/networking/main.go
Labels: dependencies, size/M

#3229 chore(ci): remove dependabot automerge (approve)
  .github/workflows/automerge-dependabot.yaml
Labels: area/ci, size/S

#3230 fix: match listener names for routes
  CHANGELOG.md
  internal/controllers/gateway/route_utils.go
  internal/controllers/gateway/route_utils_test.go
Labels: area/gateway-api, size/L

#3246 chore(docs): deprecate KongIngress' proxy and route in favor of annotations
  CHANGELOG.md
  config/crd/bases/configuration.konghq.com_kongingresses.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  docs/api-reference.md
  pkg/apis/configuration/v1/kongingress_types.go
Labels: area/docs, size/L

#3248 chore(tests): add v1.26 to k8s versions of nightly and e2e tests
  .github/workflows/e2e.yaml
  .github/workflows/e2e_targeted.yaml
  .github/workflows/nightly.yaml
  .github/workflows/test.yaml
  .github/workflows/test_nightly.yaml
Labels: size/M

#3251 chore(deps): bump k8s libs to v0.26
  .golangci.yaml
  go.mod
  go.sum
  hack/generators/controllers/networking/main.go
  internal/controllers/configuration/zz_generated_controllers.go
  internal/controllers/utils/conversion.go
  internal/controllers/utils/conversion_test.go
  internal/dataplane/address_finder.go
  internal/dataplane/address_finder_test.go
  internal/meshdetect/detector_test.go
  internal/store/store_test.go
Labels: dependencies, size/L

#3257 fix: do not create two Detached conditions when no port for the protocol available
  CHANGELOG.md
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gateway_utils.go
  internal/controllers/gateway/gateway_utils_test.go
Labels: area/tests, area/gateway-api, size/M

#3254 chore(dataplane) rename and move failure system
  internal/dataplane/failures/failures.go
  internal/dataplane/failures/failures_test.go
  internal/dataplane/kong_client.go
  internal/dataplane/parser/failures.go
  internal/dataplane/parser/failures_test.go
  internal/dataplane/parser/ingressrules.go
  internal/dataplane/parser/ingressrules_test.go
  internal/dataplane/parser/parser.go
Labels: size/XL

#3263 chore(deps): bump controller-runtime to v0.14.0
  go.mod
  go.sum
Labels: dependencies, size/S

#3261 feat(validation): warn when KongIngress deprecated fields get populated
  CHANGELOG.md
  hack/deploy-admission-controller.sh
  internal/admission/handler.go
  internal/admission/response_builder.go
  internal/admission/response_builder_test.go
  internal/admission/server.go
  internal/admission/server_test.go
  test/integration/kongingress_webhook_test.go
Labels: area/feature, size/XL

#3264 chore(deps): use lo.ToPtr for pointer casting
  .golangci.yaml
  go.mod
  internal/controllers/gateway/gateway_controller_test.go
  internal/controllers/gateway/gateway_utils_test.go
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/route_utils_test.go
  internal/dataplane/parser/ingressrules_test.go
  internal/dataplane/parser/translate_httproute_test.go
  internal/dataplane/parser/translate_routes_helpers_test.go
  internal/util/address/of.go
  internal/util/builder/backendref.go
  internal/util/builder/httpbackendref.go
  internal/util/builder/kongstateservicebackend.go
  internal/util/builder/listener.go
  internal/util/builder/routegroupkind.go
  internal/util/builder/routenamespaces.go
  internal/util/conversions.go
  test/integration/kongingress_webhook_test.go
Labels: dependencies, size/L

#3266 fix: check out repo before running codecov uploader
  .github/workflows/test.yaml
Labels: area/ci, size/XS

#3267 refactor: make synchronizer accept option parameters
  internal/dataplane/synchronizer.go
  internal/dataplane/synchronizer_test.go
  internal/manager/setup.go
Labels: area/tests, refactor, size/M

#3270 chore(metrics): display metrics over dashboard time
  grafana.json
Labels: size/L

#3271 fix: don't fail integration tests when ingres class is already present in the cluster
  test/integration/ingress_regex_match_test.go
  test/integration/suite_test.go
  test/integration/utils_test.go
Labels: area/tests, size/M

#3272 fix(tests): add GITHUB_TOKEN to tests so that they can authenticate against Github API
  .github/workflows/test.yaml
  .github/workflows/test_nightly.yaml
Labels: area/tests, size/XS

#3275 chore(tests): add GITHUB_TOKEN to nightly test runs
  .github/workflows/nightly.yaml
Labels: area/ci, area/tests, area/maintenance, size/XS

#3277 chore(deps): bump e2e matrix dependencies
  .github/workflows/e2e.yaml
Labels: size/S

#3279 chore: custom entites known issue note
  CHANGELOG.md
  internal/manager/config.go
Labels: area/debt, size/XS

#3280 chore(ci): don't test istio against k8s v1.26
  .github/workflows/e2e.yaml
Labels: size/XS

#3283 chore(e2e): test istio according to its support matrix
  .github/workflows/e2e.yaml
Labels: size/XS

#3281 chore: release 2.8
  CHANGELOG.md
  LICENSES
  config/image/oss/kustomization.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
Labels: area/release, size/XXL

#3276 fix(tests): generate test namespaces in tests
  test/integration/gateway_webhook_test.go
  test/integration/ingress_test.go
  test/integration/knative_test.go
  test/integration/kongingress_test.go
  test/integration/suite_test.go
  test/integration/udpingress_test.go
  test/integration/utils_test.go
  test/integration/webhook_test.go
Labels: area/tests, size/L

#3274 build: add more linters to golangci-lint configuration
  .golangci.yaml
  internal/admission/handler.go
  internal/cmd/rootcmd/env_test.go
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gatewayclass_controller.go
  internal/controllers/gateway/route_utils.go
  internal/controllers/knative/knative.go
  internal/controllers/reference/reference.go
  internal/dataplane/kong_client.go
  internal/dataplane/kongstate/route.go
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/translate_httproute.go
  internal/dataplane/parser/translate_knative.go
  internal/dataplane/parser/wrappers_backendref.go
  internal/diagnostics/server.go
  internal/manager/run.go
  internal/manager/utils/reports.go
  internal/meshdetect/detector.go
  internal/meshdetect/detector_test.go
  internal/util/k8s_test.go
  internal/util/reports.go
  internal/util/reports_mesh_test.go
  internal/util/reports_test.go
  test/integration/helpers_test.go
  test/integration/suite_test.go
  test/integration/utils_test.go
Labels: area/maintenance, size/L

#3285 chore(ci): fix release tests command
  .github/workflows/release.yaml
Labels: area/ci, size/S

#3287 fix(release) align test inputs with regular E2E
  .github/workflows/release.yaml
Labels: size/S

#3288 chore(deploy) bump Kong to 3.1
  config/image/enterprise/kustomization.yaml
  config/image/oss/kustomization.yaml
  config/variants/enterprise/kustomization.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
Labels: size/S

#3291 chore(ci): adjust codecov config
  .github/codecov.yml
Labels: area/ci, size/S

#3294 chore: update release issue template
  .github/ISSUE_TEMPLATE/release.yaml
Labels: size/S

#3299 chore: extend fossa instructions in release template
  .github/ISSUE_TEMPLATE/release.yaml
Labels: area/release, size/XS

#3295 chore(ci): align docs workflow
  .github/ISSUE_TEMPLATE/release.yaml
  .github/workflows/release_docs.yaml
  scripts/apidocs-gen/post-process-for-konghq.sh
Labels: area/docs, area/ci, area/release, size/M

#3300 chore: tag RH images with latest tag in release
  .github/workflows/release.yaml
Labels: area/release, size/XS

#3301 chore: update release issue template
  .github/ISSUE_TEMPLATE/release.yaml
Labels: area/release, size/XS
