Repository Kong/kubernetes-ingress-controller, pull requests merged in 2022-06, with the labels that each got.

#2533 fix: unconfigured objects in ctrls should debug log as info
  hack/generators/controllers/networking/main.go
  internal/controllers/configuration/zz_generated_controllers.go
Labels: bug, severity/low

#2538 docs: fix dead links in FEATURE_GATES.md
  FEATURE_GATES.md
Labels: area/docs

#2542 docs(README): README.md cleanup
  README.md
Labels: area/docs

#2546 docs(README): document supported container platforms
  README.md
Labels: area/docs

#2560 chore: bump golangci-lint to v1.46.2
  Makefile
  internal/controllers/gateway/utils.go
Labels: area/ci

#2554 chore: remove KongIngress support for Gateway API Route objects and Services referenced by those Routes
  CHANGELOG.md
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/route.go
  internal/dataplane/kongstate/route_test.go
  internal/dataplane/kongstate/service.go
  internal/dataplane/kongstate/service_test.go
  internal/dataplane/kongstate/upstream.go
  internal/dataplane/kongstate/upstream_test.go
  internal/dataplane/kongstate/util.go
  internal/dataplane/kongstate/util_test.go
  internal/dataplane/parser/ingressrules.go
  internal/dataplane/parser/translate_httproute_test.go
  internal/dataplane/parser/translate_utils.go
  internal/dataplane/parser/translate_utils_test.go
  internal/util/objectmeta.go
  internal/util/objectmeta_test.go
Labels: area/gateway-api, area/ingress-controller

#2577 fix(ingressclass) disable watches with controller
  CHANGELOG.md
  hack/generators/controllers/networking/main.go
  internal/controllers/configuration/zz_generated_controllers.go
  internal/manager/controllerdef.go
Labels: bug

#2536 docs: add IngressClassParams KEP
  keps/0009-ingress-class-params-crd.md
Labels: area/docs, area/kep

#2615 tests: make verifyEnterprise helper more verbose on version string failure
  test/e2e/helpers_test.go
Labels: area/testing
