Repository Kong/kubernetes-ingress-controller, pull requests merged in 2022-07, with the labels that each got.

#2636 chore(ci): add third_party dir to dependabot config
  .github/dependabot.yml
Labels: github_actions

#2602 Gateway resources consolidation
  test/integration/gateway_test.go
  test/integration/gateway_webhook_test.go
  test/integration/helpers_test.go
  test/integration/httproute_test.go
  test/integration/httproute_webhook_test.go
  test/integration/suite_test.go
  test/integration/tcpingress_test.go
  test/integration/tcproute_test.go
  test/integration/tlsroute_test.go
  test/integration/udpingress_test.go
  test/integration/udproute_test.go
Labels: do not merge

#2678 ci: add godot and golint linters
  .golangci.yaml
  hack/generators/controllers/networking/main.go
  internal/admission/utils.go
  internal/admission/validator.go
  internal/annotations/annotations.go
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gateway_utils.go
  internal/controllers/gateway/gatewayclass_controller.go
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/referencepolicy_controller.go
  internal/controllers/gateway/tcproute_controller.go
  internal/controllers/gateway/tlsroute_controller.go
  internal/controllers/gateway/udproute_controller.go
  internal/controllers/gateway/utils.go
  internal/controllers/utils/utils.go
  internal/dataplane/kong_client.go
  internal/dataplane/kongstate/credentials.go
  internal/dataplane/kongstate/route.go
  internal/dataplane/kongstate/service.go
  internal/dataplane/kongstate/upstream.go
  internal/dataplane/kongstate/util.go
  internal/dataplane/parser/translate_utils.go
  internal/dataplane/sendconfig/kong.go
  internal/dataplane/synchronizer.go
  internal/diagnostics/server.go
  internal/manager/controllerdef.go
  internal/manager/feature_gates.go
  internal/manager/metadata/metadata.go
  internal/meshdetect/detector.go
  internal/meshdetect/mesh_kind.go
  internal/store/store.go
  internal/util/configdiag.go
  internal/util/k8s.go
  internal/util/kongversion.go
  internal/util/logging.go
  internal/util/protocol.go
  internal/util/reports_test.go
  internal/util/types.go
  internal/validation/consumers/credentials/vars.go
Labels: area/ci

#2681 tests: add logs to TestKongIngressEssentials
  test/integration/kongingress_test.go
Labels: area/testing, test-flake

#2648 feat(ci): use github action to obtain kong license
  .github/workflows/e2e.yaml
  .github/workflows/e2e_targeted.yaml
  .github/workflows/test.yaml
Labels: area/ci, github_actions

#2691 chore: update deps for GW API v0.5.0
  CHANGELOG.md
  Makefile
  examples/gateway-httproute.yaml
  examples/gateway-tcproute.yaml
  examples/gateway-tlsroute.yaml
  examples/gateway-udproute.yaml
  go.mod
  go.sum
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/tcproute_controller.go
  internal/controllers/gateway/tlsroute_controller.go
  internal/controllers/gateway/udproute_controller.go
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/translate_tcproute.go
  internal/dataplane/parser/translate_udproute.go
  internal/dataplane/parser/translate_utils.go
  internal/dataplane/parser/translate_utils_test.go
  internal/store/fake_store_test.go
  test/conformance/gateway_conformance_test.go
  test/consts/gateway.go
  test/e2e/kuma_test.go
  test/integration/tcproute_test.go
  test/integration/tlsroute_test.go
Labels: area/gateway-api

#2710 tests: print error only when not nil in gateway tests
  test/integration/helpers_test.go
Labels: area/testing

#2717 ci: add tests build tags to golangci-lint
  .golangci.yaml
  test/e2e/utils_test.go
  test/integration/helpers_test.go
  test/integration/knative_test.go
Labels: area/ci, area/testing

#2727 ci(lint): do check errors in tests
  .golangci.yaml
  test/e2e/kuma_test.go
  test/integration/tlsroute_test.go
Labels: area/testing
