Repository Kong/kubernetes-ingress-controller, pull requests merged in 2022-02, with the labels that each got.

#2205 test(e2e) add Gateway test
  test/e2e/all_in_one_test.go
Labels: ci/license/unchanged

#2235 fix(grafana) use shareable dashboard
  grafana.json
Labels: ci/license/unchanged

#2240 doc(changelog) backfill 2.2 items
  CHANGELOG.md
Labels: ci/license/unchanged

#2188 ci(codecov): configure the codecov integration
  .github/codecov.yml
Labels: ci/license/unchanged

#2264 chore: remove todos from translate code
  internal/dataplane/parser/translate.go
  internal/dataplane/parser/translate_httproute.go
Labels: severity/low, ci/license/unchanged, area/cleanup

#2266 chore(*) release 2.2.1
  CHANGELOG.md
  config/image/oss/kustomization.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
Labels: ci/license/unchanged

#2268 chore(ci) update older Kubernetes versions
  .github/workflows/release.yaml
Labels: ci/license/unchanged

#2273 ci(license) skip secret-required steps when secrets unavailable
  .github/workflows/license.yaml
  .github/workflows/test.yaml
Labels: ci/license/unchanged

#2260 feat(gateway) support HTTPRoute regex and exact matches
  internal/dataplane/parser/translate_httproute.go
  internal/dataplane/parser/translate_httproute_test.go
  test/integration/httproute_test.go
Labels: ci/license/unchanged

#2283 fix(ci) use github api to determine membership
  .github/workflows/license.yaml
Labels: ci/license/unchanged

#2272 docs: more kep cleanup
  keps/0004-kong-kubernetes-testing.md
  keps/0007-kic-performance-test.md
Labels: severity/low, area/kep, ci/license/unchanged, area/cleanup

#2267 docs: cleanup gateway apis kep
  keps/0002-kong-gateway-api.md
Labels: severity/low, area/kep, ci/license/unchanged, area/cleanup

#2286 chore(deps) update deck to v1.11.0
  CHANGELOG.md
  go.mod
  go.sum
  internal/dataplane/sendconfig/sendconfig.go
Labels: ci/license/changed

#2293 docs: retarget kong docs for gateway guide
  FEATURE_PREVIEW_DOCUMENTATION.md
Labels: area/docs, ci/license/unchanged, area/cleanup
