Repository Kong/kubernetes-ingress-controller, pull requests merged in 2022-11, with the labels that each got.

#3114 feat(#3097): propagate translation failures of CA certificate secrets
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/parser_test.go
  internal/dataplane/parser/translate_secrets.go
  internal/dataplane/parser/translate_secrets_test.go
  internal/store/store.go
Labels: area/feature, size/L

#3121 Add missing Service/Route annotations
  CHANGELOG.md
  internal/annotations/annotations.go
  internal/annotations/annotations_test.go
  internal/dataplane/kongstate/route.go
  internal/dataplane/kongstate/route_test.go
  internal/dataplane/kongstate/service.go
  internal/dataplane/kongstate/service_test.go
Labels: size/XL

#3125 feat(#3097): create warning translation failure events for CA secrets
  CHANGELOG.md
  internal/dataplane/kong_client.go
  internal/manager/consts.go
  internal/manager/run.go
  test/integration/translation_failures_test.go
Labels: area/feature, area/ingress-controller, size/L

#3134 chore(tests): mark dataplane synchronizer unit test as long
  internal/dataplane/synchronizer_test.go
Labels: area/tests, size/XS

#3135 chore(tests): use shorter rsa keys for adminapi unit tests
  internal/adminapi/client_test.go
Labels: area/tests, size/XS

#3132 chore(config) enable combined routes by default
  .github/workflows/test.yaml
  CHANGELOG.md
  FEATURE_GATES.md
  internal/manager/feature_gates.go
Labels: size/L

#3130 feat(#3097): propagate translation failures for annotations not matching in grouped services
  CHANGELOG.md
  internal/dataplane/parser/failures.go
  internal/dataplane/parser/failures_test.go
  internal/dataplane/parser/ingressrules.go
  internal/dataplane/parser/ingressrules_test.go
  internal/dataplane/parser/parser.go
  internal/util/test/name.go
  test/consts.go
  test/integration/translation_failures_test.go
Labels: area/feature, area/ingress-controller, size/L

#3136 feat(#3097): use CRD validations for TCP/UDPIngress
  CHANGELOG.md
  config/crd/bases/configuration.konghq.com_tcpingresses.yaml
  config/crd/bases/configuration.konghq.com_udpingresses.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  internal/dataplane/parser/translate_kong_l4.go
  internal/dataplane/parser/translate_kong_l4_test.go
  pkg/apis/configuration/v1beta1/ingress_rules.go
  test/integration/crd_validations_test.go
Labels: area/feature, size/L

#3137 feat(#3097): propagate translation failures for missing service's referred client-cert
  CHANGELOG.md
  internal/dataplane/parser/ingressrules.go
  internal/dataplane/parser/parser_test.go
  test/integration/translation_failures_test.go
Labels: area/feature, area/ingress-controller, size/M

#3129 feat(gateway-api): add destination port matching GEP-957
  CHANGELOG.md
  go.mod
  go.sum
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/route_utils.go
  internal/controllers/gateway/route_utils_test.go
  internal/controllers/gateway/types.go
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/translate_errors.go
  internal/dataplane/parser/translate_httproute.go
  internal/dataplane/parser/translate_httproute_test.go
  internal/dataplane/parser/translate_routes_helpers.go
  internal/dataplane/parser/translate_tcproute.go
  internal/dataplane/parser/translate_tlsroute.go
  internal/dataplane/parser/translate_udproute.go
  test/integration/helpers_test.go
  test/integration/httproute_test.go
  test/integration/utils_test.go
Labels: area/feature, area/gateway-api, size/XL

#3035 Support GKE E2E tests and use (actual) E2E tests to gate releases
  .github/workflows/e2e.yaml
  .github/workflows/release.yaml
  Makefile
  hack/e2e/cluster/deploy/main.go
  test/e2e/all_in_one_test.go
  test/e2e/environment.go
  test/e2e/features_test.go
  test/e2e/helpers_test.go
  test/e2e/kuma_test.go
  test/e2e/utils_test.go
Labels: size/L

#3138 feat(#3097): propagate translation failures for netv1.Ingress
  CHANGELOG.md
  internal/dataplane/parser/failures.go
  internal/dataplane/parser/failures_test.go
  internal/dataplane/parser/ingressrules_test.go
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/parser_test.go
  internal/dataplane/parser/translate_ingress.go
  internal/dataplane/parser/translate_ingress_test.go
  internal/dataplane/parser/translate_knative.go
  internal/dataplane/parser/translate_kong_l4.go
  internal/dataplane/parser/translators/ingress.go
  internal/dataplane/parser/translators/ingress_test.go
  test/integration/translation_failures_test.go
Labels: area/feature, area/ingress-controller, size/L

#3145 chore(validations): remove unnecessary targetPort validation for ExternalName services
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/parser_test.go
Labels: area/maintenance, area/ingress-controller, size/S

#3146 chore(deps): update gcloud package containerpb
  go.mod
  go.sum
  hack/e2e/cluster/cleanup/main.go
Labels: size/XS

#3147 feat(#3097): propagate translation failures for gateway listeners referred secrets
  CHANGELOG.md
  internal/controllers/gateway/gateway_controller_test.go
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/translate_utils_test.go
  test/integration/translation_failures_test.go
Labels: area/feature, area/ingress-controller, size/L

#3151 feat(tests) support manager logs to file
  internal/cmd/rootcmd/run.go
  internal/cmd/rootcmd/servers.go
  internal/cmd/rootcmd/signal.go
  internal/manager/run.go
  internal/manager/setup.go
  internal/util/logging.go
  internal/util/test/controller_manager.go
  internal/util/test/crds.go
  test/conformance/gateway_conformance_test.go
  test/conformance/suite_test.go
  test/e2e/istio_test.go
  test/integration/suite_test.go
Labels: area/tests, size/L

#3150 feat(#3097): propagate translation failures for ingress referred secrets
  CHANGELOG.md
  internal/dataplane/parser/ingressrules.go
  internal/dataplane/parser/ingressrules_test.go
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/translate_ingress.go
  internal/dataplane/parser/translate_ingress_test.go
  internal/dataplane/parser/translate_knative.go
  internal/dataplane/parser/translate_knative_test.go
  internal/dataplane/parser/translate_kong_l4.go
  internal/dataplane/parser/translate_kong_l4_test.go
  test/integration/translation_failures_test.go
Labels: area/feature, area/ingress-controller, size/L

#3165 chore(deploy) align listens with upstream
  CHANGELOG.md
  config/base/kong-ingress-dbless.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
Labels: size/S

#3171 perf: use maps in SecretNameToSNIs
  internal/dataplane/parser/ingressrules.go
  internal/dataplane/parser/ingressrules_test.go
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/parser_test.go
  internal/dataplane/parser/translate_httproute_test.go
  internal/dataplane/parser/translate_ingress_test.go
  internal/dataplane/parser/translate_knative_test.go
  internal/dataplane/parser/translate_kong_l4_test.go
Labels: area/perf, size/L

#3167 feat(#3097): propagate translation failures for http routes not having backend refs
  CHANGELOG.md
  internal/dataplane/parser/translate_httproute.go
  test/integration/translation_failures_test.go
Labels: area/feature, size/M

#3154 add regex match tests for paths and headers
  test/integration/ingress_regex_match_test.go
Labels: size/L

#3181 feat(gateway-api): matching routes by `Listener.AllowedRoutes`
  CHANGELOG.md
  go.mod
  internal/controllers/gateway/route_utils.go
  internal/controllers/gateway/route_utils_test.go
  internal/controllers/gateway/types.go
  test/integration/httproute_test.go
Labels: area/gateway-api, size/XXL

#3185 chore(docs): generate CRDs API reference in markdown
  Makefile
  config/crd/bases/configuration.konghq.com_ingressclassparameterses.yaml
  config/crd/bases/configuration.konghq.com_kongclusterplugins.yaml
  config/crd/bases/configuration.konghq.com_kongconsumers.yaml
  config/crd/bases/configuration.konghq.com_kongingresses.yaml
  config/crd/bases/configuration.konghq.com_kongplugins.yaml
  config/crd/bases/configuration.konghq.com_tcpingresses.yaml
  config/crd/bases/configuration.konghq.com_udpingresses.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  docs/api-reference.md
  pkg/apis/configuration/v1/configsource.go
  pkg/apis/configuration/v1/groupversion_info.go
  pkg/apis/configuration/v1/kongclusterplugin_types.go
  pkg/apis/configuration/v1/kongconsumer_types.go
  pkg/apis/configuration/v1/kongingress_types.go
  pkg/apis/configuration/v1/kongplugin_types.go
  pkg/apis/configuration/v1alpha1/groupversion_info.go
  pkg/apis/configuration/v1alpha1/ingress_class_param_types.go
  pkg/apis/configuration/v1beta1/groupversion_info.go
  pkg/apis/configuration/v1beta1/tcpingress_types.go
  pkg/apis/configuration/v1beta1/udpingress_types.go
  scripts/apidocs-gen/config.yaml
  scripts/apidocs-gen/generate.sh
  scripts/apidocs-gen/template/gv_details.tpl
  scripts/apidocs-gen/template/gv_list.tpl
  scripts/apidocs-gen/template/type.tpl
  scripts/apidocs-gen/template/type_members.tpl
  third_party/crd-ref-docs.go
  third_party/go.mod
  third_party/go.sum
Labels: area/docs, area/ci, size/XXL

#3183 Add Gateway API listener builder
  internal/controllers/gateway/route_utils_test.go
  internal/util/builder/address.go
  internal/util/builder/listener.go
Labels: size/L

#3189 Add builders for `AllowedRoutes`, `RouteNamespaces` and `RouteGroupKind`
  internal/controllers/gateway/route_utils_test.go
  internal/util/builder/allowedroutes.go
  internal/util/builder/routegroupkind.go
  internal/util/builder/routenamespaces.go
Labels: size/L

#3196 chore(docs): add missing CRDs' documentation from docs.konghq.com's CRD reference
  config/crd/bases/configuration.konghq.com_kongclusterplugins.yaml
  config/crd/bases/configuration.konghq.com_kongconsumers.yaml
  config/crd/bases/configuration.konghq.com_kongingresses.yaml
  config/crd/bases/configuration.konghq.com_kongplugins.yaml
  config/crd/bases/configuration.konghq.com_tcpingresses.yaml
  config/crd/bases/configuration.konghq.com_udpingresses.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  docs/api-reference.md
  pkg/apis/configuration/v1/kongclusterplugin_types.go
  pkg/apis/configuration/v1/kongconsumer_types.go
  pkg/apis/configuration/v1/kongingress_types.go
  pkg/apis/configuration/v1/kongplugin_types.go
  pkg/apis/configuration/v1beta1/ingress_rules.go
  pkg/apis/configuration/v1beta1/tcpingress_types.go
  pkg/apis/configuration/v1beta1/udpingress_types.go
  scripts/apidocs-gen/template/gv_list.tpl
Labels: area/docs, size/XL

#3197 chore(docs): add workflow for synchronizing docs with docs.konghq.com
  .github/ISSUE_TEMPLATE/release.yaml
  .github/workflows/synchronize_docs.yaml
  scripts/apidocs-gen/post-process-for-konghq.sh
Labels: area/docs, size/M

#3200 chore: add yum update in redhat's image
  Dockerfile
Labels: area/ci, size/XS

#3180 fix: filter hostnames in HTTPRoute
  CHANGELOG.md
  internal/controllers/gateway/gateway_utils.go
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/route_utils.go
  internal/controllers/gateway/route_utils_test.go
  test/integration/httproute_test.go
Labels: size/L
