Repository Kong/kubernetes-ingress-controller, pull requests merged in 2022-04, with the labels that each got.

#2385 tests: add run and debug to Makefile
  Makefile
Labels: severity/low, area/testing, ci/license/unchanged

#2363 Add UDPRoute implementation
  CHANGELOG.md
  PROJECT
  config/rbac/role.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  examples/gateway-udproute.yaml
  internal/controllers/gateway/route_utils.go
  internal/controllers/gateway/udproute_controller.go
  internal/controllers/gateway/utils.go
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/translate_udproute.go
  internal/manager/controllerdef.go
  internal/store/fake_store.go
  internal/store/fake_store_test.go
  internal/store/store.go
  test/integration/examples_test.go
  test/integration/udpingress_test.go
  test/integration/udproute_test.go
Labels: ci/license/unchanged

#2392 fix(build) correct Dockerfile metadata paths
  Dockerfile
Labels: ci/license/unchanged

#2393 fix(changelog) add 2.3.0 TOC link
  CHANGELOG.md
Labels: ci/license/unchanged

#2394 fix(hack) add SAN to admission setup script
  hack/deploy-admission-controller.sh
Labels: ci/license/unchanged

#2396 tests: fix reporter ordering in test
  internal/util/reports_test.go
Labels: bug, severity/medium, area/ci, area/testing, ci/license/unchanged

#2389 Implement Gateaway Listener allowedRoutes.namespaces
  CHANGELOG.md
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gateway_controller_test.go
  internal/controllers/gateway/route_utils.go
  test/integration/gateway_test.go
  test/integration/ingress_test.go
  test/integration/suite_test.go
Labels: ci/license/changed

#2418 feat: enable multi-backendRefs for TCPRoute
  CHANGELOG.md
  internal/dataplane/parser/translate_tcproute.go
  test/integration/tcproute_test.go
Labels: severity/medium, area/gateway-api, ci/license/unchanged

#2416 Retry init connections to kong admin api
  CHANGELOG.md
  go.mod
  go.sum
  internal/manager/config.go
  internal/manager/run.go
  internal/manager/setup.go
Labels: severity/low, area/maintenance

#2422 fix(sendconfig) suppress deck diff logs at info
  CHANGELOG.md
  internal/manager/setup.go
Labels: ci/license/unchanged
