Repository Kong/kubernetes-ingress-controller, pull requests merged in 2022-05, with the labels that each got.

#2448 fix: race conditions for object status updates
  CHANGELOG.md
  internal/dataplane/kong_client.go
Labels: bug, severity/medium, ci/license/unchanged

#2341 Add flag to skip CA certificates
  CHANGELOG.md
  internal/dataplane/kong_client.go
  internal/dataplane/sendconfig/sendconfig.go
  internal/manager/config.go
  internal/manager/run.go
Labels: ci/license/unchanged

#2450 fix(kic): updated error message of env binding to include environment variable name
  internal/cmd/rootcmd/env.go
  internal/cmd/rootcmd/env_test.go
Labels: pending author feedback, severity/low, area/maintenance

#2424 feat(controllers) add ReferencePolicy controller
  PROJECT
  config/rbac/role.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  internal/controllers/gateway/referencepolicy_controller.go
  internal/manager/controllerdef.go
  internal/store/fake_store.go
  internal/store/fake_store_test.go
  internal/store/store.go
Labels: ci/license/changed

#2453 Test HTTPRoute plugin support
  test/integration/httproute_test.go
Labels: ci/license/unchanged

#2460 fix(build) enable arm64 for Red Hat images
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
Labels: ci/license/unchanged

#2459 fix: enable gw apis with broken lb svc
  CHANGELOG.md
  internal/controllers/gateway/gateway_controller.go
Labels: severity/medium, area/gateway-api, ci/license/changed

#2466 Refactor test coverage download and upload steps
  .github/workflows/test.yaml
Labels: severity/low, area/ci

#2463 doc(crd) add descripiton for each field of kongingress CRD
  CHANGELOG.md
  config/crd/bases/configuration.konghq.com_kongingresses.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  pkg/apis/configuration/v1/kongingress_types.go
Labels: area/docs, severity/low, onboarding

#2451 feat(translate) support ReferencePolicy in Routes
  CHANGELOG.md
  internal/dataplane/kongstate/types.go
  internal/dataplane/parser/ingressrules.go
  internal/dataplane/parser/translate_httproute.go
  internal/dataplane/parser/translate_httproute_test.go
  internal/dataplane/parser/translate_tcproute.go
  internal/dataplane/parser/translate_udproute.go
  internal/dataplane/parser/translate_utils.go
  internal/dataplane/parser/translate_utils_test.go
  test/integration/httproute_test.go
  test/integration/tcproute_test.go
  test/integration/udproute_test.go
Labels: ci/license/changed

#2485 chore: use `networking.knative.dev/ingress-class` additionally to `networking.knative.dev/ingress.class`
  CHANGELOG.md
  internal/annotations/annotations.go
  internal/controllers/utils/utils.go
  internal/dataplane/parser/parser_test.go
  internal/store/fake_store_test.go
  internal/store/store.go
  test/integration/knative_test.go
Labels: area/knative

#2509 fix: upgrade ktf & kind version for CI
  go.mod
  go.sum
  scripts/check-container-environment.sh
Labels: severity/high, area/maintenance

#2478 fix: skip logging errors for usage reports
  internal/util/reports.go
Labels: severity/low, area/maintenance

#2507 feat: ingress translator w/ combined routes
  .github/workflows/test.yaml
  CHANGELOG.md
  FEATURE_GATES.md
  Makefile
  examples/ingress.yaml
  internal/dataplane/kong_client.go
  internal/dataplane/kongstate/service.go
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/translate_ingress.go
  internal/dataplane/parser/translators/ingress.go
  internal/dataplane/parser/translators/ingress_test.go
  internal/manager/feature_gates.go
  internal/manager/run.go
  test/integration/httproute_test.go
  test/integration/suite_test.go
  test/integration/tcproute_test.go
  test/integration/utils_test.go
Labels: area/feature, severity/high

#2506 fix: Refactors the function return for `store` pkg
  internal/store/store.go
Labels: pending author feedback, severity/low, area/maintenance

#2525 fix(build): remove default for TARGETARCH which made arm64 builds end up with amd64 binaries
  Dockerfile
  Makefile
Labels: area/ci

#2528 chore: update gopkg.in/yaml to v3
  go.mod
  go.sum
Labels: severity/medium, area/maintenance
