Repository Kong/kubernetes-ingress-controller, pull requests merged in 2023-10, with the labels that each got.

#4760 chore: remove deprecated KongIngress functionality
  CHANGELOG.md
  internal/admission/handler.go
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/route.go
  internal/dataplane/kongstate/route_test.go
  internal/dataplane/kongstate/service.go
  internal/dataplane/kongstate/service_test.go
  internal/dataplane/kongstate/util.go
  test/e2e/helpers_test.go
  test/integration/kongingress_test.go
  test/integration/kongingress_webhook_test.go
Labels: size/XL, area/CRD

#4762 feat(telemetry) add Kong router flavor
  CHANGELOG.md
  internal/manager/telemetry/reports.go
  test/envtest/telemetry_test.go
Labels: size/S

#4765 chore: replace (deprecate) flag family --publish-service, etc. with --ingress-service
  CHANGELOG.md
  CONTRIBUTING.md
  Makefile
  internal/cmd/rootcmd/rootcmd_test.go
  internal/controllers/gateway/gateway_controller.go
  internal/manager/config.go
  internal/manager/config_validation_test.go
  internal/manager/controllerdef.go
  internal/manager/run.go
  internal/manager/setup.go
  internal/manager/telemetry/manager.go
  internal/manager/telemetry/manager_test.go
  internal/util/test/controller_manager.go
  test/envtest/crds_envtest_test.go
  test/envtest/gateway_envtest_test.go
  test/envtest/gatewayclass_envtest_test.go
  test/envtest/k8s_objects_status_envtest_test.go
  test/envtest/programmed_condition_envtest_test.go
  test/envtest/run.go
  test/integration/gateway_test.go
Labels: area/ingress-controller, size/L

#4769 chore(docs): add autogenerated flags reference
  .github/ISSUE_TEMPLATE/release.yaml
  .github/workflows/release_docs.yaml
  Makefile
  docs/cli-arguments.md
  scripts/cli-arguments-docs-gen/main.go
  scripts/cli-arguments-docs-gen/post-process-for-konghq.sh
Labels: area/docs, area/maintenance, size/L

#4771 chore: update KongIngress algorithm CRD doc
  config/crd/bases/configuration.konghq.com_kongingresses.yaml
  deploy/single/all-in-one-dbless-enterprise.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless-legacy.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  docs/api-reference.md
  pkg/apis/configuration/v1/kongingress_types.go
Labels: area/docs, size/XS, area/CRD

#4566 chore: replace "runtime_group" with "control_plane" in konnect APIs
  CHANGELOG.md
  internal/adminapi/konnect.go
  internal/konnect/license/client.go
  internal/konnect/nodes/client.go
  test/e2e/konnect_test.go
Labels: work in progress, size/S, area/konnect

#4770 chore: remove deprecated flags for 3.0
  CHANGELOG.md
  internal/manager/config.go
Labels: size/M

#4782 tests: use `ingressClass` spec field instead of a deprecated `kubernetes.io/ingress.class` annotation
  test/e2e/features_test.go
  test/e2e/helpers_test.go
  test/e2e/istio_test.go
  test/integration/config_error_event_test.go
  test/integration/consumer_group_test.go
  test/integration/consumer_test.go
  test/integration/ingress_https_test.go
  test/integration/ingress_test.go
  test/integration/kongingress_test.go
  test/integration/plugin_test.go
  test/integration/translation_failures_test.go
Labels: area/tests, area/maintenance, size/L

#4784 fix: mention in release template usage of main for major/minor
  .github/ISSUE_TEMPLATE/release.yaml
Labels: area/release, size/XS

#4785 chore: use 'control plane' instead of 'runtime group' naming
  Makefile
  docs/cli-arguments.md
  hack/cleanup/konnect_runtime_groups.go
  hack/cleanup/main.go
  internal/adminapi/backoff_strategy_konnect.go
  internal/adminapi/client.go
  internal/adminapi/konnect.go
  internal/adminapi/konnect_test.go
  internal/clients/manager.go
  internal/dataplane/kong_client.go
  internal/dataplane/sendconfig/sendconfig.go
  internal/dataplane/sendconfig/strategy.go
  internal/dataplane/sendconfig/strategy_test.go
  internal/konnect/controlplanes/client.go
  internal/konnect/controlplanesconfig/client.go
  internal/konnect/license/client.go
  internal/konnect/node_agent.go
  internal/konnect/node_agent_test.go
  internal/konnect/nodes/client.go
  internal/konnect/roles/client.go
  internal/konnect/roles/client_test.go
  internal/manager/config.go
  internal/manager/config_validation_test.go
  internal/manager/run.go
  test/e2e/konnect_test.go
Labels: area/maintenance, size/XL

#4786 tests: migrate `TestIngressWorksWithServiceBackendsSpecifyingOnlyPortNames` integration tests to envtest suite
  internal/cmd/rootcmd/run.go
  internal/manager/config.go
  test/envtest/ingress_test.go
  test/envtest/manager_debugendpoints_test.go
  test/envtest/run.go
  test/envtest/setup.go
  test/integration/ingress_test.go
  test/mocks/admin_api_handler.go
Labels: area/tests, size/L

#4781 chore(tests): fix flaky asserts in TestParserSNI
  internal/dataplane/parser/parser_test.go
Labels: area/tests, test-flake

#4792 chore: remove RegexHeaderVersionCutoff check
  internal/admission/validation/gateway/httproute.go
  internal/admission/validation/gateway/httproute_test.go
  internal/admission/validator.go
  internal/dataplane/parser/translate_httproute.go
  internal/dataplane/parser/translate_utils.go
  internal/dataplane/parser/translate_utils_test.go
  internal/versions/versions.go
  test/integration/httproute_test.go
Labels: size/L

#4799 tests: run envtest suite in parallel, add test.envtest.pretty
  Makefile
  test/envtest/crds_envtest_test.go
  test/envtest/gateway_envtest_test.go
  test/envtest/k8s_objects_status_envtest_test.go
  test/envtest/manager_envtest_test.go
  test/envtest/setup.go
  test/envtest/telemetry_test.go
Labels: area/tests, size/L

#4800 chore: remove TLSPassthroughCutoff leftover
  internal/versions/versions.go
Labels: size/XS

#4793 chore: remove ConsumerGroupsVersionCutoff check
  internal/admission/errors.go
  internal/admission/validator.go
  internal/admission/validator_test.go
  internal/versions/versions.go
  test/integration/consumer_group_test.go
Labels: size/M

#4798 chore: extract test dependencies to a separate file
  .github/test_dependencies.yaml
  .github/workflows/_e2e_tests.yaml
  .github/workflows/_integration_tests.yaml
Labels: area/ci, dependencies, size/L

#4803 tests(integration): log setup failure reason
  test/integration/utils_test.go
Labels: area/tests, size/XS

#4804 chore: drop unnecessary version field in UpdateStrategyInMemory
  internal/dataplane/sendconfig/inmemory.go
  internal/dataplane/sendconfig/strategy.go
Labels: area/maintenance

#4790 tests: migrate `TestConfigErrorEventGeneration` to envtest suite
  test/envtest/adminapimock.go
  test/envtest/configerrorevent_envtest_test.go
  test/envtest/crds_envtest_test.go
  test/envtest/gateway_envtest_test.go
  test/envtest/ingress_test.go
  test/envtest/k8s_objects_status_envtest_test.go
  test/envtest/kongstate_consumer_failures_test.go
  test/envtest/manager_debugendpoints_test.go
  test/envtest/manager_envtest_test.go
  test/envtest/programmed_condition_envtest_test.go
  test/envtest/run.go
  test/envtest/setup.go
  test/integration/config_error_event_test.go
  test/mocks/admin_api_handler.go
Labels: area/tests, size/L

#4797 chore: remove MTLSCredentialVersionCutoff check
  internal/dataplane/kongstate/consumer.go
  internal/dataplane/kongstate/consumer_test.go
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/kongstate_test.go
  internal/dataplane/parser/parser.go
  internal/versions/versions.go
Labels: size/M

#4807 test(e2e): update kind node image tags
  .github/test_dependencies.yaml
Labels: area/ci, size/S

#4810 chore: remove ExpressionRouterL4Cutoff check
  internal/controllers/configuration/object_references_test.go
  internal/dataplane/deckgen/deckgen_test.go
  internal/dataplane/deckgen/generate.go
  internal/dataplane/deckgen/generate_test.go
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_test.go
  internal/dataplane/parser/golden_test.go
  internal/dataplane/parser/translate_failures_test.go
  internal/dataplane/parser/translate_kong_l4.go
  internal/dataplane/parser/translate_tcproute.go
  internal/dataplane/parser/translate_tcproute_test.go
  internal/dataplane/parser/translate_udproute.go
  internal/dataplane/parser/translate_udproute_test.go
  internal/dataplane/sendconfig/kong.go
  internal/manager/run.go
  internal/versions/deck.go
  internal/versions/deck_test.go
  internal/versions/versions.go
  test/expressionrouter/helpers_test.go
  test/internal/helpers/kong.go
Labels: size/L

#4811 ci: add errname linter
  .golangci.yaml
  Makefile
  internal/dataplane/kongstate/util.go
  internal/dataplane/parser/ingressclassparemeters_test.go
  internal/dataplane/parser/translate_ingress.go
  internal/dataplane/parser/translate_tlsroute.go
  internal/store/errors.go
  internal/store/fake_store_test.go
  internal/store/store.go
Labels: area/ci, size/M

#4809 feat(expression router) add validation to creating predicates
  internal/dataplane/parser/atc/expression_test.go
  internal/dataplane/parser/atc/predicate.go
  internal/dataplane/parser/atc/predicate_test.go
  internal/dataplane/parser/translators/l4route_atc.go
Labels: size/L

#4813 fix: handle flattened errors related to whole entities
  CHANGELOG.md
  internal/dataplane/sendconfig/error_handling_test.go
  internal/dataplane/sendconfig/inmemory_error_handling.go
  internal/dataplane/sendconfig/sendconfig.go
  test/envtest/configerrorevent_envtest_test.go
  test/integration/config_error_event_test.go
Labels: size/L, fix

#4788 test: add host to MustHTTPRequest and implement HTTP client with proxy
  test/expressionrouter/generate_test.go
  test/integration/consumer_group_test.go
  test/integration/consumer_test.go
  test/integration/gateway_test.go
  test/integration/httproute_test.go
  test/integration/ingress_regex_match_test.go
  test/integration/ingress_test.go
  test/integration/plugin_test.go
  test/internal/helpers/http.go
Labels: area/tests, size/L

#4808 feat: provide Kong admin token via file
  CHANGELOG.md
  docs/cli-arguments.md
  internal/manager/config.go
  internal/manager/config_test.go
  internal/manager/config_validation.go
  internal/manager/config_validation_test.go
  internal/manager/run.go
Labels: size/M

#4817 fix: allow run validation webhook tests with Lima based env
  internal/util/test/webhooks.go
  test/conformance/suite_test.go
  test/integration/webhook_test.go
Labels: size/M, area/admission

#4826 chore: add missing kind renovate annotations
  .github/test_dependencies.yaml
Labels: area/ci, dependencies, size/S

#4778 check issues state
  .github/workflows/check_fixed_issues_references.yaml
  .github/workflows/e2e_nightly.yaml
  hack/check_fixed_issues_references.sh
  hack/generators/controllers/networking/main.go
  internal/admission/validation/gateway/httproute.go
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/route_utils.go
  internal/dataplane/kongstate/upstream.go
  internal/dataplane/synchronizer.go
  pkg/apis/configuration/v1/kongingress_types.go
  test/integration/gateway_test.go
Labels: size/M

#4830 chore: setup GKE Renovate custom datasource
  .github/test_dependencies.yaml
  renovate.json
Labels: area/ci, dependencies, size/S

#4827 chore(refactor): reuse tested code in test helpers
  internal/manager/telemetry/reports.go
  internal/manager/utils/kongconfig/root.go
  internal/manager/utils/kongconfig/root_test.go
  test/internal/helpers/kong.go
Labels: area/tests, area/maintenance, size/XXL

#4833 chore: remove test matrix checkup from release template
  .github/ISSUE_TEMPLATE/release.yaml
Labels: area/docs, area/maintenance, size/XS

#4837 chore(tests): remove event generation integration test
  test/envtest/configerrorevent_envtest_test.go
  test/integration/config_error_event_test.go
Labels: area/tests, size/L

#4802 chore: add kongintegration test flavor and cover UpdateStrategyInMemory as a reference
  .github/test_dependencies.yaml
  .github/workflows/_kongintegration_tests.yaml
  .github/workflows/checks.yaml
  Makefile
  TESTING.md
  go.mod
  go.sum
  test/kongintegration/doc.go
  test/kongintegration/inmemory_update_strategy_test.go
  test/kongintegration/kong.go
Labels: area/ci, area/tests, size/L

#4796 fix: fix deploy-admission-controller.sh broken on darwin
  hack/deploy-admission-controller.sh
Labels: area/maintenance, size/S

#4832 review: decorate client instead of calling multiple times
  hack/generators/controllers/networking/main.go
  internal/controllers/configuration/kongadminapi_controller.go
  internal/controllers/configuration/secret_controller.go
  internal/controllers/configuration/zz_generated_controllers.go
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gatewayclass_controller.go
  internal/controllers/gateway/grpcroute_controller.go
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/referencegrant_controller.go
  internal/controllers/gateway/tcproute_controller.go
  internal/controllers/gateway/tlsroute_controller.go
  internal/controllers/gateway/udproute_controller.go
  internal/controllers/reference/indexer.go
  internal/manager/controllerdef.go
  internal/manager/type_meta_setting_client.go
  internal/util/types.go
  internal/util/types_test.go
  test/integration/consumer_test.go
Labels: size/L

#4835 fix: fix typo in UDPRoute controller's watch
  CHANGELOG.md
  internal/controllers/gateway/udproute_controller.go
Labels: size/XS, fix

#4806 chore: migrate expressionrouter tests to kongintegration
  Makefile
  go.mod
  test/expressionrouter/generate_test.go
  test/expressionrouter/helpers_test.go
  test/expressionrouter/suite_test.go
  test/kongintegration/containers/httpbin.go
  test/kongintegration/containers/kong.go
  test/kongintegration/expression_router_test.go
  test/kongintegration/inmemory_update_strategy_test.go
  test/kongintegration/kong.go
Labels: area/tests, size/XL

#4831 chore: remove ExplicitRegexPathVersionCutoff check
  go.sum
  internal/adminapi/kong_test.go
  internal/admission/validation/gateway/httproute.go
  internal/admission/validation/ingress/ingress.go
  internal/admission/validator.go
  internal/dataplane/parser/golden_test.go
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/parser_test.go
  internal/dataplane/parser/testdata/golden/grpcroute-example/regex-path-prefix-off_golden.yaml
  internal/dataplane/parser/testdata/golden/grpcroute-example/regex-path-prefix-off_settings.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-regex-prefix-exact-rule/regex-path-prefix-off_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-regex-prefix-exact-rule/regex-path-prefix-off_settings.yaml
  internal/dataplane/parser/translate_failures_test.go
  internal/dataplane/parser/translate_grpcroute.go
  internal/dataplane/parser/translate_httproute.go
  internal/dataplane/parser/translate_httproute_test.go
  internal/dataplane/parser/translate_ingress.go
  internal/dataplane/parser/translate_udproute_test.go
  internal/dataplane/parser/translators/grpcroute.go
  internal/dataplane/parser/translators/grpcroute_test.go
  internal/dataplane/parser/translators/ingress.go
  internal/dataplane/parser/translators/ingress_atc_test.go
  internal/dataplane/parser/translators/ingress_test.go
  internal/konnect/node_agent_test.go
  internal/manager/run.go
  internal/manager/setup.go
  internal/versions/versions.go
  test/integration/ingress_regex_match_test.go
  test/integration/ingress_test.go
  test/integration/ingress_webhook_test.go
Labels: size/XL

#4846 feat(ci): add renovate config for kong helm chart
  .github/test_dependencies.yaml
  .github/workflows/_conformance_tests.yaml
  .github/workflows/_e2e_tests.yaml
  .github/workflows/_integration_tests.yaml
  .github/workflows/_kongintegration_tests.yaml
  Makefile
  renovate.json
  test/conformance/suite_test.go
  test/consts/helm.go
  test/integration/suite_test.go
  test/internal/testenv/testenv.go
Labels: area/ci, size/M

#4805 chore: verify golden tests outputs validity against Kong
  Makefile
  internal/dataplane/parser/testdata/golden/consumer-group-example-ee/default_golden.yaml
  internal/dataplane/parser/testdata/golden/consumer-group-example-ee/in.yaml
  internal/dataplane/parser/testdata/golden/httproute-example/default_golden.yaml
  internal/dataplane/parser/testdata/golden/httproute-example/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/httproute-example/in.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-multiple-ports-for-one-service/default_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-multiple-ports-for-one-service/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-multiple-ports-for-one-service/in.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-rule-with-tls/default_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-rule-with-tls/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-rule-with-tls/in.yaml
  internal/dataplane/parser/testdata/golden/kongplugin-instance-name/default_golden.yaml
  internal/dataplane/parser/testdata/golden/kongplugin-instance-name/in.yaml
  test/kongintegration/containers/kong.go
  test/kongintegration/parser_golden_tests_outputs_test.go
Labels: area/tests, size/L

#4767 fix(controllers) expand TypeMeta population
  CHANGELOG.md
  hack/generators/controllers/networking/main.go
  internal/controllers/configuration/secret_controller.go
  internal/controllers/configuration/zz_generated_controllers.go
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gatewayclass_controller.go
  internal/controllers/gateway/grpcroute_controller.go
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/referencegrant_controller.go
  internal/controllers/gateway/tcproute_controller.go
  internal/controllers/gateway/tlsroute_controller.go
  internal/controllers/gateway/udproute_controller.go
  internal/controllers/reference/indexer.go
  internal/manager/run.go
  internal/manager/scheme/scheme.go
  internal/manager/setup.go
  internal/manager/type_meta_setting_client.go
  internal/store/store.go
  internal/store/store_test.go
  internal/util/types.go
  internal/util/types_test.go
  test/integration/consumer_test.go
Labels: size/L

#4852 chore(tests): enforce Kong Gateway in the version >= 3.4.1
  test/conformance/gateway_conformance_test.go
  test/consts.go
  test/envtest/programmed_condition_envtest_test.go
  test/integration/httproute_test.go
  test/integration/suite_test.go
  test/integration/version_test.go
  test/integration/webhook_test.go
  test/internal/helpers/kong.go
  test/kongintegration/containers/kong.go
Labels: area/tests, area/maintenance, size/L

#4860 tests(kongintegration): make kong version retrieval run in .Eventually()
  test/kongintegration/containers/kong.go
Labels: area/tests, size/M

#4871 test: fix flake on finding translation failure events if multiple events received
  test/integration/translation_failures_test.go
Labels: area/tests, size/M

#4866 chore: remove all in one dbless legacy manifest
  CHANGELOG.md
  deploy/single/all-in-one-dbless-legacy.yaml
  scripts/build-single-manifests.sh
Labels: size/XS

#4873 chore: remove all in one enterprise manifest
  CHANGELOG.md
  deploy/single/all-in-one-dbless-enterprise.yaml
  scripts/build-single-manifests.sh
Labels: area/maintenance, size/S

#4872 fix: enable by default referenceGrant controller
  internal/manager/controllerdef.go
Labels: size/XS

#4875 chore: don't use kustomize patchesStrategicMerge which is deprecated
  config/components/konnect/kustomization.yaml
  config/variants/enterprise-postgres/kong-enterprise-job.yaml
  config/variants/enterprise-postgres/kong-enterprise.yaml
  config/variants/enterprise-postgres/kustomization.yaml
  config/variants/enterprise/kustomization.yaml
  config/variants/konnect/base/kustomization.yaml
  config/variants/konnect/debug/kustomization.yaml
  config/variants/multi-gw/base/kustomization.yaml
  config/variants/postgres/wait/kustomization.yaml
  scripts/build-single-manifests.sh
Labels: area/maintenance, size/M

#4574 feat: support tls expression route.
  CHANGELOG.md
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/translate_failures_test.go
  internal/dataplane/parser/translate_tlsroute.go
  internal/dataplane/parser/translate_tlsroute_test.go
  test/integration/tlsroute_test.go
Labels: size/L

#4877 chore(refactor): simplify API of TCPEchoResponds and tlsEchoResponds
  test/e2e/helpers_gateway_test.go
  test/integration/examples_test.go
  test/integration/tcproute_test.go
  test/integration/tlsroute_test.go
  test/tcp_utils.go
Labels: area/tests, refactor, size/L

#4878 chore(deps): make Renovate bump kind/istio minors only for latest
  .github/test_dependencies.yaml
  renovate.json
Labels: area/ci, dependencies, size/M

#4780 feat(expression router): implement query parameter match of HTTPRoute
  CHANGELOG.md
  internal/admission/validation/gateway/httproute.go
  internal/admission/validation/gateway/httproute_test.go
  internal/dataplane/parser/atc/field.go
  internal/dataplane/parser/atc/predicate.go
  internal/dataplane/parser/translate_httproute.go
  internal/dataplane/parser/translators/httproute_atc.go
  internal/dataplane/parser/translators/httproute_atc_test.go
  internal/gatewayapi/aliases.go
  internal/util/builder/httproutematch.go
  test/conformance/gateway_conformance_test.go
  test/conformance/gateway_expermimental_conformance_test.go
  test/integration/httproute_test.go
Labels: area/gateway-api, size/L

#4881 test(integration): remove skipTestForExpressionRouter helper in tests
  test/integration/examples_test.go
  test/integration/gateway_test.go
  test/integration/kongingress_test.go
  test/integration/kongingress_webhook_test.go
  test/integration/skip_helpers_test.go
  test/integration/tcpingress_test.go
  test/integration/translation_failures_test.go
Labels: size/S

#4883 fix(tests): fix setting GKE cluster version setting
  test/e2e/helpers_test.go
Labels: area/tests

#4884 tests: use testenv.ClusterVersion() for cluster version in E2E tests
  test/e2e/environment.go
  test/e2e/features_test.go
  test/e2e/helpers_test.go
  test/internal/testenv/testenv.go
Labels: area/tests, size/M

#4855 chore(gateway) use dedicated publish annotation
  internal/annotations/annotations.go
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gateway_controller_test.go
  test/conformance/gateway_conformance_test.go
  test/conformance/suite_test.go
  test/e2e/helpers_gateway_test.go
  test/envtest/gatewayclass_envtest_test.go
  test/integration/gateway_test.go
  test/integration/gateway_webhook_test.go
  test/integration/helpers_test.go
Labels: size/M

#4825 Determine credential type from label
  CHANGELOG.md
  internal/admission/handler.go
  internal/admission/validation/consumers/credentials/validation.go
  internal/admission/validation/consumers/credentials/validation_test.go
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/kongstate_test.go
  internal/dataplane/parser/parser.go
  internal/labels/labels.go
  internal/util/credential.go
  internal/util/credential_test.go
  test/envtest/kongstate_consumer_failures_test.go
Labels: size/L

#4894 tests: add `GracefulShutdownTimeout` option to manager to extend it in tests
  internal/manager/config.go
  internal/manager/setup.go
  test/envtest/run.go
Labels: area/tests, size/XS

#4895 chore(deps): enable kustomize manager in Renovate
  .github/ISSUE_TEMPLATE/release.yaml
  renovate.json
Labels: dependencies, size/S

#4887 fix: run basic credentials validation despite relation with consumers
  CHANGELOG.md
  hack/deploy-admission-controller.sh
  internal/admission/handler.go
  internal/admission/validator.go
  internal/admission/validator_test.go
  test/integration/webhook_test.go
Labels: size/L, fix, area/admission, backport release/2.12.x

#4906 chore: add changelog for 2.12.1
  CHANGELOG.md
Labels: area/docs, size/S

#4904 [backport release/2.12.x] fix: run basic credentials validation despite relation with consumers (#4887)
  CHANGELOG.md
  hack/deploy-admission-controller.sh
  internal/admission/handler.go
  internal/admission/validator.go
  internal/admission/validator_test.go
  test/integration/webhook_test.go
Labels: size/L, area/admission

#4909 chore: bump dependencies
  go.mod
  go.sum
Labels: dependencies, size/M

#4892 chore: remove feature gate ExpressionRoutes
  .github/workflows/_integration_tests.yaml
  CHANGELOG.md
  FEATURE_GATES.md
  internal/dataplane/parser/golden_test.go
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/parser_test.go
  internal/manager/featuregates/feature_gates.go
  internal/manager/run.go
  test/conformance/suite_test.go
  test/consts/feature_gates.go
  test/envtest/telemetry_test.go
Labels: size/M

#4910 chore(deps) bump k8s libs
  go.mod
  go.sum
Labels: size/S

#4893 chore: bump gateway API to 1.0.0-rc1
  CHANGELOG.md
  go.mod
  go.sum
  internal/admission/handler.go
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gateway_controller_test.go
  internal/controllers/gateway/gateway_utils.go
  internal/controllers/gateway/gateway_utils_test.go
  internal/controllers/gateway/gatewayclass_controller.go
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/route_utils.go
  internal/controllers/gateway/route_utils_test.go
  internal/dataplane/kongstate/util_test.go
  internal/dataplane/parser/testdata/golden/httproute-example/default_golden.yaml
  internal/dataplane/parser/testdata/golden/httproute-example/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/httproute-example/in.yaml
  internal/dataplane/parser/testdata/golden/same-name-services-single-backend/default_golden.yaml
  internal/dataplane/parser/testdata/golden/same-name-services-single-backend/in.yaml
  internal/dataplane/parser/translate_tlsroute.go
  internal/gatewayapi/aliases.go
  internal/gatewayapi/typemeta.go
  internal/manager/controllerdef.go
  internal/manager/scheme/scheme.go
  internal/store/fake_store.go
  internal/store/store.go
  internal/util/builder/routegroupkind.go
  test/conformance/gateway_conformance_test.go
  test/conformance/gateway_expermimental_conformance_test.go
  test/conformance/suite_test.go
  test/consts/zz_generated_gateway.go
  test/e2e/features_test.go
  test/e2e/helpers_gateway_test.go
  test/envtest/gatewayclass_envtest_test.go
  test/envtest/httproute_controller_test.go
  test/envtest/scheme.go
  test/envtest/telemetry_test.go
  test/integration/examples_test.go
  test/integration/gateway_test.go
  test/integration/gateway_webhook_test.go
  test/integration/helpers_test.go
  test/integration/httproute_test.go
  test/integration/httproute_webhook_test.go
  test/integration/tcproute_test.go
  test/integration/tlsroute_test.go
  test/integration/translation_failures_test.go
  test/integration/udproute_test.go
Labels: area/gateway-api, size/XL

#4917 tests(envtest): use comming log encoder in envtest suite when printing logs
  internal/util/logging.go
  test/envtest/run.go
Labels: area/tests, size/S

#4886 chore: separate validation and translation for HTTPRoute
  internal/dataplane/parser/translate_httproute.go
  internal/dataplane/parser/translate_httproute_test.go
Labels: size/L

#4921 revert: deprecate and replace flag family --publish-service, etc. with --ingress-service (#4765 & #4820)
  CHANGELOG.md
  CONTRIBUTING.md
  Makefile
  docs/cli-arguments.md
  internal/cmd/rootcmd/rootcmd_test.go
  internal/controllers/gateway/gateway_controller.go
  internal/manager/config.go
  internal/manager/config_validation_test.go
  internal/manager/controllerdef.go
  internal/manager/run.go
  internal/manager/setup.go
  internal/manager/telemetry/manager.go
  internal/manager/telemetry/manager_test.go
  internal/util/test/controller_manager.go
  test/envtest/configerrorevent_envtest_test.go
  test/envtest/crds_envtest_test.go
  test/envtest/gateway_envtest_test.go
  test/envtest/gatewayclass_envtest_test.go
  test/envtest/ingress_test.go
  test/envtest/k8s_objects_status_envtest_test.go
  test/envtest/run.go
  test/envtest/setup.go
  test/integration/gateway_test.go
Labels: size/L

#4919 chore(deps): auto-regenerate manifests on Renovate manifests bumps
  .github/workflows/regenerate_on_deps_bump.yaml
  renovate.json
Labels: area/ci, dependencies, size/M

#4920 chore(linter): in switch case default signifies exhaustive match
  .golangci.yaml
  internal/admission/handler.go
  internal/controllers/gateway/gateway_utils.go
  internal/manager/setup.go
  test/e2e/utils_test.go
  test/integration/helpers_test.go
Labels: area/ci, area/maintenance, size/S

#4727 Consolidate E2E environment variables with integration varaibles
  .github/workflows/_e2e_tests.yaml
  test/e2e/environment.go
  test/e2e/features_test.go
  test/e2e/helpers_test.go
  test/e2e/konnect_test.go
  test/e2e/utils_test.go
  test/internal/testenv/testenv.go
Labels: area/ci, area/tests, size/L

#4911 chore: change container UID and GID
  CHANGELOG.md
  Dockerfile
Labels: size/S

#4935 chore: update gatewayv1beta1 to gatewayv1 in examples and docs
  CHANGELOG.md
  examples/gateway-grpcroute.yaml
  examples/gateway-httproute.yaml
  examples/gateway-referencegrant-httproute.yaml
  examples/gateway-tcproute.yaml
  examples/gateway-tlsroute.yaml
  examples/gateway-udproute.yaml
  internal/controllers/gateway/httproute_controller.go
  internal/dataplane/parser/translators/httproute_atc.go
  internal/util/k8s_test.go
Labels: area/gateway-api, size/M

#4880 feat: define KongUpstreamPolicy CRD
  .golangci.yaml
  config/crd/bases/configuration.konghq.com_kongupstreampolicies.yaml
  docs/api-reference.md
  examples/kong-upstream-policy-httproute.yaml
  examples/kong-upstream-policy-service.yaml
  pkg/apis/configuration/v1beta1/kongupstreampolicy_types.go
  pkg/apis/configuration/v1beta1/zz_generated.deepcopy.go
  pkg/clientset/typed/configuration/v1beta1/configuration_client.go
  pkg/clientset/typed/configuration/v1beta1/fake/fake_configuration_client.go
  pkg/clientset/typed/configuration/v1beta1/fake/fake_kongupstreampolicy.go
  pkg/clientset/typed/configuration/v1beta1/generated_expansion.go
  pkg/clientset/typed/configuration/v1beta1/kongupstreampolicy.go
  scripts/apidocs-gen/generate.sh
  scripts/apidocs-gen/template/type.tpl
  scripts/apidocs-gen/template/type_members.tpl
Labels: size/XL

#4942 chore: exclude admin API comms from mesh
  CHANGELOG.md
  config/variants/multi-gw/oss/kustomization.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless.yaml
Labels: size/S

#4943 feat: add KongUpstreamPolicySpec translation
  config/crd/bases/configuration.konghq.com_kongupstreampolicies.yaml
  docs/api-reference.md
  internal/dataplane/parser/translators/kongupstreampolicy.go
  internal/dataplane/parser/translators/kongupstreampolicy_test.go
  pkg/apis/configuration/v1beta1/kongupstreampolicy_types.go
  pkg/apis/configuration/v1beta1/zz_generated.deepcopy.go
Labels: area/feature, size/L

#4953 chore: remove unused PortDefFromIntStr
  internal/dataplane/parser/translators/portdef.go
Labels: area/maintenance, size/XS

#4954 build: expand golangci-lint config to verify comments etc
  .golangci.yaml
  Makefile
  internal/admission/errors.go
  internal/annotations/annotations.go
  internal/dataplane/kong_client.go
  internal/dataplane/kongstate/types.go
  internal/dataplane/parser/atc/predicate.go
  test/consts/exit_codes.go
Labels: area/ci, area/maintenance, size/M

#4955 feat: add KongUpstreamPolicy CRD validation rules
  config/crd/bases/configuration.konghq.com_kongupstreampolicies.yaml
  docs/api-reference.md
  internal/dataplane/parser/translators/kongupstreampolicy.go
  internal/dataplane/parser/translators/kongupstreampolicy_test.go
  pkg/apis/configuration/v1beta1/kongupstreampolicy_types.go
  pkg/apis/configuration/v1beta1/zz_generated.deepcopy.go
  test/envtest/crds_envtest_test.go
Labels: area/feature, size/L

#4838 feat: HTTPRoute extensionRef filter converted onto plugin
  CHANGELOG.md
  internal/dataplane/parser/translate_httproute.go
  internal/dataplane/parser/translate_httproute_test.go
  internal/dataplane/parser/translators/httproute.go
  internal/dataplane/parser/translators/httproute_atc.go
  internal/dataplane/parser/translators/httproute_atc_test.go
  internal/dataplane/parser/translators/httproute_test.go
  internal/gatewayapi/aliases.go
Labels: area/gateway-api, size/L

#4952 fix(tests): print message instead of controller panic for expected errors
  internal/util/test/controller_manager.go
Labels: area/maintenance, size/XS, fix

#4957 chore: add kongintegration test for KongUpstreamPolicy translation
  config/crd/bases/configuration.konghq.com_kongupstreampolicies.yaml
  internal/dataplane/parser/translators/kongupstreampolicy_test.go
  pkg/apis/configuration/v1beta1/kongupstreampolicy_types.go
  test/envtest/crds_envtest_test.go
  test/kongintegration/kongupstreampolicy_test.go
Labels: area/tests, size/L

#4928 fix: set proper destination port for TCPRoute and UDPRoute
  CHANGELOG.md
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/translate_routes_helpers.go
  internal/dataplane/parser/translate_routes_helpers_test.go
  internal/dataplane/parser/translate_tcproute.go
  internal/dataplane/parser/translate_tcproute_test.go
  internal/dataplane/parser/translate_tlsroute.go
  internal/dataplane/parser/translate_udproute.go
  internal/dataplane/parser/translate_udproute_test.go
  test/integration/tcproute_test.go
  test/integration/tlsroute_test.go
Labels: breaking change, area/gateway-api, size/XL, fix

#4967 chore: move misplaced change entry
  CHANGELOG.md
Labels: area/docs, size/XS

#4962 chore(docs): update feature preview docs by removing mention to alpha Gatway API
  FEATURE_PREVIEW_DOCUMENTATION.md
Labels: area/docs, area/gateway-api, area/maintenance, size/XS

#4970 chore: remove (deprecate) all manifests from deploy/single
  .gitattributes
  CHANGELOG.md
  README.md
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  scripts/build-single-manifests.sh
  test/e2e/all_in_one_test.go
  test/e2e/konnect_test.go
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
  test/e2e/utils_test.go
Labels: breaking change, size/XXL

#4971 chore: add CLI flags for enabling and disabling Gateway API controllers
  Makefile
  docs/cli-arguments.md
  internal/manager/config.go
  internal/manager/controllerdef.go
  test/envtest/crds_envtest_test.go
  test/envtest/gateway_envtest_test.go
  test/envtest/k8s_objects_status_envtest_test.go
  test/envtest/kongstate_consumer_failures_test.go
  test/envtest/manager_envtest_test.go
  test/envtest/metrics_envtest_test.go
  test/envtest/programmed_condition_envtest_test.go
  test/envtest/run.go
Labels: area/gateway-api, area/maintenance, size/L

#4978 chore(ci): increase lint timeout to prevent CI failures
  .golangci.yaml
Labels: area/ci, area/maintenance, size/XS

#4965 chore(cleanup): remove obsolete example manifests
  deploy/manifests/dummy-application.yaml
  deploy/manifests/httpbin.yaml
  deploy/manifests/sample-apps/grpc.yaml
Labels: area/maintenance, size/L

#4969 feat: add KongUpstreamPolicy controller
  config/crd/kustomization.yaml
  config/rbac/role.yaml
  docs/cli-arguments.md
  hack/generators/controllers/networking/main.go
  internal/controllers/configuration/zz_generated_controllers.go
  internal/manager/config.go
  internal/manager/controllerdef.go
  internal/store/cache_stores.go
  internal/store/cache_stores_test.go
  internal/store/fake_store.go
  internal/store/fake_store_test.go
  internal/store/store.go
  internal/store/store_test.go
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
Labels: area/feature, size/XL

#4981 chore: bump gateway APIs to 1.0.0-rc2
  CHANGELOG.md
  go.mod
  go.sum
  test/conformance/gateway_conformance_test.go
  test/consts/zz_generated_gateway.go
Labels: area/gateway-api, size/S, kind/conformance

#4980 feat: listing nodes from Konnect using cursor pagination
  internal/konnect/nodes/client.go
  internal/konnect/nodes/types.go
Labels: size/S

#4986 chore(ci): remove k8s 1.23 from testing matrix
  .github/test_dependencies.yaml
Labels: area/ci, area/maintenance, size/XS

#4979 feat: allow setting hashOn.input in KongUpstreamPolicy
  config/crd/bases/configuration.konghq.com_kongupstreampolicies.yaml
  docs/api-reference.md
  internal/dataplane/parser/translators/kongupstreampolicy.go
  internal/dataplane/parser/translators/kongupstreampolicy_test.go
  pkg/apis/configuration/v1beta1/kongupstreampolicy_types.go
  pkg/apis/configuration/v1beta1/zz_generated.deepcopy.go
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
  test/envtest/crds_envtest_test.go
  test/kongintegration/kongupstreampolicy_test.go
Labels: area/feature, size/L

#4968 chore: update features gates for v3, remove Gateway feature gate
  CHANGELOG.md
  FEATURE_GATES.md
  internal/manager/controllerdef.go
  internal/manager/featuregates/feature_gates.go
  internal/manager/featuregates/feature_gates_test.go
  internal/manager/telemetry/manager_test.go
  test/envtest/run.go
  test/envtest/telemetry_test.go
Labels: area/docs, blocked, area/maintenance, size/M

#4934 chore: update router default
  .github/workflows/_integration_tests.yaml
  CHANGELOG.md
  config/base/kong-ingress-dbless.yaml
  config/variants/multi-gw/base/gateway_deployment.yaml
  config/variants/postgres/kustomization.yaml
  test/e2e/compatibilities_test.go
  test/e2e/helpers_test.go
  test/e2e/kustomizations_test.go
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
  test/e2e/utils_test.go
Labels: size/L

#4988 tests: fix `TestKongRouterFlavorCompatibility` e2e test and make it test all Kong Gateway flavors
  test/e2e/compatibilities_test.go
  test/e2e/helpers_test.go
Labels: area/tests, size/S

#4985 chore: more consistent CLI flags' descriptions, improve generation of cli-arguments.md
  docs/cli-arguments.md
  internal/manager/config.go
  scripts/cli-arguments-docs-gen/main.go
Labels: area/docs, area/tests, size/L

#4994 fix: set router flavor to traditional_compatible in konnect related manifests
  config/components/konnect/manager.yaml
  config/variants/konnect/base/manager.yaml
  config/variants/konnect/debug/manager_debug.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
Labels: area/tests, size/M, area/konnect

#4997 tests: fix `TestDeployAndUpgradeAllInOneDBLESS` tests by using traditional router in upgrade tests
  test/e2e/upgrade_test.go
Labels: area/tests, size/S

#5003 fix: fix a panic when receiving a broken config from Gateway
  CHANGELOG.md
  internal/dataplane/configfetcher/config_fetcher.go
  internal/dataplane/configfetcher/kongrawstate.go
  internal/dataplane/configfetcher/kongrawstate_test.go
Labels: bug, size/M

#5007 chore(docs): update README for KIC 3.0.0
  README.md
Labels: area/docs, size/M

#5006 chore: add changelog entry for KongUpstreamPolicy
  CHANGELOG.md
Labels: area/docs, size/S

#5005 tests: workaround docker bug affecting kongintegration flakiness
  Makefile
  internal/manager/health_check_test.go
  test/e2e/utils_test.go
  test/envtest/ingress_test.go
  test/envtest/manager_debugendpoints_test.go
  test/envtest/run.go
  test/helpers/ports.go
  test/kongintegration/containers/httpbin.go
  test/kongintegration/containers/kong.go
  test/kongintegration/containers/ports.go
  test/kongintegration/parser_golden_tests_outputs_test.go
Labels: area/tests, size/L, fix

#5019 feat: set KIC's UserAgent
  internal/manager/config.go
Labels: size/XS

#5024 fix: use only 46 bits for priorities of Kong routes
  CHANGELOG.md
  internal/dataplane/parser/testdata/golden/grpcroute-example/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/httproute-example/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-empty-path/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-multiple-ports-for-one-service/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-ports-defined-by-name/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-regex-prefix-exact-rule/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-regex-prefixed-path/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-rule-with-tls/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-single-service-in-multiple-ingresses/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-with-acme-like-path/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-with-default-backend/expression-routes-on_golden.yaml
  internal/dataplane/parser/translators/atc_utils.go
  internal/dataplane/parser/translators/grpcroute_atc.go
  internal/dataplane/parser/translators/grpcroute_atc_test.go
  internal/dataplane/parser/translators/httproute_atc.go
  internal/dataplane/parser/translators/httproute_atc_test.go
  internal/dataplane/parser/translators/ingress_atc_test.go
Labels: size/L

#5025 chore(docs): add CHANGELOG for adding UserAgent in 3.0
  CHANGELOG.md
Labels: area/docs, size/XS

#4989 feat: override Upstream config with KongUpstreamPolicy
  config/crd/bases/configuration.konghq.com_kongupstreampolicies.yaml
  docs/api-reference.md
  examples/kong-upstream-policy-ingress.yaml
  internal/annotations/annotations.go
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/kongstate_test.go
  internal/dataplane/kongstate/kongupstreampolicy.go
  internal/dataplane/kongstate/kongupstreampolicy_test.go
  internal/dataplane/kongstate/upstream.go
  internal/dataplane/kongstate/upstream_test.go
  internal/dataplane/kongstate/util.go
  internal/dataplane/kongstate/util_test.go
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/testdata/golden/host-header-annotation-httproute/default_golden.yaml
  internal/dataplane/parser/testdata/golden/host-header-annotation-httproute/in.yaml
  internal/dataplane/parser/testdata/golden/kongupstreampolicy-httproute/default_golden.yaml
  internal/dataplane/parser/testdata/golden/kongupstreampolicy-httproute/in.yaml
  internal/dataplane/parser/testdata/golden/kongupstreampolicy-ingress/default_golden.yaml
  internal/dataplane/parser/testdata/golden/kongupstreampolicy-ingress/in.yaml
  internal/store/store.go
  pkg/apis/configuration/v1beta1/kongupstreampolicy_types.go
  pkg/apis/configuration/v1beta1/zz_generated.deepcopy.go
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
  test/envtest/crds_envtest_test.go
  test/kongintegration/kongupstreampolicy_test.go
Labels: area/feature, size/XXL, area/CRD

#5029 fix: use debug level for readiness checks logs
  CHANGELOG.md
  internal/clients/readiness.go
  internal/dataplane/sendconfig/backoff_strategy.go
Labels: size/S, fix, backport release/2.12.x

#5008 docs(README): Make the Helm installation command simpler.
  README.md
Labels: size/XS

#5031 chore: add #5030 changelog entry for release 2.12.1
  CHANGELOG.md
Labels: area/docs, size/XS

#4987 fix: set accepted even if gateway could not be programmed and attach route to listener even if listener not ready
  CHANGELOG.md
  Makefile
  go.mod
  go.sum
  internal/controllers/gateway/gateway_utils.go
  internal/controllers/gateway/gateway_utils_test.go
  internal/controllers/gateway/grpcroute_controller.go
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/route_utils.go
  internal/controllers/gateway/route_utils_test.go
  internal/controllers/gateway/tcproute_controller.go
  internal/controllers/gateway/tlsroute_controller.go
  internal/controllers/gateway/udproute_controller.go
  test/conformance/gateway_conformance_test.go
Labels: area/gateway-api, size/L

#5030 Backport #5029 to release/2.12.x
  internal/clients/readiness.go
Labels: size/S, fix

#5022 Handle `KongIngress` deprecation in admission webhook and in `KongIngress` validation rules
  CHANGELOG.md
  config/crd/bases/configuration.konghq.com_kongingresses.yaml
  go.mod
  go.sum
  hack/deploy-admission-controller.sh
  internal/admission/handler.go
  internal/admission/handler_test.go
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/kongstate_test.go
  pkg/apis/configuration/v1/kongingress_types.go
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
  test/envtest/crds_envtest_test.go
  test/integration/kongingress_webhook_test.go
Labels: area/maintenance, size/L, area/CRD

#5039 chore: remove unused KongClient's ingressClass field
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_test.go
  internal/manager/run.go
Labels: area/maintenance

#5041 chore: bump GWAPI to 1.0, fix target test.conformance-experimental
  .github/workflows/conformance_tests_report.yaml
  .gitignore
  Makefile
  README.md
  go.mod
  go.sum
  test/conformance/gateway_conformance_test.go
  test/conformance/gateway_expermimental_conformance_test.go
  test/conformance/suite_test.go
  test/consts/zz_generated_gateway.go
Labels: area/ci, area/tests, dependencies, size/L, kind/conformance
