Repository Kong/kubernetes-ingress-controller, pull requests merged in 2023-01, with the labels that each got.

#3312 fix: replace * in name of kong routes
  CHANGELOG.md
  internal/dataplane/parser/translators/ingress.go
  internal/dataplane/parser/translators/ingress_test.go
  test/integration/ingress_test.go
Labels: size/L

#3304 chore(ci): allow running pre-release pipeline
  .github/workflows/release.yaml
Labels: area/ci, area/release, size/M

#3273 refactor: remove unused code
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gateway_controller_test.go
  internal/controllers/gateway/gateway_utils.go
  internal/controllers/gateway/referencegrant_controller.go
  internal/dataplane/sendconfig/kong.go
  internal/util/types.go
Labels: area/maintenance, size/L

#3313 fix: use port name when port number is not provided in combined routes
  CHANGELOG.md
  internal/dataplane/parser/translate_ingress.go
  internal/dataplane/parser/translate_knative.go
  internal/dataplane/parser/translators/ingress.go
  internal/dataplane/parser/translators/ingress_test.go
  internal/dataplane/parser/translators/portdef.go
  test/integration/ingress_test.go
Labels: size/L

#3307 build: add skaffold debugging and running in cluster code
  .gitignore
  Makefile
  config/debug/kustomization.yaml
  config/debug/manager_debug.yaml
  config/dev/kustomization.yaml
  config/dev/manager_dev.yaml
  skaffold.yaml
  third_party/dlv.go
  third_party/go.mod
  third_party/go.sum
Labels: size/L

#3319 fix: parse ttl to int in key auth credentials
  CHANGELOG.md
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/kongstate_test.go
Labels: size/S

#3317 chore(ci) update and sync action version
  .github/workflows/release.yaml
  .github/workflows/release_docs.yaml
Labels: size/XS

#3323 Add 2.8.1 release changes
  .github/ISSUE_TEMPLATE/release.yaml
  CHANGELOG.md
  LICENSES
  config/image/oss/kustomization.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
Labels: size/XXL

#3327 fix: set max-parallel to 16 on e2e tests on GKE
  .github/workflows/release.yaml
Labels: area/ci, size/XS

#3329 chore(ci): fix GKE cleanup for broken clusters
  hack/e2e/cluster/cleanup/main.go
Labels: area/ci, area/maintenance, size/M

#3330 chore(ci): replace set-output with GITHUB_OUTPUT
  .github/workflows/e2e.yaml
  .github/workflows/release.yaml
Labels: area/ci, area/maintenance, size/XS

#3335 chore(ci): don't run each e2e case in separate worker
  .github/workflows/release.yaml
Labels: area/ci, size/M

#3337 chore: add v2.8.1 diff link to changelog
  CHANGELOG.md
Labels: size/XS

#3336 fix(reports) skip mesh when namespace-limited
  CHANGELOG.md
  internal/manager/run.go
  internal/manager/utils/reports.go
Labels: size/M

#3262 refactor: delete custom entities
  CHANGELOG.md
  internal/dataplane/deckgen/deckgen.go
  internal/dataplane/kong_client.go
  internal/dataplane/sendconfig/sendconfig.go
  internal/dataplane/sendconfig/sendconfig_test.go
  internal/manager/config.go
Labels: area/debt, refactor, size/L

#3351 refactor: refactor rootcmd, add command context, mark deprecated flags with `flagSet.MarkDeprecated`
  internal/cmd/rootcmd/rootcmd.go
  internal/cmd/rootcmd/run.go
  internal/cmd/rootcmd/signal.go
  internal/manager/config.go
  internal/util/test/controller_manager.go
Labels: area/maintenance, size/M

#3346 fix: only check if condition contained in ensuring gateway associated of httproute
  CHANGELOG.md
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/route_utils.go
Labels: size/S

#3353 build: add staticcheck
  Makefile
  config/crd/bases/configuration.konghq.com_kongclusterplugins.yaml
  config/crd/bases/configuration.konghq.com_kongingresses.yaml
  config/crd/bases/configuration.konghq.com_kongplugins.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  docs/api-reference.md
  internal/dataplane/parser/translators/httproute.go
  internal/dataplane/parser/wrappers_backendref.go
  internal/manager/conditions.go
  internal/store/store.go
  internal/util/test/webhooks.go
  pkg/apis/configuration/v1/kongprotocol_types.go
  staticcheck.conf
  third_party/go.mod
  third_party/staticcheck.go
Labels: area/ci, size/M

#3347 chore(ci): don't run e2e in GKE clusters
  .github/workflows/e2e.yaml
  .github/workflows/release.yaml
Labels: area/debt, area/ci, size/L

#3366 docs: fix `KongIngressService` docs
  docs/api-reference.md
  pkg/apis/configuration/v1/kongingress_types.go
Labels: area/docs, size/XS

#3369 chores: use Gateway<Version><Kind> for object key in loggers inside gateway API controllers
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gatewayclass_controller.go
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/referencegrant_controller.go
  internal/controllers/gateway/tcproute_controller.go
  internal/controllers/gateway/tlsroute_controller.go
  internal/controllers/gateway/udproute_controller.go
Labels: size/S

#3370 refactor: pass parent ingress object
  internal/dataplane/parser/translators/ingress.go
  internal/dataplane/parser/translators/ingress_test.go
Labels: refactor, size/L

#3371 docs: fix KongProtocol doc
  config/crd/bases/configuration.konghq.com_kongclusterplugins.yaml
  config/crd/bases/configuration.konghq.com_kongingresses.yaml
  config/crd/bases/configuration.konghq.com_kongplugins.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  docs/api-reference.md
  pkg/apis/configuration/v1/kongprotocol_types.go
Labels: area/docs, size/M

#3372 chore(tests): allow creating gke clusters using getEnvironmentBuilder
  test/e2e/environment.go
  test/e2e/helpers_test.go
Labels: area/ci, area/tests, size/M

#3375 chore: improve logging in tests running commands
  internal/util/test/webhooks.go
  test/e2e/features_test.go
  test/e2e/helpers_test.go
  test/e2e/utils_test.go
Labels: area/tests, size/M

#3376 tests: upload diagnostics when enterprise tests fail
  .github/workflows/test.yaml
Labels: area/ci, area/tests, size/XS

#3377 build: remove manifests.single from verify.manifest as it's already part of manifests target
  Makefile
Labels: area/maintenance, size/XS

#3379 feat: add version command
  CHANGELOG.md
  Dockerfile
  Makefile
  internal/cmd/rootcmd/rootcmd.go
  internal/manager/config.go
Labels: area/feature, size/M

#3382 chore: silence cobra errors to prevent double message about exit error
  internal/cmd/rootcmd/rootcmd.go
Labels: area/maintenance, size/XS

#3386 fix: change existing resolvedRef condition to avoid duplicates
  CHANGELOG.md
  internal/controllers/gateway/httproute_controller.go
Labels: area/gateway-api, size/S

#3389 refactor: add a generic version of getting route parent refs map
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/route_parent_status.go
  internal/controllers/gateway/route_parent_status_test.go
  internal/controllers/gateway/tcproute_controller.go
  internal/controllers/gateway/tlsroute_controller.go
  internal/controllers/gateway/udproute_controller.go
Labels: area/gateway-api, refactor, size/L

#3381 test: fix TestHTTPRouteFilterHosts test by repeatedly querying for an HTTPRoute before Update
  test/integration/httproute_test.go
Labels: area/tests, size/M

#3342 feat: set "Programmed" condition for *Route in gateway APIs
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/route_parent_status.go
  internal/controllers/gateway/route_utils.go
  internal/controllers/gateway/tcproute_controller.go
  internal/controllers/gateway/tlsroute_controller.go
  internal/controllers/gateway/udproute_controller.go
  internal/types/types.go
  test/integration/helpers_test.go
  test/integration/httproute_test.go
  test/integration/tcproute_test.go
  test/integration/tlsroute_test.go
  test/integration/udproute_test.go
Labels: area/feature, area/gateway-api, size/XL

#3391 build: extract debug related targets from Dockerfile to separate one
  Dockerfile
  Dockerfile.debug
  Makefile
  config/debug/manager_debug.yaml
  skaffold.yaml
Labels: area/maintenance, size/M

#3392 fix: do not return an error when IngressClass does not reference IngressClassParameters
  internal/dataplane/parser/ingressclassparemeters_test.go
  internal/dataplane/parser/parser.go
  internal/store/store.go
Labels: area/maintenance, size/S

#3268 feat: add support for single controller, multi gateway deployments
  CHANGELOG.md
  go.mod
  go.sum
  internal/cmd/rootcmd/env_test.go
  internal/controllers/gateway/gateway_controller.go
  internal/dataplane/kong_client.go
  internal/dataplane/sendconfig/kong.go
  internal/dataplane/sendconfig/sendconfig.go
  internal/dataplane/synchronizer.go
  internal/manager/config.go
  internal/manager/run.go
  internal/manager/setup.go
  internal/manager/utils/kongconfig/root.go
  internal/manager/utils/kongconfig/root_test.go
  internal/manager/utils/reports.go
  internal/util/plugin_schema_helper.go
Labels: area/feature, size/XXL

#3378 tests: fix e2e tests for gke
  .github/workflows/cleanup.yaml
  .github/workflows/e2e.yaml
  go.mod
  go.sum
  hack/deploy-admission-controller.sh
  test/e2e/all_in_one_test.go
  test/e2e/compatibilities_test.go
  test/e2e/features_test.go
  test/e2e/helpers_gateway_test.go
  test/e2e/helpers_test.go
  test/e2e/istio_test.go
  test/e2e/kuma_test.go
  test/e2e/utils_test.go
Labels: area/ci, area/tests, size/XL

#3395 chore(ci): move 'concurrency' property from job to workflow level
  .github/workflows/e2e.yaml
Labels: area/ci, size/XS

#3398 tests: fix TestGatewayFilters
  test/integration/gateway_test.go
Labels: area/tests, area/maintenance, test-flake, size/L

#3399 chore(ci): cleanup gke related scripts
  .github/workflows/cleanup.yaml
  .github/workflows/e2e.yaml
  Makefile
  hack/cleanup_gke_clusters.go
  test/e2e/clusters.go
  test/e2e/helpers_test.go
Labels: size/L

#3403 chore: remove #3393 todo
  test/e2e/features_test.go
Labels: area/maintenance, size/S

#3404 refactor: don't check service upstream twice for service
  internal/dataplane/parser/parser.go
Labels: refactor, size/M

#3405 feat: add Config.Validate() to allow validation of configuration options before starting the manager
  internal/cmd/rootcmd/rootcmd.go
  internal/cmd/rootcmd/rootcmd_test.go
  internal/cmd/rootcmd/run.go
  internal/manager/config.go
  internal/manager/config_test.go
  internal/manager/controllerdef.go
  internal/manager/feature_gates.go
  internal/manager/feature_gates_test.go
  internal/manager/flagnamespacedname.go
  internal/manager/run.go
  internal/manager/setup.go
Labels: area/maintenance, refactor, size/L

#3413 chore: don't send anonymous reports when running locally
  Makefile
Labels: area/maintenance, size/XS

#3318 Include Kong service name in multi-Service Events
  CHANGELOG.md
  internal/dataplane/parser/ingressrules.go
  internal/dataplane/parser/ingressrules_test.go
  test/integration/translation_failures_test.go
Labels: size/M

#3416 chore(deps): bump github.com/emicklei/go-restful to v3.10.1
  go.mod
  go.sum
Labels: dependencies, size/XS

#3422 chore: add -trimpath when building debug binary
  Makefile
Labels: area/maintenance, size/XS

#3415 refactor: replace config validation with generic ValidatedValue implementation
  internal/manager/config.go
  internal/manager/config_test.go
  internal/manager/config_validation.go
  internal/manager/config_validation_test.go
  internal/manager/flagnamespacedname.go
  internal/manager/run.go
  internal/manager/setup.go
  internal/manager/validated.go
  internal/manager/validated_test.go
Labels: size/L

#3425 fix(tests): fix e2e data race when starting port forwarding
  test/e2e/utils_test.go
Labels: area/tests, size/XS

#3427 refactor: simplify udp address finder setup
  hack/generators/controllers/networking/main.go
  internal/controllers/configuration/zz_generated_controllers.go
  internal/dataplane/address_finder.go
  internal/dataplane/address_finder_test.go
  internal/manager/run.go
  internal/manager/setup.go
Labels: area/maintenance, size/L

#3419 ci: add concurrency to run tests only on most recent PR commit
  .github/workflows/codeql.yaml
  .github/workflows/test.yaml
Labels: area/ci, size/S

#3431 refactor(tests): refactor tests cleanup
  go.mod
  go.sum
  test/e2e/all_in_one_test.go
  test/e2e/compatibilities_test.go
  test/e2e/features_test.go
  test/e2e/helpers_test.go
  test/e2e/istio_test.go
  test/e2e/kuma_test.go
  test/integration/consumer_test.go
  test/integration/crd_validations_test.go
  test/integration/examples_test.go
  test/integration/gateway_test.go
  test/integration/httproute_test.go
  test/integration/httproute_webhook_test.go
  test/integration/ingress_https_test.go
  test/integration/ingress_regex_match_test.go
  test/integration/ingress_test.go
  test/integration/kongingress_webhook_test.go
  test/integration/plugin_test.go
  test/integration/tcpingress_test.go
  test/integration/tcproute_test.go
  test/integration/tlsroute_test.go
  test/integration/translation_failures_test.go
  test/integration/udpingress_test.go
  test/integration/udproute_test.go
  test/integration/utils_test.go
  test/internal/helpers/teardown.go
Labels: area/tests, refactor, size/XL

#3433 fix: don't constrain test helpers with build tags
  test/internal/helpers/teardown.go
Labels: area/tests, size/XS

#3434 tests: don't share context in integration tests
  test/integration/consumer_test.go
  test/integration/crd_validations_test.go
  test/integration/examples_test.go
  test/integration/gateway_test.go
  test/integration/gateway_webhook_test.go
  test/integration/helpers_test.go
  test/integration/httproute_test.go
  test/integration/httproute_webhook_test.go
  test/integration/ingress_https_test.go
  test/integration/ingress_regex_match_test.go
  test/integration/ingress_test.go
  test/integration/knative_test.go
  test/integration/kongingress_test.go
  test/integration/kongingress_webhook_test.go
  test/integration/plugin_test.go
  test/integration/suite_test.go
  test/integration/tcpingress_test.go
  test/integration/tcproute_test.go
  test/integration/tlsroute_test.go
  test/integration/translation_failures_test.go
  test/integration/udpingress_test.go
  test/integration/udproute_test.go
  test/integration/utils_test.go
  test/integration/webhook_test.go
Labels: area/tests, size/L

#3435 refactor: use 1 alias for k8s api errors package
  .golangci.yaml
  hack/generators/controllers/networking/main.go
  internal/admission/utils.go
  internal/admission/validator.go
  internal/controllers/configuration/secret_controller.go
  internal/controllers/configuration/zz_generated_controllers.go
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gateway_utils.go
  internal/controllers/gateway/gatewayclass_controller.go
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/referencegrant_controller.go
  internal/controllers/gateway/route_utils.go
  internal/controllers/gateway/tcproute_controller.go
  internal/controllers/gateway/tlsroute_controller.go
  internal/controllers/gateway/udproute_controller.go
  internal/controllers/knative/knative.go
  internal/controllers/reference/reference.go
  internal/util/test/crds.go
  test/e2e/helpers_gateway_test.go
  test/e2e/helpers_test.go
  test/integration/gateway_webhook_test.go
  test/integration/ingress_test.go
  test/integration/kongingress_test.go
  test/integration/suite_test.go
  test/integration/udproute_test.go
  test/integration/webhook_test.go
Labels: area/maintenance, size/L

#3441 tests: use cleanup for locking gateway ports to prevent `defer` and `t.Cleanup` ordering issues
  test/integration/examples_test.go
  test/integration/tcpingress_test.go
  test/integration/tcproute_test.go
  test/integration/tlsroute_test.go
  test/integration/udpingress_test.go
Labels: area/tests, size/L

#3440 tests: add matrix for integration tests
  .github/workflows/test.yaml
  Makefile
  test/integration/addons_knative_test.go
  test/integration/addons_test.go
  test/integration/knative_test.go
  test/integration/suite_test.go
Labels: area/ci, area/tests, size/L

#3442 ci: make codeql workflow happy by targeting only main
  .github/workflows/codeql.yaml
Labels: area/ci, size/XS

#3444 tests: use t.Cleanup() for locks on IngressClass in integration tests
  .github/workflows/test.yaml
  test/integration/ingress_test.go
Labels: area/tests, area/maintenance, size/L

#3445 chore(deps): bump skaffold to v2.1.0
  Makefile
Labels: area/maintenance, size/XS

#3453 tests: don't share http.Client in tests
  test/e2e/features_test.go
  test/e2e/helpers_gateway_test.go
  test/e2e/helpers_test.go
  test/e2e/istio_test.go
  test/e2e/utils_test.go
  test/integration/consumer_test.go
  test/integration/controller_test.go
  test/integration/examples_test.go
  test/integration/httproute_test.go
  test/integration/ingress_regex_match_test.go
  test/integration/ingress_test.go
  test/integration/kongingress_test.go
  test/integration/metrics_test.go
  test/integration/plugin_test.go
  test/integration/tcpingress_test.go
  test/integration/utils_test.go
  test/internal/helpers/http.go
Labels: area/tests, size/L

#3448 feat(konnect): add manifests for konnect config variant
  CHANGELOG.md
  Makefile
  config/variants/konnect/base/kustomization.yaml
  config/variants/konnect/base/manager.yaml
  config/variants/konnect/debug/.gitignore
  config/variants/konnect/debug/kustomization.yaml
  config/variants/konnect/debug/manager_debug.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  scripts/build-single-manifests.sh
  skaffold.yaml
Labels: size/XXL

#3458 tests: extract integration tests helpers so separate packages for reuse
  internal/util/test/controller_manager.go
  test/conformance/gateway_conformance_test.go
  test/consts/exit_codes.go
  test/consts/feature_gates.go
  test/consts/misc.go
  test/e2e/features_test.go
  test/integration/consts_test.go
  test/integration/consumer_test.go
  test/integration/crd_validations_test.go
  test/integration/examples_test.go
  test/integration/gateway_test.go
  test/integration/gateway_webhook_test.go
  test/integration/httproute_test.go
  test/integration/httproute_webhook_test.go
  test/integration/ingress_https_test.go
  test/integration/ingress_regex_match_test.go
  test/integration/ingress_test.go
  test/integration/knative_test.go
  test/integration/kongingress_test.go
  test/integration/kongingress_webhook_test.go
  test/integration/plugin_test.go
  test/integration/suite_test.go
  test/integration/tcpingress_test.go
  test/integration/tcproute_test.go
  test/integration/tlsroute_test.go
  test/integration/translation_failures_test.go
  test/integration/udpingress_test.go
  test/integration/udproute_test.go
  test/integration/utils_test.go
  test/integration/webhook_test.go
  test/internal/helpers/http.go
  test/internal/helpers/ingress.go
  test/internal/helpers/k8s.go
  test/internal/helpers/kong.go
  test/internal/helpers/ktf.go
  test/internal/helpers/namespace.go
  test/internal/helpers/setup.go
  test/internal/testenv/testenv.go
Labels: area/tests, area/maintenance, size/XXL
