Repository Kong/kubernetes-ingress-controller, pull requests merged in 2023-12, with the labels that each got.

#5234 feat: handle KongServiceFacade Ingress backends
  CHANGELOG.md
  FEATURE_GATES.md
  config/variants/multi-gw/dev/manager.yaml
  internal/admission/validation/ingress/ingress.go
  internal/admission/validator.go
  internal/admission/validator_test.go
  internal/dataplane/kongstate/types.go
  internal/dataplane/translator/golden_test.go
  internal/dataplane/translator/ingressrules.go
  internal/dataplane/translator/ingressrules_test.go
  internal/dataplane/translator/subtranslator/ingress.go
  internal/dataplane/translator/subtranslator/ingress_atc.go
  internal/dataplane/translator/subtranslator/ingress_atc_test.go
  internal/dataplane/translator/subtranslator/ingress_test.go
  internal/dataplane/translator/subtranslator/portdef.go
  internal/dataplane/translator/testdata/golden/kong-service-facade/default_golden.yaml
  internal/dataplane/translator/testdata/golden/kong-service-facade/expression-routes-on_golden.yaml
  internal/dataplane/translator/testdata/golden/kong-service-facade/expression-routes-on_settings.yaml
  internal/dataplane/translator/testdata/golden/kong-service-facade/feature-flag-on_golden.yaml
  internal/dataplane/translator/testdata/golden/kong-service-facade/feature-flag-on_settings.yaml
  internal/dataplane/translator/testdata/golden/kong-service-facade/in.yaml
  internal/dataplane/translator/translate_ingress.go
  internal/dataplane/translator/translator.go
  internal/manager/controllerdef.go
  internal/manager/featuregates/feature_gates.go
  internal/manager/run.go
  internal/manager/scheme/scheme.go
  internal/manager/setup.go
  internal/store/store.go
  internal/util/builder/ingress.go
  internal/util/builder/kongstateservicebackend.go
  pkg/apis/incubator/v1alpha1/kongservicefacade_types.go
  test/envtest/telemetry_test.go
Labels: area/feature, size/XXL

#5133 docs(readme): add KGO instructions alongside Helm
  README.md
Labels: size/S

#5267 fix: set tags on GRPCRoute routes
  CHANGELOG.md
  internal/dataplane/translator/subtranslator/grpcroute.go
  internal/dataplane/translator/subtranslator/grpcroute_test.go
Labels: size/S

#5275 fix: set tags on GRPCRoute routes (follow-up)
  CHANGELOG.md
  internal/dataplane/translator/subtranslator/grpcroute.go
  internal/dataplane/translator/subtranslator/grpcroute_test.go
  internal/dataplane/translator/testdata/golden/grpcroute-example/default_golden.yaml
Labels: size/M, fix

#5283 fix: restore defaulting to protocol "grpcs" for gRPC Service
  CHANGELOG.md
  examples/gateway-grpcroute-via-http.yaml
  examples/gateway-grpcroute-via-https.yaml
  internal/dataplane/translator/translate_grpcroute.go
  test/integration/isolated/examples_grpc_test.go
  test/integration/isolated/grpc_test.go
  test/integration/isolated/ingress_test.go
Labels: size/L, fix

#5270 fix: restore standard diagnostics port
  CHANGELOG.md
  internal/manager/config.go
Labels: size/XS, backport release/3.0.x

#5281 fix: tag Services backed by KongServiceFacade correctly
  internal/dataplane/translator/ingressrules.go
  internal/dataplane/translator/subtranslator/ingress.go
  internal/dataplane/translator/subtranslator/ingress_atc_test.go
  internal/dataplane/translator/subtranslator/ingress_test.go
  internal/dataplane/translator/testdata/golden/kong-service-facade/expression-routes-on_golden.yaml
  internal/dataplane/translator/testdata/golden/kong-service-facade/feature-flag-on_golden.yaml
Labels: area/feature, size/L

#5288 [backport release/3.0.x] fix: restore diagnostics server port (#5270)
  internal/manager/config.go
Labels: size/XS

#5287 test: skip TestIngressRewriteURI if rewrite uri is disabled
  test/integration/ingress_test.go
  test/internal/helpers/setup.go
Labels: area/tests, size/S, backport release/2.12.x

#5282 feat: add support of KongServiceFacade as default Ingress backend
  CHANGELOG.md
  internal/dataplane/translator/ingressrules.go
  internal/dataplane/translator/ingressrules_test.go
  internal/dataplane/translator/subtranslator/ingress.go
  internal/dataplane/translator/testdata/golden/kong-service-facade/expression-routes-on_golden.yaml
  internal/dataplane/translator/testdata/golden/kong-service-facade/feature-flag-on_golden.yaml
  internal/dataplane/translator/testdata/golden/kong-service-facade/in.yaml
  internal/dataplane/translator/translate_ingress.go
  internal/dataplane/translator/translate_ingress_test.go
  internal/dataplane/translator/translator_test.go
  internal/util/builder/ingress.go
  test/integration/isolated/ingress_test.go
  test/integration/isolated/suite_test.go
  test/internal/helpers/http.go
Labels: area/feature, size/XL

#5290 feat: set KongServiceFacade's Programmed condition
  CHANGELOG.md
  internal/dataplane/translator/ingressrules.go
  internal/dataplane/translator/ingressrules_test.go
  internal/dataplane/translator/subtranslator/ingress.go
  internal/dataplane/translator/subtranslator/ingress_atc_test.go
  internal/dataplane/translator/subtranslator/ingress_test.go
  internal/dataplane/translator/translator.go
  test/envtest/programmed_condition_envtest_test.go
  test/envtest/run.go
  test/envtest/scheme.go
  test/envtest/setup.go
Labels: area/feature, size/L

#5285 chore(gha): preemptively add 1p creds
  .github/workflows/_e2e_tests.yaml
  .github/workflows/_integration_tests.yaml
  .github/workflows/test_nightly.yaml
Labels: size/XS

#5297 fix(test): upgrade GKE version to v1.28.3
  .github/test_dependencies.yaml
Labels: size/XS

#5299 fix: change events emit toggle name to --emit-kubernetes-events
  CHANGELOG.md
  docs/cli-arguments.md
  internal/manager/config.go
  internal/manager/run.go
Labels: size/S

#5302 feat: rename incubator package to incubator.ingress-controller.konghq.com
  CHANGELOG.md
  config/crd/incubator/incubator.ingress-controller.konghq.com_kongservicefacades.yaml
  config/crd/incubator/kustomization.yaml
  config/rbac/role.yaml
  hack/generators/controllers/networking/main.go
  internal/controllers/configuration/zz_generated_controllers.go
  internal/dataplane/translator/testdata/golden/kong-service-facade/expression-routes-on_golden.yaml
  internal/dataplane/translator/testdata/golden/kong-service-facade/feature-flag-on_golden.yaml
  internal/dataplane/translator/testdata/golden/kong-service-facade/in.yaml
  internal/dataplane/translator/translator_test.go
  pkg/apis/incubator/doc.go
  pkg/apis/incubator/v1alpha1/doc.go
  pkg/apis/incubator/v1alpha1/groupversion_info.go
  pkg/clientset/typed/incubator/v1alpha1/incubator_client.go
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
Labels: area/feature, size/M

#5303 fix: allow GRPCRoute without hostnames and matches
  CHANGELOG.md
  internal/dataplane/translator/subtranslator/grpcroute.go
  internal/dataplane/translator/subtranslator/grpcroute_test.go
  internal/dataplane/translator/translate_grpcroute.go
  internal/dataplane/translator/translate_grpcroute_test.go
Labels: area/gateway-api, size/L, fix

#5305 Backport `--emit-kubernetes-events` to release/2.12.x
  CHANGELOG.md
  docs/cli-arguments.md
  internal/manager/config.go
  internal/manager/run.go
Labels: size/M, < v3.0.0

#5314 chore(ci): don't fix linting issues in CI
  .github/workflows/_linters.yaml
  Makefile
Labels: area/ci, size/XS

#5203 feat: add validation on secrets on generated plugin cofigs
  CHANGELOG.md
  internal/admission/handler.go
  internal/admission/handler_test.go
  internal/admission/server_test.go
  internal/admission/validator.go
  internal/admission/validator_test.go
  internal/controllers/configuration/object_references.go
  internal/controllers/reference/indexer.go
  internal/controllers/reference/indexer_test.go
  internal/manager/controllerdef.go
  internal/manager/run.go
  internal/manager/setup.go
  test/integration/webhook_test.go
Labels: area/feature, size/XL, area/admission

#5318 chore: bump E2E upgrade manifests
  test/e2e/upgrade_test.go
Labels: size/XS

#5320 fix: remove logs to print config and correct integration test names
  internal/admission/validator.go
  test/integration/webhook_test.go
Labels: size/XS, area/admission

#5312 feat: validate HTTPRoute features
  CHANGELOG.md
  internal/admission/validation/gateway/httproute.go
  internal/admission/validation/gateway/httproute_test.go
  internal/admission/validator.go
  internal/admission/validator_test.go
  internal/gatewayapi/aliases.go
Labels: size/L, area/admission

#5298 docs: add KongServiceFacade docs and examples
  CHANGELOG.md
  FEATURE_GATES.md
  config/crd/incubator/incubator.ingress-controller.konghq.com_kongservicefacades.yaml
  docs/incubator-api-reference.md
  examples/kong-service-facade.yaml
  pkg/apis/incubator/v1alpha1/kongservicefacade_types.go
  scripts/apidocs-gen/generate.sh
  test/e2e/all_in_one_test.go
  test/e2e/helpers_test.go
  test/e2e/upgrade_test.go
  test/integration/isolated/consts.go
  test/integration/isolated/examples_grpc_test.go
  test/integration/isolated/examples_kong_service_facade_test.go
  test/integration/isolated/examples_udproute_test.go
  test/internal/helpers/deployment.go
  test/internal/testlabels/labels.go
Labels: area/docs, area/tests, size/XL

#5327 fix(tests): skip upgrade tests if not upgrading between two consecutive Kong versions
  go.mod
  test/e2e/upgrade_test.go
Labels: area/tests, size/L

#5347 Backport 1p creds to release/2.12.x
  .github/workflows/_e2e_tests.yaml
  .github/workflows/_integration_tests.yaml
  .github/workflows/test_nightly.yaml
Labels: size/S, < v3.0.0

#5343 chore(deps): bump k8s.io group packages from 0.28.4 to 0.29.0
  config/crd/bases/configuration.konghq.com_tcpingresses.yaml
  config/crd/bases/configuration.konghq.com_udpingresses.yaml
  go.mod
  go.sum
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
  third_party/go.mod
  third_party/go.sum
Labels: dependencies, size/L

#5346 fix: print concrete error from fillPlugin in logs
  internal/dataplane/deckgen/generate.go
Labels: area/debt, size/XS, < v3.0.0

#5356 Revert "chore(deps): bump actions/download-artifact from 3 to 4"
  .github/workflows/_e2e_tests.yaml
  .github/workflows/_test_reports.yaml
Labels: size/XS

#5342 feat: change message for Programmed Unknown KongServiceFacade condition
  hack/generators/controllers/networking/main.go
  internal/controllers/configuration/zz_generated_controllers.go
  internal/controllers/utils/conditions.go
  internal/controllers/utils/conditions_test.go
Labels: area/feature, size/L

#5361 Revert "chore(deps): bump actions/download-artifact from 3 to 4"
  .github/workflows/_e2e_tests.yaml
  .github/workflows/_test_reports.yaml
Labels: size/XS

#5362 test: verify golden configs against Konnect
  .github/workflows/_kongintegration_tests.yaml
  test/e2e/konnect_test.go
  test/internal/helpers/konnect/access.go
  test/internal/helpers/konnect/certificates.go
  test/internal/helpers/konnect/control_plane.go
  test/kongintegration/translator_golden_tests_outputs_test.go
Labels: area/tests, size/L, area/konnect

#5365 Backport(v2.12.x): fix(tests): skip upgrade tests if not upgrading between two consecuti…
  go.mod
  test/e2e/upgrade_test.go
  test/internal/testenv/testenv.go
Labels: size/M, < v3.0.0

#5364 docs: update v2.12.3 release date
  CHANGELOG.md
Labels: size/XS

#5371 chore: specify GKE release channel for E2E tests
  .github/workflows/_e2e_tests.yaml
  go.mod
  go.sum
  test/e2e/helpers_test.go
  test/internal/testenv/testenv.go
Labels: area/ci, size/S

#5376 test: Set different feature gates for versions before 3.1.x
  test/e2e/features_test.go
  test/internal/testenv/feature_gates.go
  test/internal/testenv/testenv.go
Labels: area/ci, size/M

#5374 docs: add the CHANGELOG for v2.12.3
  CHANGELOG.md
Labels: size/S

#5354 feat: add KongVault CRD
  CHANGELOG.md
  config/crd/bases/configuration.konghq.com_kongvaults.yaml
  docs/api-reference.md
  pkg/apis/configuration/v1alpha1/kong_vault_types.go
  pkg/apis/configuration/v1alpha1/zz_generated.deepcopy.go
  pkg/clientset/typed/configuration/v1alpha1/configuration_client.go
  pkg/clientset/typed/configuration/v1alpha1/fake/fake_configuration_client.go
  pkg/clientset/typed/configuration/v1alpha1/fake/fake_kongvault.go
  pkg/clientset/typed/configuration/v1alpha1/generated_expansion.go
  pkg/clientset/typed/configuration/v1alpha1/kongvault.go
Labels: area/feature, size/L, area/CRD
