Repository Kong/kubernetes-ingress-controller, pull requests merged in 2023-04, with the labels that each got.

#3834 [backport] fix: make AdminAPIClientsManager.Notify safe for concurrent use (#3816)
  internal/dataplane/clients_manager.go
  internal/dataplane/clients_manager_test.go
Labels: size/M

#3838 chore(tests): fix receivedNotificationsCount log
  internal/dataplane/clients_manager_test.go
Labels: area/tests, size/XS, backport release/2.9.x

#3837 chore: update changelog for 2.9.2
  CHANGELOG.md
Labels: area/release, size/S, backport release/2.9.x

#3841 tests: refactor GenerateTagsForObject and its UT
  internal/util/k8s.go
  internal/util/k8s_test.go
Labels: area/tests, size/M

#3845 chore: add patch release step to verify diff
  .github/ISSUE_TEMPLATE/release.yaml
Labels: area/docs, size/XS

#3847 chore: remove `go.uber.org/multierr` direct dependency
  go.mod
  internal/manager/utils/kongconfig/root.go
Labels: area/maintenance, size/XS

#3857 chore: go version updated to 1.20 in go.mod
  go.mod
Labels: size/XS

#3858 refactor: don't send empty configs when no config detected in dataplace
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_test.go
  internal/dataplane/sendconfig/config_change_detector.go
  internal/dataplane/sendconfig/config_change_detector_test.go
  internal/dataplane/sendconfig/sendconfig.go
Labels: refactor, size/L

#3832 feat(gateway) support UDP services
  CHANGELOG.md
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gateway_utils.go
  internal/controllers/gateway/udproute_controller.go
  internal/manager/controllerdef.go
  test/integration/gateway_test.go
  test/integration/grpcroute_test.go
  test/integration/helpers_test.go
  test/integration/httproute_test.go
  test/integration/tcproute_test.go
  test/integration/tlsroute_test.go
  test/integration/udproute_test.go
Labels: area/gateway-api, size/XL

#3852 fix(versions) add mutex to version functions
  CHANGELOG.md
  internal/versions/versions.go
Labels: size/XS

#3872 chore(tests) use cleaner in TestTCPRouteReferenceGrant
  test/integration/tcproute_test.go
Labels: size/S

#3887 chore(tests) use Kong minor tags for testing
  .github/workflows/_integration_tests.yaml
Labels: size/XS

#3889 fix: fix reconciliation for Admin API EndpointSlice deletion
  CHANGELOG.md
  internal/controllers/configuration/kongadminapi_controller.go
  internal/controllers/configuration/kongadminapi_controller_envtest_test.go
  internal/dataplane/clients_manager.go
  internal/dataplane/clients_manager_test.go
Labels: size/L

#3894 test: add timeout to context to trigger cleanup on wait for env ready
  test/conformance/suite_test.go
  test/e2e/helpers_test.go
  test/e2e/istio_test.go
  test/expressionrouter/suite_test.go
  test/integration/suite_test.go
  test/internal/testenv/testenv.go
Labels: area/tests, size/M

#3896 chore(tests): fix data race in `TestAdminAPIClientsManager_ConcurrentNotify`
  internal/dataplane/clients_manager_test.go
Labels: area/tests, size/XS

#3897 [Backport release/2.9.x] fix: fix reconciliation for Admin API EndpointSlice deletion
  CHANGELOG.md
  internal/controllers/configuration/kongadminapi_controller.go
  internal/controllers/configuration/kongadminapi_controller_envtest_test.go
  internal/dataplane/clients_manager.go
  internal/dataplane/clients_manager_test.go
Labels: size/L

#3874 Update CODEOWNERS
  CODEOWNERS
Labels: size/XS

#3899 chore: prepare release 2.9.3
  CHANGELOG.md
  config/image/oss/kustomization.yaml
  config/variants/enterprise/kustomization.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless-legacy.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
Labels: size/S

#3902 chore: update changelog and manifests for 2.9.3
  CHANGELOG.md
  config/image/oss/kustomization.yaml
  deploy/single/all-in-one-dbless-enterprise.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless-legacy.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
Labels: area/maintenance, size/M

#3903 chore(deps) bump k8s.io/code-generator from 0.26.3 to 0.27.1
  pkg/clientset/typed/configuration/v1/fake/fake_kongclusterplugin.go
  pkg/clientset/typed/configuration/v1/fake/fake_kongconsumer.go
  pkg/clientset/typed/configuration/v1/fake/fake_kongingress.go
  pkg/clientset/typed/configuration/v1/fake/fake_kongplugin.go
  pkg/clientset/typed/configuration/v1alpha1/fake/fake_ingressclassparameters.go
  pkg/clientset/typed/configuration/v1beta1/fake/fake_tcpingress.go
  pkg/clientset/typed/configuration/v1beta1/fake/fake_udpingress.go
  third_party/go.mod
  third_party/go.sum
Labels: size/S

#3917 chore(docs): collapse 2.9.0 changelog
  CHANGELOG.md
Labels: area/docs, size/M

#3927 feat(konnect): assign gateway nodes their respective ids
  internal/adminapi/client.go
  internal/konnect/client.go
  internal/konnect/node_agent.go
  internal/konnect/node_agent_test.go
  internal/manager/id.go
  internal/manager/run.go
  internal/manager/telemetry/reports.go
  test/e2e/konnect_test.go
Labels: area/feature, size/L, area/konnect

#3930 chore(ci): run konnect e2e tests on gke
  .github/workflows/_e2e_tests.yaml
Labels: area/ci, size/XS

#3929 fix: handle empty udp publish service
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gateway_controller_test.go
  internal/controllers/gateway/gateway_utils.go
  internal/manager/controllerdef.go
Labels: size/M, fix

#3883 Add license agent
  CHANGELOG.md
  go.mod
  go.sum
  internal/adminapi/konnect.go
  internal/clients/config_status.go
  internal/clients/config_status_test.go
  internal/clients/manager.go
  internal/clients/manager_test.go
  internal/controllers/gateway/gateway_controller.go
  internal/dataplane/deckgen/generate.go
  internal/dataplane/kong_client.go
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/parser/parser.go
  internal/konnect/license_client.go
  internal/konnect/license_types.go
  internal/konnect/node_agent.go
  internal/konnect/node_agent_test.go
  internal/konnect/node_client.go
  internal/konnect/node_types.go
  internal/license/agent.go
  internal/manager/config.go
  internal/manager/run.go
  internal/manager/setup.go
  test/e2e/features_test.go
  test/e2e/helpers_test.go
  test/e2e/konnect_test.go
  test/e2e/kustomizations_test.go
  test/e2e/utils_test.go
Labels: size/XL

#3933 feat: assign Service, Route and Consumer entities stable IDs
  CHANGELOG.md
  go.mod
  go.sum
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/kongstate_test.go
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/parser_test.go
Labels: area/feature, size/L, area/konnect

#3932 fix(rbac): fix leader election policy rules
  CHANGELOG.md
  config/rbac/leader_election_role.yaml
  deploy/single/all-in-one-dbless-enterprise.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless-legacy.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
Labels: area/maintenance, size/L

#3938 chore(konnect): cleanup license agent
  internal/license/agent.go
  internal/license/agent_test.go
  internal/manager/run.go
Labels: size/L, area/konnect

#3939 refactor: reorganize ingressRulesFromIngressV1 into smaller pieces
  internal/dataplane/parser/translate_ingress.go
  internal/dataplane/parser/translate_ingress_test.go
  internal/dataplane/parser/translators/ingress.go
  internal/dataplane/parser/translators/ingress_test.go
  internal/dataplane/parser/translators/translator_vars.go
Labels: area/maintenance, size/XXL
