Repository Kong/kubernetes-ingress-controller, pull requests merged in 2023-03, with the labels that each got.

#3605 test(e2e): add e2e tests for konnect node registration
  internal/konnect/client.go
  test/e2e/helpers_test.go
  test/e2e/konnect_test.go
Labels: size/L

#3621 fix: fake clientset not using the correct group name
  CHANGELOG.md
  pkg/apis/configuration/v1/doc.go
  pkg/apis/configuration/v1/groupversion_info.go
  pkg/apis/configuration/v1alpha1/doc.go
  pkg/apis/configuration/v1alpha1/groupversion_info.go
  pkg/apis/configuration/v1beta1/doc.go
  pkg/apis/configuration/v1beta1/groupversion_info.go
  pkg/clientset/typed/configuration/v1/configuration_client.go
  pkg/clientset/typed/configuration/v1/fake/fake_kongclusterplugin.go
  pkg/clientset/typed/configuration/v1/fake/fake_kongconsumer.go
  pkg/clientset/typed/configuration/v1/fake/fake_kongingress.go
  pkg/clientset/typed/configuration/v1/fake/fake_kongplugin.go
  pkg/clientset/typed/configuration/v1alpha1/configuration_client.go
  pkg/clientset/typed/configuration/v1alpha1/fake/fake_ingressclassparameters.go
  pkg/clientset/typed/configuration/v1beta1/configuration_client.go
  pkg/clientset/typed/configuration/v1beta1/fake/fake_tcpingress.go
  pkg/clientset/typed/configuration/v1beta1/fake/fake_udpingress.go
  pkg/clientset_test/clientset_test.go
Labels: size/L

#3629 feat(config): make all all-in-one dbless manifests use multi-gw
  CHANGELOG.md
  config/variants/enterprise/kong-enterprise.yaml
  config/variants/enterprise/kustomization.yaml
  config/variants/multi-gw/base/gateway_deployment.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless-legacy.yaml
  deploy/single/all-in-one-dbless.yaml
  scripts/build-single-manifests.sh
  test/e2e/all_in_one_test.go
  test/e2e/compatibilities_test.go
  test/e2e/features_test.go
  test/e2e/helpers_test.go
  test/e2e/konnect_test.go
  test/e2e/kuma_test.go
  test/e2e/kustomizations.go
  test/e2e/utils_test.go
Labels: area/feature, area/tests, size/XL

#3643 fix: add namespace for scale request in e2e tests
  test/e2e/kuma_test.go
Labels: size/XS

#3644 chore(tests): do not return error from getTestManifest
  test/e2e/all_in_one_test.go
  test/e2e/compatibilities_test.go
  test/e2e/features_test.go
  test/e2e/konnect_test.go
  test/e2e/kuma_test.go
  test/e2e/utils_test.go
Labels: area/tests, size/M

#3645 chore(tests): do not hardcode deployments' names in e2e
  test/e2e/all_in_one_test.go
  test/e2e/compatibilities_test.go
  test/e2e/features_test.go
  test/e2e/helpers_test.go
  test/e2e/konnect_test.go
  test/e2e/kuma_test.go
  test/e2e/kustomizations_test.go
  test/e2e/utils_test.go
Labels: area/tests, size/L

#3642 feat(gateway_discovery): allow gateway discovery only in dbless mode
  CHANGELOG.md
  internal/manager/config_validation.go
  internal/manager/config_validation_test.go
  internal/manager/run.go
Labels: size/M

#3653 docs: wording ON CHANGELOG for limiting gateway discovery to be used with dbless gateways
  CHANGELOG.md
Labels: size/XS

#3652 tests(e2e): extend multi-gw test with scaling to 0
  test/e2e/all_in_one_test.go
  test/e2e/helpers_test.go
  test/e2e/konnect_test.go
  test/e2e/utils_test.go
Labels: area/tests, size/L

#3655 tests(dataplane): cover `KongClient.Update` with unit tests
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_test.go
  internal/dataplane/sendconfig/config_change_detector.go
  internal/dataplane/sendconfig/config_change_detector_test.go
  internal/dataplane/sendconfig/sendconfig.go
  internal/dataplane/sendconfig/strategy.go
  internal/dataplane/sendconfig/strategy_test.go
  internal/manager/run.go
Labels: area/tests, size/XL

#3646 test(unit): listener conditions appear only once
  internal/controllers/gateway/gateway_utils_test.go
Labels: size/S

#3660 tests(grpc): use go-grpc client instead of grpcurl
  Makefile
  go.mod
  go.sum
  test/integration/examples_test.go
  test/integration/grpcroute_test.go
  third_party/go.mod
  third_party/go.sum
  third_party/grpcurl.go
Labels: area/tests, size/L

#3662 chore: fix linter
  Makefile
  test/integration/grpcroute_test.go
Labels: area/ci, area/maintenance, size/XS

#3667 set kong image to 3.2 in per-PR integration tests
  .github/workflows/test.yaml
Labels: size/XS

#3654 fix: unlimit retry of getting gateway admin API endpoint and move to standalone healthz server
  .golangci.yaml
  internal/manager/health_check.go
  internal/manager/health_check_test.go
  internal/manager/run.go
  internal/manager/setup.go
Labels: size/L

#3669 chore: add skaffold to third_party tools module
  Makefile
  third_party/go.mod
  third_party/go.sum
  third_party/skaffold.go
Labels: area/maintenance, size/XXL

#3675 fix: pass Konnect PAT to E2E tests
  .github/workflows/e2e.yaml
Labels: area/ci, area/tests, size/XS

#3674 chore: bump k8s versions for 2.9 release
  .github/workflows/e2e.yaml
  .github/workflows/e2e_targeted.yaml
  .github/workflows/release.yaml
Labels: area/ci, area/maintenance, size/M

#3671 test(conformance): all tests enabled
  test/conformance/gateway_conformance_test.go
Labels: size/M

#3676 fix(tests): fix e2e webhook test condition
  test/e2e/helpers_test.go
Labels: area/tests, area/maintenance, size/S

#3688 chore: remove redhat certification steps from workflows
  .github/ISSUE_TEMPLATE/release.yaml
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
Labels: size/L

#3690 chore(ci): disallow golang.org/x/net/context
  .golangci.yaml
  go.mod
  internal/dataplane/synchronizer_test.go
  internal/manager/health_check_test.go
Labels: area/ci, area/maintenance, size/S

#3677 test(conformance): fix httpRouteMatching test
  internal/dataplane/parser/translate_httproute.go
  test/conformance/gateway_conformance_test.go
Labels: size/S

#3620 fix: changes the way empty vars are handled on deploy-admission-contr…
  hack/deploy-admission-controller.sh
Labels: size/S, fix

#3699 chore: remove unused rhel dockerfile targets
  Dockerfile
Labels: area/maintenance, size/M

#3664 docs: add Gateway Discovery to README.md
  README.md
Labels: area/docs, size/XS

#3707 fix(release): fix workflow dependencies & allow pre-releases to not update kustomize
  .github/workflows/release.yaml
Labels: area/ci, size/XS

#3709 chore: make CRD detection log entry more descriptive
  internal/manager/conditions.go
Labels: area/maintenance, size/XS

#3696 chore(gateway-api): extract common programmed condition helper
  internal/controllers/gateway/grpcroute_controller.go
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/route_parent_status.go
  internal/controllers/gateway/route_utils.go
  internal/controllers/gateway/route_utils_test.go
  internal/controllers/gateway/tcproute_controller.go
  internal/controllers/gateway/tlsroute_controller.go
  internal/controllers/gateway/types.go
  internal/controllers/gateway/udproute_controller.go
Labels: area/gateway-api, area/maintenance, size/XXL

#3712 chore: reword log entry for skipping object status update
  internal/dataplane/kong_client.go
Labels: size/XS

#3714 test(e2e_logs): fix checking logs for disabling controllers in e2e tests
  test/e2e/features_test.go
Labels: size/M

#3702 feat: Gateway API `RequestRedirect` filter translated to combination of kong plugins
  CHANGELOG.md
  internal/dataplane/parser/translate_errors.go
  internal/dataplane/parser/translate_httproute.go
  internal/dataplane/parser/translate_httproute_test.go
  internal/dataplane/parser/translate_utils.go
  internal/dataplane/parser/translate_utils_test.go
  test/conformance/gateway_conformance_test.go
  test/integration/translation_failures_test.go
Labels: size/L

#3719 fix: do not update secret when tls.secretName is empty
  CHANGELOG.md
  internal/controllers/configuration/object_references.go
  internal/controllers/configuration/object_references_test.go
Labels: size/M

#3720 tests: fix TestHealthCheckServer_Start flaky test
  internal/manager/health_check_test.go
Labels: area/tests, test-flake, size/S

#3715 feat(ci): allow triggering e2e tests via Github labels
  .github/workflows/e2e.yaml
  .github/workflows/e2e_targeted.yaml
  .github/workflows/e2e_trigger_via_label.yaml
Labels: area/feature, area/ci, size/M

#3727 feat(konnect): react to gateway clients updates in NodeAgent
  CHANGELOG.md
  internal/konnect/node_agent.go
  internal/konnect/node_agent_test.go
  internal/manager/run.go
Labels: area/feature, size/L, area/konnect

#3717 chore(deps): remove unneeded mergo replace
  go.mod
Labels: dependencies, area/maintenance, size/XS

#3736 tests: allow running Gateway API conformance tests in a loop
  test/conformance/suite_test.go
Labels: area/tests, area/gateway-api, size/M

#3738 chore(ci): remove explicit go cache
  .github/workflows/cleanup.yaml
  .github/workflows/e2e.yaml
  .github/workflows/e2e_targeted.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  .github/workflows/test_nightly.yaml
Labels: area/ci, size/L

#3732 tests: fix flaky gateway conformance `HTTPRouteListenerHostnameMatching` test
  CHANGELOG.md
  Makefile
  internal/controllers/gateway/route_utils.go
  internal/controllers/gateway/route_utils_test.go
Labels: area/tests, area/gateway-api, test-flake, size/L

#3741 chore(e2e): simplify loading images
  .github/workflows/e2e_targeted.yaml
  test/e2e/environment.go
  test/e2e/features_test.go
  test/e2e/helpers_test.go
  test/e2e/utils_test.go
Labels: area/ci, area/tests, size/M

#3641 Translate GRPCRoute services/methods/headers to Kong route
  internal/dataplane/parser/translate_grpcroute.go
  test/integration/grpcroute_test.go
  test/integration/helpers_test.go
  test/integration/utils_test.go
Labels: area/gateway-api, size/L

#3753 chore(ci): don't set PATH for integration tests
  Makefile
Labels: area/ci, area/maintenance, size/XS

#3748 fix(ci): don't use gotestsum in integration tests
  .github/workflows/_conformance_tests.yaml
  .github/workflows/_integration_tests.yaml
  Makefile
  third_party/go-junit-report.go
  third_party/go.mod
  third_party/go.sum
Labels: area/ci, area/tests, size/M

#3758 feat(examples): add Gateway API ReferenceGrant example
  examples/gateway-referencegrant-httproute.yaml
Labels: area/gateway-api, size/L

#3760 fix(examples) link to updated GWAPI install guide
  examples/gateway-grpcroute.yaml
  examples/gateway-httproute.yaml
  examples/gateway-referencegrant-httproute.yaml
  examples/gateway-tcproute.yaml
  examples/gateway-tlsroute.yaml
  examples/gateway-udproute.yaml
Labels: size/M

#3766 chore: don't run e2es in pr workflow
  .github/workflows/pr_checks.yaml
Labels: area/ci, size/S

#3775 chore(deps): bump outdated go toolchain for 2.8.x release
  Dockerfile
  go.mod
  go.sum
Labels: dependencies, size/M

#3781 chore: add Gateway API version const
  Makefile
  test/consts/zz_generated_gateway.go
  test/internal/cmd/generate-gateway-api-consts/gateway_consts.tmpl
  test/internal/cmd/generate-gateway-api-consts/main.go
Labels: area/gateway-api, size/M

#3783 feat(telemetry): add `discovered_gateways_count`
  CHANGELOG.md
  internal/dataplane/clients_manager.go
  internal/dataplane/clients_manager_test.go
  internal/manager/telemetry/manager.go
  internal/manager/telemetry/manager_test.go
  internal/manager/telemetry/reports.go
  internal/manager/telemetry/workflows/gateway_discovery.go
Labels: area/telemetry, size/L

#3778 feat(annotations) support user-supplied tags
  CHANGELOG.md
  internal/annotations/annotations.go
  internal/util/k8s.go
  internal/util/k8s_test.go
Labels: size/M

#3710 chore: remove support for extensions/v1beta1 Ingress
  CHANGELOG.md
  config/rbac/role.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless-legacy.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  hack/generators/controllers/networking/main.go
  internal/controllers/configuration/object_references.go
  internal/controllers/configuration/zz_generated_controllers.go
  internal/controllers/utils/conversion.go
  internal/controllers/utils/conversion_test.go
  internal/manager/conditions.go
  internal/manager/conditions_test.go
  internal/manager/config.go
  internal/manager/controllerdef.go
  internal/store/store.go
  internal/store/store_test.go
Labels: area/maintenance, size/L

#3799 ci: add backport workflow
  .github/workflows/backport.yaml
Labels: area/ci, size/S

#3787 fix(tests): wait for expected status in TestIngressRegexMatchPath
  test/integration/consumer_test.go
  test/integration/ingress_regex_match_test.go
  test/integration/ingress_test.go
  test/integration/plugin_test.go
  test/internal/helpers/http.go
Labels: area/tests, test-flake, size/L

#3759 feat(httproute): add `ReferenceGrant` watch
  CHANGELOG.md
  internal/controllers/configuration/kongadminapi_controller_envtest_test.go
  internal/controllers/controller.go
  internal/controllers/gateway/dataplane_client.go
  internal/controllers/gateway/dataplane_mock_test.go
  internal/controllers/gateway/gateway_utils.go
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/httproute_controller_envtest_test.go
  internal/controllers/gateway/route_utils.go
  internal/util/builder/httpbackendref.go
  test/envtest/controller.go
  test/envtest/k8s.go
  test/envtest/setup.go
  test/helpers/conditions.go
Labels: area/gateway-api, size/XL, backport release/2.9.x

#3809 Final 2.9 release chores
  CHANGELOG.md
  LICENSES
Labels: size/XL, backport release/2.9.x

#3811 Handle empty matchers in ATC generator
  internal/dataplane/parser/atc/expression_test.go
  internal/dataplane/parser/atc/field.go
  internal/dataplane/parser/atc/matcher.go
  internal/dataplane/parser/atc/predicate.go
Labels: size/L

#3812 chore(release): update kic image tag to 2.9.0 in config
  config/image/oss/kustomization.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless-legacy.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
Labels: size/S, backport release/2.9.x

#3820 Suggestions for #3780
  internal/dataplane/parser/atc/field.go
  internal/dataplane/parser/atc/matcher.go
  internal/dataplane/parser/atc/predicate.go
  internal/dataplane/parser/atc/route.go
Labels: size/M

#3819 Add 2.9.1 changelog and manifest bump
  CHANGELOG.md
  LICENSES
  config/image/oss/kustomization.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless-legacy.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
Labels: size/M, backport release/2.9.x

#3824 [Backport release/2.9.x] chore: add 2.9.1 changelog and manifest bump (#3819)
  CHANGELOG.md
  LICENSES
  config/image/oss/kustomization.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless-legacy.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
Labels: area/release, size/M

#3780 feat: generator to make up expressions in kong expression routers
  Makefile
  internal/dataplane/parser/atc/expression_test.go
  internal/dataplane/parser/atc/field.go
  internal/dataplane/parser/atc/matcher.go
  internal/dataplane/parser/atc/predicate.go
  internal/dataplane/parser/atc/route.go
  test/expressionrouter/generate_test.go
  test/expressionrouter/helpers_test.go
  test/expressionrouter/suite_test.go
  test/internal/helpers/http.go
  test/internal/testenv/testenv.go
Labels: area/feature, size/XL

#3828 chore(docs) add 2.8.2 changelog
  CHANGELOG.md
Labels: size/S, backport release/2.8.x

#3827 chore(config) bump KIC image version for 2.8.x
  config/image/oss/kustomization.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
Labels: size/S

#3829 2.8.2 changelog 2
  CHANGELOG.md
Labels: size/L
