Repository Kong/kubernetes-ingress-controller, pull requests merged in 2023-05, with the labels that each got.

#3949 chore(test): set default junit report output file to null
  Makefile
Labels: size/XS

#3951 chore(tests): fix assertion for TestGetEndpoints and refactor assertion for TestKnativeSelectSplit
  internal/dataplane/parser/parser_test.go
Labels: size/S

#3957 fix: correct catch-all matcher for translating default backend of ingresses to expression routes
  internal/dataplane/parser/translate_ingress.go
  internal/dataplane/parser/translate_ingress_test.go
Labels: size/L

#3954 refactor: decouple Parser from KongClient
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_test.go
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/parser_test.go
  internal/dataplane/parser/translate_grpcroute.go
  internal/dataplane/parser/translate_httproute.go
  internal/dataplane/parser/translate_httproute_test.go
  internal/dataplane/parser/translate_ingress.go
  internal/dataplane/parser/translate_ingress_test.go
  internal/dataplane/parser/translate_knative.go
  internal/dataplane/parser/translate_kong_l4.go
  internal/dataplane/parser/translate_tcproute.go
  internal/dataplane/parser/translate_tlsroute.go
  internal/dataplane/parser/translate_udproute.go
  internal/dataplane/sendconfig/kong.go
  internal/manager/featuregates/feature_gates.go
  internal/manager/featuregates/feature_gates_test.go
  internal/manager/run.go
  internal/versions/deck.go
  internal/versions/deck_test.go
Labels: refactor, size/XL

#3968 tests(knative): fix knative integration test
  Makefile
  go.mod
  go.sum
  test/integration/knative_test.go
Labels: area/knative, area/tests, size/XL

#3964 chore: clean up old, unused telemetry code
  internal/meshdetect/detector.go
  internal/meshdetect/detector_test.go
  internal/meshdetect/mesh_kind.go
  internal/meshdetect/types.go
  internal/util/reports.go
  internal/util/reports_mesh.go
  internal/util/reports_mesh_test.go
  internal/util/reports_test.go
Labels: area/maintenance, size/XXL, area/telemetry

#3975 tests(knative): fix knative integration test
  test/integration/knative_test.go
Labels: area/ci, area/tests, size/S

#3974 chore(tests): fix flaky konnect node agent unit test
  internal/konnect/node_agent_test.go
Labels: area/tests, test-flake, size/S

#3977 chore(deps): bump github.com/kong/kubernetes-telemetry from 0.0.3 to 0.0.4
  go.mod
  go.sum
  internal/manager/telemetry/manager_test.go
Labels: area/tests, dependencies, size/L

#3963 feat: add CombinedServices for parsing netv1.Ingress
  .github/workflows/_integration_tests.yaml
  CHANGELOG.md
  FEATURE_GATES.md
  internal/dataplane/kongstate/service.go
  internal/dataplane/parser/objects.go
  internal/dataplane/parser/objects_test.go
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/parser_test.go
  internal/dataplane/parser/translate_grpcroute.go
  internal/dataplane/parser/translate_httproute.go
  internal/dataplane/parser/translate_ingress.go
  internal/dataplane/parser/translate_ingress_test.go
  internal/dataplane/parser/translate_knative.go
  internal/dataplane/parser/translate_kong_l4.go
  internal/dataplane/parser/translate_tcproute.go
  internal/dataplane/parser/translate_tlsroute.go
  internal/dataplane/parser/translate_udproute.go
  internal/dataplane/parser/translators/ingress.go
  internal/dataplane/parser/translators/ingress_atc.go
  internal/dataplane/parser/translators/ingress_atc_test.go
  internal/dataplane/parser/translators/ingress_test.go
  internal/manager/featuregates/feature_gates.go
Labels: area/feature, size/XXL

#3991 chore(ci): add testing on k8s v1.27.1
  .github/workflows/_e2e_tests.yaml
  .github/workflows/_integration_tests.yaml
  Makefile
Labels: area/ci, area/maintenance, size/XS

#3980 chore(tests): workaround to not rely on helpers from KTF
  test/integration/webhook_test.go
Labels: area/tests, size/L

#3988 feat: translate grpcroute to expression based routes
  .github/workflows/_integration_tests.yaml
  CHANGELOG.md
  internal/dataplane/parser/translate_grpcroute.go
  internal/dataplane/parser/translators/atc_utils.go
  internal/dataplane/parser/translators/atc_utils_test.go
  internal/dataplane/parser/translators/grpcroute.go
  internal/dataplane/parser/translators/grpcroute_atc.go
  internal/dataplane/parser/translators/grpcroute_atc_test.go
  internal/dataplane/parser/translators/grpcroute_test.go
  internal/dataplane/parser/translators/httproute_atc.go
  internal/dataplane/parser/translators/ingress_atc.go
  internal/dataplane/parser/translators/ingress_atc_test.go
  test/integration/examples_test.go
  test/integration/grpcroute_test.go
Labels: area/feature, work in progress, area/gateway-api, size/XXL

#4006 chore(github): new issue template gw_testing_request.yaml
  .github/ISSUE_TEMPLATE/gw_testing_request.yaml
Labels: size/M

#4012 tests: add RetryableHTTPClient util function
  go.mod
  test/e2e/konnect_test.go
  test/internal/helpers/http.go
Labels: area/tests, size/S

#4015 feat(konnect): propagate 429's retry-after header value
  CHANGELOG.md
  internal/adminapi/backoff_strategy_konnect.go
  internal/adminapi/backoff_strategy_konnect_test.go
Labels: size/L

#4017 chore(rbac): get rid of rbac permissions for secrets/status
  config/rbac/role.yaml
  deploy/single/all-in-one-dbless-enterprise.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless-legacy.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  internal/controllers/configuration/object_references.go
  internal/controllers/configuration/secret_controller.go
Labels: area/debt, size/M

#4007 fix(ci): fix kong image override
  .github/workflows/_e2e_tests.yaml
  .github/workflows/e2e_nightly.yaml
  .github/workflows/e2e_targeted.yaml
  test/e2e/helpers_test.go
  test/e2e/utils_test.go
Labels: area/ci, area/tests, size/L

#3996 feat(gwapi): setup controllers dynamically when required CRDs get installed
  CHANGELOG.md
  Makefile
  config/base/kustomization.yaml
  config/rbac/crds/kustomization.yaml
  config/rbac/crds/role.yaml
  config/rbac/crds/role_binding.yaml
  deploy/single/all-in-one-dbless-enterprise.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless-legacy.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  internal/controllers/crds/dynamic_controller.go
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/httproute_controller_envtest_test.go
  internal/manager/controllerdef.go
  internal/manager/scheme/scheme.go
  test/e2e/features_test.go
Labels: area/feature, area/gateway-api, size/XXL

#4016 chore(ci): unify import aliases and introduce forbidigo
  .golangci.yaml
  hack/generators/controllers/networking/main.go
  internal/adminapi/client.go
  internal/adminapi/endpoints.go
  internal/adminapi/endpoints_envtest_test.go
  internal/adminapi/endpoints_test.go
  internal/admission/response_builder.go
  internal/admission/response_builder_test.go
  internal/clients/manager_test.go
  internal/controllers/configuration/kongadminapi_controller.go
  internal/controllers/configuration/kongadminapi_controller_envtest_test.go
  internal/controllers/configuration/object_references.go
  internal/controllers/configuration/object_references_test.go
  internal/controllers/configuration/zz_generated_controllers.go
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gateway_controller_test.go
  internal/controllers/gateway/gateway_utils.go
  internal/controllers/gateway/grpcroute_controller.go
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/httproute_controller_envtest_test.go
  internal/controllers/gateway/route_utils_test.go
  internal/controllers/gateway/tcproute_controller.go
  internal/controllers/gateway/tlsroute_controller.go
  internal/controllers/gateway/udproute_controller.go
  internal/controllers/knative/knative.go
  internal/controllers/reference/reference.go
  internal/dataplane/parser/ingressrules.go
  internal/dataplane/parser/parser_test.go
  internal/dataplane/parser/translate_secrets.go
  internal/dataplane/parser/translate_secrets_test.go
  internal/manager/config.go
  internal/manager/config_validation.go
  internal/manager/config_validation_test.go
  internal/manager/setup.go
  internal/manager/telemetry/manager.go
  internal/manager/telemetry/manager_test.go
  internal/util/k8s.go
  internal/util/kubernetes/object/set.go
  test/e2e/all_in_one_test.go
  test/e2e/compatibilities_test.go
  test/e2e/helpers_test.go
  test/e2e/konnect_test.go
  test/e2e/utils_test.go
  test/envtest/setup.go
  test/helpers/conditions.go
  test/integration/gateway_webhook_test.go
  test/integration/ingress_https_test.go
  test/integration/tlsroute_test.go
  test/integration/translation_failures_test.go
Labels: area/debt, area/ci, size/L

#4021 tests: align E2E to dynamic handling of GW API CRDs
  test/e2e/features_test.go
Labels: area/tests, size/S

#4023 chore(ci): Notify on Slack for failures of e2e tests run at night
  .github/workflows/e2e_nightly.yaml
Labels: area/ci, area/tests, size/S

#4028 CI workflow for Gateway validation
  .github/workflows/_integration_tests.yaml
  .github/workflows/e2e_targeted.yaml
  .github/workflows/validate_kong_image.yaml
Labels: size/L

#4030 fix(ci): workflow param name typo
  .github/workflows/_integration_tests.yaml
Labels: size/XS

#4031 chore(ci): add code block when posting comment in validate kong issue
  .github/workflows/validate_kong_image.yaml
Labels: area/ci, size/XS

#4022 feat: attach translation failure events to unsupported objects when ExpressionRoutes enabled
  CHANGELOG.md
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/translate_failures_test.go
  internal/dataplane/parser/translate_knative.go
  internal/dataplane/parser/translate_kong_l4.go
  internal/dataplane/parser/translate_tcproute.go
  internal/dataplane/parser/translate_tlsroute.go
  internal/dataplane/parser/translate_udproute.go
Labels: size/L

#4032 fix(ci): access inputs in integration tests workflow correctly
  .github/workflows/_integration_tests.yaml
  .github/workflows/validate_kong_image.yaml
Labels: area/ci, size/S

#4029 feat(konnect): account for config sync failures in reported node status
  CHANGELOG.md
  internal/clients/config_status.go
  internal/clients/config_status_test.go
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_test.go
  internal/konnect/node_agent.go
  internal/konnect/node_agent_test.go
  internal/konnect/nodes/types.go
Labels: area/feature, size/XL, area/konnect

#4033 tests(integration): more visibililty into customized kong images
  test/integration/suite_test.go
  test/internal/helpers/kong.go
  test/internal/helpers/ktf.go
Labels: area/tests, size/M

#4044 feat: Gateway Discovery produce DNS names instead of IP addresses
  CHANGELOG.md
  internal/adminapi/endpoints.go
  internal/adminapi/endpoints_test.go
  internal/controllers/configuration/kongadminapi_controller_envtest_test.go
Labels: area/feature, size/L

#4053 chore(ci): fix notifications for failures of e2e nightly tests
  .github/workflows/e2e_nightly.yaml
Labels: size/XS

#4049 chore(konnect): improve logging
  internal/adminapi/backoff_strategy_konnect.go
  internal/adminapi/backoff_strategy_konnect_test.go
  internal/dataplane/kong_client.go
Labels: size/S, area/konnect

#4055 ci: fix broken skaffold builds
  .github/workflows/pr_checks.yaml
  third_party/go.mod
  third_party/go.sum
Labels: area/ci, size/M

#4057 feat: disable expression routes mode when ExpressionRoutes is on but CombinedRoutes is off
  CHANGELOG.md
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/parser_test.go
Labels: size/M

#4059 chore(deps): bump go-echo to 0.3.0 everywhere
  examples/gateway-tcproute.yaml
  examples/gateway-tlsroute.yaml
  test/consts.go
Labels: area/tests, dependencies, area/maintenance, size/XS

#4054 feat: generate events on pods when apply Kong configurations
  CHANGELOG.md
  internal/dataplane/kong_client.go
Labels: area/feature, size/M

#4073 ci: add auto issue close and comment to validate kong image workflow
  .github/workflows/validate_kong_image.yaml
Labels: area/ci, size/S

#4076 fix: assume router_flavor to default value according to kong version if missing
  CHANGELOG.md
  internal/manager/utils/kongconfig/root.go
  internal/manager/utils/kongconfig/root_test.go
Labels: size/XL, fix

#4079 chore(deps): bump github.com/kong/kubernetes-testing-framework from 0.30.1 to 0.31.0
  go.mod
  go.sum
  test/e2e/features_test.go
  test/integration/webhook_test.go
Labels: area/debt, dependencies, area/maintenance, size/L

#4075 feat: add FillIDs feature gate
  .github/workflows/_integration_tests.yaml
  CHANGELOG.md
  FEATURE_GATES.md
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/parser_test.go
  internal/manager/featuregates/feature_gates.go
Labels: area/feature, size/M

#4071 feat: add `--gateway-discovery-dns-strategy` flag
  CHANGELOG.md
  internal/adminapi/endpoints.go
  internal/adminapi/endpoints_envtest_test.go
  internal/adminapi/endpoints_test.go
  internal/controllers/configuration/kongadminapi_controller.go
  internal/controllers/configuration/kongadminapi_controller_envtest_test.go
  internal/dataplane/parser/parser_test.go
  internal/manager/config.go
  internal/manager/config/types/dnsstrategy.go
  internal/manager/config_validation.go
  internal/manager/controllerdef.go
  internal/manager/setup.go
  internal/util/builder/endpointport.go
  test/integration/webhook_test.go
Labels: area/feature, size/XL

#4088 refactor(tests): use constants for referencing images and ports
  test/consts.go
  test/e2e/features_test.go
  test/e2e/helpers_gateway_test.go
  test/e2e/helpers_test.go
  test/e2e/istio_test.go
  test/expressionrouter/generate_test.go
  test/integration/config_error_event_test.go
  test/integration/consumer_test.go
  test/integration/gateway_test.go
  test/integration/httproute_test.go
  test/integration/ingress_https_test.go
  test/integration/ingress_regex_match_test.go
  test/integration/ingress_test.go
  test/integration/knative_test.go
  test/integration/kongingress_test.go
  test/integration/plugin_test.go
  test/integration/tcpingress_test.go
  test/integration/tcproute_test.go
  test/integration/tlsroute_test.go
  test/integration/translation_failures_test.go
Labels: area/tests, area/maintenance, size/L

#4090 refactor(tests): make TestTLSRouteEssentials easier to follow
  test/consts.go
  test/integration/tlsroute_test.go
Labels: area/tests, refactor, size/M

#4091 feat(tests): set --max-endpoints-per-slice=2 in K8s Kind clusters used in e2e tests
  test/e2e/helpers_test.go
Labels: area/tests, size/S

#4089 tests: propagate exit code from makefile targets using pipes
  Makefile
Labels: area/tests, size/XS

#4082 tests: make upgrade tests run, add one for postgres
  test/e2e/all_in_one_test.go
  test/e2e/upgrade_test.go
  test/e2e/utils_test.go
Labels: area/tests, size/L

#4087 refactor: don't use kong version singleton
  internal/dataplane/kongstate/consumer.go
  internal/dataplane/kongstate/consumer_test.go
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/parser_test.go
  internal/dataplane/parser/translate_httproute.go
  internal/dataplane/parser/translate_utils.go
  internal/dataplane/parser/translate_utils_test.go
  internal/dataplane/sendconfig/inmemory.go
  internal/dataplane/sendconfig/inmemory_test.go
  internal/dataplane/sendconfig/strategy.go
  internal/manager/run.go
  internal/versions/deck.go
  internal/versions/deck_test.go
  internal/versions/versions.go
  test/integration/config_error_event_test.go
  test/integration/httproute_test.go
  test/integration/ingress_regex_match_test.go
  test/integration/ingress_test.go
  test/integration/plugin_test.go
  test/integration/tcpingress_test.go
  test/integration/version_test.go
  test/internal/helpers/kong.go
Labels: area/debt, area/ci, area/tests, size/XL

#4052 keep Gateway's `AttachedRoutes` field up to date
  CHANGELOG.md
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gateway_utils.go
  internal/controllers/gateway/gateway_utils_test.go
  internal/controllers/gateway/route_utils.go
  internal/controllers/gateway/route_utils_test.go
  internal/util/builder/allowedroutes.go
  test/integration/helpers_test.go
  test/integration/httproute_test.go
Labels: area/gateway-api, size/XL

#4094 refactor: replace debugging endpoints integration tests with envtest
  internal/cmd/rootcmd/rootcmd.go
  internal/cmd/rootcmd/run.go
  internal/cmd/rootcmd/run_envtest_test.go
  internal/manager/conditions.go
  internal/manager/conditions_test.go
  internal/manager/config.go
  test/envtest/setup.go
  test/integration/controller_test.go
Labels: area/tests, area/maintenance, refactor, size/L

#4092 feat(tests): verify routing to every backend in e2e tests
  test/e2e/all_in_one_test.go
  test/e2e/compatibilities_test.go
  test/e2e/features_test.go
  test/e2e/helpers_test.go
  test/e2e/konnect_test.go
  test/e2e/kuma_test.go
  test/e2e/upgrade_test.go
Labels: area/tests, size/L

#4100 tests: delete migrations job before upgrade in e2e test
  test/e2e/features_test.go
  test/e2e/helpers_test.go
  test/e2e/upgrade_test.go
Labels: size/M

#4101 refactor: replace integration test checking metrics with an envtest based test
  internal/cmd/rootcmd/run_envtest_test.go
  internal/dataplane/synchronizer.go
  internal/dataplane/synchronizer_test.go
  internal/manager/config.go
  internal/manager/run.go
  internal/manager/setup.go
  internal/metrics/metrics_envtest_test.go
  internal/metrics/prometheus.go
  test/envtest/adminapimock.go
  test/envtest/run.go
  test/integration/metrics_test.go
Labels: area/tests, refactor, size/L

#4104 chore: relax uniform Gateway version check
  internal/manager/utils/kongconfig/root.go
Labels: size/XS

#4116 feat: all-in-one manifests migrations job improvement
  CHANGELOG.md
  config/variants/postgres/migration.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
Labels: area/feature, size/S
