Repository Kong/kubernetes-ingress-controller, pull requests merged in 2023-11, with the labels that each got.

#5035 chore(logs): modifying the capitalization consistency of the logs - Part 2
  internal/admission/validation/gateway/httproute.go
  internal/admission/validation/gateway/httproute_test.go
  internal/admission/validation/ingress/ingress.go
  internal/admission/validator.go
Labels: size/M

#5046 chore: remove temp go-get-gatewayapi and update CHANGELOG
  CHANGELOG.md
  Makefile
Labels: size/S

#5037 chore(logs): modifying the capitalization consistency of the logs - Part 3
  hack/generators/controllers/networking/main.go
  internal/admission/handler.go
  internal/admission/server.go
  internal/admission/server_test.go
  internal/admission/validator.go
  internal/clients/readiness.go
  internal/controllers/configuration/secret_controller.go
  internal/controllers/configuration/zz_generated_controllers.go
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/grpcroute_controller.go
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/tcproute_controller.go
  internal/controllers/gateway/tlsroute_controller.go
  internal/controllers/gateway/udproute_controller.go
  internal/controllers/reference/reference.go
  internal/dataplane/failures/failures.go
  internal/dataplane/kong_client.go
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/kongstate_test.go
  internal/dataplane/parser/ingressrules.go
  internal/dataplane/parser/ingressrules_test.go
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/translate_grpcroute.go
  internal/dataplane/parser/translate_httproute.go
  internal/dataplane/parser/translate_ingress.go
  internal/dataplane/parser/translate_kong_l4.go
  internal/dataplane/parser/translate_secrets.go
  internal/dataplane/parser/translate_tcproute.go
  internal/dataplane/parser/translate_tlsroute.go
  internal/dataplane/parser/translate_udproute.go
  internal/konnect/node_agent.go
  internal/license/agent.go
  internal/manager/setup.go
  internal/util/test/webhooks.go
  test/e2e/features_test.go
  test/e2e/konnect_test.go
  test/e2e/utils_test.go
  test/envtest/gateway_envtest_test.go
  test/envtest/httproute_controller_test.go
  test/envtest/k8s_objects_status_envtest_test.go
  test/envtest/kongstate_consumer_failures_test.go
  test/envtest/telemetry_test.go
  test/helpers/certificate/certificate.go
  test/helpers/conditions.go
  test/integration/tcpingress_test.go
  test/integration/translation_failures_test.go
  test/integration/webhook_test.go
  test/internal/helpers/http.go
Labels: size/L

#5033 chore(logs): modifying the capitalization consistency of the logs
  internal/adminapi/backoff_strategy_konnect.go
  internal/adminapi/backoff_strategy_konnect_test.go
  internal/admission/validation/consumers/credentials/validation_test.go
  internal/clients/readiness.go
  internal/controllers/configuration/kongadminapi_controller.go
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gatewayclass_controller.go
  internal/dataplane/sendconfig/sendconfig.go
  internal/manager/run.go
  test/envtest/manager_envtest_test.go
Labels: size/L

#5038 chore(logs): modifying the capitalization consistency of the logs - Part4
  hack/generators/controllers/networking/main.go
  internal/clients/manager.go
  internal/cmd/rootcmd/servers.go
  internal/controllers/configuration/secret_controller.go
  internal/controllers/configuration/zz_generated_controllers.go
  internal/controllers/gateway/gateway_utils.go
  internal/controllers/gateway/gatewayclass_controller.go
  internal/controllers/gateway/grpcroute_controller.go
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/tcproute_controller.go
  internal/controllers/gateway/tlsroute_controller.go
  internal/controllers/gateway/udproute_controller.go
  internal/dataplane/configfetcher/config_fetcher.go
  internal/dataplane/deckgen/generate.go
Labels: size/M

#5043 fix: remove HTTP ports from discovery config
  CHANGELOG.md
  docs/cli-arguments.md
  internal/manager/config.go
Labels: size/S

#5049 chore(logs): modifying the capitalization consistency of the logs - Part5
  internal/diagnostics/server.go
  internal/konnect/node_agent.go
  internal/license/agent.go
  internal/manager/featuregates/feature_gates.go
  internal/manager/featuregates/feature_gates_test.go
  internal/manager/setup.go
  internal/store/store.go
Labels: size/L

#5050 chore(logs): modifying the capitalization consistency of the logs about internal/controllers/gateway
  CHANGELOG.md
  hack/cleanup/gke_clusters.go
  hack/cleanup/konnect_runtime_groups.go
  hack/generators/controllers/networking/main.go
  internal/cmd/rootcmd/servers.go
  internal/controllers/configuration/zz_generated_controllers.go
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gatewayclass_controller.go
  internal/controllers/gateway/grpcroute_controller.go
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/referencegrant_controller.go
  internal/controllers/gateway/tcproute_controller.go
  internal/controllers/gateway/tlsroute_controller.go
  internal/controllers/gateway/udproute_controller.go
Labels: size/L

#5058 fix: log KongIngress deprecation errors only when needed
  internal/dataplane/kongstate/kongstate.go
Labels: size/M, fix

#5059 fix: fix `KongUpstreamPolicy` example manifests
  examples/kong-upstream-policy-httproute.yaml
  examples/kong-upstream-policy-ingress.yaml
Labels: size/S

#4828 feat(gateway_discovery) enable gateway discovery in db mode
  CHANGELOG.md
  config/variants/multi-gw-postgres/gateway_admin_service.yaml
  config/variants/multi-gw-postgres/gateway_deployment.yaml
  config/variants/multi-gw-postgres/gateway_service_patch.yaml
  config/variants/multi-gw-postgres/kustomization.yaml
  config/variants/multi-gw-postgres/manager_multi_gateway_patch.yaml
  config/variants/multi-gw-postgres/remove_proxy_container.yaml
  deploy/single/all-in-one-postgres-multiple-gateways.yaml
  internal/clients/manager.go
  internal/clients/manager_test.go
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_test.go
  internal/manager/config_validation.go
  internal/manager/config_validation_test.go
  internal/manager/run.go
  internal/util/dataplane/mode.go
  scripts/build-single-manifests.sh
  test/e2e/all_in_one_test.go
  test/e2e/helpers_test.go
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
Labels: area/feature, size/L

#5064 chore: release 3.0.0-rc1
  CHANGELOG.md
  LICENSES
  config/image/oss/kustomization.yaml
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
Labels: size/XXL, backport release/3.0.x

#5071 fix: use HTTPS port name for HTTPS port
  config/variants/multi-gw-postgres/gateway_admin_service.yaml
  config/variants/multi-gw/base/gateway_admin_service.yaml
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
Labels: size/XS

#5067 fix: fix webhook validation of `KongConsumer`s referring Secrets with `konghq.com/credential` label
  examples/kong-consumer-key-auth.yaml
  internal/admission/validation/consumers/credentials/validation.go
  internal/admission/validator_test.go
Labels: size/L

#5065 chore(logs): The log format starts with a capital letter in internal/dataplane
  CHANGELOG.md
  internal/dataplane/kong_client.go
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/route.go
  internal/dataplane/parser/backendref.go
  internal/dataplane/parser/ingressrules.go
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/parser_test.go
  internal/dataplane/parser/translate_grpcroute.go
  internal/dataplane/parser/translate_httproute.go
  internal/dataplane/parser/translate_tlsroute.go
  internal/dataplane/parser/translate_udproute.go
  internal/dataplane/sendconfig/inmemory_error_handling.go
  internal/dataplane/sendconfig/kong.go
  internal/dataplane/sendconfig/sendconfig.go
  internal/dataplane/synchronizer.go
  internal/diagnostics/server.go
  internal/license/agent.go
  internal/manager/health_check.go
Labels: size/L

#5073 tests: set GracefulShutdownTimeout to 0 to prevent context cancellation errors
  test/envtest/run.go
Labels: area/tests, test-flake, size/XS

#5076 tests: fix flaky TestGatewayWithGatewayClassReconciliation envtest based test
  test/envtest/gatewayclass_envtest_test.go
Labels: area/tests, test-flake, size/M

#5077 tests: fix logs encoding in envtest suite
  .github/workflows/_envtest_tests.yaml
  Makefile
  test/envtest/controller.go
  test/envtest/crds_envtest_test.go
  test/envtest/log.go
  test/envtest/run.go
Labels: area/tests, area/maintenance, size/L

#5063 fix(admission): use `Ignore` failure policy in tests (same as charts)
  CHANGELOG.md
  internal/admission/handler.go
  internal/admission/server_test.go
  internal/admission/validation/gateway/httproute.go
  internal/admission/validation/gateway/httproute_test.go
  internal/admission/validator.go
  internal/admission/validator_test.go
  test/integration/httproute_webhook_test.go
  test/integration/webhook_test.go
Labels: size/L, fix, backport release/3.0.x

#5083 [backport] chore(logs): The log format starts with a capital letter in internal/dataplane (#5065)
  CHANGELOG.md
  internal/dataplane/kong_client.go
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/route.go
  internal/dataplane/parser/backendref.go
  internal/dataplane/parser/ingressrules.go
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/parser_test.go
  internal/dataplane/parser/translate_grpcroute.go
  internal/dataplane/parser/translate_httproute.go
  internal/dataplane/parser/translate_tlsroute.go
  internal/dataplane/parser/translate_udproute.go
  internal/dataplane/sendconfig/inmemory_error_handling.go
  internal/dataplane/sendconfig/kong.go
  internal/dataplane/sendconfig/sendconfig.go
  internal/dataplane/synchronizer.go
  internal/diagnostics/server.go
  internal/license/agent.go
  internal/manager/health_check.go
Labels: area/maintenance, size/L

#5081 ci: use restricted GITHUB_TOKEN istead of GITHUB PAT for issue state check
  .github/workflows/check_fixed_issues_references.yaml
Labels: area/ci, size/XS

#5084 chore: finalize 3.0
  CHANGELOG.md
Labels: size/XS, backport release/3.0.x

#5080 fix(ci): use k8s-team-bot GH PAT in backport workflow
  .github/workflows/backport.yaml
Labels: area/ci, size/XS, backport release/3.0.x

#5091 chore(admission): enable admission for GatewayAPI v1
  hack/deploy-admission-controller.sh
Labels: size/XS

#5094 docs: align auto-generated references with konghq.com
  scripts/apidocs-gen/post-process-for-konghq.sh
  scripts/cli-arguments-docs-gen/post-process-for-konghq.sh
Labels: area/docs

#5099 chore: make the last 3 releases' titles link to their diffs
  CHANGELOG.md
Labels: area/docs

#5087 chore: pull Helm test version from Renovate
  go.mod
  test/internal/testenv/testenv.go
Labels: area/tests, size/M

#5106 chore(refactor): rename translators to subtranslator everywhere
  internal/admission/validation/gateway/httproute.go
  internal/dataplane/translator/subtranslator/atc_utils.go
  internal/dataplane/translator/subtranslator/atc_utils_test.go
  internal/dataplane/translator/subtranslator/grpcroute.go
  internal/dataplane/translator/subtranslator/grpcroute_atc.go
  internal/dataplane/translator/subtranslator/grpcroute_atc_test.go
  internal/dataplane/translator/subtranslator/grpcroute_test.go
  internal/dataplane/translator/subtranslator/httproute.go
  internal/dataplane/translator/subtranslator/httproute_atc.go
  internal/dataplane/translator/subtranslator/httproute_atc_test.go
  internal/dataplane/translator/subtranslator/httproute_test.go
  internal/dataplane/translator/subtranslator/ingress.go
  internal/dataplane/translator/subtranslator/ingress_atc.go
  internal/dataplane/translator/subtranslator/ingress_atc_test.go
  internal/dataplane/translator/subtranslator/ingress_test.go
  internal/dataplane/translator/subtranslator/l4route_atc.go
  internal/dataplane/translator/subtranslator/l4route_atc_test.go
  internal/dataplane/translator/subtranslator/portdef.go
  internal/dataplane/translator/subtranslator/subtranslator_errors.go
  internal/dataplane/translator/subtranslator/subtranslator_vars.go
  internal/dataplane/translator/translate_grpcroute.go
  internal/dataplane/translator/translate_grpcroute_test.go
  internal/dataplane/translator/translate_httproute.go
  internal/dataplane/translator/translate_httproute_test.go
  internal/dataplane/translator/translate_ingress.go
  internal/dataplane/translator/translate_ingress_test.go
  internal/dataplane/translator/translate_tcproute.go
  internal/dataplane/translator/translate_tlsroute.go
  internal/dataplane/translator/translate_udproute.go
  internal/dataplane/translator/translate_udproute_test.go
  internal/dataplane/translator/translate_utils.go
Labels: area/maintenance, refactor, size/L

#5107 chore(docs): reorganise 3.0.0 changelog entry
  CHANGELOG.md
Labels: area/docs, size/M

#5088 chore(test): bump kind version to v0.20.0
  scripts/check-container-environment.sh
Labels: size/XS

#5114 fix(ci): change path for regeneration of manifests for e2e tests
  .github/workflows/regenerate_on_deps_bump.yaml
Labels: area/ci, size/XS, fix

#5115 build: update golangci-lint config with Gateway API v1 and KIC v1 modules
  .golangci.yaml
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gateway_controller_test.go
  internal/controllers/gateway/gateway_utils.go
  internal/controllers/gateway/gateway_utils_test.go
  internal/gatewayapi/aliases.go
  internal/gatewayapi/consts.go
Labels: area/maintenance, size/M

#5070 feat: add skaffold config for Gateway Discovery multi gateway postgres profile
  Makefile
  config/variants/multi-gw-postgres/base/gateway_admin_service.yaml
  config/variants/multi-gw-postgres/base/gateway_deployment.yaml
  config/variants/multi-gw-postgres/base/gateway_service_patch.yaml
  config/variants/multi-gw-postgres/base/kustomization.yaml
  config/variants/multi-gw-postgres/base/manager_multi_gateway_patch.yaml
  config/variants/multi-gw-postgres/base/remove_proxy_container.yaml
  config/variants/multi-gw-postgres/dev/kustomization.yaml
  config/variants/multi-gw-postgres/oss/kustomization.yaml
  internal/manager/setup.go
  scripts/build-single-manifests.sh
  skaffold.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
Labels: size/M

#5118 chore: use k8s team GH PAT in regenerate on deps bump
  .github/workflows/regenerate_on_deps_bump.yaml
Labels: area/ci

#5120 [backport] fix: fix a panic when receiving a broken config from Gateway (#5003)
  internal/dataplane/configfetcher/config_fetcher.go
  internal/dataplane/configfetcher/kongrawstate.go
  internal/dataplane/configfetcher/kongrawstate_test.go
Labels: size/S

#5121 [backport] chore(deps): bump github.com/kong/go-kong from 0.47.0 to 0.48.0 (#5012)
  .golangci.yaml
  go.mod
  go.sum
  internal/dataplane/parser/atc/route.go
  internal/dataplane/parser/translate_httproute_test.go
  internal/dataplane/parser/translators/atc_utils.go
  internal/dataplane/parser/translators/grpcroute_atc.go
  internal/dataplane/parser/translators/grpcroute_atc_test.go
  internal/dataplane/parser/translators/httproute_atc.go
  internal/dataplane/parser/translators/httproute_atc_test.go
  internal/dataplane/parser/translators/ingress_atc.go
  internal/dataplane/parser/translators/ingress_atc_test.go
Labels: size/L

#5124 [backport] fix: use only 46 bits for priorities of Kong routes (#5024)
  internal/dataplane/parser/testdata/golden/grpcroute-example/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/httproute-example/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-empty-path/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-multiple-ports-for-one-service/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-ports-defined-by-name/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-regex-prefix-exact-rule/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-regex-prefixed-path/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-rule-with-tls/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-single-service-in-multiple-ingresses/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-with-acme-like-path/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-with-default-backend/expression-routes-on_golden.yaml
  internal/dataplane/parser/translators/atc_utils.go
  internal/dataplane/parser/translators/grpcroute_atc.go
  internal/dataplane/parser/translators/grpcroute_atc_test.go
  internal/dataplane/parser/translators/httproute_atc.go
  internal/dataplane/parser/translators/httproute_atc_test.go
  internal/dataplane/parser/translators/ingress_atc_test.go
Labels: size/L

#5112 tests: fix setting router flavor in integration tests
  .github/workflows/_integration_tests.yaml
Labels: area/tests, size/XS

#5125 chore: update 2.12.1 changelog
  CHANGELOG.md
Labels: area/release, size/S

#5092 Chore: Define dedicated types for DBMode and RouterFlavor
  .golangci.yaml
  internal/clients/manager.go
  internal/dataplane/client.go
  internal/dataplane/config/dbmode.go
  internal/dataplane/config/router.go
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_test.go
  internal/dataplane/synchronizer.go
  internal/dataplane/synchronizer_test.go
  internal/dataplane/translator/translator.go
  internal/dataplane/translator/translator_test.go
  internal/manager/run.go
  internal/manager/setup.go
  internal/manager/utils/kongconfig/root.go
  internal/manager/utils/kongconfig/root_test.go
  internal/util/dataplane/mode.go
  test/integration/version_test.go
  test/internal/helpers/kong.go
Labels: size/L

#5132 test: specify conformance tests by supported features
  .github/workflows/conformance_tests_report.yaml
  Makefile
  test/conformance/gateway_conformance_test.go
  test/conformance/gateway_expermimental_conformance_test.go
  test/conformance/suite_test.go
Labels: area/gateway-api, size/L, kind/conformance

#5119 feat: add CRD validation expression for `KongPlugin` and `KongClusterPlugin` `config` and `configFrom` fields
  CHANGELOG.md
  config/crd/bases/configuration.konghq.com_kongclusterplugins.yaml
  config/crd/bases/configuration.konghq.com_kongplugins.yaml
  internal/admission/errors.go
  internal/admission/validator.go
  internal/admission/validator_test.go
  pkg/apis/configuration/v1/kongclusterplugin_types.go
  pkg/apis/configuration/v1/kongplugin_types.go
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
  test/envtest/crds_envtest_test.go
Labels: size/L, area/CRD

#5137 feat(crd): enforce setting `KongConsume`r's either of `username` of `custom_id` via CRD validation rules
  CHANGELOG.md
  config/crd/bases/configuration.konghq.com_kongconsumers.yaml
  examples/kong-consumer-key-auth.yaml
  internal/admission/errors.go
  internal/admission/validator.go
  internal/dataplane/kongstate/kongstate.go
  pkg/apis/configuration/v1/kongconsumer_types.go
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
  test/envtest/kongstate_consumer_failures_test.go
  test/envtest/programmed_condition_envtest_test.go
Labels: size/M, area/CRD

#5139 fix: bound IPv6 addresses for discovery
  internal/adminapi/endpoints.go
  internal/adminapi/endpoints_test.go
Labels: size/M

#5074 Fix: add `kong-effective-version` input in validate Kong image tests and skip enterprise cases if enterprise not enabled
  .github/workflows/_e2e_tests.yaml
  .github/workflows/validate_kong_image.yaml
Labels: area/ci, size/XS

#5144 chore: fix typos in log entry and function identifier, reuse helper in test
  internal/controllers/gateway/grpcroute_controller.go
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/tcproute_controller.go
  internal/controllers/gateway/tlsroute_controller.go
  internal/controllers/gateway/udproute_controller.go
  internal/dataplane/translator/subtranslator/grpcroute_atc.go
  test/integration/examples_test.go
  test/integration/grpcroute_test.go
  test/internal/helpers/http.go
Labels: area/maintenance, refactor, size/M

#5142 feat(crd): enforce KongPlugin and KongClusterPlugin's `plugin` field be immutable via CRD validation rules
  CHANGELOG.md
  config/crd/bases/configuration.konghq.com_kongclusterplugins.yaml
  config/crd/bases/configuration.konghq.com_kongplugins.yaml
  internal/admission/errors.go
  internal/admission/validator.go
  internal/admission/validator_test.go
  pkg/apis/configuration/v1/kongclusterplugin_types.go
  pkg/apis/configuration/v1/kongplugin_types.go
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
  test/envtest/crds_envtest_test.go
Labels: size/M, area/CRD

#5150 chore: remove redundant if statements
  internal/dataplane/sendconfig/inmemory_error_handling.go
  internal/dataplane/translator/translate_grpcroute.go
Labels: area/maintenance, refactor, size/S

#5143 chore(kustomize): resolve Warning: 'patchesJson6902' is deprecated.
  config/base/kustomization.yaml
  config/certmanager/kustomization.yaml
  config/crd/kustomization.yaml
  config/variants/enterprise-postgres/kustomization.yaml
  config/variants/enterprise/kustomization.yaml
  config/variants/multi-gw-postgres/base/kustomization.yaml
  config/variants/multi-gw-postgres/oss/kustomization.yaml
  config/variants/multi-gw/oss/kustomization.yaml
  config/variants/postgres/kustomization.yaml
Labels: size/M

#5161 fix(test): TestIngressRewriteURI
  test/integration/ingress_test.go
Labels: area/tests, size/M, fix

#5103 fix: make `secretKeyRef` a required field in plugins' `configFrom`
  CHANGELOG.md
  config/crd/bases/configuration.konghq.com_kongclusterplugins.yaml
  config/crd/bases/configuration.konghq.com_kongconsumergroups.yaml
  config/crd/bases/configuration.konghq.com_kongplugins.yaml
  pkg/apis/configuration/v1/configsource.go
  pkg/apis/configuration/v1/kongclusterplugin_types.go
  pkg/apis/configuration/v1/kongconsumer_types.go
  pkg/apis/configuration/v1/kongingress_types.go
  pkg/apis/configuration/v1/kongplugin_types.go
  pkg/apis/configuration/v1beta1/ingress_rules.go
  pkg/apis/configuration/v1beta1/kongconsumergroup_types.go
  pkg/apis/configuration/v1beta1/tcpingress_types.go
  pkg/apis/configuration/v1beta1/udpingress_types.go
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
Labels: size/M

#5163 chore(admission): don't check Gateway's gatewayClassName in admission webhook
  internal/admission/validator.go
Labels: area/gateway-api, size/XS, area/admission

#5168 chore: add webhook configuration to dev kustomizations
  config/components/manager_dev_webhook/kustomization.yaml
  config/components/manager_dev_webhook/manager_webhook_listen_patch.yaml
  config/components/manager_dev_webhook/manager_webhook_secret.yaml
  config/components/manager_dev_webhook/validating_webhook_configuration.yaml
  config/variants/multi-gw-postgres/dev/kustomization.yaml
  config/variants/multi-gw/dev/kustomization.yaml
Labels: area/maintenance, size/L

#5173 chore: use current generated doc path
  .github/ISSUE_TEMPLATE/release.yaml
  .github/workflows/release_docs.yaml
Labels: size/XS

#5171 fix: annotation konghq.com/rewrite for multiple Ingresses routing to the same Service
  CHANGELOG.md
  internal/dataplane/translator/subtranslator/ingress.go
  internal/dataplane/translator/subtranslator/ingress_test.go
  internal/dataplane/translator/translate_ingress_test.go
  test/integration/ingress_test.go
Labels: area/tests, area/ingress-controller, size/L, fix

#5165 test: skip enterprise tests when image is enterprise but TEST_KONG_ENTERPRISE not enabled
  test/integration/version_test.go
Labels: area/ci, area/tests, size/XS

#5178 chore: fix GatewayClass controller and logger names after v1 GW API migration
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gatewayclass_controller.go
  internal/gatewayapi/consts.go
Labels: area/gateway-api, area/maintenance, size/S

#5179 fix(Makefile): target test.golden.update works
  Makefile
Labels: area/tests, area/maintenance, size/XS, fix

#5158 feat: support config patch for KongPlugin and KongClusterPlugin
  CHANGELOG.md
  config/crd/bases/configuration.konghq.com_kongclusterplugins.yaml
  config/crd/bases/configuration.konghq.com_kongplugins.yaml
  docs/api-reference.md
  go.mod
  internal/admission/validator.go
  internal/controllers/configuration/object_references.go
  internal/dataplane/kongstate/plugin.go
  internal/dataplane/kongstate/plugin_test.go
  internal/dataplane/kongstate/util.go
  internal/dataplane/kongstate/util_test.go
  pkg/apis/configuration/v1/configsource.go
  pkg/apis/configuration/v1/kongclusterplugin_types.go
  pkg/apis/configuration/v1/kongplugin_types.go
  pkg/apis/configuration/v1/zz_generated.deepcopy.go
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
  test/envtest/crds_envtest_test.go
  test/integration/plugin_test.go
Labels: area/feature, size/XXL, area/CRD

#5188 fix: Ingress with default backend targeting the same Service
  CHANGELOG.md
  internal/dataplane/translator/translate_ingress.go
  test/integration/ingress_test.go
Labels: area/ingress-controller, size/M, fix

#5187 chore(tests): for DB backed use traditional_compatible router
  .github/workflows/_integration_tests.yaml
Labels: area/ci, area/tests, area/maintenance, test-flake, size/XS

#5201 chore: add mention of KGO in issue template
  .github/ISSUE_TEMPLATE/release.yaml
Labels: area/docs, size/XS

#5194 tests: add unit test for ingress with default backend targeting the same Service
  internal/dataplane/translator/translate_ingress_test.go
Labels: area/tests, size/M

#4823 feat(tests): isolated integration tests
  .github/workflows/_integration_tests.yaml
  Makefile
  TESTING.md
  go.mod
  go.sum
  internal/cmd/rootcmd/run.go
  internal/util/test/controller_manager.go
  internal/util/test/crds.go
  internal/util/test/kustomize_consts.go
  internal/util/test/rbacs.go
  test/conformance/suite_test.go
  test/e2e/istio_test.go
  test/integration/addons_test.go
  test/integration/consts/consts.go
  test/integration/consts_test.go
  test/integration/examples_test.go
  test/integration/gateway_test.go
  test/integration/grpcroute_test.go
  test/integration/helpers_test.go
  test/integration/httproute_test.go
  test/integration/httproute_webhook_test.go
  test/integration/ingress_test.go
  test/integration/isolated/consts.go
  test/integration/isolated/ctx.go
  test/integration/isolated/examples_udproute_test.go
  test/integration/isolated/name.go
  test/integration/isolated/namespace.go
  test/integration/isolated/resolver.go
  test/integration/isolated/skip.go
  test/integration/isolated/suite_test.go
  test/integration/isolated/udproute_test.go
  test/integration/suite_test.go
  test/integration/tcproute_test.go
  test/integration/tlsroute_test.go
  test/integration/translation_failures_test.go
  test/integration/udproute_test.go
  test/integration/utils_test.go
  test/internal/helpers/controller_manager_flag_opts.go
  test/internal/helpers/controller_manager_flag_opts_test.go
  test/internal/helpers/exit.go
  test/internal/helpers/gatewayapi.go
  test/internal/helpers/ingress.go
  test/internal/testlabels/labels.go
Labels: area/tests, size/XXL

#5192 test: output logs to separate file and upload the file
  .github/workflows/_conformance_tests.yaml
  .github/workflows/_integration_tests.yaml
  .github/workflows/checks.yaml
Labels: size/M

#5210 Backport/fix validate kong image 2.12
  .github/workflows/_e2e_tests.yaml
  .github/workflows/validate_kong_image.yaml
  test/integration/version_test.go
Labels: area/ci, size/S, < v3.0.0

#5214 chore: correct configPatches comment about config field
  config/crd/bases/configuration.konghq.com_kongclusterplugins.yaml
  config/crd/bases/configuration.konghq.com_kongplugins.yaml
  docs/api-reference.md
  pkg/apis/configuration/v1/kongclusterplugin_types.go
  pkg/apis/configuration/v1/kongplugin_types.go
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
Labels: area/docs, size/S

#5207 chore(test): skip test when only docs be changed
  .github/workflows/benchmarks.yaml
  .github/workflows/checks.yaml
Labels: size/S

#5215 [backport release/2.12.x] fix: annotation konghq.com/rewrite for multiple Ingresses routing to the same Service (#5171)
  internal/dataplane/parser/translate_ingress_test.go
  internal/dataplane/parser/translators/ingress.go
  internal/dataplane/parser/translators/ingress_test.go
  test/integration/ingress_test.go
  test/internal/helpers/http.go
Labels: size/L, < v3.0.0

#5217 [backport release/2.12.x] fix: Ingress with default backend targeting the same Service (#5188)
  internal/dataplane/parser/translate_ingress.go
  test/integration/ingress_test.go
Labels: size/M, < v3.0.0

#5218 [backport release/3.0.x] fix: annotation konghq.com/rewrite for multiple Ingresses routing to the same Service (#5171)
  internal/dataplane/parser/translate_ingress_test.go
  internal/dataplane/parser/translators/ingress.go
  internal/dataplane/parser/translators/ingress_test.go
  test/integration/ingress_test.go
Labels: size/L

#5219 [backport release/3.0.x] fix: Ingress with default backend targeting the same Service (#5188)
  internal/dataplane/parser/translate_ingress.go
  test/integration/ingress_test.go
Labels: size/M

#5205 [release/2.12] fix: provide descriptive error for known bug with conflicting Kong Routes naming
  internal/dataplane/parser/translate_ingress.go
  internal/dataplane/parser/translate_ingress_test.go
  internal/dataplane/parser/translate_knative.go
Labels: area/maintenance, size/L, fix, < v3.0.0

#5193 chore(docs): install GWAPI from experimental channel
  README.md
Labels: size/S

#5208 fix: validate configPatches for KongClusterPlugin
  CHANGELOG.md
  internal/admission/validator.go
  internal/admission/validator_test.go
  internal/dataplane/kongstate/plugin.go
Labels: size/L

#5225 Revert "chore(test): skip test when only docs be changed (#5207)"
  .github/workflows/benchmarks.yaml
  .github/workflows/checks.yaml
Labels: area/ci, size/S, fix

#5221 chore: update CHANGELOG for patch releases 2.12.2 and 3.0.1
  CHANGELOG.md
Labels: area/release, size/M

#5229 chore: remove redundant entries from CHANGELOG
  CHANGELOG.md
Labels: area/docs, area/maintenance, size/XS

#5230 test: check existence of input KIC image and use it if exists in gke tests
  .github/workflows/_e2e_tests.yaml
Labels: area/ci, size/S, backport release/2.12.x, < v3.0.0

#5220 feat(crds): add KongServiceFacade CRD
  CHANGELOG.md
  Makefile
  config/crd/incubator/incubator.konghq.com_kongservicefacades.yaml
  config/crd/incubator/kustomization.yaml
  pkg/apis/incubator/doc.go
  pkg/apis/incubator/v1alpha1/doc.go
  pkg/apis/incubator/v1alpha1/groupversion_info.go
  pkg/apis/incubator/v1alpha1/kongservicefacade_types.go
  pkg/apis/incubator/v1alpha1/zz_generated.deepcopy.go
Labels: size/L, area/CRD

#5232 Chore: Fix script to generate reference page of custom resources in docs
  scripts/apidocs-gen/post-process-for-konghq.sh
Labels: area/docs, area/ci, size/XS

#5233 enable setting KIC image for e2e on GKE clusters (#5230)
  .github/workflows/_e2e_tests.yaml
Labels: size/S

#5235 chore(test): test SectionName and port do not match.
  internal/controllers/gateway/route_utils.go
  internal/controllers/gateway/route_utils_test.go
  test/integration/tcproute_test.go
Labels: area/tests, area/gateway-api, size/L

#5128 fix: support GRPC with Gateway's HTTP listener
  CHANGELOG.md
  examples/gateway-grpcroute-via-http.yaml
  examples/gateway-grpcroute-via-https.yaml
  internal/controllers/gateway/gateway_utils.go
  internal/controllers/gateway/gateway_utils_test.go
  internal/controllers/gateway/route_utils.go
  internal/dataplane/translator/translate_grpcroute.go
  test/integration/examples_test.go
  test/integration/grpcroute_test.go
  test/integration/isolated/consts.go
  test/integration/isolated/ctx.go
  test/integration/isolated/examples_grpc_test.go
  test/integration/isolated/examples_udproute_test.go
  test/integration/isolated/grpc_test.go
  test/integration/isolated/suite_test.go
  test/internal/testlabels/labels.go
Labels: area/feature, size/XL

#5231 feat: add KongServiceFacade controller and feature gate
  FEATURE_GATES.md
  config/rbac/role.yaml
  docs/cli-arguments.md
  hack/generators/controllers/networking/main.go
  internal/controllers/configuration/zz_generated_controllers.go
  internal/manager/config.go
  internal/manager/controllerdef.go
  internal/manager/featuregates/feature_gates.go
  internal/store/cache_stores.go
  internal/store/cache_stores_test.go
  internal/store/fake_store.go
  internal/store/fake_store_test.go
  internal/store/store.go
  pkg/apis/incubator/doc.go
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
  test/envtest/telemetry_test.go
Labels: area/feature, size/L

#5242 Backport kic log dump to release/2.12.x
  .github/workflows/_conformance_tests.yaml
  .github/workflows/_integration_tests.yaml
  .github/workflows/e2e_nightly.yaml
  .github/workflows/pr_checks.yaml
  .github/workflows/validate_kong_image.yaml
Labels: area/ci, size/M, < v3.0.0

#5213 disable HTTP/2 of admin api in e2e if Kong < 3.0.0
  test/e2e/all_in_one_test.go
  test/e2e/helpers_test.go
  test/e2e/kustomizations_test.go
  test/e2e/upgrade_test.go
  test/e2e/utils_test.go
Labels: area/tests, size/L, < v3.0.0

#5250 fix: do not set `instance_name` of plugin if Kong version is below 3.2.0
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/kongstate_test.go
  internal/dataplane/kongstate/util.go
  internal/dataplane/kongstate/util_test.go
  internal/dataplane/parser/parser.go
  internal/versions/versions.go
Labels: size/L, < v3.0.0

#5239 chore(tests): gRPC with Ingress over HTTP and HTTPS
  test/integration/consts/consts.go
  test/integration/consts_test.go
  test/integration/ingress_test.go
  test/integration/isolated/ctx.go
  test/integration/isolated/ingress_test.go
  test/integration/isolated/suite_test.go
  test/internal/testlabels/labels.go
Labels: area/tests, area/maintenance, size/L

#5238 fix(manager): set InitCacheSyncDuration to 5s by default and allow it…
  CHANGELOG.md
  docs/cli-arguments.md
  internal/manager/config.go
Labels: size/XS, backport release/2.12.x

#5262 chore: add defaultServiceTimeoutInKongFormat helper
  internal/dataplane/translator/subtranslator/ingress.go
  internal/dataplane/translator/subtranslator/ingress_atc_test.go
  internal/dataplane/translator/subtranslator/ingress_test.go
Labels: area/maintenance
