Repository Kong/kubernetes-ingress-controller, pull requests merged in 2023-07, with the labels that each got.

#4255 [Backport release/2.10.x] Backport #4238 to 2.10.x
  CHANGELOG.md
  internal/dataplane/parser/testdata/golden/grpcroute-example/default_golden.yaml
  internal/dataplane/parser/testdata/golden/grpcroute-example/in.yaml
  internal/dataplane/parser/testdata/golden/grpcroute-example/regex-path-prefix-off_golden.yaml
  internal/dataplane/parser/testdata/golden/grpcroute-example/regex-path-prefix-off_settings.yaml
  internal/dataplane/parser/translate_grpcroute.go
  internal/dataplane/parser/translators/grpcroute.go
  internal/dataplane/parser/translators/grpcroute_test.go
Labels: size/L

#4271 test: generate certs in each run in integration tests using TLS
  test/envtest/telemetry_test.go
  test/helpers/certificate/certificate.go
  test/integration/ingress_https_test.go
  test/integration/tcpingress_test.go
  test/integration/tlsroute_test.go
Labels: area/tests, size/L

#4240 feat(expression router) assign route priority ingress
  CHANGELOG.md
  internal/dataplane/parser/translators/atc_utils.go
  internal/dataplane/parser/translators/ingress_atc.go
  internal/dataplane/parser/translators/ingress_atc_test.go
Labels: area/feature, size/L

#4274 chore: remove redundant // +optional for CRDs' fields
  pkg/apis/configuration/v1beta1/ingress_rules.go
  pkg/apis/configuration/v1beta1/tcpingress_types.go
  pkg/apis/configuration/v1beta1/udpingress_types.go
Labels: area/maintenance, size/XS

#4275 test: add common name to SANs in certificate used in TestHTTPSIngress
  test/integration/ingress_https_test.go
Labels: area/tests, size/XS

#4277 refactor: don't log missing pod reference in every update
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_test.go
  test/mocks/events_recorder.go
Labels: size/L

#4267 fix: make status queue not block when no sub exists
  CHANGELOG.md
  internal/adminapi/endpoints_envtest_test.go
  internal/controllers/gateway/grpcroute_controller.go
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/tcproute_controller.go
  internal/controllers/gateway/tlsroute_controller.go
  internal/controllers/gateway/udproute_controller.go
  internal/manager/config.go
  internal/manager/controllerdef.go
  internal/manager/run.go
  internal/util/builder/httproutematch.go
  internal/util/kubernetes/object/status/queue.go
  internal/util/kubernetes/object/status/queue_test.go
  test/envtest/adminapimock.go
  test/envtest/controller.go
  test/envtest/httproute_controller_test.go
  test/envtest/k8s_objects_status_envtest_test.go
Labels: bug, size/XL, backport release/2.10.x

#4279 chore: add grpcroute to changelog entry
  CHANGELOG.md
Labels: size/XS

#4283 prepare release 2.10.2
  CHANGELOG.md
Labels: area/release, size/XS

#4096 test(e2e): use legacy manifest and skip tests for KIC version < 2.9
  test/e2e/all_in_one_test.go
  test/e2e/compatibilities_test.go
  test/e2e/features_test.go
  test/e2e/konnect_test.go
  test/e2e/kuma_test.go
  test/e2e/utils_test.go
Labels: area/tests, area/maintenance, size/M

#4288 chore(manifests): update KIC image version to 2.10.2 in manifests
  config/image/oss/kustomization.yaml
  deploy/single/all-in-one-dbless-enterprise.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless-legacy.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
Labels: size/S, backport release/2.10.x

#4287 [Backport release/2.10.x] chore(ci): do not run e2e tests triggered by label on GKE clusters
  .github/workflows/e2e_targeted.yaml
  .github/workflows/e2e_trigger_via_label.yaml
Labels: size/S

#4291 [Backport release/2.10.x] Bump kubernetes telemetry to 0.1.0
  go.mod
  go.sum
  test/envtest/telemetry_test.go
Labels: area/telemetry, size/M

#4285 [Backport release/2.9.x] ci: run PR checks on PRs against all branches (#4223)
  .github/workflows/_integration_tests.yaml
  .github/workflows/pr_checks.yaml
Labels: area/ci, size/XS

#4276 [Backport release/2.9.x] fix(rbac): fix leader election policy rules
  CHANGELOG.md
  config/rbac/leader_election_role.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless-legacy.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
Labels: area/maintenance, size/M

#4297 [backport-to-2.10.x] update KIC image version to 2.10.2 in manifests (#4288)
  config/image/oss/kustomization.yaml
  deploy/single/all-in-one-dbless-enterprise.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless-legacy.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
Labels: size/S

#4300 chore: correct v2.10.2 release date
  CHANGELOG.md
Labels: area/docs

#4299 chore: add v2.10.2 changelog entry
  CHANGELOG.md
Labels: area/docs, size/S

#4302 chore: namespace RBACs added
  config/rbac/gateway/role.yaml
  deploy/single/all-in-one-dbless-enterprise.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless-legacy.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  internal/controllers/gateway/httproute_controller.go
Labels: area/gateway-api, size/M

#4306 refactor: extract adminapi.Discoverer and add tests
  internal/adminapi/client.go
  internal/adminapi/endpoints.go
  internal/adminapi/endpoints_envtest_test.go
  internal/adminapi/endpoints_test.go
  internal/clients/manager.go
  internal/clients/manager_test.go
  internal/controllers/configuration/kongadminapi_controller.go
  internal/controllers/configuration/kongadminapi_controller_envtest_test.go
  internal/manager/config.go
  internal/manager/controllerdef.go
  internal/manager/run.go
  internal/manager/setup.go
  internal/manager/setup_test.go
  test/mocks/admin_api_client_factory.go
  test/mocks/admin_api_discoverer.go
Labels: size/L

#4314 chore(release): clarify what is a latest release
  .github/ISSUE_TEMPLATE/release.yaml
Labels: size/XS

#4305 feat(ci): release workflow updates the latest branch to point to latest tag
  .github/ISSUE_TEMPLATE/release.yaml
  .github/workflows/release.yaml
Labels: area/ci, size/S

#4320 chore(docs): remove bit.ly link from README.md
  README.md
Labels: area/docs, area/maintenance

#4316 feat: add stub upstream when config is empty in dbless mode
  CHANGELOG.md
  internal/dataplane/deckgen/deckgen.go
  internal/dataplane/deckgen/deckgen_test.go
  internal/dataplane/deckgen/generate.go
  internal/dataplane/deckgen/generate_test.go
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_test.go
  internal/dataplane/sendconfig/config_change_detector.go
Labels: area/feature, size/L

#4323 tests: watch instead of busy loop in gatewayclass envtest
  test/envtest/gatewayclass_envtest_test.go
Labels: area/tests, area/maintenance, size/M

#4324 fix(konnect): update nodes status only when it actually changes
  CHANGELOG.md
  internal/clients/manager.go
  internal/clients/manager_test.go
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_test.go
  internal/konnect/mock_node_api_test.go
  internal/konnect/node_agent.go
  internal/konnect/node_agent_test.go
Labels: size/L, area/konnect, fix, backport release/2.10.x

#4326 chore: mark all all-in-one-*.yaml as autogenerated
  deploy/single/all-in-one-dbless-enterprise.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless-legacy.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  scripts/build-single-manifests.sh
Labels: area/maintenance, size/M

#4319 tests: transform TestMissingCRDsDontCrashTheControler into envtest
  test/e2e/features_test.go
  test/e2e/kustomizations_test.go
  test/e2e/utils_test.go
  test/envtest/crds_envtest_test.go
  test/envtest/k8s_objects_status_envtest_test.go
  test/envtest/run.go
Labels: area/tests, size/L

#4331 chore: mark content of deploy/single/ dir as autogenerated
  .gitattributes
Labels: area/maintenance, size/XS

#4334 chore: mark file docs/api-reference.md as autogenerated
  .gitattributes
Labels: area/maintenance, size/XS

#4332 [Backport 2.10.x] fix(konnect): update nodes status only when it actually changes
  CHANGELOG.md
  internal/clients/manager.go
  internal/clients/manager_test.go
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_test.go
  internal/konnect/mock_node_api_test.go
  internal/konnect/node_agent.go
  internal/konnect/node_agent_test.go
  internal/util/clock/clock.go
  internal/util/clock/ticker.go
  test/mocks/ticker.go
  test/mocks/ticker_test.go
Labels: size/XL, area/konnect, fix

#4337 [Backport release/2.10.x] tests: fix flaky TestAgent (#4203)
  internal/adminapi/backoff_strategy_konnect.go
  internal/adminapi/client.go
  internal/license/agent.go
  internal/license/agent_test.go
Labels: area/tests, size/L

#4335 chore: changelog and manifests for 2.10.3 release
  CHANGELOG.md
  config/image/oss/kustomization.yaml
  deploy/single/all-in-one-dbless-enterprise.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless-legacy.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
Labels: area/release

#4338 [Backport release/2.9.x] fix: make status queue not block when no sub exists (#4267)
  CHANGELOG.md
  internal/controllers/gateway/grpcroute_controller.go
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/tcproute_controller.go
  internal/controllers/gateway/tlsroute_controller.go
  internal/controllers/gateway/udproute_controller.go
  internal/manager/controllerdef.go
  internal/util/builder/httproutematch.go
  internal/util/kubernetes/object/status/queue.go
  internal/util/kubernetes/object/status/queue_test.go
Labels: size/L, fix

#4336 chore: prepare release 2.10.3
  CHANGELOG.md
  config/image/oss/kustomization.yaml
  deploy/single/all-in-one-dbless-enterprise.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless-legacy.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
Labels: area/release, size/XS

#4341 chore: prepare release 2.9.4
  .github/workflows/release.yaml
  CHANGELOG.md
  config/image/oss/kustomization.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless-legacy.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
Labels: area/release

#4339 chore(ci): require major.minor in manifests
  .github/workflows/release.yaml
Labels: area/ci, size/XS

#4296 implement assigning priorities to Kong routes translated from `HTTPRoute`
  CHANGELOG.md
  internal/dataplane/parser/translate_httproute.go
  internal/dataplane/parser/translate_httproute_test.go
  internal/dataplane/parser/translators/httproute_atc.go
  internal/dataplane/parser/translators/httproute_atc_test.go
  test/conformance/gateway_conformance_test.go
Labels: area/feature, size/XXL

#4340 [release/2.10.x] chore(ci): require major.minor in manifests
  .github/workflows/release.yaml
Labels: area/ci, size/XS

#4344 chore: add missing changelog links
  CHANGELOG.md
Labels: area/docs

#4345 test(conformance): disable HTTPRouteHeaderMatching
  test/conformance/gateway_conformance_test.go
Labels: size/XS

#4280 [Backport release/2.5.x] fix: make status queue not block when no sub exists (#4267)
  CHANGELOG.md
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/tcproute_controller.go
  internal/controllers/gateway/tlsroute_controller.go
  internal/controllers/gateway/udproute_controller.go
  internal/manager/controllerdef.go
  internal/util/kubernetes/object/status/queue.go
  internal/util/kubernetes/object/status/queue_test.go
Labels: bug, size/L

#4347 chore(release) date changelog and generate manifests
  CHANGELOG.md
  config/image/oss/kustomization.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
Labels: size/XS

#4349 chore(ci) update 2.5 test platform versions
  .github/workflows/e2e.yaml
  .github/workflows/release.yaml
Labels: size/S

#4350 feat: support ResponseHeaderModifier filter
  CHANGELOG.md
  internal/dataplane/parser/translators/httproute.go
  internal/dataplane/parser/translators/httproute_test.go
  test/conformance/gateway_conformance_test.go
Labels: size/M

#4353 chore(ci): make github release latest only when asked for
  .github/workflows/release.yaml
Labels: area/ci, size/XS, backport release/2.10.x, backport release/2.5.x

#4346 chore(ci): make release e2e tests run in parallel jobs
  .github/workflows/release.yaml
Labels: area/ci, size/M

#4356 feat(ci): release workflow updates the latest branch to point to late…
  .github/ISSUE_TEMPLATE/release.yaml
  .github/workflows/release.yaml
Labels: area/ci, size/S

#4357 feat: make NewKongClientForWorkspace first verify status + tests
  internal/adminapi/client_test.go
  internal/adminapi/kong.go
  internal/adminapi/kong_test.go
  test/envtest/adminapimock.go
  test/mocks/admin_api_handler.go
Labels: area/feature, size/L

#4355 tests: verify all deployments are ready after installation
  test/e2e/all_in_one_test.go
  test/e2e/compatibilities_test.go
  test/e2e/features_test.go
  test/e2e/helpers_test.go
  test/e2e/konnect_test.go
  test/e2e/kuma_test.go
  test/e2e/upgrade_test.go
  test/e2e/utils_test.go
Labels: area/tests, size/L

#4365 chore: maintainers.md update
  MAINTAINERS.md
Labels: size/S

#4367 chore: remove outdated debug skaffold profile
  Makefile
  skaffold.yaml
Labels: area/maintenance

#4325 feat(crd): add KongConsumerGroup CRD
  CHANGELOG.md
  PROJECT
  config/crd/bases/configuration.konghq.com_kongconsumergroups.yaml
  config/crd/kustomization.yaml
  config/rbac/role.yaml
  deploy/single/all-in-one-dbless-enterprise.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless-legacy.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  docs/api-reference.md
  hack/generators/controllers/networking/main.go
  internal/controllers/configuration/zz_generated_controllers.go
  internal/manager/controllerdef.go
  pkg/apis/configuration/v1beta1/kongconsumergroup_types.go
  pkg/apis/configuration/v1beta1/zz_generated.deepcopy.go
  pkg/clientset/typed/configuration/v1beta1/configuration_client.go
  pkg/clientset/typed/configuration/v1beta1/fake/fake_configuration_client.go
  pkg/clientset/typed/configuration/v1beta1/fake/fake_kongconsumergroup.go
  pkg/clientset/typed/configuration/v1beta1/generated_expansion.go
  pkg/clientset/typed/configuration/v1beta1/kongconsumergroup.go
  test/envtest/crds_envtest_test.go
Labels: area/feature, size/L, area/CRD

#4383 refactor: use controllers.DataPlane interface instead of concrete *dataplane.KongClient
  hack/generators/controllers/networking/main.go
  internal/controllers/configuration/object_references.go
  internal/controllers/configuration/secret_controller.go
  internal/controllers/configuration/zz_generated_controllers.go
  internal/controllers/dataplane.go
  internal/controllers/gateway/grpcroute_controller.go
  internal/controllers/gateway/referencegrant_controller.go
  internal/controllers/gateway/tcproute_controller.go
  internal/controllers/gateway/tlsroute_controller.go
  internal/controllers/gateway/udproute_controller.go
  internal/controllers/knative/knative.go
  internal/dataplane/kong_client.go
  internal/manager/controllerdef.go
  test/mocks/dataplane.go
Labels: area/debt, refactor, size/M

#4374 chore(tests): add proper error for unexpected status code in GetKongVersion
  test/internal/helpers/kong.go
Labels: area/tests, area/maintenance, size/S

#4265 feat: fetch and store last good config
  CHANGELOG.md
  internal/dataplane/configfetcher/config_fetcher.go
  internal/dataplane/configfetcher/kongrawstate.go
  internal/dataplane/configfetcher/kongrawstate_test.go
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_test.go
  internal/dataplane/kongstate/types.go
  internal/dataplane/kongstate/upstream.go
  internal/dataplane/sendconfig/config_change_detector.go
  internal/dataplane/sendconfig/config_change_detector_test.go
  internal/dataplane/synchronizer.go
  internal/manager/config_validation.go
  internal/manager/run.go
  internal/manager/setup.go
  internal/util/dataplane/mode.go
  test/e2e/all_in_one_test.go
  test/e2e/helpers_test.go
Labels: size/XXL

#4386 feat: extend KongPlugin, KongClusterPlugin and Consumer with status
  config/crd/bases/configuration.konghq.com_kongclusterplugins.yaml
  config/crd/bases/configuration.konghq.com_kongconsumers.yaml
  config/crd/bases/configuration.konghq.com_kongplugins.yaml
  deploy/single/all-in-one-dbless-enterprise.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless-legacy.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  docs/api-reference.md
  pkg/apis/configuration/v1/kongclusterplugin_types.go
  pkg/apis/configuration/v1/kongconsumer_types.go
  pkg/apis/configuration/v1/kongplugin_types.go
  pkg/apis/configuration/v1/zz_generated.deepcopy.go
  pkg/clientset/typed/configuration/v1/fake/fake_kongclusterplugin.go
  pkg/clientset/typed/configuration/v1/fake/fake_kongconsumer.go
  pkg/clientset/typed/configuration/v1/fake/fake_kongplugin.go
  pkg/clientset/typed/configuration/v1/kongclusterplugin.go
  pkg/clientset/typed/configuration/v1/kongconsumer.go
  pkg/clientset/typed/configuration/v1/kongplugin.go
Labels: size/L

#4388 chore(tests): better logging for retries of GetKongVersion
  test/integration/suite_test.go
Labels: area/maintenance, size/S

#4368 feat: use /status/ready as readiness probe of gateway for gateway discovery
  CHANGELOG.md
  config/variants/multi-gw/base/gateway_deployment.yaml
  deploy/single/all-in-one-dbless-enterprise.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless.yaml
  internal/adminapi/client.go
  internal/adminapi/endpoints.go
  internal/adminapi/endpoints_test.go
  internal/clients/config_status_test.go
  internal/clients/manager.go
  internal/clients/manager_test.go
  internal/clients/readiness.go
  internal/clients/readiness_test.go
  internal/controllers/configuration/kongadminapi_controller.go
  internal/controllers/configuration/kongadminapi_controller_envtest_test.go
  internal/manager/run.go
  test/e2e/helpers_test.go
  test/e2e/kuma_test.go
  test/e2e/upgrade_test.go
Labels: size/XXL

#4400 fix: bump deck to handle Certificate updates in Konnect sync properly
  CHANGELOG.md
  go.mod
  go.sum
  internal/dataplane/sendconfig/dbmode.go
  internal/dataplane/sendconfig/strategy.go
Labels: size/M, area/konnect, fix, backport release/2.10.x

#4399 chore: add SetLogger to all reconcilers to use them in envtest
  hack/generators/controllers/networking/main.go
  internal/controllers/configuration/kongadminapi_controller.go
  internal/controllers/configuration/secret_controller.go
  internal/controllers/configuration/zz_generated_controllers.go
Labels: size/S

#4401 fix: bump deck to handle Certificate updates in Konnect sync, prepare 2.10.4
  CHANGELOG.md
  config/crd/bases/configuration.konghq.com_kongingresses.yaml
  deploy/single/all-in-one-dbless-enterprise.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless-legacy.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  go.mod
  go.sum
  internal/dataplane/sendconfig/dbmode.go
  internal/dataplane/sendconfig/strategy.go
Labels: dependencies, size/L, area/konnect, fix

#4364 feat: implement assignment of priorities to Kong routes from GRPCRoutes
  CHANGELOG.md
  internal/dataplane/parser/translate_grpcroute.go
  internal/dataplane/parser/translate_grpcroute_test.go
  internal/dataplane/parser/translators/grpcroute_atc.go
  internal/dataplane/parser/translators/grpcroute_atc_test.go
  internal/dataplane/parser/translators/grpcroute_test.go
  internal/dataplane/parser/translators/httproute_atc.go
  internal/dataplane/parser/translators/httproute_atc_test.go
Labels: area/feature, size/XXL

#4398 fix: register translation failures on translating KongConsumers
  CHANGELOG.md
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/kongstate_test.go
  internal/dataplane/parser/parser.go
  test/envtest/kongstate_consumer_failures_test.go
  test/envtest/setup.go
Labels: size/XL

#4410 refactor: introduce KongTestWorkspace constant
  test/consts/misc.go
  test/internal/helpers/ktf.go
Labels: area/maintenance, refactor, size/XS

#4391 fix(parser) bound v6 targets properly
  CHANGELOG.md
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/parser_test.go
Labels: size/M

#4409 feat: populate Programmed condition for KongConsumer
  CHANGELOG.md
  config/crd/bases/configuration.konghq.com_kongconsumers.yaml
  deploy/single/all-in-one-dbless-enterprise.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless-legacy.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  hack/generators/controllers/networking/main.go
  internal/controllers/configuration/zz_generated_controllers.go
  internal/controllers/utils/conditions.go
  internal/controllers/utils/conditions_test.go
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/parser_test.go
  internal/manager/controllerdef.go
  internal/metrics/metrics_envtest_test.go
  pkg/apis/configuration/v1/conditions.go
  pkg/apis/configuration/v1/kongconsumer_types.go
  test/envtest/manager_debugendpoints_test.go
  test/envtest/programmed_condition_envtest_test.go
  test/envtest/telemetry_test.go
Labels: area/feature, size/XL, area/CRD

#4413 tests: do not use global scheme in envtests
  internal/adminapi/endpoints_envtest_test.go
  internal/controllers/configuration/kongadminapi_controller_envtest_test.go
  test/envtest/controller.go
  test/envtest/gatewayclass_envtest_test.go
  test/envtest/httproute_controller_test.go
  test/envtest/k8s_objects_status_envtest_test.go
  test/envtest/kongstate_consumer_failures_test.go
  test/envtest/programmed_condition_envtest_test.go
  test/envtest/scheme.go
Labels: area/tests, size/L

#4412 feat: populate Programmed condition for KongPlugin and KongClusterPlugin
  CHANGELOG.md
  hack/generators/controllers/networking/main.go
  internal/controllers/configuration/zz_generated_controllers.go
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/types.go
  internal/dataplane/kongstate/util.go
  internal/dataplane/kongstate/util_test.go
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/parser_test.go
  internal/manager/controllerdef.go
  test/envtest/programmed_condition_envtest_test.go
Labels: area/feature, size/L, area/CRD

#4417 chore(docs): update testing docs
  CONTRIBUTING.md
  Makefile
  TESTING.md
Labels: area/docs, area/maintenance, size/M

#4387 feat: Consumer Group can be configured
  CHANGELOG.md
  internal/dataplane/deckgen/generate.go
  internal/dataplane/kongstate/consumergroup.go
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/parser/parser.go
  internal/store/fake_store.go
  internal/store/fake_store_test.go
  internal/store/store.go
  internal/versions/versions.go
  test/integration/consumer_group_test.go
Labels: area/feature, size/L, area/CRD

#4375 fix(parser) support same-name services across NSes
  CHANGELOG.md
  internal/dataplane/parser/ingressrules.go
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/testdata/golden/same-name-services-single-backend/default_golden.yaml
  internal/dataplane/parser/testdata/golden/same-name-services-single-backend/in.yaml
Labels: size/L

#4424 feat: add kubebuilder annotations to programmed conditions
  config/crd/bases/configuration.konghq.com_kongclusterplugins.yaml
  config/crd/bases/configuration.konghq.com_kongplugins.yaml
  deploy/single/all-in-one-dbless-enterprise.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless-legacy.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  pkg/apis/configuration/v1/kongclusterplugin_types.go
  pkg/apis/configuration/v1/kongplugin_types.go
Labels: area/feature, size/M, area/CRD

#4425 feat: add printer columns for programmed condition
  CHANGELOG.md
  config/crd/bases/configuration.konghq.com_kongclusterplugins.yaml
  config/crd/bases/configuration.konghq.com_kongconsumers.yaml
  config/crd/bases/configuration.konghq.com_kongplugins.yaml
  deploy/single/all-in-one-dbless-enterprise.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless-legacy.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  pkg/apis/configuration/v1/kongclusterplugin_types.go
  pkg/apis/configuration/v1/kongconsumer_types.go
  pkg/apis/configuration/v1/kongplugin_types.go
Labels: area/feature, size/S, area/CRD

#4426 tests: add parser golden tests covering expression routes
  .gitattributes
  internal/dataplane/parser/testdata/golden/grpcroute-example/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/grpcroute-example/expression-routes-on_settings.yaml
  internal/dataplane/parser/testdata/golden/httproute-example/default_golden.yaml
  internal/dataplane/parser/testdata/golden/httproute-example/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/httproute-example/expression-routes-on_settings.yaml
  internal/dataplane/parser/testdata/golden/httproute-example/in.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-empty-path/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-empty-path/expression-routes-on_settings.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-multiple-ports-for-one-service/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-multiple-ports-for-one-service/expression-routes-on_settings.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-ports-defined-by-name/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-ports-defined-by-name/expression-routes-on_settings.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-regex-prefix-exact-rule/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-regex-prefix-exact-rule/expression-routes-on_settings.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-regex-prefixed-path/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-regex-prefixed-path/expression-routes-on_settings.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-rule-with-tls/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-rule-with-tls/expression-routes-on_settings.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-single-service-in-multiple-ingresses/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-single-service-in-multiple-ingresses/expression-routes-on_settings.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-with-acme-like-path/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-with-acme-like-path/expression-routes-on_settings.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-with-default-backend/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-with-default-backend/expression-routes-on_settings.yaml
Labels: area/tests, size/XL

#4423 feat: populate Programmed condition for KongConsumerGroup
  CHANGELOG.md
  config/crd/bases/configuration.konghq.com_kongconsumergroups.yaml
  deploy/single/all-in-one-dbless-enterprise.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless-legacy.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  docs/api-reference.md
  hack/generators/controllers/networking/main.go
  internal/controllers/configuration/zz_generated_controllers.go
  internal/dataplane/kongstate/consumergroup.go
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/parser_test.go
  internal/manager/controllerdef.go
  pkg/apis/configuration/v1/conditions.go
  pkg/apis/configuration/v1/kongprotocol_types.go
  pkg/apis/configuration/v1beta1/kongconsumergroup_types.go
  pkg/apis/configuration/v1beta1/zz_generated.deepcopy.go
  pkg/clientset/typed/configuration/v1beta1/fake/fake_kongconsumergroup.go
  pkg/clientset/typed/configuration/v1beta1/kongconsumergroup.go
  test/envtest/programmed_condition_envtest_test.go
  test/integration/consumer_group_test.go
Labels: area/feature, size/L, area/CRD

#4427 fix: do not use address to a loop variable in parser
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/parser_test.go
Labels: size/M, fix

#4419 feat: Consumer Groups can be configured in Consumer
  CHANGELOG.md
  config/crd/bases/configuration.konghq.com_kongconsumers.yaml
  deploy/single/all-in-one-dbless-enterprise.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless-legacy.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  docs/api-reference.md
  internal/dataplane/deckgen/generate.go
  internal/dataplane/kongstate/consumer.go
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/parser/testdata/golden/consumer-group-example/default_golden.yaml
  internal/dataplane/parser/testdata/golden/consumer-group-example/in.yaml
  pkg/apis/configuration/v1/kongconsumer_types.go
  pkg/apis/configuration/v1/zz_generated.deepcopy.go
  test/integration/consumer_group_test.go
Labels: area/feature, size/L, area/CRD

#4429 chore: add looppointer linter and fix found issues
  Makefile
  internal/admission/server_test.go
  internal/admission/validator.go
  internal/controllers/gateway/grpcroute_controller.go
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/tcproute_controller.go
  internal/controllers/gateway/tlsroute_controller.go
  internal/controllers/gateway/udproute_controller.go
  internal/dataplane/deckgen/generate.go
  internal/dataplane/kongstate/route_test.go
  internal/dataplane/kongstate/service_test.go
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/translate_ingress.go
  internal/dataplane/parser/translators/ingress.go
  third_party/go.mod
  third_party/go.sum
  third_party/looppointer.go
Labels: area/maintenance, size/M

#4428 feat: propagate translation failures for KongPlugin and KongClusterPlugin
  CHANGELOG.md
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/util.go
  internal/dataplane/parser/parser.go
  test/envtest/programmed_condition_envtest_test.go
Labels: area/feature, size/L

#4432 chore: remove non-existent makefile test.integration dependency
  Makefile
Labels: area/maintenance, size/XS

#4376 tests: add impersonation to integration test
  internal/manager/config.go
  internal/util/test/controller_manager.go
  internal/util/test/crds.go
  internal/util/test/rbacs.go
Labels: area/tests, size/M
