Repository Kong/kubernetes-ingress-controller, pull requests merged in 2023-02, with the labels that each got.

#3464 refactor: extract prepareSendDiagnosticFn
  internal/dataplane/kong_client.go
Labels: refactor, size/M

#3470 refactor: extract gateway controller name utils
  internal/admission/validator.go
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gateway_controller_test.go
  internal/controllers/gateway/gateway_utils.go
  internal/controllers/gateway/gatewayclass_controller.go
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/route_utils.go
  internal/controllers/gateway/tcproute_controller.go
  internal/controllers/gateway/tlsroute_controller.go
  internal/controllers/gateway/udproute_controller.go
  internal/manager/config.go
  internal/manager/config_validation_test.go
  internal/manager/run.go
  test/conformance/gateway_conformance_test.go
  test/e2e/helpers_gateway_test.go
  test/integration/helpers_test.go
Labels: refactor, size/M

#3451 test: Conformance tests flakiness fix
  internal/controllers/gateway/httproute_controller.go
Labels: size/L

#3473 fix: don't panic when calling NewCtrlFuncMetrics() more than once
  internal/metrics/prometheus.go
  internal/metrics/prometheus_test.go
Labels: area/tests, size/S

#3471 tests: don't set plugin annotation when not needed
  test/integration/httproute_test.go
Labels: area/tests, size/XS

#3476 chore: fix udp related flags descriptions
  internal/manager/config.go
Labels: area/maintenance, size/S

#3474 chore: add config manifests and skaffold configuration for kong admin api servie discovery
  Makefile
  config/debug/base/kustomization.yaml
  config/debug/base/manager_debug.yaml
  config/debug/multi_gw/gateway_admin_service.yaml
  config/debug/multi_gw/gateway_deployment.yaml
  config/debug/multi_gw/gateway_service_patch.yaml
  config/debug/multi_gw/kustomization.yaml
  config/debug/multi_gw/manager_multi_gateway_patch.yaml
  config/debug/multi_gw/remove_proxy_container.yaml
  skaffold.yaml
Labels: area/maintenance, size/L

#3478 chore: fix ingress class const refactor
  test/integration/ingress_test.go
  test/integration/suite_test.go
Labels: area/maintenance, size/XS

#3462 refactor: extract sendconfig.Config
  internal/dataplane/kong_client.go
  internal/dataplane/sendconfig/kong.go
  internal/dataplane/sendconfig/sendconfig.go
  internal/manager/run.go
Labels: refactor, size/L

#3483 chore(scd): add multi-gw manifests variant
  config/variants/multi-gw/base/gateway_admin_service.yaml
  config/variants/multi-gw/base/gateway_deployment.yaml
  config/variants/multi-gw/base/gateway_service_patch.yaml
  config/variants/multi-gw/base/kustomization.yaml
  config/variants/multi-gw/base/manager_multi_gateway_patch.yaml
  config/variants/multi-gw/base/remove_proxy_container.yaml
  config/variants/multi-gw/debug/kustomization.yaml
  config/variants/multi-gw/debug/manager_debug.yaml
  deploy/single/all-in-one-dbless-multi-gw.yaml
  scripts/build-single-manifests.sh
  skaffold.yaml
Labels: area/maintenance, size/XXL

#3487 chore: Confomance flakiness changelog update
  CHANGELOG.md
Labels: size/XS

#3486 fix(tests): overwrite an old enterprise image in ktf
  test/integration/suite_test.go
Labels: area/maintenance, size/XS

#3485 fix: correct validation of tls cert and key
  internal/manager/config_validation.go
  internal/manager/config_validation_test.go
Labels: area/maintenance, size/S

#3488 feat: print kong version when skipping tests
  internal/dataplane/parser/translate_utils.go
  test/integration/ingress_regex_match_test.go
  test/integration/ingress_test.go
  test/integration/plugin_test.go
Labels: area/maintenance, size/M

#3489 fix(tests): don't use 2.x style path regex where requiring 3.x one
  test/integration/ingress_test.go
Labels: area/tests, size/XS

#3463 refactor: join adminapi.Client and sendconfig.ClientWithPluginSchemaStore
  internal/adminapi/client.go
  internal/adminapi/kong.go
  internal/adminapi/konnect.go
  internal/adminapi/konnect_test.go
  internal/dataplane/deckgen/generate.go
  internal/dataplane/kong_client.go
  internal/dataplane/sendconfig/kong.go
  internal/dataplane/sendconfig/sendconfig.go
  internal/manager/setup.go
  internal/manager/utils/kongconfig/root.go
  internal/manager/utils/reports.go
Labels: refactor, size/L

#3498 refactor: extract hasConfigurationChanged
  internal/dataplane/sendconfig/sendconfig.go
  internal/dataplane/sendconfig/sendconfig_test.go
Labels: size/L

#3496 chore: bump Gateway API to 0.6.0
  CHANGELOG.md
  go.mod
  go.sum
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gateway_controller_test.go
  internal/controllers/gateway/gateway_utils.go
  internal/controllers/gateway/gateway_utils_test.go
  internal/controllers/gateway/route_parent_status.go
  internal/controllers/gateway/route_utils.go
  internal/controllers/gateway/tcproute_controller.go
  internal/controllers/gateway/tlsroute_controller.go
  internal/controllers/gateway/udproute_controller.go
  internal/dataplane/parser/backendref.go
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/translate_httproute.go
  internal/dataplane/parser/translate_httproute_test.go
  internal/dataplane/parser/translate_tlsroute.go
  internal/dataplane/parser/translate_utils.go
  internal/dataplane/parser/wrappers_backendref.go
  internal/dataplane/parser/wrappers_refchecker.go
  internal/types/types.go
  internal/util/conditions_test.go
  internal/util/test/crds.go
  test/conformance/gateway_conformance_test.go
  test/consts/zz_generated_gateway.go
  test/e2e/features_test.go
  test/integration/gateway_test.go
  test/integration/helpers_test.go
  test/integration/tlsroute_test.go
Labels: size/XL

#3507 chore: referenceGrant promoted to beta
  CHANGELOG.md
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gateway_controller_test.go
  internal/controllers/gateway/gateway_utils.go
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/referencegrant_controller.go
  internal/controllers/gateway/route_utils.go
  internal/dataplane/parser/backendref.go
  internal/dataplane/parser/translate_utils.go
  internal/dataplane/parser/translate_utils_test.go
  internal/dataplane/parser/wrappers_refchecker.go
  internal/store/fake_store.go
  internal/store/fake_store_test.go
  internal/store/store.go
  test/integration/tcproute_test.go
  test/integration/tlsroute_test.go
Labels: size/L

#3510 chore: delete unused code
  internal/util/ingressapi.go
  internal/util/ingressapi_test.go
  internal/util/networking.go
  internal/util/networking_test.go
  internal/util/objectmeta.go
  internal/util/secretgetter.go
  internal/util/secretgetter_test.go
Labels: area/maintenance, size/L

#3509 feat: add adminapi endpoints helpers
  internal/adminapi/endpoints.go
  internal/adminapi/endpoints_test.go
Labels: area/feature, size/L

#3512 fix: fix incorrect debug log about listener missing status information
  internal/dataplane/parser/parser.go
Labels: area/gateway-api, area/maintenance, size/M

#3508 fix(ci): fix pinned enterprise tag
  .github/workflows/test.yaml
  test/integration/suite_test.go
Labels: area/ci, size/S

#3519 feat: enable ReferenceGrant controller if Gateway feature gate turned on
  CHANGELOG.md
  internal/manager/controllerdef.go
Labels: size/XS

#3520 chore(ci): don't run buildpulse if workflow has been cancelled
  .github/workflows/test.yaml
Labels: area/ci, area/maintenance, size/XS

#3469 feat: add Konnect client & move tls cert extract to util
  CHANGELOG.md
  internal/adminapi/kong.go
  internal/adminapi/konnect.go
  internal/adminapi/tls.go
  internal/konnect/client.go
  internal/konnect/node_agent.go
  internal/konnect/protocol.go
  internal/manager/run.go
  internal/util/tls/tls_cert.go
Labels: area/feature, size/XL

#3421 feat: add service discovery for kong admin service
  CHANGELOG.md
  config/rbac/role.yaml
  config/variants/multi-gw/base/manager_multi_gateway_patch.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless-multi-gw.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  internal/adminapi/client.go
  internal/adminapi/kong.go
  internal/adminapi/kong_test.go
  internal/controllers/configuration/kongadminapi_controller.go
  internal/dataplane/client.go
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_test.go
  internal/dataplane/synchronizer.go
  internal/dataplane/synchronizer_test.go
  internal/manager/config.go
  internal/manager/config_validation.go
  internal/manager/controllerdef.go
  internal/manager/run.go
  internal/manager/setup.go
  internal/manager/utils/kongconfig/root.go
  test/e2e/all_in_one_test.go
  test/e2e/helpers_test.go
  test/e2e/utils_test.go
  test/internal/helpers/teardown.go
Labels: area/feature, size/XXL

#3521 feat: add dataplane metrics label
  CHANGELOG.md
  internal/dataplane/deckerrors/conflict.go
  internal/dataplane/kong_client.go
  internal/dataplane/sendconfig/sendconfig.go
  internal/dataplane/sendconfig/sendconfig_test.go
  internal/metrics/prometheus.go
  internal/metrics/prometheus_test.go
Labels: size/L

#3531 chore: remove unused Store params
  internal/dataplane/kong_client.go
  internal/dataplane/parser/ingressclassparemeters_test.go
  internal/store/fake_store.go
  internal/store/store.go
Labels: area/maintenance

#3529 feat: set leader election when single controller deployments are configured
  CHANGELOG.md
  internal/manager/run.go
  internal/manager/setup.go
Labels: size/M

#3532 chore: warning messages removed
  examples/gateway-httproute.yaml
  examples/gateway-tcproute.yaml
  examples/gateway-tlsroute.yaml
  examples/gateway-udproute.yaml
Labels: size/XS

#3527 tests: fix TestDebugLoggerThreadSafety test
  internal/util/debug_logging_test.go
Labels: area/tests, area/maintenance, test-flake, size/M

#3530 refactor: extract AdminAPIClientsManager
  CHANGELOG.md
  internal/adminapi/client.go
  internal/adminapi/kong.go
  internal/adminapi/konnect.go
  internal/dataplane/client.go
  internal/dataplane/clients_manager.go
  internal/dataplane/clients_manager_test.go
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_test.go
  internal/dataplane/sendconfig/kong.go
  internal/dataplane/synchronizer.go
  internal/manager/run.go
  internal/manager/setup.go
  internal/manager/utils/kongconfig/root.go
  internal/manager/utils/reports.go
Labels: area/feature, size/XL

#3500 feat(konnect): use konnect client to sync config
  CHANGELOG.md
  internal/dataplane/clients_manager.go
  internal/dataplane/clients_manager_test.go
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_test.go
  internal/dataplane/sendconfig/dbmode.go
  internal/dataplane/sendconfig/inmemory.go
  internal/dataplane/sendconfig/kong.go
  internal/dataplane/sendconfig/sendconfig.go
  internal/dataplane/sendconfig/strategy.go
  internal/dataplane/sendconfig/strategy_test.go
  internal/konnect/client.go
  internal/konnect/node_agent.go
  internal/manager/run.go
  internal/manager/setup.go
  internal/manager/utils/kongconfig/root.go
  internal/manager/utils/reports.go
Labels: area/feature, size/XL

#3540 chore(ci): bump go to 1.20
  .github/workflows/cleanup.yaml
  .github/workflows/e2e.yaml
  .github/workflows/e2e_targeted.yaml
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  .github/workflows/test_nightly.yaml
  CHANGELOG.md
Labels: area/ci, size/M

#3545 tests: fix logClusterInfo not defined in istio tests
  test/e2e/all_in_one_test.go
  test/e2e/clusters.go
Labels: size/S

#3547 test(e2e): extend gw configuration timeout in multi-gw test
  test/e2e/all_in_one_test.go
Labels: area/tests, size/M

#3546 tests(e2e): extract setup function
  go.mod
  go.sum
  test/e2e/all_in_one_test.go
  test/e2e/compatibilities_test.go
  test/e2e/features_test.go
  test/e2e/helpers_test.go
  test/e2e/istio_test.go
  test/e2e/kuma_test.go
Labels: area/tests, size/L

#3553 chore: replace k8s.gcr.io registry usage
  examples/gateway-udproute.yaml
  examples/udpingress.yaml
  test/integration/udpingress_test.go
Labels: area/maintenance, size/XS

#3535 tests(konnect): add e2e test covering Konnect config push
  .github/workflows/e2e_targeted.yaml
  go.mod
  go.sum
  internal/adminapi/konnect.go
  internal/konnect/runtimegroups/client.gen.go
  internal/konnect/runtimegroupsconfig/client.gen.go
  test/e2e/all_in_one_test.go
  test/e2e/helpers_test.go
  test/e2e/konnect_test.go
Labels: area/feature, area/tests, size/L, area/konnect

#3554 chore(ci): extend test environment cleanup timeout to unblock e2e tests
  test/internal/helpers/teardown.go
Labels: area/tests, area/maintenance, size/XS

#3556 feat: add configurable Admin API service port names to be used for service discovery
  CHANGELOG.md
  internal/adminapi/endpoints.go
  internal/adminapi/endpoints_test.go
  internal/controllers/configuration/kongadminapi_controller.go
  internal/manager/config.go
  internal/manager/controllerdef.go
  internal/manager/setup.go
Labels: area/feature, size/L

#3557 tests: introduce `testenv.WaitForClusterDelete()` to make wait for cluster deletion configurable
  test/e2e/clusters.go
  test/e2e/helpers_test.go
  test/e2e/kuma_test.go
  test/e2e/utils_test.go
  test/internal/testenv/testenv.go
Labels: area/tests, size/M

#3559 chore: CHANGELOG.md updated with gwapi 0.6.1
  CHANGELOG.md
Labels: size/XS

#3446 Report config push failures as Events
  CHANGELOG.md
  internal/dataplane/kong_client.go
  internal/dataplane/kongstate/consumer.go
  internal/dataplane/kongstate/consumer_test.go
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/util.go
  internal/dataplane/kongstate/util_test.go
  internal/dataplane/parser/ingressrules.go
  internal/dataplane/parser/ingressrules_test.go
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/parser_test.go
  internal/dataplane/parser/translate_httproute.go
  internal/dataplane/parser/translate_httproute_test.go
  internal/dataplane/parser/translate_ingress.go
  internal/dataplane/parser/translate_ingress_test.go
  internal/dataplane/parser/translate_knative.go
  internal/dataplane/parser/translate_knative_test.go
  internal/dataplane/parser/translate_kong_l4.go
  internal/dataplane/parser/translate_kong_l4_test.go
  internal/dataplane/parser/translate_routes_helpers.go
  internal/dataplane/parser/translate_routes_helpers_test.go
  internal/dataplane/parser/translate_secrets.go
  internal/dataplane/parser/translate_tcproute.go
  internal/dataplane/parser/translate_tlsroute.go
  internal/dataplane/parser/translate_udproute.go
  internal/dataplane/parser/translators/ingress.go
  internal/dataplane/parser/translators/ingress_test.go
  internal/dataplane/sendconfig/dbmode.go
  internal/dataplane/sendconfig/error_handling_test.go
  internal/dataplane/sendconfig/inmemory.go
  internal/dataplane/sendconfig/inmemory_error_handling.go
  internal/dataplane/sendconfig/sendconfig.go
  internal/dataplane/sendconfig/strategy.go
  internal/dataplane/sendconfig/strategy_test.go
  internal/util/k8s.go
  internal/versions/versions.go
  test/integration/config_error_event_test.go
  test/internal/testenv/testenv.go
Labels: area/feature, size/XXL, ci/run-nightly

#3563 feat(config): use projected volume for SA token
  CHANGELOG.md
  config/base/kong-ingress-dbless.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless-multi-gw.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
Labels: area/feature, area/maintenance, size/L

#3558 chore(ci): filter out istio tests from general e2e pipeline
  .github/workflows/e2e.yaml
  .github/workflows/e2e_targeted.yaml
Labels: area/ci, area/tests, size/S

#3565 fix(konnect): make NodeAgent manager.Runnable
  internal/konnect/node_agent.go
  internal/manager/run.go
Labels: size/M, area/konnect

#3569 test(conformance): routes generation bumped
  internal/controllers/gateway/route_utils.go
  test/conformance/gateway_conformance_test.go
Labels: size/S

#3566 tests: wait for all pods ready in multi-gw e2e
  .github/workflows/e2e_targeted.yaml
  test/e2e/all_in_one_test.go
Labels: area/tests, size/S

#3571 fix: add context to retry in `getKongClients()` and `kongconfig.GetRoots()` to allow proper cancellation
  internal/manager/setup.go
  internal/manager/utils/kongconfig/root.go
Labels: area/maintenance, size/XS

#3572 fix(parser) copy parent info when consolidating
  internal/dataplane/parser/ingressrules.go
Labels: size/XS

#3573 fix: add pod namespace in node hostname
  internal/manager/run.go
Labels: size/S

#3578 fix: don't return address to package variable
  internal/versions/versions.go
Labels: bug, size/S

#3576 chore: don't get pod info when not necessary
  internal/manager/run.go
  internal/manager/telemetry/manager.go
  internal/manager/telemetry/manager_test.go
  internal/manager/telemetry/reports.go
  internal/manager/utils/reports.go
  internal/util/k8s.go
Labels: area/maintenance, size/M

#3579 fix: not accepted when unsupportedProtocol
  internal/controllers/gateway/gateway_utils.go
Labels: size/S

#3537 feat: GRPCRoute controller
  CHANGELOG.md
  Makefile
  config/rbac/gateway/role.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless-multi-gw.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  examples/gateway-grpcroute.yaml
  internal/controllers/gateway/gateway_utils.go
  internal/controllers/gateway/gateway_utils_test.go
  internal/controllers/gateway/grpcroute_controller.go
  internal/controllers/gateway/route_utils.go
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/translate_grpcroute.go
  internal/dataplane/parser/translate_httproute.go
  internal/manager/controllerdef.go
  internal/store/fake_store.go
  internal/store/store.go
  internal/types/types.go
  internal/util/builder/routegroupkind.go
  test/integration/examples_test.go
  test/integration/grpcroute_test.go
  test/integration/tlsroute_test.go
  third_party/go.mod
  third_party/go.sum
  third_party/grpcurl.go
Labels: size/XXL

#3584 chore: programmed condition and conformance
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gateway_utils.go
  test/conformance/gateway_conformance_test.go
Labels: size/M

#3585 refactor(konnect): propagate discovered admin api endpoints' pod references
  internal/adminapi/client.go
  internal/adminapi/endpoints.go
  internal/adminapi/endpoints_test.go
  internal/controllers/configuration/kongadminapi_controller.go
  internal/dataplane/clients_manager.go
  internal/dataplane/clients_manager_test.go
  internal/manager/run.go
  internal/manager/setup.go
Labels: size/L, area/konnect

#3574 fix: list all nodes in konnect by pages
  internal/konnect/client.go
  internal/konnect/node_agent.go
Labels: size/M, area/konnect

#3586 chore: gateway certificates checked
  internal/controllers/gateway/gateway_utils.go
  test/conformance/gateway_conformance_test.go
  test/integration/translation_failures_test.go
Labels: size/L

#3593 feat(dataplane): allow subscribing to gateway clients changes
  internal/dataplane/clients_manager.go
  internal/dataplane/clients_manager_test.go
Labels: area/feature, size/L

#3577 chore(tests): use k8s v1.26.0 integration tests
  Makefile
Labels: area/tests, area/maintenance, size/XS

#3594 chore(config): remove not needed secret
  config/base/kustomization.yaml
  config/base/secret-sa-token.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless-multi-gw.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
Labels: area/maintenance, size/M

#3587 feat: update kong nodes status to konnect
  CHANGELOG.md
  internal/adminapi/client.go
  internal/konnect/node_agent.go
  internal/konnect/node_agent_test.go
  internal/konnect/protocol.go
  internal/manager/run.go
Labels: area/feature, size/XL, area/konnect

#3599 feat(gwapi) reject non-Gateway parentRefs
  internal/controllers/gateway/route_utils.go
  internal/controllers/gateway/route_utils_test.go
Labels: size/L

#3601 fix: get Admin API services dynamically in admission webhook
  CHANGELOG.md
  internal/admission/adminapi_provider.go
  internal/admission/adminapi_provider_test.go
  internal/admission/validator.go
  internal/admission/validator_test.go
  internal/konnect/client.go
  internal/manager/run.go
  internal/manager/setup.go
Labels: bug, size/L

#3602 fix(config): correctly check `types.NamespacedName` flags are set
  CHANGELOG.md
  go.mod
  go.sum
  internal/manager/config.go
  internal/manager/config_validation.go
  internal/manager/config_validation_test.go
  internal/manager/controllerdef.go
  internal/manager/run.go
  internal/manager/setup.go
  internal/manager/validated.go
  internal/manager/validated_test.go
Labels: bug, size/L

#3622 fix(parser) use proper name for GRPCRoute routes
  internal/dataplane/parser/translate_grpcroute.go
Labels: size/XS

#3617 feat(konnect): make sure Konnect misconfiguration doesn't affect ingress
  internal/adminapi/konnect.go
  internal/adminapi/konnect_test.go
  internal/dataplane/config_status.go
  internal/dataplane/config_status_test.go
  internal/dataplane/kong_client.go
  internal/konnect/client.go
  internal/konnect/node_agent.go
  internal/konnect/node_agent_test.go
  internal/manager/run.go
  test/e2e/konnect_test.go
Labels: size/L, area/konnect

#3624 fix: don't leak timer
  internal/dataplane/config_status.go
Labels: area/debt, size/XS

#3625 chore: bump tools versions and unblock dependabot for third_party module
  internal/adminapi/kong.go
  test/integration/utils_test.go
  third_party/go.mod
  third_party/go.sum
Labels: dependencies, area/maintenance, size/XL

#3626 chore(ci): don't run enterprise tests for PRs from forks
  .github/workflows/test.yaml
Labels: area/ci, size/XS

#3630 chore(ci): don't run enterprise tests for PRs from forks
  .github/workflows/test.yaml
Labels: area/ci, area/maintenance, size/S
