Repository Kong/kubernetes-ingress-controller, pull requests merged in 2023-08, with the labels that each got.

#4433 feat(ci): use up-to-date shared action
  .github/workflows/pr_checks.yaml
Labels: area/ci, size/M

#4441 ci: fix up-to-date job
  .github/workflows/pr_checks.yaml
Labels: area/ci, size/S

#4443 ci: don't build the image on main when PR branch was up to date
  .github/workflows/pr_checks.yaml
Labels: area/ci, size/S

#4444 ci: add missing up-to-date needs for build job
  .github/workflows/pr_checks.yaml
Labels: area/ci, size/XS

#4445 chore(ci): log skipped gke clusters
  hack/cleanup/gke_clusters.go
Labels: area/ci, size/S

#4447 chore(ci) run nightly integration against dev kong
  .github/workflows/e2e_nightly.yaml
Labels: size/S

#4449 chore: unify import aliases for Kong CRDs
  .golangci.yaml
  internal/admission/handler.go
  internal/admission/server_test.go
  internal/admission/validator_test.go
  internal/dataplane/failures/failures_test.go
  internal/dataplane/kongstate/consumer.go
  internal/dataplane/kongstate/consumer_test.go
  internal/dataplane/kongstate/consumergroup.go
  internal/dataplane/kongstate/kongstate_test.go
  internal/dataplane/kongstate/route.go
  internal/dataplane/kongstate/route_test.go
  internal/dataplane/kongstate/service.go
  internal/dataplane/kongstate/service_test.go
  internal/dataplane/kongstate/upstream.go
  internal/dataplane/kongstate/upstream_test.go
  internal/dataplane/kongstate/util.go
  internal/dataplane/kongstate/util_test.go
  internal/dataplane/parser/ingressclassparemeters_test.go
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/parser_test.go
  internal/dataplane/parser/translate_ingress.go
  internal/dataplane/parser/translate_kong_l4_test.go
  internal/dataplane/parser/translators/ingress.go
  internal/dataplane/parser/translators/ingress_atc_test.go
  internal/dataplane/parser/translators/ingress_test.go
  internal/manager/controllerdef.go
  internal/manager/scheme/scheme.go
  internal/store/fake_store.go
  internal/store/fake_store_test.go
  pkg/clientset_test/clientset_test.go
  test/integration/ingress_test.go
  test/integration/kongingress_webhook_test.go
Labels: area/maintenance, size/XL

#4451 chore(ci): adjust golangci-lint config, fix reported
  .golangci.yaml
  internal/controllers/configuration/kongadminapi_controller_envtest_test.go
  internal/dataplane/configfetcher/config_fetcher.go
  internal/dataplane/sendconfig/config_change_detector.go
  internal/dataplane/sendconfig/inmemory_error_handling.go
  internal/dataplane/sendconfig/sendconfig.go
  internal/manager/utils/kongconfig/root_test.go
  pkg/apis/configuration/v1/conditions.go
Labels: area/ci, area/maintenance, size/S

#4454 chore(deps): bump dependencies versions in go.mod
  go.mod
  go.sum
  internal/dataplane/parser/parser_test.go
  internal/dataplane/parser/translate_httproute_test.go
  internal/dataplane/parser/translate_routes_helpers_test.go
  internal/dataplane/parser/translate_utils_test.go
  internal/dataplane/parser/translators/grpcroute_atc_test.go
  internal/dataplane/parser/translators/grpcroute_test.go
  internal/util/objectmeta_test.go
  test/integration/tcproute_test.go
  test/integration/tlsroute_test.go
  test/integration/udproute_test.go
  third_party/go.mod
  third_party/go.sum
Labels: dependencies, size/L

#4453 fix: introduce deck content to dbless config converter
  examples/consumer-groups.yaml
  internal/dataplane/deckgen/deckgen.go
  internal/dataplane/sendconfig/inmemory.go
  internal/dataplane/sendconfig/inmemory_schema.go
  internal/dataplane/sendconfig/inmemory_schema_test.go
  internal/dataplane/sendconfig/strategy.go
  test/integration/consumer_group_test.go
Labels: size/XL, fix

#4455 ci(deps): group updates of several dependencies
  .github/dependabot.yml
Labels: area/ci, dependencies, size/S

#4463 Revert "ci(deps): group updates of several dependencies (#4455)"
  .github/dependabot.yml
Labels: dependencies, size/S

#4469 chore(ci): update test_nightly.yaml GH workflow
  .github/workflows/test_nightly.yaml
Labels: area/ci, area/maintenance, size/L

#4452 feat(consumer group): allow assigning plugins to consumer groups
  CHANGELOG.md
  go.mod
  go.sum
  internal/dataplane/deckgen/deckgen.go
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/kongstate_test.go
  internal/dataplane/parser/parser.go
  internal/util/relations.go
  internal/util/relations_test.go
  internal/versions/versions.go
  test/integration/consumer_group_test.go
Labels: area/feature, size/L, area/CRD

#4439 use namespace kong for integration tests
  test/conformance/suite_test.go
  test/consts/misc.go
  test/helpers/certificate/certificate.go
  test/integration/gateway_test.go
  test/internal/helpers/ktf.go
Labels: size/S

#4481 fix(ci) correct latest push
  .github/workflows/release.yaml
Labels: area/ci

#4484 fix: update kind k8s versions because tags of kindest/node removed
  .github/workflows/_e2e_tests.yaml
  test/e2e/istio_test.go
Labels: size/S, backport release/2.11.x

#4494 tests: pin chart version in integration and conformance tests, bump KTF
  go.mod
  go.sum
  test/conformance/suite_test.go
  test/consts/helm.go
  test/integration/suite_test.go
Labels: area/tests, size/S, fix

#4490 refactor: use helpers for certificates in TestWebhookUpdate, fix typo
  test/e2e/features_test.go
  test/helpers/certificate/certificate.go
Labels: area/debt, area/tests, area/maintenance, size/M

#4496 tests: fix flaky TestNodeAgent_TickerResetsOnEveryNodesUpdate
  internal/konnect/node_agent_test.go
Labels: area/tests, test-flake, size/M

#4498 tests: pin chart version in integration and conformance tests, bump KTF (#4494)
  go.mod
  go.sum
  test/conformance/suite_test.go
  test/consts/helm.go
  test/integration/suite_test.go
Labels: size/S

#4500 refactor: convert integration TestCRDValidations to envtest
  test/envtest/crds_envtest_test.go
  test/integration/crd_validations_test.go
Labels: area/tests, area/maintenance, size/L

#4502 chore(release) add description file step
  .github/ISSUE_TEMPLATE/release.yaml
Labels: size/XS

#4492 fix: update kind k8s versions because tags of kindest/node removed (#4484)
  test/e2e/istio_test.go
Labels: size/XS

#4491 [Backport release/2.11.x] fix(ci) correct latest push (#4481)
  .github/workflows/release.yaml
Labels: area/maintenance, size/XS

#4501 refactor: use common helpers for certs in TestMakeHTTPClientWithTLSOpts
  internal/adminapi/kong_test.go
  test/helpers/certificate/certificate.go
Labels: area/debt, area/tests, area/maintenance, size/L

#4504 refactor: use helpers for certs in parser_test.go and improve getCertFromSecret
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/parser_test.go
  test/helpers/certificate/certificate.go
Labels: area/debt, area/tests, area/maintenance, size/L

#4507 test: fix parse semver error in integration tests
  test/consts/helm.go
Labels: area/tests, size/XS

#4503 Use Service port in generated Kong services
  CHANGELOG.md
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/testdata/golden/httproute-example/default_golden.yaml
  internal/dataplane/parser/testdata/golden/httproute-example/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-multiple-ports-for-one-service/combined-routes-off_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-multiple-ports-for-one-service/combined-services_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-multiple-ports-for-one-service/default_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-multiple-ports-for-one-service/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/same-name-services-single-backend/default_golden.yaml
Labels: size/S

#4512 fix: generate routes with hostname match only when GRPCRoute rule does not have matches
  CHANGELOG.md
  internal/dataplane/parser/translate_grpcroute.go
  internal/dataplane/parser/translate_grpcroute_test.go
  internal/dataplane/parser/translators/grpcroute.go
  internal/dataplane/parser/translators/grpcroute_atc.go
  internal/dataplane/parser/translators/grpcroute_atc_test.go
  internal/dataplane/parser/translators/grpcroute_test.go
Labels: size/L

#4519 chore: bump github.com/kong/deck to 1.26
  go.mod
  go.sum
Labels: dependencies, size/XS

#4527 chore(ci): improve logs for test.conformance
  internal/util/test/crds.go
  internal/util/test/rbacs.go
Labels: area/ci, area/tests, size/S

#4534 chore: bump Kong Gateway to 3.4
  .github/workflows/_integration_tests.yaml
  config/image/enterprise/kustomization.yaml
  config/image/oss/kustomization.yaml
  deploy/single/all-in-one-dbless-enterprise.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless-legacy.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  internal/dataplane/parser/golden_test.go
Labels: area/maintenance, area/release, size/S

#4535 chore: bump Kong Gateway to 3.4 (#4534)
  .github/workflows/_integration_tests.yaml
  config/image/enterprise/kustomization.yaml
  config/image/oss/kustomization.yaml
  deploy/single/all-in-one-dbless-enterprise.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless-legacy.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  internal/dataplane/parser/golden_test.go
Labels: area/maintenance, size/S

#4497 test: fix TLSRoute tests to use passthrough
  examples/gateway-tlsroute.yaml
  internal/dataplane/parser/translate_tlsroute.go
  test/integration/examples_test.go
  test/integration/tlsroute_test.go
Labels: size/XL

#4538 chore(deps): bump sigs.k8s.io/kustomize/kustomize from 4.5.7 to 5.1.1 in /third_party
  third_party/go.mod
  third_party/go.sum
  third_party/kustomize.go
Labels: dependencies, size/M

#4385 feat: support expression route for TCPRoute.
  CHANGELOG.md
  internal/dataplane/parser/atc/field.go
  internal/dataplane/parser/translate_failures_test.go
  internal/dataplane/parser/translate_tcproute.go
  internal/dataplane/parser/translate_tcproute_test.go
  internal/dataplane/parser/translate_utils.go
  internal/dataplane/parser/translators/l4route_atc.go
  test/integration/tcproute_test.go
Labels: size/L

#4543 refactor: use helpers for certs in konnect_test.go, remove redundant type TLSPair
  test/e2e/features_test.go
  test/e2e/konnect_test.go
Labels: area/debt, area/tests, area/maintenance, size/M

#4511 test: update helm chart version to the latest
  .github/ISSUE_TEMPLATE/release.yaml
  .github/workflows/_integration_tests.yaml
  .github/workflows/e2e_nightly.yaml
  .github/workflows/test_nightly.yaml
  test/consts/helm.go
  test/internal/helpers/ktf.go
  test/internal/testenv/testenv.go
Labels: area/tests, size/S

#4544 docs: add RewriteURI to `FEATURE_GATES.md`
  .github/workflows/_integration_tests.yaml
  FEATURE_GATES.md
Labels: size/XS

#4549 fix: define vars for effective semver in manifest of integration tests
  .github/workflows/_integration_tests.yaml
Labels: area/ci, size/S

#4550 feat: support `UDPRoute` when expression router enabled
  CHANGELOG.md
  internal/dataplane/parser/translate_failures_test.go
  internal/dataplane/parser/translate_grpcroute_test.go
  internal/dataplane/parser/translate_tcproute.go
  internal/dataplane/parser/translate_tcproute_test.go
  internal/dataplane/parser/translate_udproute.go
  internal/dataplane/parser/translate_udproute_test.go
  internal/dataplane/parser/translators/translator_errors.go
  internal/versions/versions.go
  test/integration/examples_test.go
  test/integration/helpers_test.go
  test/integration/tcproute_test.go
  test/integration/udproute_test.go
  test/integration/version_test.go
  test/internal/helpers/kong.go
Labels: area/gateway-api, size/XL

#4564 chore: remove out of date TODO comment
  internal/controllers/gateway/gateway_utils.go
Labels: size/XS

#4580 chore(deps): bump kind image to 1.28
  .github/workflows/_e2e_tests.yaml
  .github/workflows/_integration_tests.yaml
  Makefile
Labels: area/maintenance, size/XS

#4584 fix: disable Kong(Cluster)Plugin Programmed status
  hack/generators/controllers/networking/main.go
  internal/controllers/configuration/zz_generated_controllers.go
  internal/manager/controllerdef.go
  test/envtest/programmed_condition_envtest_test.go
Labels: size/L, backport release/2.11.x

#4586 backport effective version CI fixes to release/2.11.x
  .github/ISSUE_TEMPLATE/release.yaml
  .github/workflows/_integration_tests.yaml
  .github/workflows/e2e_nightly.yaml
  .github/workflows/test_nightly.yaml
  go.mod
  go.sum
  test/consts/helm.go
  test/internal/helpers/ktf.go
  test/internal/testenv/testenv.go
Labels: area/ci, area/maintenance, size/L

#4588 fix(plugins) add suffix to instance_name
  CHANGELOG.md
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/kongstate_test.go
  internal/dataplane/parser/testdata/golden/kongplugin-instance-name/default_golden.yaml
  internal/dataplane/parser/testdata/golden/kongplugin-instance-name/in.yaml
  test/integration/plugin_test.go
Labels: size/L

#4590 chore(docs) add 2.10.5 changelog
  CHANGELOG.md
Labels: size/S

#4594 chore(tests): move metrics envtest to test/envtest
  test/envtest/gateway_envtest_test.go
  test/envtest/metrics_envtest_test.go
Labels: area/tests, size/M
