Repository Kong/kubernetes-ingress-controller, pull requests merged in 2023-09, with the labels that each got.

#4596 fix(plugins) add suffix to instance_name
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/kongstate_test.go
  internal/dataplane/parser/testdata/golden/kongplugin-instance-name/default_golden.yaml
  internal/dataplane/parser/testdata/golden/kongplugin-instance-name/in.yaml
  test/integration/plugin_test.go
Labels: size/L

#4610 feat(build): add docker cache mounts for go mod cache
  Dockerfile
Labels: area/ci, size/S

#4609 chore(go): introduce usage of Go toolchain
  .github/workflows/_conformance_tests.yaml
  .github/workflows/_e2e_tests.yaml
  .github/workflows/_envtest_tests.yaml
  .github/workflows/_integration_tests.yaml
  .github/workflows/_linters.yaml
  .github/workflows/_unit_tests.yaml
  .github/workflows/benchmarks.yaml
  .github/workflows/cleanup.yaml
  .github/workflows/codeql.yaml
  .github/workflows/pr_checks.yaml
  go.mod
  go.sum
  third_party/go.mod
  third_party/go.sum
Labels: area/ci, dependencies, area/maintenance, go, size/L

#4611 chore: manually adapt once generated Konnect clients
  Makefile
  go.mod
  go.sum
  hack/cleanup/konnect_runtime_groups.go
  internal/konnect/runtimegroups/client.go
  internal/konnect/runtimegroupsconfig/client.go
Labels: area/tests, area/maintenance, size/L

#4591 chore(*) update GWAPI to v0.8.0
  go.mod
  go.sum
  internal/controllers/gateway/gateway_controller.go
  internal/util/builder/httpbackendref.go
  test/conformance/gateway_conformance_test.go
  test/consts/zz_generated_gateway.go
  test/envtest/httproute_controller_test.go
  test/integration/gateway_test.go
  test/integration/grpcroute_test.go
  test/integration/helpers_test.go
  test/internal/cmd/generate-gateway-api-consts/gateway_consts.tmpl
Labels: area/gateway-api, size/L

#4615 chore: fix workflow manifests for go-version-file
  .github/workflows/_e2e_tests.yaml
Labels: area/ci, size/S

#4614 test: enable HTTPS redirect tests with expression router
  test/integration/ingress_https_test.go
  test/internal/helpers/kong.go
Labels: area/tests, size/S

#4608 feat(admission): validate regex supplied in HTTPRoute (stop rejecting)
  CHANGELOG.md
  internal/admission/adminapi_provider.go
  internal/admission/validator.go
  internal/admission/validator_test.go
  internal/dataplane/parser/translate_httproute.go
  internal/manager/run.go
  internal/manager/setup.go
  internal/validation/gateway/httproute.go
  internal/validation/gateway/httproute_test.go
  test/integration/gateway_webhook_test.go
  test/integration/helpers_test.go
  test/integration/httproute_webhook_test.go
  test/integration/kongingress_webhook_test.go
  test/integration/skip_helpers_test.go
  test/integration/webhook_test.go
Labels: area/feature, area/gateway-api, size/XL, area/admission

#4622 chore(tests): move all envtest based tests into test/envtest
  Makefile
  test/envtest/adminapi_discoverer_envtest_test.go
  test/envtest/crds_envtest_test.go
  test/envtest/k8s_objects_status_envtest_test.go
  test/envtest/kongadminapi_controller_envtest_test.go
  test/envtest/telemetry_test.go
Labels: area/tests, area/maintenance, size/L

#4551 tests: add experimental conformance test suite
  .gitignore
  Makefile
  internal/manager/metadata/metadata.go
  internal/manager/metadata/metadata_test.go
  test/conformance/gateway_conformance_test.go
  test/conformance/gateway_expermimental_conformance_test.go
  test/conformance/suite_test.go
  test/internal/testenv/testenv.go
Labels: area/tests, area/gateway-api, size/L

#4628 chore(linter): fix golangci-lint forbidigo config
  .golangci.yaml
Labels: area/ci, area/maintenance, size/XS

#4627 fix: fix panic when last known configuration fetcher gets a nil status
  CHANGELOG.md
  internal/dataplane/configfetcher/config_fetcher.go
  internal/dataplane/configfetcher/config_fetcher_test.go
  test/mocks/admin_api_handler.go
Labels: size/L, fix

#4629 refactor(tests): improve code for webhooks
  test/integration/gateway_webhook_test.go
  test/integration/httproute_webhook_test.go
  test/integration/kongingress_webhook_test.go
  test/integration/webhook_test.go
Labels: area/tests, area/maintenance, refactor, size/M, area/admission

#4631 fix(tests): validate regex supplied in HTTPRoute for Kong < 3.0
  test/integration/httproute_webhook_test.go
Labels: area/ci, area/tests, area/gateway-api, size/XS, fix

#4634 chore(tests): add namespace selector in ensureAdmissionRegistration
  test/integration/gateway_webhook_test.go
  test/integration/httproute_webhook_test.go
  test/integration/kongingress_webhook_test.go
  test/integration/webhook_test.go
Labels: area/tests, area/maintenance, size/S, area/admission

#4630 tests: add CI workflow for generating conformance tests report
  .github/ISSUE_TEMPLATE/release.yaml
  .github/workflows/conformance_tests_report.yaml
Labels: area/ci, area/gateway-api, size/M, kind/conformance

#4612 Support TCPIngress and UDPIngress expression routes
  CHANGELOG.md
  internal/dataplane/parser/translate_failures_test.go
  internal/dataplane/parser/translate_kong_l4.go
  internal/dataplane/parser/translators/l4route_atc.go
  internal/dataplane/parser/translators/l4route_atc_test.go
  test/integration/tcpingress_test.go
  test/integration/udpingress_test.go
Labels: size/L

#4636 chore(ci): disable toolchain in go.mod
  go.mod
Labels: area/ci, area/maintenance, size/S

#4639 chore: don't use global controller-runtime logger
  internal/cmd/rootcmd/run.go
  internal/manager/conditions.go
  internal/manager/conditions_test.go
  internal/manager/controllerdef.go
  internal/manager/run.go
  internal/manager/setup.go
  test/envtest/run.go
Labels: area/tests, area/maintenance, size/M

#4641 fix: ensure connectivity with Kubernetes API on start-up
  internal/controllers/crds/dynamic_controller.go
  internal/manager/conditions.go
  internal/manager/conditions_test.go
  internal/manager/controllerdef.go
  internal/manager/run.go
  test/envtest/crds_envtest_test.go
  test/envtest/gateway_envtest_test.go
  test/envtest/kongstate_consumer_failures_test.go
  test/envtest/manager_envtest_test.go
  test/envtest/programmed_condition_envtest_test.go
  test/envtest/run.go
  test/envtest/setup.go
  test/internal/helpers/tcp.go
  test/internal/helpers/tcp_test.go
Labels: bug, size/XL, fix

#4640 test: enable `GatewayWithAttachedRoutes` test
  test/conformance/gateway_conformance_test.go
  test/conformance/gateway_expermimental_conformance_test.go
Labels: size/M

#4643 Remove Ingress API selection code
  CHANGELOG.md
  internal/manager/conditions.go
  internal/manager/conditions_test.go
  internal/manager/controllerdef.go
  internal/manager/run.go
Labels: size/L

#4645 test(conformance): `gatewayclassGenerationBump` test enabled
  internal/controllers/gateway/gateway_utils.go
  test/conformance/gateway_conformance_test.go
Labels: size/M

#4647 feat(admission): validate path with regex supplied in Ingress
  CHANGELOG.md
  internal/admission/handler.go
  internal/admission/server_test.go
  internal/admission/validator.go
  internal/dataplane/parser/translate_ingress.go
  internal/util/builder/ingress.go
  internal/validation/gateway/httproute.go
  internal/validation/ingress/ingress.go
  internal/versions/versions.go
  test/integration/httproute_webhook_test.go
  test/integration/ingress_webhook_test.go
Labels: area/feature, size/XL, area/admission

#4656 refactor: move internal/validation to internal/admission/validation
  internal/admission/utils.go
  internal/admission/validation/consumers/credentials/constraints.go
  internal/admission/validation/consumers/credentials/validation.go
  internal/admission/validation/consumers/credentials/validation_test.go
  internal/admission/validation/consumers/credentials/vars.go
  internal/admission/validation/gateway/httproute.go
  internal/admission/validation/gateway/httproute_test.go
  internal/admission/validation/ingress/ingress.go
  internal/admission/validator.go
  internal/dataplane/kongstate/kongstate.go
Labels: refactor, size/S, area/admission

#4660 ci: add comment when kong image validation workflow fails
  .github/workflows/validate_kong_image.yaml
Labels: area/ci, size/S

#4661 chore(tests): get rid of "log.SetLogger(...) was never called..." log
  internal/util/test/controller_manager.go
Labels: area/ci, area/tests, area/maintenance, size/XS

#4663 fix: add type meta when saving them to cache and reference indexer
  CHANGELOG.md
  hack/generators/controllers/networking/main.go
  internal/controllers/configuration/zz_generated_controllers.go
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/knative/knative.go
  internal/controllers/reference/indexer.go
  internal/controllers/reference/indexer_test.go
  internal/controllers/reference/reference.go
  internal/manager/controllerdef.go
  internal/store/store.go
  test/envtest/gatewayclass_envtest_test.go
Labels: bug, area/maintenance, size/L

#4646 feat(rewrite): Remove braces from the rewrite annotation format
  CHANGELOG.md
  internal/annotations/annotations_test.go
  internal/dataplane/parser/translate_ingress_test.go
  internal/dataplane/parser/translators/ingress.go
  internal/dataplane/parser/translators/ingress_test.go
  test/integration/ingress_test.go
Labels: area/feature, size/L

#4666 fix(log): do not parse error body when response is empty in reloading config
  CHANGELOG.md
  internal/dataplane/sendconfig/error_handling_test.go
  internal/dataplane/sendconfig/inmemory_error_handling.go
Labels: size/S

#4677 docs: add sections to tell usage of Draft PR
  CONTRIBUTING.md
Labels: area/docs, size/S

#4700 chore: bump GW API to v0.8.1
  CHANGELOG.md
  go.mod
  go.sum
  test/conformance/gateway_conformance_test.go
  test/consts/zz_generated_gateway.go
Labels: area/gateway-api, size/S

#4702 chore: fix path in comment in GW consts
  test/consts/zz_generated_gateway.go
  test/internal/cmd/generate-gateway-api-consts/gateway_consts.tmpl
Labels: area/tests, area/maintenance, size/XS

#4704 tests: fix data race when accessing manager buffer in envtest based tests
  test/envtest/run.go
Labels: area/tests, size/S

#4703 feat: add `latency` to supported values of KongIngress upstream.algoritm field
  CHANGELOG.md
  config/crd/bases/configuration.konghq.com_kongingresses.yaml
  deploy/single/all-in-one-dbless-enterprise.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless-legacy.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  pkg/apis/configuration/v1/kongingress_types.go
Labels: size/XS, area/CRD

#4709 chore(tests): re-enable gateway config (bug fixed in upstream)
  test/integration/gateway_test.go
Labels: area/tests, size/S

#4710 fix: include Licenses and ConsumerGroups in sanitized copies of config
  CHANGELOG.md
  internal/dataplane/deckgen/generate.go
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/kongstate_test.go
  internal/dataplane/kongstate/license.go
  internal/dataplane/parser/parser.go
Labels: size/M, fix

#4717 test(e2e): include istio 1.19, drop istio 1.15
  .github/workflows/_e2e_tests.yaml
Labels: size/XS

#4713 chore(tests): replace image moul/grpcbin with kong/grpcbin
  deploy/manifests/sample-apps/grpc.yaml
  examples/gateway-grpcroute.yaml
  test/consts.go
  test/integration/grpcroute_test.go
  test/integration/ingress_test.go
Labels: area/debt, area/tests, area/maintenance, size/S

#4726 tests(conformance): for experimental enable test and change report name
  test/conformance/gateway_expermimental_conformance_test.go
Labels: area/tests, area/gateway-api, size/XS, kind/conformance

#4733 Add Ingress and GWAPI v1beta1 to admission webhook
  hack/deploy-admission-controller.sh
Labels: size/S

#4738 fix: no more "log.SetLogger(...) was never called..." log entry during shutdown
  CHANGELOG.md
  internal/manager/setup.go
Labels: area/ingress-controller, size/S, fix

#4743 chore: remove feature gate CombinedServices
  .github/workflows/_integration_tests.yaml
  CHANGELOG.md
  FEATURE_GATES.md
  internal/dataplane/parser/golden_test.go
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/parser_test.go
  internal/dataplane/parser/testdata/golden/ingress-v1-empty-path/combined-services_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-empty-path/combined-services_settings.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-multiple-ports-for-one-service/combined-services_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-multiple-ports-for-one-service/combined-services_settings.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-ports-defined-by-name/combined-services_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-ports-defined-by-name/combined-services_settings.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-rule-with-tls/combined-services_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-rule-with-tls/combined-services_settings.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-single-service-in-multiple-ingresses/combined-services_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-single-service-in-multiple-ingresses/combined-services_settings.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-with-acme-like-path/combined-services_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-with-acme-like-path/combined-services_settings.yaml
  internal/dataplane/parser/translate_ingress.go
  internal/dataplane/parser/translators/ingress.go
  internal/dataplane/parser/translators/ingress_atc_test.go
  internal/dataplane/parser/translators/ingress_test.go
  internal/manager/featuregates/feature_gates.go
  test/envtest/telemetry_test.go
Labels: breaking change, area/ingress-controller, size/L

#4746 chore: graduate feature gate FillIDs to Beta and set to true by default
  .github/workflows/_integration_tests.yaml
  CHANGELOG.md
  FEATURE_GATES.md
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/parser/parser_test.go
  internal/dataplane/parser/testdata/golden/consumer-group-example/default_golden.yaml
  internal/dataplane/parser/testdata/golden/grpcroute-example/default_golden.yaml
  internal/dataplane/parser/testdata/golden/grpcroute-example/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/grpcroute-example/regex-path-prefix-off_golden.yaml
  internal/dataplane/parser/testdata/golden/httproute-example/default_golden.yaml
  internal/dataplane/parser/testdata/golden/httproute-example/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-empty-path/combined-routes-off_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-empty-path/default_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-empty-path/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-ingress-class-annotation/default_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-multiple-ports-for-one-service/combined-routes-off_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-multiple-ports-for-one-service/default_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-multiple-ports-for-one-service/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-ports-defined-by-name/combined-routes-off_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-ports-defined-by-name/default_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-ports-defined-by-name/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-regex-prefix-exact-rule/default_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-regex-prefix-exact-rule/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-regex-prefix-exact-rule/regex-path-prefix-off_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-regex-prefixed-path/default_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-regex-prefixed-path/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-rule-with-tls/combined-routes-off_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-rule-with-tls/default_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-rule-with-tls/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-single-service-in-multiple-ingresses/combined-routes-off_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-single-service-in-multiple-ingresses/default_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-single-service-in-multiple-ingresses/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-with-acme-like-path/combined-routes-off_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-with-acme-like-path/default_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-with-acme-like-path/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-with-default-backend/default_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-with-default-backend/expression-routes-on_golden.yaml
  internal/dataplane/parser/testdata/golden/kongplugin-instance-name/default_golden.yaml
  internal/dataplane/parser/testdata/golden/same-name-services-single-backend/default_golden.yaml
  internal/manager/featuregates/feature_gates.go
  test/e2e/upgrade_test.go
  test/envtest/telemetry_test.go
Labels: area/maintenance, size/M

#4749 chore: remove feature gate CombinedRoutes
  .github/workflows/_integration_tests.yaml
  CHANGELOG.md
  FEATURE_GATES.md
  internal/admission/validation/ingress/ingress.go
  internal/dataplane/parser/golden_test.go
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/parser_test.go
  internal/dataplane/parser/testdata/golden/ingress-v1-empty-path/combined-routes-off_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-empty-path/combined-routes-off_settings.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-multiple-ports-for-one-service/combined-routes-off_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-multiple-ports-for-one-service/combined-routes-off_settings.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-ports-defined-by-name/combined-routes-off_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-ports-defined-by-name/combined-routes-off_settings.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-rule-with-tls/combined-routes-off_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-rule-with-tls/combined-routes-off_settings.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-single-service-in-multiple-ingresses/combined-routes-off_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-single-service-in-multiple-ingresses/combined-routes-off_settings.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-with-acme-like-path/combined-routes-off_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-with-acme-like-path/combined-routes-off_settings.yaml
  internal/dataplane/parser/translate_grpcroute_test.go
  internal/dataplane/parser/translate_httproute.go
  internal/dataplane/parser/translate_httproute_test.go
  internal/dataplane/parser/translate_ingress.go
  internal/dataplane/parser/translate_udproute_test.go
  internal/manager/featuregates/feature_gates.go
  test/envtest/telemetry_test.go
Labels: breaking change, size/XL

#4737 chore: remove everything related obsolete global KongPlugins
  CHANGELOG.md
  internal/dataplane/kongstate/kongstate.go
  internal/store/fake_store_test.go
  internal/store/store.go
Labels: area/debt, area/maintenance, size/M

#4750 chore: use upstream RouteReasonNoMatchingParent
  internal/controllers/gateway/route_utils.go
  internal/controllers/gateway/route_utils_test.go
  test/e2e/utils_test.go
  test/integration/httproute_test.go
Labels: area/maintenance, size/M

#4748 chore: remove knative support
  .github/workflows/_integration_tests.yaml
  CHANGELOG.md
  FEATURE_GATES.md
  Makefile
  config/base/kustomization.yaml
  config/rbac/knative/kustomization.yaml
  config/rbac/knative/role.yaml
  config/rbac/knative/role_binding.yaml
  deploy/single/all-in-one-dbless-enterprise.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless-legacy.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  go.mod
  go.sum
  internal/annotations/annotations.go
  internal/controllers/knative/knative.go
  internal/controllers/utils/utils.go
  internal/controllers/utils/utils_test.go
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/parser_test.go
  internal/dataplane/parser/translate_failures_test.go
  internal/dataplane/parser/translate_knative.go
  internal/dataplane/parser/translate_knative_test.go
  internal/dataplane/parser/translate_utils.go
  internal/manager/config.go
  internal/manager/controllerdef.go
  internal/manager/featuregates/feature_gates.go
  internal/manager/scheme/scheme.go
  internal/manager/telemetry/manager_test.go
  internal/store/fake_store.go
  internal/store/fake_store_test.go
  internal/store/store.go
  internal/util/test/rbacs.go
  test/envtest/telemetry_test.go
  test/integration/addons_knative_test.go
  test/integration/addons_test.go
  test/integration/knative_test.go
  test/internal/testenv/feature_gates.go
  test/internal/testenv/feature_gates_knative.go
Labels: breaking change, area/knative, size/XXL

#4755 tests(integration): run invalid confg tests in parallel with all other
  .github/workflows/_integration_tests.yaml
Labels: area/ci, area/tests, size/S

#4752 changelog: add 2.12 deprecations
  CHANGELOG.md
Labels: size/S

#4747 chore: fix build badge
  .github/workflows/checks.yaml
  README.md
Labels: size/XS

#4761 tests(integration): remove clusterVersion and test skipping code for EOLd k8s versions
  test/integration/ingress_test.go
  test/integration/suite_test.go
  test/integration/utils_test.go
Labels: area/tests, area/maintenance, size/S
