Repository Kong/kubernetes-ingress-controller, pull requests merged in 2023-06, with the labels that each got.

#4117 tests: make upgrade tests more robust
  test/e2e/helpers_test.go
  test/e2e/konnect_test.go
  test/e2e/upgrade_test.go
  test/e2e/utils_test.go
Labels: area/tests, size/L

#4058 feat(telemetry): introduce count for all Gateway API objects
  CHANGELOG.md
  go.mod
  go.sum
  internal/manager/telemetry/manager.go
  internal/manager/telemetry/telemetry_test.go
Labels: area/tests, area/telemetry, size/L

#4111 docs: add TESTING.md
  README.md
  TESTING.md
Labels: area/docs, area/tests, size/L

#4125 test: trim prefix / of path and suffix / of proxy URL in MustHTTPRequest
  test/internal/helpers/http.go
Labels: size/XS

#4126 chore(release): bump K8s & Istio versions for 2.10 release
  .github/workflows/_e2e_tests.yaml
  .github/workflows/release.yaml
Labels: dependencies, area/release, size/M

#4128 chore(release): prepare release/2.10.0
  CHANGELOG.md
  config/image/oss/kustomization.yaml
  deploy/single/all-in-one-dbless-enterprise.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless-legacy.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
Labels: area/release, size/M, backport release/2.10.x

#4137 perf(config_validation): make regex a global variable and avoid `[]byte` conversion
  internal/manager/config_validation.go
Labels: size/XS

#4139 chore(linter) update depguard configuration
  .golangci.yaml
Labels: size/S

#4146 chore(ci): make `toggle` latest in release workflow a boolean
  .github/workflows/release.yaml
Labels: area/ci, area/release, size/XS

#4148 chore(ci): fix notifications for failures of e2e nightly tests
  .github/workflows/e2e_nightly.yaml
Labels: area/debt, area/ci, area/tests, size/XS

#4123 tests: turn ingress tests into golden
  Makefile
  go.mod
  internal/dataplane/parser/golden_test.go
  internal/dataplane/parser/testdata/golden/ingress-v1-empty-path/combined-routes-off_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-empty-path/combined-routes-off_settings.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-empty-path/combined-services_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-empty-path/combined-services_settings.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-empty-path/default_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-empty-path/in.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-multiple-ports-for-one-service/combined-routes-off_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-multiple-ports-for-one-service/combined-routes-off_settings.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-multiple-ports-for-one-service/combined-services_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-multiple-ports-for-one-service/combined-services_settings.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-multiple-ports-for-one-service/default_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-multiple-ports-for-one-service/in.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-ports-defined-by-name/combined-routes-off_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-ports-defined-by-name/combined-routes-off_settings.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-ports-defined-by-name/combined-services_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-ports-defined-by-name/combined-services_settings.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-ports-defined-by-name/default_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-ports-defined-by-name/in.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-regex-prefix-exact-rule/default_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-regex-prefix-exact-rule/in.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-regex-prefix-exact-rule/regex-path-prefix-off_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-regex-prefix-exact-rule/regex-path-prefix-off_settings.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-regex-prefixed-path/default_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-regex-prefixed-path/in.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-rule-with-tls/combined-routes-off_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-rule-with-tls/combined-routes-off_settings.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-rule-with-tls/combined-services_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-rule-with-tls/combined-services_settings.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-rule-with-tls/default_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-rule-with-tls/in.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-single-service-in-multiple-ingresses/combined-routes-off_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-single-service-in-multiple-ingresses/combined-routes-off_settings.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-single-service-in-multiple-ingresses/combined-services_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-single-service-in-multiple-ingresses/combined-services_settings.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-single-service-in-multiple-ingresses/default_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-single-service-in-multiple-ingresses/in.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-with-acme-like-path/combined-routes-off_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-with-acme-like-path/combined-routes-off_settings.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-with-acme-like-path/combined-services_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-with-acme-like-path/combined-services_settings.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-with-acme-like-path/default_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-with-acme-like-path/in.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-with-default-backend/default_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-with-default-backend/in.yaml
  internal/dataplane/parser/translate_ingress_test.go
  internal/store/fake_store.go
  internal/store/store.go
Labels: area/tests, size/XXL

#4158 Update golden and test hint
  internal/dataplane/parser/golden_test.go
  internal/dataplane/parser/testdata/golden/ingress-v1-empty-path/default_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-multiple-ports-for-one-service/default_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-ports-defined-by-name/default_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-regex-prefix-exact-rule/default_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-regex-prefix-exact-rule/regex-path-prefix-off_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-regex-prefixed-path/default_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-rule-with-tls/default_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-single-service-in-multiple-ingresses/default_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-with-acme-like-path/default_golden.yaml
  internal/dataplane/parser/testdata/golden/ingress-v1-with-default-backend/default_golden.yaml
Labels: size/M

#4161 chore(logs): `no active endpoints` is logged at debug instead of warning level
  CHANGELOG.md
  internal/dataplane/parser/parser.go
Labels: area/maintenance, size/XS

#4171 feat(parser) error for all inconsistent services
  CHANGELOG.md
  internal/dataplane/parser/ingressrules.go
  internal/dataplane/parser/ingressrules_test.go
  test/integration/translation_failures_test.go
Labels: size/M

#4174 Support plugin instance name
  CHANGELOG.md
  config/crd/bases/configuration.konghq.com_kongclusterplugins.yaml
  config/crd/bases/configuration.konghq.com_kongplugins.yaml
  deploy/single/all-in-one-dbless-enterprise.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless-legacy.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
  docs/api-reference.md
  internal/dataplane/kongstate/util.go
  internal/dataplane/kongstate/util_test.go
  pkg/apis/configuration/v1/kongclusterplugin_types.go
  pkg/apis/configuration/v1/kongplugin_types.go
Labels: size/L, area/CRD

#4178 feat(konnect): allow configuring license polling periods
  CHANGELOG.md
  internal/adminapi/konnect.go
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/parser_test.go
  internal/konnect/license/client.go
  internal/konnect/license/client_test.go
  internal/konnect/license/types.go
  internal/license/agent.go
  internal/license/agent_test.go
  internal/manager/config.go
  internal/manager/run.go
Labels: area/feature, size/XL, area/konnect, backport release/2.10.x

#4172 tests: migrate GatewayClass related integration tests to envtest based tests
  internal/controllers/dataplane.go
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gatewayclass_controller.go
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/reference/indexer.go
  internal/controllers/reference/reference.go
  internal/util/builder/serviceport.go
  test/envtest/controller.go
  test/envtest/gatewayclass_envtest_test.go
  test/envtest/httproute_controller_test.go
  test/helpers/conditions/conditions.go
  test/integration/gateway_test.go
  test/mocks/dataplane.go
Labels: area/tests, size/XL

#4181 Add Prometheus error count and last successful metrics
  CHANGELOG.md
  internal/dataplane/kong_client.go
  internal/dataplane/sendconfig/sendconfig.go
  internal/metrics/metrics_envtest_test.go
  internal/metrics/prometheus.go
  internal/metrics/prometheus_test.go
Labels: area/telemetry, size/L

#4204 test(conformance): enable `GatewaySecretReferenceGrantSpecific` conformance test
  test/conformance/gateway_conformance_test.go
Labels: size/XS

#4182 feat(ci): add benchmarking code
  .github/workflows/benchmarks.yaml
  Makefile
  internal/dataplane/deckgen/deckgen_test.go
Labels: area/ci, size/L

#4203 tests: fix flaky TestAgent
  internal/adminapi/backoff_strategy_konnect.go
  internal/adminapi/client.go
  internal/license/agent.go
  internal/license/agent_test.go
  internal/util/clock/clock.go
  internal/util/clock/ticker.go
  test/mocks/ticker.go
  test/mocks/ticker_test.go
Labels: area/tests, test-flake, size/L

#4213 fix: fix incorrect .Is() method on update skipped due to backoff error
  CHANGELOG.md
  internal/dataplane/kong_client.go
  internal/dataplane/sendconfig/backoff_strategy.go
  internal/dataplane/sendconfig/backoff_strategy_test.go
  internal/dataplane/sendconfig/sendconfig.go
Labels: size/M

#4215 fix: fix incorrect .Is() method on update skipped due to backoff error (#4213)
  internal/dataplane/kong_client.go
  internal/dataplane/sendconfig/backoff_strategy.go
  internal/dataplane/sendconfig/backoff_strategy_test.go
  internal/dataplane/sendconfig/sendconfig.go
Labels: size/M

#4214 chore(ci): remove redundant vet and fmt commands
  CONTRIBUTING.md
  Makefile
Labels: area/ci, area/maintenance, size/M

#4216 [backport] feat(konnect): allow configuring license polling periods
  internal/adminapi/konnect.go
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/parser_test.go
  internal/konnect/license/client.go
  internal/konnect/license/client_test.go
  internal/konnect/license/types.go
  internal/license/agent.go
  internal/license/agent_test.go
  internal/manager/config.go
  internal/manager/run.go
Labels: size/XL

#4224 chore(ci): replace deprecated buildpulse GH Action
  .github/workflows/_test_reports.yaml
Labels: area/ci, area/maintenance, size/XS

#4223 ci: run PR checks on PRs against all branches
  .github/workflows/benchmarks.yaml
  .github/workflows/pr_checks.yaml
Labels: area/ci, area/maintenance, size/XS

#4226 chore(ci): cleanup orphaned Konnect RGs and roles in cleanup job
  .github/workflows/cleanup.yaml
  hack/cleanup/gke_clusters.go
  hack/cleanup/konnect_runtime_groups.go
  hack/cleanup/main.go
  internal/konnect/roles/client.go
  internal/konnect/roles/client_test.go
  test/e2e/konnect_test.go
Labels: area/ci, size/XL, area/konnect

#4228 chore(release): add 2.10.1 entry to the changelog
  CHANGELOG.md
Labels: area/release, size/S, backport release/2.10.x

#4230 [backport] chore(release): add 2.10.1 entry to the changelog (#4228)
  CHANGELOG.md
Labels: area/release, size/S

#4232 [backport] ci: run PR checks on PRs against all branches (#4223)
  .github/workflows/pr_checks.yaml
Labels: area/ci, size/XS

#4222 refactor: use gojson to marshal config for SHA
  CHANGELOG.md
  go.mod
  internal/dataplane/deckgen/deckgen.go
Labels: area/perf, refactor, size/S

#4231 fix(actions) fix path in cleanup workflow
  .github/workflows/cleanup.yaml
Labels: size/XS

#4233 chore: bump test dependencies
  .github/workflows/_e2e_tests.yaml
  .github/workflows/_integration_tests.yaml
  .github/workflows/release.yaml
Labels: area/ci, area/tests, size/M, backport release/2.10.x

#4236 chore(release): bump KIC version in manifests
  config/image/oss/kustomization.yaml
  deploy/single/all-in-one-dbless-enterprise.yaml
  deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect-enterprise.yaml
  deploy/single/all-in-one-dbless-konnect.yaml
  deploy/single/all-in-one-dbless-legacy.yaml
  deploy/single/all-in-one-dbless.yaml
  deploy/single/all-in-one-postgres-enterprise.yaml
  deploy/single/all-in-one-postgres.yaml
Labels: area/release, size/S

#4235 chore(ci): do not run e2e tests triggered by label on GKE clusters
  .github/workflows/e2e_targeted.yaml
  .github/workflows/e2e_trigger_via_label.yaml
Labels: area/ci, area/tests, size/S

#4194 test(e2e): fix retry on create konnect RG
  test/e2e/environment.go
  test/e2e/konnect_test.go
Labels: area/tests, size/M

#4238 fix: do not prepend ~ before regex paths for Kong < 3.0
  CHANGELOG.md
  internal/dataplane/parser/testdata/golden/grpcroute-example/default_golden.yaml
  internal/dataplane/parser/testdata/golden/grpcroute-example/in.yaml
  internal/dataplane/parser/testdata/golden/grpcroute-example/regex-path-prefix-off_golden.yaml
  internal/dataplane/parser/testdata/golden/grpcroute-example/regex-path-prefix-off_settings.yaml
  internal/dataplane/parser/translate_grpcroute.go
  internal/dataplane/parser/translators/grpcroute.go
  internal/dataplane/parser/translators/grpcroute_test.go
Labels: size/L, backport release/2.9.x, backport release/2.10.x

#4241 chore(docs): mention konnect tests in TESTING.md
  TESTING.md
Labels: area/docs, size/S

#4247 chore(ci): mark as failure notifications from e2e nightly tests
  .github/workflows/e2e_nightly.yaml
Labels: area/ci, area/tests, area/maintenance, size/XS

#4253 chore(ci): ensure nightly image is built in nightly e2e
  .github/workflows/e2e_nightly.yaml
Labels: area/ci, size/XS

#4252 chore(ci): make running gke/konnect cleanup separately possible
  .github/workflows/cleanup.yaml
  hack/cleanup/main.go
Labels: area/ci, size/L

#4254 chore(ci): fix gke cleanup
  .github/workflows/cleanup.yaml
Labels: area/ci

#4256 backport #4238: fix: do not prepend ~ before regex paths for Kong < 3.0
  internal/dataplane/parser/translate_grpcroute.go
Labels: size/S
