Repository Kong/kubernetes-ingress-controller, pull requests merged in 2024-06, with the labels that each got.

#6112 conformance: enable HTTPRouteHostRewrite
  test/conformance/gateway_conformance_test.go
Labels: area/gateway-api, size/XS, kind/conformance

#6105 feat: add metrics for FallbackConfiguration
  CHANGELOG.md
  internal/dataplane/kong_client.go
  internal/dataplane/sendconfig/sendconfig.go
  internal/metrics/prometheus.go
  internal/metrics/prometheus_test.go
  test/envtest/metrics_envtest_test.go
  test/mocks/admin_api_handler.go
Labels: size/L

#6101 feat(diag) expose fallback diagnostic
  CHANGELOG.md
  internal/dataplane/fallback/cache_to_graph_test.go
  internal/dataplane/fallback/graph.go
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_test.go
  internal/diagnostics/server.go
  internal/diagnostics/server_test.go
  internal/diagnostics/types.go
  internal/manager/run.go
  internal/util/configdiag.go
  test/envtest/crds_envtest_test.go
  test/envtest/ingress_test.go
  test/envtest/kongupstreampolicy_test.go
  test/envtest/telemetry_test.go
Labels: size/L

#6119 tests: use expressions router by default in test manifests
  Makefile
  config/components/konnect/manager.yaml
  config/variants/konnect/base/manager.yaml
  config/variants/konnect/debug/manager_debug.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
Labels: area/tests, size/M

#6128 tests: skip flaky `TestMetricsAreServed/with_push_error_and_FallbackConfiguration_enabled`
  test/envtest/metrics_envtest_test.go
Labels: area/tests, test-flake, size/XS

#6129 tests: fix flaky `TestCustomVault` test
  test/integration/vault_test.go
Labels: area/tests, test-flake, size/S

#6127 chore: fix dev admisison webhook config
  config/components/manager_dev_webhook/manager_webhook_secret.yaml
  config/components/manager_dev_webhook/validating_webhook_configuration.yaml
Labels: size/S

#6126 fix: reconcile admin API endpoints on all replicas
  CHANGELOG.md
  internal/controllers/configuration/kongadminapi_controller.go
Labels: size/XS

#6055 feat(custom_entity): add KCE controller
  CHANGELOG.md
  FEATURE_GATES.md
  config/crd/kustomization.yaml
  config/rbac/role.yaml
  docs/cli-arguments.md
  hack/generators/cache-stores/spec.go
  hack/generators/controllers/networking/main.go
  internal/controllers/configuration/zz_generated_controllers.go
  internal/controllers/utils/utils.go
  internal/dataplane/configfetcher/kongrawstate_test.go
  internal/dataplane/deckgen/deckgen.go
  internal/dataplane/fallback/graph_dependencies.go
  internal/dataplane/kong_client.go
  internal/dataplane/kongstate/customentity.go
  internal/dataplane/kongstate/customentity_test.go
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/kongstate_test.go
  internal/dataplane/kongstate/plugin.go
  internal/dataplane/sendconfig/inmemory.go
  internal/dataplane/sendconfig/sendconfig.go
  internal/dataplane/sendconfig/strategy.go
  internal/dataplane/translator/golden_test.go
  internal/dataplane/translator/translator.go
  internal/dataplane/translator/translator_test.go
  internal/manager/config.go
  internal/manager/controllerdef.go
  internal/manager/featuregates/feature_gates.go
  internal/manager/featuregates/feature_gates_test.go
  internal/manager/run.go
  internal/manager/schema_service.go
  internal/store/fake_store.go
  internal/store/store.go
  internal/store/zz_generated_cache_stores.go
  internal/store/zz_generated_cache_stores_test.go
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
  test/envtest/admission_webhook_envtest_test.go
  test/envtest/telemetry_test.go
Labels: size/XXL

#6138 fix: do not sanitize plugins' config
  CHANGELOG.md
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/kongstate_test.go
  internal/dataplane/kongstate/plugin.go
  internal/dataplane/kongstate/plugin_test.go
  internal/dataplane/kongstate/types.go
Labels: size/XXL, fix

#5776 conformance: add support for GRPCRoute
  CHANGELOG.md
  examples/gateway-grpcroute-via-http.yaml
  examples/gateway-grpcroute-via-https.yaml
  internal/controllers/gateway/grpcroute_controller.go
  internal/controllers/gateway/route_parent_status.go
  internal/dataplane/translator/subtranslator/grpcroute_test.go
  internal/dataplane/translator/translate_grpcroute.go
  test/conformance/gateway_conformance_test.go
  test/conformance/suite_test.go
  test/consts.go
  test/integration/isolated/grpc_test.go
  test/integration/isolated/ingress_test.go
  test/internal/helpers/gatewayapi.go
Labels: area/gateway-api, size/L, kind/conformance

#6137 add integration tests for custom entities
  examples/kong-custom-entity.yaml
  test/consts/feature_gates.go
  test/integration/isolated/custom_entity_test.go
  test/internal/testlabels/labels.go
Labels: area/tests, size/L

#6145 chore: add skaffold config for multi gw enterprise
  config/base/kong-ingress-dbless.yaml
  config/components/manager_dev_patch/kustomization.yaml
  config/components/manager_dev_patch/manager.yaml
  config/image/enterprise/kustomization.yaml
  config/image/oss/kustomization.yaml
  config/variants/multi-gw/dev/kustomization.yaml
  renovate.json
  skaffold.yaml
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
Labels: area/maintenance, size/M

#6146 tests: add UT for deckgen.fillPlugin
  internal/dataplane/deckgen/generate_test.go
Labels: area/tests, size/XL

#6152 perf: optimize `GetCombinations`
  internal/util/relations.go
  internal/util/relations_test.go
Labels: size/L

#6157 chore(tests): add fallback config golden tests for Ingress and Service
  internal/dataplane/kong_client_golden_test.go
  internal/dataplane/testdata/golden/fallback-config-ingress/default_golden.yaml
  internal/dataplane/testdata/golden/fallback-config-ingress/in.yaml
  internal/dataplane/testdata/golden/fallback-config-service/default_golden.yaml
  internal/dataplane/testdata/golden/fallback-config-service/in.yaml
Labels: area/tests, size/L

#6154 chore: fix renovate config
  config/image/enterprise/kustomization.yaml
  config/image/oss/kustomization.yaml
  renovate.json
Labels: area/ci, size/M

#6155 [Backport release/3.1.x] fix: do not sanitize plugins' config (#6138)
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/kongstate_test.go
  internal/dataplane/kongstate/plugin.go
  internal/dataplane/kongstate/plugin_test.go
  internal/dataplane/kongstate/types.go
Labels: size/XXL

#6132 Fix CG+<service/route> associated plugins
  CHANGELOG.md
  internal/util/relations.go
  internal/util/relations_test.go
  test/conformance/gateway_conformance_test.go
  test/integration/consumer_group_test.go
Labels: bug, size/L, backport release/3.1.x

#6161 chore(tests): add fallback golden tests for plugins
  internal/dataplane/testdata/golden/fallback-config-kong-cluster-plugin/default_golden.yaml
  internal/dataplane/testdata/golden/fallback-config-kong-cluster-plugin/in.yaml
  internal/dataplane/testdata/golden/fallback-config-kong-plugin/default_golden.yaml
  internal/dataplane/testdata/golden/fallback-config-kong-plugin/in.yaml
Labels: size/L

#6162 chore(tests): add fallback golden tests for gateway api
  internal/dataplane/testdata/golden/fallback-config-gateway-api/default_golden.yaml
  internal/dataplane/testdata/golden/fallback-config-gateway-api/in.yaml
Labels: area/tests

#6158 chore(tests): introduce isolated TestHTTPRouteUseLastValidConfigWithBrokenPluginFallback
  internal/manager/featuregates/feature_gates.go
  test/integration/isolated/examples_httproute_test.go
  test/internal/helpers/controller_manager_flag_opts.go
Labels: area/tests, size/L

#6163 chore(tests): add fallback golden tests for kong resources
  internal/dataplane/kong_client_golden_test.go
  internal/dataplane/sendconfig/inmemory_error_handling.go
  internal/dataplane/testdata/golden/fallback-config-kong/default_golden.yaml
  internal/dataplane/testdata/golden/fallback-config-kong/in.yaml
  internal/dataplane/testdata/golden/fallback-config-kong/service-facade-on_golden.yaml
  internal/dataplane/testdata/golden/fallback-config-kong/service-facade-on_settings.yaml
  internal/store/cache_stores.go
  internal/store/store.go
Labels: area/tests, size/L

#6167 chore: fix changelog for 3.1.5
  CHANGELOG.md
Labels: size/S

#6169 chore: fix golang warnings regarding linker
  Makefile
Labels: area/maintenance, size/S

#6164 chore(tests): add fallback golden tests for remaining resources
  internal/dataplane/testdata/golden/fallback-config-ingress-class/default_golden.yaml
  internal/dataplane/testdata/golden/fallback-config-ingress-class/in.yaml
  internal/dataplane/testdata/golden/fallback-config-kong-upstream-policy/default_golden.yaml
  internal/dataplane/testdata/golden/fallback-config-kong-upstream-policy/in.yaml
  internal/dataplane/testdata/golden/fallback-config-kong-upstream-policy/service-facade-on_golden.yaml
  internal/dataplane/testdata/golden/fallback-config-kong-upstream-policy/service-facade-on_settings.yaml
  internal/dataplane/testdata/golden/fallback-config-secret/default_golden.yaml
  internal/dataplane/testdata/golden/fallback-config-secret/in.yaml
Labels: area/tests, size/L

#6168 feat: validate --use-last-valid-config-for-fallback flag
  docs/cli-arguments.md
  internal/manager/config.go
  internal/manager/config_validation.go
  internal/manager/config_validation_test.go
Labels: size/M

#6171 chore: fix docs post processing script
  scripts/apidocs-gen/post-process-for-konghq.sh
Labels: area/maintenance, size/S

#6166 fix: handing GRPCRoute hostname from Gateway
  internal/dataplane/translator/subtranslator/grpcroute.go
  internal/dataplane/translator/subtranslator/grpcroute_atc_test.go
  internal/dataplane/translator/subtranslator/grpcroute_test.go
  internal/dataplane/translator/translate_grpcroute.go
  test/conformance/gateway_conformance_test.go
Labels: area/gateway-api, size/L

#6172 fix(fallback): backfill all affected objects, not only broken
  internal/dataplane/fallback/fallback.go
  internal/dataplane/fallback/fallback_test.go
  internal/manager/run.go
  test/integration/isolated/examples_httproute_test.go
  test/internal/helpers/http.go
Labels: size/L

#6174 chore: add notes in release procedure about updating CRDs in charts
  .github/ISSUE_TEMPLATE/release.yaml
Labels: size/XS

#6176 chore: skip GRPCExactMethodMatching
  test/conformance/gateway_conformance_test.go
Labels: area/tests, area/gateway-api, size/XS, kind/conformance

#6175 fix(fallback): guard for nil last valid cache
  internal/dataplane/fallback/fallback.go
  internal/dataplane/fallback/fallback_test.go
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_test.go
Labels: fix

#6177 fix(fallback): resolve KongConsumer dependency on credentials
  internal/dataplane/fallback/graph_dependencies_kong.go
  internal/dataplane/fallback/graph_dependencies_kong_test.go
Labels: size/M

#6178 chore: use feature flags in dev manifests
  config/dev/manager_dev.yaml
  config/variants/konnect/debug/manager_debug.yaml
  config/variants/multi-gw-postgres/dev/kustomization.yaml
  config/variants/multi-gw/debug/manager_debug.yaml
Labels: area/ci, area/maintenance, size/S

#6179 chore: fix renovate annotation for kubernetes/code-generator
  .tools_versions.yaml
Labels: area/ci, area/maintenance, size/XS

#6180 Fix renovate config for kustomize images
  config/image/enterprise/kustomization.yaml
  config/image/oss/kustomization.yaml
  renovate.json
Labels: area/ci, size/S

#6184 suggestion: fallback config diagnostics server
  internal/dataplane/fallback/cache_to_graph.go
  internal/dataplane/fallback/cache_to_graph_test.go
  internal/dataplane/fallback/fallback.go
  internal/dataplane/fallback/fallback_meta.go
  internal/dataplane/fallback/fallback_meta_test.go
  internal/dataplane/fallback/fallback_test.go
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_test.go
  internal/diagnostics/api_types.go
  internal/diagnostics/mapping.go
  internal/diagnostics/server.go
  internal/diagnostics/server_test.go
  internal/diagnostics/types.go
  test/integration/isolated/examples_httproute_test.go
Labels: size/XL

#6159 feat(diag) expose fallback objects
  internal/dataplane/fallback/fallback.go
  internal/dataplane/fallback/fallback_meta.go
  internal/dataplane/fallback/fallback_meta_test.go
  internal/dataplane/fallback/fallback_test.go
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_test.go
  internal/diagnostics/api_types.go
  internal/diagnostics/mapping.go
  internal/diagnostics/server.go
  internal/diagnostics/server_test.go
  internal/diagnostics/types.go
  test/integration/isolated/ctx.go
  test/integration/isolated/examples_httproute_test.go
  test/integration/isolated/suite_test.go
Labels: size/XL

#6186 chore: rearange changelog, add 3.2 highlights
  CHANGELOG.md
Labels: size/L

#6187 chore(docs) add 3.1.6 changelog
  CHANGELOG.md
Labels: size/S, backport release/3.1.x

#6190 chore(release): prepare 3.2 release
  LICENSES
  config/image/oss/kustomization.yaml
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
Labels: size/XXL

#6192 ci: add missing GOCACHE and GOPATH in release worflow
  .github/workflows/release.yaml
Labels: area/ci, size/S

#6194 chore(ci): add mise install step to conformance tests report
  .github/workflows/conformance_tests_report.yaml
Labels: area/ci, size/XS

#6196 chore: backport missing 3.2 commits
  .github/workflows/conformance_tests_report.yaml
  .github/workflows/release.yaml
  LICENSES
  config/image/oss/kustomization.yaml
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
Labels: area/maintenance, size/XXL

#6195 chore(docs): do not suggest creating release branch upfront
  .github/ISSUE_TEMPLATE/release.yaml
Labels: area/docs, size/S

#6199 chore: remove stale todo
  internal/dataplane/translator/subtranslator/httproute.go
Labels: area/maintenance, size/XS

#6200 chore: make `config/webhook` to not store the resultant (incomplete) ValidatingWebhookConfiguration
  Makefile
  config/webhook/base/manifests.yaml
  config/webhook/kustomization.yaml
Labels: size/S

#6211 chore: fix 3.2.0 changelog
  CHANGELOG.md
Labels: area/docs, size/XS

#6212 chore: enable prealloc linter
  .golangci.yaml
  internal/admission/validation/ingress/ingress.go
  internal/dataplane/address_finder.go
  internal/dataplane/deckgen/deckgen.go
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/route.go
  internal/dataplane/sendconfig/inmemory_error_handling.go
  internal/dataplane/translator/atc/matcher.go
  internal/dataplane/translator/subtranslator/ingress.go
  internal/dataplane/translator/translate_certs.go
  internal/dataplane/translator/translate_kong_l4.go
  internal/dataplane/translator/translate_secrets.go
  internal/konnect/roles/client.go
  internal/store/store.go
  pkg/apis/configuration/v1/kongprotocol_types.go
Labels: size/M

#6220 chore: use latest kong in envtests
  .github/test_dependencies.yaml
Labels: area/maintenance, size/XS

#6227 chore: update release procedure
  .github/ISSUE_TEMPLATE/release.yaml
Labels: area/maintenance, area/release, size/XS

#6228 fix(translator): Re-fill client certificates of services after merging certificate
  CHANGELOG.md
  internal/dataplane/translator/translate_certs.go
  internal/dataplane/translator/translate_certs_test.go
  internal/dataplane/translator/translator.go
  internal/dataplane/translator/translator_test.go
Labels: size/L

#6232 backport(2.12.x): fix: Re-fill client certificates of services after merging certificate (#6228)
  CHANGELOG.md
  internal/dataplane/parser/parser.go
  internal/dataplane/parser/parser_test.go
  internal/dataplane/parser/translate_certs_test.go
Labels: size/L

#6234 chore: update comment about gRPCRoute conformance test
  test/conformance/gateway_conformance_test.go
Labels: size/XS

#6239 ci(perf): draw report for performance test
  .github/workflows/performance_nightly.yaml
Labels: area/ci, size/M

#6243 chore: add incubator crds to debug skaffold config
  config/variants/multi-gw/debug/kustomization.yaml
Labels: area/maintenance, size/XS

#6242 prepare changelog for release 2.12.5
  CHANGELOG.md
Labels: size/XS

#6244 chore: read admin api response body from error
  go.mod
  go.sum
  internal/dataplane/sendconfig/inmemory.go
  internal/dataplane/sendconfig/inmemory_test.go
  test/kongintegration/kong_client_golden_tests_outputs_test.go
Labels: size/M

#6247 docs(changelog): add changelog for 2.12.4 and 2.12.5 into main
  CHANGELOG.md
Labels: area/docs, size/S

#6254 chore: temporarily disable konnect roles cleanup
  hack/cleanup/konnect_runtime_groups.go
  test/internal/helpers/konnect/control_plane.go
Labels: size/M

#6252 fix(admission): allow multiple plugins of the same type
  CHANGELOG.md
  internal/admission/handler.go
  internal/admission/handler_test.go
  internal/admission/validation/gateway/httproute.go
  internal/admission/validation/gateway/httproute_test.go
  internal/admission/validation/ingress/ingress.go
  internal/admission/validation/ingress/ingress_test.go
  internal/admission/validation/kongplugin/kongplugin.go
  internal/admission/validator.go
  internal/admission/validator_test.go
Labels: size/L, backport release/3.2.x

#6257 Revert "chore: temporarily disable konnect roles cleanup"
  hack/cleanup/konnect_runtime_groups.go
  test/internal/helpers/konnect/control_plane.go
Labels: area/ci, size/M

#6259 backport: fix(admission): allow multiple plugins of the same type #6252
  CHANGELOG.md
  internal/admission/handler.go
  internal/admission/handler_test.go
  internal/admission/validation/gateway/httproute.go
  internal/admission/validation/gateway/httproute_test.go
  internal/admission/validation/ingress/ingress.go
  internal/admission/validation/ingress/ingress_test.go
  internal/admission/validation/kongplugin/kongplugin.go
  internal/admission/validator.go
  internal/admission/validator_test.go
Labels: size/L

#6260 backport: fix: try recovering from gateway sync failure only on UpdateError (#6237)
  CHANGELOG.md
  go.mod
  go.sum
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_test.go
  internal/dataplane/sendconfig/inmemory.go
  internal/dataplane/sendconfig/inmemory_test.go
  test/envtest/configerrorevent_envtest_test.go
  test/kongintegration/inmemory_update_strategy_test.go
Labels: size/XL

#6268 chore: prepare release 3.2.1
  CHANGELOG.md
Labels: area/release

#6269 chore: add v3.2.1 changelog
  CHANGELOG.md
Labels: area/release, size/XS
