Repository Kong/kubernetes-ingress-controller, pull requests merged in 2024-12, with the labels that each got.

#6711 feat: combine services across different httproutes for traditional routes
  CHANGELOG.md
  FEATURE_GATES.md
  internal/dataplane/translator/subtranslator/backendref.go
  internal/dataplane/translator/subtranslator/backendref_test.go
  internal/dataplane/translator/subtranslator/httproute.go
  internal/dataplane/translator/subtranslator/httproute_test.go
  internal/dataplane/translator/subtranslator/subtranslator_vars.go
  internal/dataplane/translator/translate_httproute.go
  internal/dataplane/translator/translate_httproute_test.go
  internal/dataplane/translator/translate_utils.go
  internal/dataplane/translator/translate_utils_test.go
  internal/dataplane/translator/translate_vars.go
  internal/dataplane/translator/translator.go
  internal/manager/featuregates/feature_gates.go
  test/envtest/telemetry_test.go
Labels: size/XXL

#6697 feat: allow configuring cluster domain and use FQDN for upstream service targets
  CHANGELOG.md
  docs/cli-arguments.md
  internal/dataplane/kong_client_golden_test.go
  internal/dataplane/translator/translate_upstreams.go
  internal/dataplane/translator/translator.go
  internal/dataplane/translator/translator_test.go
  internal/manager/config.go
  internal/manager/consts.go
  internal/manager/consts/consts.go
  internal/manager/run.go
Labels: size/L

#6763 chore: add mention in release template about konnect-ui-apps
  .github/ISSUE_TEMPLATE/release.yaml
Labels: size/XS

#6767 fix(controller): set creationTimestamp of ancestors of KongUpstreamPolicy status
  CHANGELOG.md
  internal/controllers/configuration/kongupstreampolicy_utils.go
  internal/controllers/configuration/kongupstreampolicy_utils_test.go
Labels: area/ingress-controller, size/L

#6768 chore(ci): fix e2e's artifact name
  .github/workflows/_e2e_tests.yaml
Labels: area/ci, size/M

#6770 docs(CONTRIBUTING.md): remove references to `next` branch
  CONTRIBUTING.md
Labels: size/S

#6759 feat(HTTPRoute): propagate to Kong tag `k8s-named-route-rule`
  CHANGELOG.md
  internal/dataplane/testdata/golden/httproute-example/default_golden.yaml
  internal/dataplane/testdata/golden/httproute-example/expression-routes-on_golden.yaml
  internal/dataplane/testdata/golden/httproute-example/in.yaml
  internal/dataplane/translator/subtranslator/httproute.go
  internal/dataplane/translator/subtranslator/httproute_atc.go
  internal/dataplane/translator/translate_httproute.go
  internal/util/k8s.go
  internal/util/k8s_test.go
Labels: area/feature, area/gateway-api, size/L, area/observability

#6762 fix: fix ExtensionRef plugins for HTTPRoutes
  CHANGELOG.md
  internal/dataplane/translator/subtranslator/httproute_test.go
  internal/util/objectmeta.go
  internal/util/objectmeta_test.go
Labels: size/L

#6771 chore(tests): dump diagnostics in isolated integration tests
  test/integration/isolated/suite_test.go
  test/internal/helpers/setup.go
  test/internal/helpers/teardown.go
Labels: area/tests, size/S

#6777 chore(tests): skip e2e TestDeployAllInOneDBLESS scaling proxy to 0
  test/e2e/all_in_one_test.go
Labels: area/tests, test-flake, size/M

#6778 chore(ci): fix performance tests artifacts
  .github/workflows/performance_nightly.yaml
  .github/workflows/performance_targeted.yaml
Labels: area/ci, size/XS

#6779 docs(ISSUE_TEMPLATE): add epic template
  .github/ISSUE_TEMPLATE/epic.yaml
Labels: size/M

#6781 fix(log): get rid of `No targets found to create upstream ...`
  CHANGELOG.md
  internal/dataplane/translator/translate_upstreams.go
Labels: area/maintenance, size/S, fix

#6785 ci: only run benchmarks on main and labeled PRs
  .github/workflows/benchmarks.yaml
Labels: area/ci, size/S

#6786 ci: fix assigning duplicated instance names to plugins bound to different entity types (e.g. route and consumer group)
  CHANGELOG.md
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/kongstate_test.go
  internal/dataplane/testdata/golden/kongplugin-instance-name/default_golden.yaml
Labels: size/L

#6789 chore(ci): renovate update kubernetes-configuration to unstable versions
  renovate.json
Labels: area/ci, size/XS

#6791 fix: verify if the referenced KongPlugin/KongClusterPlugin exists and set Programmed condition accordingly
  CHANGELOG.md
  internal/dataplane/kongstate/customentity.go
  internal/dataplane/kongstate/customentity_test.go
  internal/dataplane/testdata/golden/kong-custom-entity-ee/default_golden.yaml
  internal/dataplane/testdata/golden/kong-custom-entity-ee/in.yaml
Labels: size/L

#6795 feat: Add the flag `--secret-label-selector` to set the label selector for `Secrets` to ingest.
  CHANGELOG.md
  docs/cli-arguments.md
  internal/controllers/configuration/secret_controller.go
  internal/manager/config.go
  internal/manager/config_validation_test.go
  internal/manager/controllerdef.go
Labels: size/M

#6800 fix: resolve panic in resourceErrorFromEntityAction
  internal/dataplane/configfetcher/kongrawstate_test.go
  internal/dataplane/kongstate/kongstate_test.go
  internal/dataplane/sendconfig/dbmode.go
Labels: area/maintenance, size/XS, fix

#6801 fix(debug): fix /raw-error endpoint not serving raw response body
  internal/dataplane/kong_client.go
Labels: size/XS

#6790 chore(logs): DEBUG instead of ERROR for K8s Event push
  CHANGELOG.md
  internal/dataplane/failures/failures.go
  internal/dataplane/failures/failures_test.go
  internal/dataplane/kong_client.go
  internal/dataplane/translator/ingressrules_test.go
Labels: area/debt, size/M

#6131 feat(diagnostics) add diff endpoints
  CHANGELOG.md
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_golden_test.go
  internal/dataplane/kong_client_test.go
  internal/dataplane/sendconfig/dbmode.go
  internal/dataplane/sendconfig/sendconfig.go
  internal/dataplane/sendconfig/strategy.go
  internal/dataplane/sendconfig/strategy_test.go
  internal/diagnostics/api_types.go
  internal/diagnostics/diff.go
  internal/diagnostics/diff_test.go
  internal/diagnostics/server.go
  internal/diagnostics/server_test.go
  internal/diagnostics/types.go
  internal/konnect/config_synchronizer.go
  internal/konnect/config_synchronizer_test.go
  internal/manager/run.go
  test/envtest/crds_envtest_test.go
  test/envtest/telemetry_test.go
  test/integration/suite_test.go
  test/kongintegration/dbmode_update_strategy_test.go
  test/kongintegration/kong_client_golden_tests_outputs_test.go
Labels: priority/low, size/XXL

#6802 feat(custom_entity): introduce schema validation
  CHANGELOG.md
  internal/dataplane/kongstate/customentity.go
  internal/dataplane/kongstate/customentity_test.go
  internal/dataplane/kongstate/kongstate_test.go
  internal/dataplane/translator/translator.go
  test/integration/isolated/custom_entity_test.go
Labels: size/L

#6766 feat(translator): combine services across httproutes expression router
  CHANGELOG.md
  internal/dataplane/testdata/golden/httproute-example/expression-routes-on_golden.yaml
  internal/dataplane/testdata/golden/httproute-url-rewrite-path-prefix/expression-routes-on_golden.yaml
  internal/dataplane/translator/subtranslator/httproute.go
  internal/dataplane/translator/subtranslator/httproute_atc.go
  internal/dataplane/translator/subtranslator/httproute_atc_test.go
  internal/dataplane/translator/subtranslator/httproute_test.go
  internal/dataplane/translator/translate_httproute.go
  internal/dataplane/translator/translate_httproute_test.go
Labels: area/feature, size/XXL

#6753 feat: convert `BackendTLSPolicies` into service annotations
  CHANGELOG.md
  config/rbac/gateway/role.yaml
  config/rbac/role.yaml
  docs/cli-arguments.md
  examples/ingress-upstream-tls.yaml
  hack/generators/cache-stores/spec.go
  internal/annotations/annotations.go
  internal/annotations/annotations_test.go
  internal/controllers/configuration/configmap_controller.go
  internal/controllers/configuration/object_references.go
  internal/controllers/gateway/backendtlspolicy_controller.go
  internal/controllers/gateway/backendtlspolicy_utils.go
  internal/controllers/gateway/backendtlspolicy_utils_test.go
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/reference/reference.go
  internal/dataplane/fallback/graph_dependencies.go
  internal/dataplane/translator/ingressrules.go
  internal/dataplane/translator/ingressrules_test.go
  internal/dataplane/translator/translate_cacerts.go
  internal/dataplane/translator/translator_test.go
  internal/gatewayapi/aliases.go
  internal/manager/config.go
  internal/manager/config_validation_test.go
  internal/manager/consts/consts.go
  internal/manager/controllerdef.go
  internal/store/fake_store.go
  internal/store/fake_store_test.go
  internal/store/store.go
  internal/store/zz_generated.cache_stores.go
  internal/store/zz_generated.cache_stores_test.go
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
  test/integration/isolated/ingress_verify_upstream_tls_test.go
  test/integration/translation_failures_test.go
  test/internal/testlabels/labels.go
Labels: size/XXL

#6808 tests(kongintegration): retry when creating kong's container
  test/kongintegration/containers/kong.go
Labels: area/tests, test-flake, size/S

#6799 test: `BackendTLSPolicy` integration test
  CHANGELOG.md
  config/rbac/gateway/role.yaml
  internal/controllers/gateway/backendtlspolicy_controller.go
  internal/dataplane/translator/ingressrules.go
  internal/gatewayapi/consts.go
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
  test/integration/isolated/backendtlspolicy_test.go
Labels: area/tests, area/gateway-api, size/L

#6822 chore: revert go-database-reconciler to 1.16.1 and go-kong to 0.60.0
  go.mod
  go.sum
Labels: size/S

#6813 chore(examples): add BackendTLSPolicy example manifest
  examples/gateway-backendtlspolicy.yaml
Labels: area/gateway-api, size/L

#6828 chore: predicate.And -> predicate.Or in secret and configmap controllers
  examples/gateway-backendtlspolicy.yaml
  internal/controllers/configuration/configmap_controller.go
  internal/controllers/configuration/secret_controller.go
Labels: size/XS

#6814 feat(KongPlugin): generate K8s Events for misconfiguration
  CHANGELOG.md
  internal/dataplane/deckgen/generate.go
  internal/dataplane/kongstate/customentity.go
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/kongstate_test.go
  internal/dataplane/kongstate/plugin.go
  internal/util/relations.go
  internal/util/relations_test.go
  test/envtest/configerrorevent_envtest_test.go
Labels: area/debt, size/XXL

#6837 feat(backendtlspolicy): enqueue for ConfigMaps
  CHANGELOG.md
  internal/controllers/gateway/backendtlspolicy_controller.go
  internal/controllers/gateway/backendtlspolicy_utils.go
  internal/controllers/gateway/backendtlspolicy_utils_test.go
Labels: area/gateway-api, size/L

#6833 refactor: update conflict error is not an error, don't report it but requeue
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/handle_error.go
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/tcproute_controller.go
  internal/controllers/gateway/tlsroute_controller.go
  internal/controllers/gateway/udproute_controller.go
Labels: size/L

#6840 fix(fallback): check for nil stores in `cacheToGraph` and recovering from fallback config to prevent panics
  internal/dataplane/fallback/cache_to_graph.go
  internal/dataplane/fallback/cache_to_graph_test.go
  internal/dataplane/kong_client.go
  internal/store/cache_stores.go
  internal/store/cache_stores_snapshot.go
Labels: size/M

#6843 tests(envtest): disable metrics by default
  test/envtest/metrics_envtest_test.go
  test/envtest/run.go
Labels: area/tests, size/S

#6841 feat(KongPlugin): generate K8s Events for missing grant
  CHANGELOG.md
  internal/dataplane/kongstate/customentity.go
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/kongstate_test.go
  internal/gatewayapi/contraints.go
  test/envtest/configerrorevent_envtest_test.go
Labels: area/debt, size/L

#6845 chore: make CA certificate annotations use plural form
  CHANGELOG.md
  examples/ingress-upstream-tls.yaml
  internal/annotations/annotations.go
Labels: size/S

#6848 fix(credentials): ignore missing secret field on secret validation for JWT credentials with non HMAC algo
  CHANGELOG.md
  internal/admission/validation/consumers/credentials/validation.go
  internal/admission/validation/consumers/credentials/validation_test.go
  test/envtest/admission_webhook_envtest_test.go
Labels: size/L

#6852 chore(deps): update e2e tests deps
  .github/test_dependencies.yaml
Labels: size/S

#6853 feat: allow `Secret`s as `BackendTLSPolicy` `CACertificateRefs`
  CHANGELOG.md
  config/rbac/gateway/role.yaml
  internal/annotations/annotations.go
  internal/controllers/gateway/backendtlspolicy_controller.go
  internal/controllers/gateway/backendtlspolicy_utils.go
  internal/controllers/gateway/backendtlspolicy_utils_test.go
  internal/dataplane/translator/ingressrules.go
  internal/store/store.go
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
  test/integration/isolated/backendtlspolicy_test.go
Labels: area/gateway-api, release/required, size/L

#6855 fix: no redundant space in header `Location` for `HTTPRoute` with requestRedirect filter
  CHANGELOG.md
  internal/dataplane/translator/subtranslator/httproute.go
  internal/dataplane/translator/subtranslator/httproute_atc_test.go
  internal/dataplane/translator/subtranslator/httproute_test.go
  internal/dataplane/translator/translate_httproute_test.go
Labels: size/L, fix

#6862 chore: update FEATURE_GATES.md
  CHANGELOG.md
  FEATURE_GATES.md
Labels: size/XS

#6863 chore(tests): fix flake due to missing HTTPRoute CRD
  internal/manager/controllerdef.go
Labels: area/tests, area/maintenance, test-flake, size/S, fix

#6860 chore: v3.4.0 CHANGELOG and config update
  CHANGELOG.md
  config/image/oss/kustomization.yaml
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
Labels: size/L, backport release/3.4.x

#6868 chore: extract common mocks to mocks package
  internal/dataplane/kong_client_test.go
  internal/dataplane/kongstate/consumer_test.go
  internal/dataplane/kongstate/credentials_test.go
  internal/dataplane/kongstate/kongstate_test.go
  internal/dataplane/kongstate/uuid_test.go
  internal/konnect/config_synchronizer.go
  internal/konnect/config_synchronizer_test.go
  internal/manager/setup.go
  test/mocks/configuration_change_detector.go
  test/mocks/update_strategy.go
  test/mocks/update_strategy_resolver.go
Labels: size/XL

#6879 chore: update docs pr label
  .github/workflows/release_docs.yaml
Labels: size/XS

#6881 fix: do not unregister Kong DPs metrics when Konnect integration is enabled
  CHANGELOG.md
  go.mod
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_golden_test.go
  internal/dataplane/kong_client_test.go
  internal/dataplane/sendconfig/sendconfig.go
  internal/konnect/config_synchronizer.go
  internal/konnect/config_synchronizer_test.go
  internal/manager/run.go
  internal/manager/setup.go
  internal/metrics/prometheus.go
  internal/metrics/prometheus_test.go
  test/mocks/metrics_recorder.go
Labels: size/L, fix, backport release/3.3.x, backport release/3.4.x

#6880 chore(ci): fix extractVersion for kustomize
  renovate.json
Labels: area/ci, size/XS

#6884 ci: add actionlint in CI
  .github/workflows/_docker_build.yaml
  .github/workflows/_e2e_tests.yaml
  .github/workflows/_integration_tests.yaml
  .github/workflows/_linters.yaml
  .github/workflows/_performance_tests.yaml
  .github/workflows/nightly.yaml
  .github/workflows/regenerate_on_deps_bump.yaml
  .github/workflows/release.yaml
  .github/workflows/release_docs.yaml
  .github/workflows/validate_kong_image_trigger_via_label.yaml
  .tools_versions.yaml
  Makefile
Labels: area/ci, size/L

#6861 chore: remove kube-rbac-proxy from default kustomization
  CHANGELOG.md
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  docs/cli-arguments.md
  go.mod
  go.sum
  internal/manager/config.go
  internal/manager/config/types/metricsfilter.go
  internal/manager/config_validation.go
  internal/manager/flags/validated.go
  internal/manager/setup.go
  scripts/cli-arguments-docs-gen/main.go
Labels: size/L

#6889 chore(refactor): dedicated rels package
  internal/dataplane/kongstate/customentity.go
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/kongstate_test.go
  internal/util/rels/relations.go
  internal/util/rels/relations_test.go
Labels: area/debt, refactor, size/L

#6898 [backport release/3.3.x] fix: do not unregister Kong DPs metrics when Konnect integration is enabled (#6881)
  go.mod
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_golden_test.go
  internal/dataplane/kong_client_test.go
  internal/dataplane/sendconfig/sendconfig.go
  internal/konnect/config_synchronizer.go
  internal/konnect/config_synchronizer_test.go
  internal/manager/run.go
  internal/manager/setup.go
  internal/metrics/prometheus.go
  internal/metrics/prometheus_test.go
  test/mocks/metrics_recorder.go
Labels: size/L

#6897 [backport release/3.4.x] fix: do not unregister Kong DPs metrics when Konnect integration is enabled (#6881)
  go.mod
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_golden_test.go
  internal/dataplane/kong_client_test.go
  internal/dataplane/sendconfig/sendconfig.go
  internal/konnect/config_synchronizer.go
  internal/konnect/config_synchronizer_test.go
  internal/manager/run.go
  internal/manager/setup.go
  internal/metrics/prometheus.go
  internal/metrics/prometheus_test.go
  test/mocks/metrics_recorder.go
Labels: size/L

#6877 refactor: refactor Gateway API's route parent status update code
  internal/controllers/gateway/conditions.go
  internal/controllers/gateway/grpcroute_controller.go
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/route_parent_status.go
  internal/controllers/gateway/route_parent_status_test.go
  internal/controllers/gateway/route_utils.go
  internal/controllers/gateway/route_utils_test.go
  internal/controllers/gateway/tcproute_controller.go
  internal/controllers/gateway/tlsroute_controller.go
  internal/controllers/gateway/udproute_controller.go
  internal/gatewayapi/typemeta.go
  internal/util/builder/backendref.go
  internal/util/builder/parentref.go
  internal/util/conversions.go
Labels: size/XXL, refactor
