Repository Kong/kubernetes-ingress-controller, pull requests merged in 2024-09, with the labels that each got.

#6508 chore: group dependabot k8s libs bumps
  .github/dependabot.yml
  .github/workflows/_linters.yaml
  config/crd/bases/configuration.konghq.com_ingressclassparameterses.yaml
  config/crd/bases/configuration.konghq.com_kongclusterplugins.yaml
  config/crd/bases/configuration.konghq.com_kongconsumergroups.yaml
  config/crd/bases/configuration.konghq.com_kongconsumers.yaml
  config/crd/bases/configuration.konghq.com_kongcustomentities.yaml
  config/crd/bases/configuration.konghq.com_kongingresses.yaml
  config/crd/bases/configuration.konghq.com_konglicenses.yaml
  config/crd/bases/configuration.konghq.com_kongplugins.yaml
  config/crd/bases/configuration.konghq.com_kongupstreampolicies.yaml
  config/crd/bases/configuration.konghq.com_kongvaults.yaml
  config/crd/bases/configuration.konghq.com_tcpingresses.yaml
  config/crd/bases/configuration.konghq.com_udpingresses.yaml
  config/crd/incubator/incubator.ingress-controller.konghq.com_kongservicefacades.yaml
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
Labels: area/maintenance, size/M

#6110 test: add translator golden tests for gateway API L4 routes
  internal/dataplane/translator/testdata/golden/tcproute-example/default_golden.yaml
  internal/dataplane/translator/testdata/golden/tcproute-example/in.yaml
  internal/dataplane/translator/testdata/golden/tlsroute-example/default_golden.yaml
  internal/dataplane/translator/testdata/golden/tlsroute-example/in.yaml
  internal/dataplane/translator/testdata/golden/udproute-example/default_golden.yaml
  internal/dataplane/translator/testdata/golden/udproute-example/in.yaml
Labels: size/L

#6517 chore: get back to using junit's upstream version of mise plugin
  Makefile
Labels: area/maintenance, size/XS
