Repository Kong/kubernetes-ingress-controller, pull requests merged in 2024-07, with the labels that each got.

#6271 fix(fallback): do not skip config update when gateways out of sync
  CHANGELOG.md
  internal/adminapi/client.go
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_golden_test.go
  internal/dataplane/kong_client_test.go
  internal/dataplane/sendconfig/sendconfig.go
  internal/manager/run.go
Labels: size/L, fix, backport release/3.2.x

#6274 backport: fix(fallback): do not skip config update when gateways out of sync (#6271)
  CHANGELOG.md
  internal/adminapi/client.go
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_golden_test.go
  internal/dataplane/kong_client_test.go
  internal/dataplane/sendconfig/sendconfig.go
  internal/manager/run.go
Labels: size/L

#6275 chore: add v3.2.2 changelog entry
  CHANGELOG.md
Labels: area/release

#6262 ci: fallback when using vars to a default
  .github/workflows/_conformance_tests.yaml
  .github/workflows/_docker_build.yaml
  .github/workflows/_e2e_tests.yaml
  .github/workflows/_envtest_tests.yaml
  .github/workflows/_integration_tests.yaml
  .github/workflows/_kongintegration_tests.yaml
  .github/workflows/_linters.yaml
  .github/workflows/_performance_tests.yaml
  .github/workflows/_test_reports.yaml
  .github/workflows/_unit_tests.yaml
  .github/workflows/checks.yaml
  .github/workflows/codeql.yaml
  .github/workflows/regenerate_on_deps_bump.yaml
Labels: size/M

#6280 Fix(custom entity): Generate multiple entities if KongCustomEntity attached to multiple foreign entities
  CHANGELOG.md
  internal/dataplane/kongstate/customentity.go
  internal/dataplane/kongstate/customentity_test.go
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/kongstate_test.go
  test/integration/isolated/custom_entity_test.go
Labels: size/XXL

#6293 chore(tests): enable ee kongintegration tests
  .github/test_dependencies.yaml
  .github/workflows/_kongintegration_tests.yaml
  test/internal/testenv/testenv.go
  test/kongintegration/containers/kong.go
  test/kongintegration/kong_client_golden_tests_outputs_test.go
Labels: area/tests, size/M

#6286 feat(fallback): support custom entities
  CHANGELOG.md
  internal/dataplane/fallback/cache_to_graph_test.go
  internal/dataplane/fallback/graph_dependencies.go
  internal/dataplane/fallback/graph_dependencies_kong.go
  internal/dataplane/fallback/graph_dependencies_kong_test.go
  internal/dataplane/fallback/helpers_test.go
  internal/dataplane/kong_client_golden_test.go
  internal/dataplane/testdata/golden/fallback-config-kong-custom-entities-ee/custom-entities-on_golden.yaml
  internal/dataplane/testdata/golden/fallback-config-kong-custom-entities-ee/custom-entities-on_settings.yaml
  internal/dataplane/testdata/golden/fallback-config-kong-custom-entities-ee/default_golden.yaml
  internal/dataplane/testdata/golden/fallback-config-kong-custom-entities-ee/in.yaml
  internal/dataplane/testdata/golden/kong-custom-entity-ee/custom-entities-on_golden.yaml
  internal/dataplane/testdata/golden/kong-custom-entity-ee/custom-entities-on_settings.yaml
  internal/dataplane/testdata/golden/kong-custom-entity-ee/default_golden.yaml
  internal/dataplane/testdata/golden/kong-custom-entity-ee/in.yaml
  internal/store/store.go
  staticcheck.conf
Labels: area/feature, size/XL

#6296 fix(translator): Pass typemeta in ingress sub-translator
  internal/dataplane/translator/subtranslator/ingress.go
  internal/dataplane/translator/subtranslator/ingress_atc.go
  internal/dataplane/translator/subtranslator/ingress_atc_test.go
  internal/dataplane/translator/subtranslator/ingress_test.go
Labels: size/L

#6297 perf: don't deep copy the annotations in FromK8sObject
  internal/dataplane/kongstate/util.go
  internal/dataplane/kongstate/util_test.go
  internal/dataplane/translator/translate_httproute_test.go
  internal/util/objectmeta.go
  internal/util/objectmeta_test.go
Labels: area/perf, size/L

#6298 chore(tests): do not use InsecureSkipVerify for GRPC and TLS tests
  examples/gateway-grpcroute-via-https.yaml
  examples/gateway-tlsroute.yaml
  test/helpers/certificate/certificate.go
  test/integration/examples_test.go
  test/integration/isolated/examples_grpc_test.go
  test/integration/isolated/grpc_test.go
  test/integration/isolated/ingress_test.go
  test/integration/tcpingress_test.go
  test/integration/tlsroute_test.go
Labels: area/tests, area/maintenance, size/L

#6295 fix(plugin): fix filling type meta and namespace in plugin reference check
  CHANGELOG.md
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/kongstate_test.go
  internal/util/objectmeta.go
  internal/util/objectmeta_test.go
Labels: size/L

#6302 chore(refs) add grant check logs
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/kongstate_test.go
  internal/dataplane/translator/backendref.go
  internal/dataplane/translator/translate_utils.go
  internal/dataplane/translator/translate_utils_test.go
  internal/dataplane/translator/wrappers_refchecker_test.go
  internal/gatewayapi/references.go
  internal/gatewayapi/references_test.go
Labels: size/XL

#6310 chore(tests): test Gateway with HTTPS wildcard domains
  test/integration/isolated/ctx.go
  test/integration/isolated/gateway_https_test.go
Labels: area/tests, area/maintenance, size/L

#6316 test: add case for incorrect reference in remote plugin test
  test/integration/plugin_test.go
Labels: area/tests, size/M

#6313 feat: --konnect-disable-consumer-sync flag
  CHANGELOG.md
  docs/cli-arguments.md
  internal/adminapi/client.go
  internal/adminapi/konnect.go
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_test.go
  internal/manager/config.go
Labels: size/S

#6289 feat(custom_entity) support cross-namespace reference for KongCustomEntity
  CHANGELOG.md
  internal/dataplane/kongstate/customentity.go
  internal/dataplane/kongstate/customentity_test.go
Labels: size/L

#6333 docs: add retro to release checklist
  .github/ISSUE_TEMPLATE/release.yaml
Labels: size/XS

#6345 chore(docs) add 3.2.3 changelog
  CHANGELOG.md
Labels: size/S, backport release/3.2.x

#6341 feat(konnect): Add Konnect config syncer
  internal/konnect/config_synchronizer.go
  internal/konnect/config_synchronizer_test.go
  internal/metrics/prometheus_test.go
Labels: size/L, area/konnect

#6349 feat: Separate channels to notify gateway and Konnect config status
  CHANGELOG.md
  internal/clients/config_status.go
  internal/clients/config_status_test.go
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_test.go
  internal/dataplane/synchronizer_test.go
  internal/konnect/node_agent.go
  internal/konnect/node_agent_test.go
Labels: size/L, area/konnect

#6354 chore(ci): bump k8s version to 1.28 for GKE
  .github/workflows/_e2e_tests.yaml
Labels: size/XS

#6347 chore: make the status check of the gateway client to be executed concurrently
  internal/clients/readiness.go
Labels: size/M

#6357 feat: check Gateway pending clients readiness concurrently
  CHANGELOG.md
  internal/clients/manager_test.go
  internal/clients/readiness.go
  internal/clients/readiness_test.go
Labels: size/L
