Repository Kong/kubernetes-ingress-controller, pull requests merged in 2024-04, with the labels that each got.

#5786 ci: set timeout for e2e test and perf test
  .github/workflows/_e2e_tests.yaml
  .github/workflows/_performance_tests.yaml
Labels: area/ci, size/XS

#5792 chore(docs): add checkbox for docs update in enhancement issue template
  .github/ISSUE_TEMPLATE/enhancement.yaml
Labels: area/docs, size/S

#5788 build: do not use qemu for emulation when building docker images
  .dockerignore
  .github/workflows/_docker_build.yaml
  .github/workflows/checks.yaml
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
  Dockerfile
  Dockerfile.debug
Labels: area/ci, size/S

#5793 tests: fix flaky `TestSynchronizer_IsReadyDoesntBlockWhenDataPlaneIsBlocked`
  internal/dataplane/synchronizer_test.go
Labels: area/tests, test-flake, size/M

#5791 [Backport release/3.1.x] fix(webhook): do not require rsa_public_key field in credentials secrets when working with jwt HMAC algorigthms (#5737)
  CHANGELOG.md
  internal/admission/validation/consumers/credentials/validation.go
  internal/admission/validation/consumers/credentials/validation_test.go
Labels: size/M

#5789 [Backport release/3.1.x] fix: do not require namespaces when parsing errors about cluster scoped resources (#5764)
  internal/dataplane/sendconfig/inmemory_error_handling.go
  internal/dataplane/sendconfig/inmemory_error_handling_test.go
Labels: size/M

#5806 [backport release/3.1.x] fix: add check for existence of HTTPRoute in KongUpstreamPolicy controller
  CHANGELOG.md
  internal/controllers/configuration/konglicense_controller.go
  internal/controllers/configuration/kongupstreampolicy_controller.go
  internal/controllers/configuration/kongupstreampolicy_utils.go
  internal/controllers/configuration/kongupstreampolicy_utils_test.go
  internal/manager/controllerdef.go
  test/envtest/adminapi_discoverer_envtest_test.go
  test/envtest/kongupstreampolicy_test.go
  test/envtest/setup.go
Labels: size/XL, fix

#5797 tests: move KongPlugin and KongClusterPlugin admission webhook integration tests to envtest suite
  test/envtest/admission_webhook_envtest_test.go
  test/integration/webhook_test.go
Labels: area/tests, size/XL

#5807 tests: fix flaky TestIngressMatchByHost
  test/integration/ingress_test.go
Labels: area/tests, test-flake, size/S

#5773 feat(diag) expose unparseable config errors
  CHANGELOG.md
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_test.go
  internal/dataplane/sendconfig/backoff_strategy.go
  internal/dataplane/sendconfig/backoff_strategy_test.go
  internal/dataplane/sendconfig/dbmode.go
  internal/dataplane/sendconfig/inmemory.go
  internal/dataplane/sendconfig/inmemory_error_handling.go
  internal/dataplane/sendconfig/sendconfig.go
  internal/dataplane/sendconfig/strategy.go
  internal/diagnostics/server.go
  internal/diagnostics/server_test.go
  internal/util/configdiag.go
  test/kongintegration/inmemory_update_strategy_test.go
  test/kongintegration/kongupstreampolicy_test.go
  test/kongintegration/translator_golden_tests_outputs_test.go
Labels: size/L

#5760 [2.12.x] chore: upgrade KTF and pin Kuma to 2.6.2
  go.mod
  go.sum
  test/e2e/helpers_test.go
  test/e2e/kuma_test.go
Labels: size/M

#5809 chore: do not return requeue true when err is not nil
  internal/controllers/gateway/gateway_controller.go
Labels: area/maintenance, size/XS

#5816 fix: do reconcile secrets with `konghq.com/credential` label
  CHANGELOG.md
  internal/admission/validation/consumers/credentials/validation.go
  internal/admission/validation/consumers/credentials/validation_test.go
  internal/controllers/configuration/secret_controller.go
  internal/controllers/configuration/secret_controller_test.go
  internal/dataplane/kongstate/kongstate_test.go
  internal/labels/labels.go
  internal/util/credential.go
  internal/util/credential_test.go
Labels: size/L

#5823 chore(deps): bump controller-runtime to include a data race fix
  go.mod
  go.sum
Labels: dependencies, area/maintenance, size/XS

#5826 fix(tests): do not run TestExampleUDPRoute in parallel
  test/integration/isolated/examples_udproute_test.go
Labels: area/ci, area/tests, test-flake, size/XS, fix

#5648 support license with DB backed Kong gateways
  CHANGELOG.md
  go.mod
  go.sum
  internal/dataplane/configfetcher/kongrawstate_test.go
  internal/dataplane/sendconfig/dbmode.go
  internal/dataplane/sendconfig/strategy.go
  test/integration/isolated/license_test.go
  test/integration/isolated/suite_test.go
Labels: size/M

#5822 tests: move KongConsumer and credential Secret validation integration tests to envtest suite
  internal/admission/validation/consumers/credentials/validation_test.go
  test/envtest/admission_webhook_envtest_test.go
  test/integration/admission_webhook_helpers_test.go
  test/integration/webhook_test.go
Labels: area/tests, size/XXL

#5827 chore: pin fossa action to the newest 1.3.3 tag
  .github/workflows/license.yaml
Labels: area/ci, size/XS

#5824 perf: preallocate when listing Gateway API objects in store
  CHANGELOG.md
  internal/store/store.go
  internal/store/store_test.go
Labels: area/perf, size/L

#5829 chore: fix compilation warnings about malformed LC_DYSYMTAB
  Makefile
Labels: area/maintenance, size/M

#5832 tests: fix feature gates used in TestDeployAllInOneDBLESSGateway
  test/e2e/features_test.go
Labels: area/tests, size/S

#5842 tests: use GenerateName for isolated integration tests namespaces
  test/integration/isolated/namespace.go
Labels: area/tests, size/S

#5843 chore(ci): migrate actions/upload-artifact and actions/download-artifact to v4
  .github/workflows/_conformance_tests.yaml
  .github/workflows/_envtest_tests.yaml
  .github/workflows/_integration_tests.yaml
  .github/workflows/_kongintegration_tests.yaml
  .github/workflows/_test_reports.yaml
  .github/workflows/_unit_tests.yaml
Labels: area/ci, size/M

#5817 fix(upstreams) deduplicate like targets
  internal/dataplane/translator/translator.go
  internal/dataplane/translator/translator_test.go
Labels: size/L

#5846 fix(diag): get rid of wrongly logged errors
  CHANGELOG.md
  internal/dataplane/kong_client.go
  internal/dataplane/sendconfig/sendconfig.go
Labels: size/M, fix

#5849 chore(docs) add missing changelog for #5817
  CHANGELOG.md
Labels: size/XS

#5850 chore(translator): move non top-level methods to separate files
  internal/dataplane/translator/translate_certs.go
  internal/dataplane/translator/translate_kong_l4.go
  internal/dataplane/translator/translate_routes_helpers.go
  internal/dataplane/translator/translate_upstreams.go
  internal/dataplane/translator/translator.go
Labels: area/maintenance, size/XXL

#5808 test: allow installation using a specified GatewayAPI commit
  Makefile
  test/consts/zz_generated_gateway.go
  test/envtest/setup.go
  test/internal/cmd/generate-gateway-api-consts/gateway_consts.tmpl
  test/internal/cmd/generate-gateway-api-consts/main.go
Labels: area/tests, size/M

#5852 chore(tests): better logs for HTTPRoute integration tests
  test/integration/httproute_test.go
Labels: area/tests, area/maintenance, size/M

#5858 tests: add logs to konnect license test
  test/e2e/helpers_test.go
  test/e2e/konnect_test.go
Labels: area/tests, size/S

#5859 docs: remove KGO alpha note from readme
  README.md
Labels: area/docs

#5855 feat(gateway-api): support ReplaceFullPath for URLRewrite
  CHANGELOG.md
  examples/gateway-httproute-rewrite-path-full.yaml
  internal/admission/validation/gateway/httproute.go
  internal/admission/validation/gateway/httproute_test.go
  internal/dataplane/translator/subtranslator/httproute.go
  internal/dataplane/translator/subtranslator/httproute_test.go
  internal/gatewayapi/aliases.go
  test/integration/isolated/exmples_httproute_rewrite_test.go
  test/internal/testlabels/labels.go
Labels: area/gateway-api, size/L

#5867 chore: remove -s -w ldflags from debug build
  Makefile
Labels: size/XS

#5841 add workflow to trigger "validate kong image" from issue label
  .github/workflows/validate_kong_image_trigger_via_label.yaml
Labels: area/ci, size/L

#5871 fix: add runs-on to `check-and-remove-issue-label`
  .github/workflows/validate_kong_image_trigger_via_label.yaml
Labels: area/ci, size/XS

#5872 chore: add mise logs in CI
  .github/workflows/_conformance_tests.yaml
  .github/workflows/_e2e_tests.yaml
  .github/workflows/_integration_tests.yaml
  .github/workflows/_kongintegration_tests.yaml
  .github/workflows/_linters.yaml
  .github/workflows/_performance_tests.yaml
  .github/workflows/_unit_tests.yaml
  Makefile
Labels: area/ci, size/M

#5873 tests: disable controller manager graceful shutdown timeout
  internal/manager/config.go
  internal/util/test/controller_manager.go
  test/conformance/suite_test.go
  test/e2e/istio_test.go
  test/integration/isolated/suite_test.go
  test/integration/suite_test.go
Labels: area/tests, size/M

#5870 tests: fix free ports assignment
  test/helpers/ports.go
  test/helpers/ports_test.go
Labels: area/tests, size/M

#5863 test(conformance): upgrade gwapi version
  .github/workflows/_linters.yaml
  config/crd/bases/configuration.konghq.com_kongupstreampolicies.yaml
  go.mod
  go.sum
  test/conformance/gateway_conformance_test.go
  test/conformance/suite_test.go
  test/consts/zz_generated_gateway.go
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
Labels: area/gateway-api, size/L, kind/conformance

#5877 chore: remove flaky HTTPRoute list benchmark
  internal/store/store_test.go
Labels: area/tests, test-flake, size/XS

#5894 feat: enforce KongConsumer's credentials and consumerGroups uniqueness
  CHANGELOG.md
  config/crd/bases/configuration.konghq.com_kongconsumers.yaml
  internal/admission/validator.go
  internal/admission/validator_test.go
  pkg/apis/configuration/v1/kongconsumer_types.go
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
  test/envtest/crds_envtest_test.go
Labels: size/L, area/CRD

#5905 backport: upgrade golang to latest patch of go 1.21 in release/3.1.x
  Dockerfile
  Dockerfile.debug
  go.mod
  third_party/go.mod
  third_party/skaffold/go.mod
Labels: size/S

#5910 chore: use specific version of go in go.mods
  go.mod
  third_party/go.mod
Labels: area/maintenance, size/XS

#5919 fix: remove check of parentRef group and kind in validating HTTPRoutes
  CHANGELOG.md
  internal/admission/validation/gateway/httproute.go
  internal/admission/validation/gateway/httproute_test.go
Labels: size/M, backport release/3.1.x

#5917 backprt: bump golang to 1.21.9 in 3.0.x
  Dockerfile
  Dockerfile.debug
  go.mod
  third_party/go.mod
Labels: size/S

#5909 chore: improve docstring for ExtractClientCertificates and other tweaks
  internal/util/tls/tls_cert.go
Labels: area/debt, area/maintenance, size/S

#5916 backport: bump golang to 1.21.9 in 2.12.x
  Dockerfile
  Dockerfile.debug
  go.mod
  third_party/go.mod
Labels: size/S

#5939 [backport release/3.1.x] fix: remove check of parentRef group and kind in validating HTTPRoutes
  CHANGELOG.md
  internal/admission/validation/gateway/httproute.go
  internal/admission/validation/gateway/httproute_test.go
Labels: size/M, fix

#5920 Prepare release/3.1.4
  CHANGELOG.md
Labels: area/release, size/M

#5856 feat(creds) remove kongCredType field support
  CHANGELOG.md
  config/default/kustomization.yaml
  config/webhook/additional_secret_hooks.yaml
  config/webhook/kustomization.yaml
  config/webhook/manifests.yaml
  internal/admission/handler.go
  internal/admission/handler_test.go
  internal/admission/validation/consumers/credentials/validation.go
  internal/admission/validation/consumers/credentials/validation_test.go
  internal/admission/validation/consumers/credentials/vars.go
  internal/admission/validator.go
  internal/admission/validator_test.go
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/kongstate_test.go
  internal/labels/labels.go
  internal/util/credential.go
  internal/util/credential_test.go
  internal/util/types_test.go
  test/envtest/admission_webhook.go
  test/envtest/admission_webhook_envtest_test.go
  test/envtest/kongstate_consumer_failures_test.go
  test/integration/consumer_group_test.go
  test/integration/consumer_test.go
Labels: size/XL

#5947 bump golang.org/x/net and google.golang.org/protobuf in KIC 2.12
  go.mod
  go.sum
  third_party/go.mod
  third_party/go.sum
Labels: size/M

#5948 bump golang.org/x/net and google.golang.org/protobuf in KIC 3.0
  go.mod
  go.sum
  third_party/go.mod
  third_party/go.sum
Labels: size/M

#5945 chore(docs) add 3.1.4 changelog to main
  CHANGELOG.md
Labels: size/S

#5953 add 2.12.4 changelog entries
  CHANGELOG.md
Labels: size/S
