Repository Kong/kubernetes-ingress-controller, pull requests merged in 2024-01, with the labels that each got.

#5379 chore: encapsulate ServiceBackend
  internal/dataplane/kongstate/service_backend.go
  internal/dataplane/kongstate/types.go
  internal/dataplane/translator/backendref.go
  internal/dataplane/translator/golden_test.go
  internal/dataplane/translator/ingressrules.go
  internal/dataplane/translator/ingressrules_test.go
  internal/dataplane/translator/subtranslator/ingress.go
  internal/dataplane/translator/subtranslator/ingress_atc_test.go
  internal/dataplane/translator/subtranslator/ingress_test.go
  internal/dataplane/translator/translate_grpcroute_test.go
  internal/dataplane/translator/translate_httproute_test.go
  internal/dataplane/translator/translate_ingress.go
  internal/dataplane/translator/translate_ingress_test.go
  internal/dataplane/translator/translate_kong_l4.go
  internal/dataplane/translator/translate_tcproute_test.go
  internal/dataplane/translator/translate_tlsroute_test.go
  internal/dataplane/translator/translate_udproute_test.go
  internal/dataplane/translator/translate_utils_test.go
  internal/dataplane/translator/translator.go
  internal/util/builder/kongstateservicebackend.go
Labels: area/maintenance, size/XXL

#5391 fix: remove check of namespace in generating translation failures
  internal/dataplane/failures/failures.go
  internal/dataplane/failures/failures_test.go
Labels: size/XS, area/observability

#5401 fix: add workspace in FillIDs
  CHANGELOG.md
  go.mod
  go.sum
  internal/dataplane/configfetcher/config_fetcher.go
  internal/dataplane/configfetcher/config_fetcher_test.go
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/kongstate_test.go
  internal/dataplane/translator/golden_test.go
  internal/dataplane/translator/translator.go
  internal/dataplane/translator/translator_test.go
  internal/manager/run.go
Labels: size/M

#5420 docs: Add CHANGELOG for v3.0.2
  CHANGELOG.md
Labels: size/S

#5419 docs: update CHANGELOG
  CHANGELOG.md
Labels: size/XS

#5417 fix: properly detect UpstreamPolicy conflict in HTTPRoutes
  internal/controllers/configuration/kongupstreampolicy_utils.go
  internal/controllers/configuration/kongupstreampolicy_utils_test.go
Labels: size/L, fix

#5426 chore: do not announce expressions router as default in changelog
  CHANGELOG.md
Labels: area/docs, size/XS, backport release/3.0.x

#5436 chore: isolate third_party/skaffold module
  Makefile
  third_party/go.mod
  third_party/go.sum
  third_party/skaffold/go.mod
  third_party/skaffold/go.sum
  third_party/skaffold/skaffold.go
Labels: size/XXL

#5438 fix: support ConsumerGroups in KongRawStateToKongState
  CHANGELOG.md
  internal/dataplane/configfetcher/kongrawstate.go
  internal/dataplane/configfetcher/kongrawstate_test.go
Labels: size/M, fix

#5428 feat: support populating KongUpstreamPolicy status for ServiceFacade
  CHANGELOG.md
  internal/controllers/configuration/kongupstreampolicy_controller.go
  internal/controllers/configuration/kongupstreampolicy_utils.go
  internal/controllers/configuration/kongupstreampolicy_utils_test.go
  internal/manager/controllerdef.go
Labels: area/feature, size/XL

#5392 fix: fix refChecker when namespace is specified and is the same as route's namespace
  CHANGELOG.md
  internal/dataplane/translator/backendref.go
  internal/dataplane/translator/backendref_test.go
  internal/dataplane/translator/translate_grpcroute_test.go
  internal/dataplane/translator/translate_httproute_test.go
  internal/dataplane/translator/translate_tcproute_test.go
  internal/dataplane/translator/translate_tlsroute_test.go
  internal/dataplane/translator/translate_udproute_test.go
  internal/dataplane/translator/translate_utils.go
  internal/dataplane/translator/translate_utils_test.go
  internal/dataplane/translator/wrappers_refchecker.go
  internal/dataplane/translator/wrappers_refchecker_test.go
Labels: area/gateway-api, size/XL

#5435 feat: translate only one if multiple KongVaults with the same spec.prefix
  CHANGELOG.md
  config/crd/bases/configuration.konghq.com_kongvaults.yaml
  docs/api-reference.md
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/kongstate_test.go
  pkg/apis/configuration/v1alpha1/kong_vault_types.go
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
  test/envtest/crds_envtest_test.go
Labels: area/feature, size/L, area/CRD

#5412 feat: add uniqueness check of spec.prefix of KongVault
  CHANGELOG.md
  internal/admission/validator.go
  internal/admission/validator_test.go
  internal/dataplane/kongstate/kongstate.go
  test/integration/webhook_test.go
Labels: size/L

#5405 feat: add new flag to reconcile one specific Gateway only
  CHANGELOG.md
  docs/cli-arguments.md
  internal/controllers/controller.go
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/grpcroute_controller.go
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/route_utils.go
  internal/controllers/gateway/route_utils_test.go
  internal/controllers/gateway/tcproute_controller.go
  internal/controllers/gateway/tlsroute_controller.go
  internal/controllers/gateway/udproute_controller.go
  internal/manager/config.go
  internal/manager/config_validation_test.go
  internal/manager/controllerdef.go
  test/envtest/run.go
  test/envtest/specific_gateway_envtest_test.go
Labels: size/L

#5454 chore(deps): bump go in go.mod to 1.21.6
  go.mod
Labels: dependencies, size/XS

#5452 feat: allow multiple subscribers on single GVK status updates
  internal/util/kubernetes/object/status/queue.go
  internal/util/kubernetes/object/status/queue_test.go
Labels: size/M

#5444 feat: add Programmed condition to KongUpstreamPolicy ancestors status
  CHANGELOG.md
  internal/controllers/configuration/kongupstreampolicy_controller.go
  internal/controllers/configuration/kongupstreampolicy_utils.go
  internal/controllers/configuration/kongupstreampolicy_utils_test.go
  internal/controllers/dataplane.go
  internal/dataplane/translator/ingressrules.go
  internal/dataplane/translator/translator_test.go
  internal/manager/controllerdef.go
Labels: size/L

#5450 tests: integrate populating UpstreamPolicy's ancestors status
  test/integration/isolated/kongupstreampolicy_test.go
  test/internal/testlabels/labels.go
Labels: size/L

#5243 feat: add support for HTTPRouteTimeoutBackendRequest
  CHANGELOG.md
  internal/admission/validation/gateway/httproute.go
  internal/admission/validation/gateway/httproute_test.go
  internal/dataplane/translator/translate_httproute.go
  internal/dataplane/translator/translate_httproute_test.go
  test/conformance/gateway_conformance_test.go
Labels: area/gateway-api, release/not-required, size/L

#5484 simpler performance testing
  .github/workflows/_performance_tests.yaml
  .github/workflows/performance_targeted.yaml
  .github/workflows/performance_trigger_via_label.yaml
  Makefile
  test/e2e/helpers_test.go
  test/e2e/kustomizations_test.go
  test/e2e/performance_basic_test.go
  test/e2e/utils_test.go
Labels: area/tests, size/L

#5477 fix: remove stale parent statuses from HTTPRoute
  CHANGELOG.md
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/httproute_controller_test.go
  test/envtest/httproute_controller_test.go
Labels: size/L

#5489 feat: allow sanitizing configuration sent to Konnect
  CHANGELOG.md
  FEATURE_GATES.md
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_test.go
  internal/dataplane/kongstate/credentials.go
  internal/dataplane/kongstate/license.go
  internal/dataplane/sendconfig/kong.go
  internal/dataplane/sendconfig/strategy.go
  internal/manager/featuregates/feature_gates.go
  internal/manager/run.go
  test/envtest/telemetry_test.go
Labels: size/L

#5487 define KongLicense CRD
  CHANGELOG.md
  config/crd/bases/configuration.konghq.com_konglicenses.yaml
  docs/api-reference.md
  pkg/apis/configuration/v1alpha1/kong_license_types.go
  pkg/apis/configuration/v1alpha1/zz_generated.deepcopy.go
  pkg/clientset/typed/configuration/v1alpha1/configuration_client.go
  pkg/clientset/typed/configuration/v1alpha1/fake/fake_configuration_client.go
  pkg/clientset/typed/configuration/v1alpha1/fake/fake_konglicense.go
  pkg/clientset/typed/configuration/v1alpha1/generated_expansion.go
  pkg/clientset/typed/configuration/v1alpha1/konglicense.go
Labels: size/L, area/CRD

#5507 test(e2e): set appProtocol to HTTP for kuma tests
  test/e2e/helpers_test.go
Labels: area/kong, area/tests, size/XS

#5503 refactor performance test
  .github/workflows/_performance_tests.yaml
  test/e2e/performance_basic_test.go
Labels: area/tests, size/L
