Repository Kong/kubernetes-ingress-controller, pull requests merged in 2024-08, with the labels that each got.

#6360 feat(log): log duration after sent config successfully to gateway or Konnect
  CHANGELOG.md
  internal/dataplane/sendconfig/sendconfig.go
Labels: area/maintenance, size/XS, area/konnect

#6358 Test(e2e): List entities instead of dump.Get to fetch Kong config in e2e tests
  test/e2e/all_in_one_test.go
  test/e2e/helpers_test.go
  test/helpers/ports.go
Labels: area/tests, size/M

#6366 feat(prometheus): Add translation duration metrics
  CHANGELOG.md
  internal/dataplane/kong_client.go
  internal/metrics/prometheus.go
  internal/metrics/prometheus_test.go
  test/envtest/metrics_envtest_test.go
Labels: size/M, area/observability

#6378 chore: bump github.com/kong/go-database-reconciler to v1.14.3
  CHANGELOG.md
  go.mod
  go.sum
Labels: size/M

#6352 Feat(konnect): Start Konnect config syncer to upload config to Konnect in separate loop
  CHANGELOG.md
  docs/cli-arguments.md
  internal/adminapi/client.go
  internal/adminapi/konnect.go
  internal/clients/config_status.go
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_test.go
  internal/konnect/config_synchronizer.go
  internal/konnect/config_synchronizer_test.go
  internal/manager/config.go
  internal/manager/config_validation.go
  internal/manager/config_validation_test.go
  internal/manager/run.go
  internal/manager/setup.go
Labels: size/L

#6387 chore: enable KongCustomEntity feature gate by default
  CHANGELOG.md
  FEATURE_GATES.md
  internal/dataplane/testdata/golden/fallback-config-kong-custom-entities-ee/custom-entities-on_golden.yaml
  internal/dataplane/testdata/golden/fallback-config-kong-custom-entities-ee/custom-entities-on_settings.yaml
  internal/dataplane/testdata/golden/fallback-config-kong-custom-entities-ee/default_golden.yaml
  internal/dataplane/testdata/golden/kong-custom-entity-ee/custom-entities-on_golden.yaml
  internal/dataplane/testdata/golden/kong-custom-entity-ee/custom-entities-on_settings.yaml
  internal/dataplane/testdata/golden/kong-custom-entity-ee/default_golden.yaml
  internal/manager/featuregates/feature_gates.go
  test/envtest/telemetry_test.go
Labels: area/kong, size/L, area/CRD

#6395 fix(controller): Do not update existing Programmed condition to Unknown
  hack/generators/controllers/networking/main.go
  internal/controllers/configuration/zz_generated_controllers.go
  internal/controllers/utils/conditions.go
  internal/controllers/utils/conditions_test.go
Labels: size/S, backport release/2.12.x, backport release/3.2.x

#6399 chore: fix debug.skaffold.konnect makefile target
  Makefile
  config/base/kustomization.yaml
  config/variants/konnect/base/kustomization.yaml
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
Labels: area/maintenance, size/XS

#6403 [Backport release/2.12.x] fix(controller): Do not update existing Programmed condition to Unknown
  hack/generators/controllers/networking/main.go
  internal/controllers/configuration/zz_generated_controllers.go
  internal/controllers/utils/conditions.go
  internal/controllers/utils/conditions_test.go
Labels: size/S

#6400 fix(controller): reconcile secrets having kongCredType in data
  CHANGELOG.md
  internal/controllers/configuration/secret_controller.go
Labels: size/S

#6424 [Backport release/3.2.x] feat: check Gateway pending clients readiness concurrently
  internal/clients/manager_test.go
  internal/clients/readiness.go
  internal/clients/readiness_test.go
Labels: size/L

#6413 update changelog for release 3.2.4
  CHANGELOG.md
Labels: size/S

#6422 update changelog for 2.12.6
  CHANGELOG.md
Labels: size/XS

#6427 chore(changelog): Add changelog entries for 3.2.4 and 2.12.6
  CHANGELOG.md
Labels: size/M

#6434 Feat(gateway discovery): Add config for gateway readiness check intervals and timeouts
  CHANGELOG.md
  docs/cli-arguments.md
  internal/clients/manager.go
  internal/clients/readiness.go
  internal/clients/readiness_test.go
  internal/manager/config.go
  internal/manager/config_validation.go
  internal/manager/config_validation_test.go
  internal/manager/run.go
Labels: size/L

#6421 Fix(controller): Stop reconcilication if KongUpstreamPolicy not referred in reconciled Ingress/HTTPRoute
  CHANGELOG.md
  internal/controllers/configuration/kongupstreampolicy_controller.go
  internal/controllers/configuration/kongupstreampolicy_controller_test.go
  internal/controllers/configuration/kongupstreampolicy_utils.go
  internal/controllers/gateway/grpcroute_controller.go
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/route_predicates.go
  internal/controllers/gateway/tcproute_controller.go
  internal/controllers/gateway/tlsroute_controller.go
  internal/controllers/gateway/udproute_controller.go
  internal/manager/controllerdef.go
  test/envtest/kongupstreampolicy_test.go
  test/envtest/setup.go
Labels: size/XL

#6445 test: add integration test for dbmode strategy
  go.mod
  go.sum
  internal/dataplane/sendconfig/dbmode.go
  internal/dataplane/sendconfig/error_handling.go
  internal/dataplane/sendconfig/inmemory_error_handling.go
  test/envtest/configerrorevent_envtest_test.go
  test/kongintegration/containers/kong.go
  test/kongintegration/containers/kong_postgres.go
  test/kongintegration/dbmode_update_strategy_test.go
Labels: area/tests, size/L

#6451 chore(release): prepare 3.3.0 release
  CHANGELOG.md
  config/image/oss/kustomization.yaml
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
Labels: size/XS

#6452 chore(docs): Add the compare link in Changelog
  CHANGELOG.md
Labels: size/XS

#6453 Chore(changelog): add highlight items for KIC 3.3
  CHANGELOG.md
Labels: size/S

#6460 chore: prepare 3.3.1 release
  CHANGELOG.md
Labels: area/release, size/XS

#6459 chore(ci): make PR checks workflow runnable for external contributors
  .github/workflows/_e2e_tests.yaml
  .github/workflows/_envtest_tests.yaml
  .github/workflows/_integration_tests.yaml
  .github/workflows/_kongintegration_tests.yaml
  .github/workflows/_permission_check.yaml
  .github/workflows/_test_reports.yaml
  .github/workflows/checks.yaml
  .github/workflows/e2e_trigger_via_label.yaml
Labels: area/debt, area/ci, size/L

#6461 chore: update changelog for 3.3.1
  CHANGELOG.md
Labels: area/release

#6462 chore(ci): remove redundant pull_request trigger and fix e2e trigger (#6462)
  .github/workflows/checks.yaml
  .github/workflows/e2e_trigger_via_label.yaml
Labels: area/ci, area/maintenance, size/XS

#6450 chore(tests): migrate TestTCPIngressEssentials to isolated
  test/integration/isolated/tcpingress_test.go
  test/integration/tcpingress_test.go
Labels: size/L

#6467 chore(ci): make dependabot and renovate trusted for CI
  .github/workflows/_permission_check.yaml
Labels: area/ci, area/maintenance, size/XS
