Repository Kong/kubernetes-ingress-controller, pull requests merged in 2024-11, with the labels that each got.

#6617 refactor: do not allocate for SanitizedCopy()
  internal/dataplane/kongstate/consumer.go
  internal/dataplane/kongstate/consumer_test.go
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/kongstate_test.go
  internal/dataplane/kongstate/license.go
  internal/dataplane/kongstate/types.go
  internal/dataplane/kongstate/types_test.go
Labels: refactor, size/L

#6622 chore(ci): remove EOLd k8s versions (1.27 and 1.28) from e2e test matrix
  .github/test_dependencies.yaml
Labels: area/tests, size/XS

#6623 docs(release): improve task about retro in release issue template
  .github/ISSUE_TEMPLATE/release.yaml
Labels: size/XS

#6624 tests: fix data race in TestSpecificGatewayNN
  test/envtest/specific_gateway_envtest_test.go
Labels: area/tests, size/XS

#6621 chore(ci): migrate actions/upload-artifact and actions/download-artifact to v4
  .github/workflows/_conformance_tests.yaml
  .github/workflows/_docker_build.yaml
  .github/workflows/_e2e_tests.yaml
  .github/workflows/_integration_tests.yaml
  .github/workflows/_kongintegration_tests.yaml
  .github/workflows/_performance_tests.yaml
  .github/workflows/_unit_tests.yaml
  .github/workflows/conformance_tests_report.yaml
  .github/workflows/performance_nightly.yaml
  .github/workflows/performance_targeted.yaml
  .github/workflows/test_nightly.yaml
Labels: area/ci, size/L

#6625 tests: fix data race in KongUpstreamPolicy envtest tests
  test/envtest/kongupstreampolicy_test.go
Labels: area/tests, test-flake, size/M

#6636 chore(ci): fix conformance test reports re-using the same artifact name
  .github/workflows/_conformance_tests.yaml
Labels: area/ci, size/S

#6638 chore(ci): fix typo in conformance report artifact name
  .github/workflows/_conformance_tests.yaml
Labels: area/ci, size/XS

#6620 konnect: use sdk-konnect-go for ControlPlanes
  .golangci.yaml
  go.mod
  go.sum
  hack/cleanup/konnect_control_planes.go
  internal/konnect/controlplanes/client.go
  internal/konnect/controlplanes/client_test.go
  internal/konnect/controlplanesconfig/client.go
  internal/konnect/controlplanesconfig/client_test.go
  internal/konnect/sdk/sdk.go
  internal/manager/metadata/metadata.go
  test/internal/helpers/konnect/access.go
  test/internal/helpers/konnect/certificates.go
  test/internal/helpers/konnect/control_plane.go
Labels: size/XXL, area/konnect

#6626 fix: annotation konghq.com/rewrite always works
  CHANGELOG.md
  internal/dataplane/translator/subtranslator/ingress.go
  test/integration/ingress_test.go
Labels: size/S, fix

#6652 chore(Makefile): fix target debug.skaffold
  config/variants/multi-gw/debug/kustomization.yaml
Labels: area/maintenance, size/XS

#6651 fix: fix panic in KongUpstreamPolicyReconciler when using with Ingress having a nil HTTP rule
  CHANGELOG.md
  internal/controllers/configuration/kongupstreampolicy_controller.go
  internal/controllers/configuration/kongupstreampolicy_controller_test.go
Labels: size/L, fix

#6661 tests: fix assertions in TestHTTPRouteEssentials
  test/integration/httproute_test.go
Labels: area/tests, test-flake, size/XS

#6668 fix: unbreak main workflows
  .github/workflows/_conformance_tests.yaml
  .github/workflows/_docker_build.yaml
  .github/workflows/_unit_tests.yaml
  internal/dataplane/kongstate/credentials_conflicts.go
  internal/dataplane/kongstate/credentials_conflicts_test.go
Labels: size/S

#6666 chore: fix konnect cleanup
  hack/cleanup/konnect_control_planes.go
Labels: area/maintenance, size/XS

#6664 feat(metrics): report configuration push size for DB-less mode
  CHANGELOG.md
  internal/dataplane/kong_client_test.go
  internal/dataplane/sendconfig/backoff_strategy.go
  internal/dataplane/sendconfig/backoff_strategy_test.go
  internal/dataplane/sendconfig/dbmode.go
  internal/dataplane/sendconfig/errors.go
  internal/dataplane/sendconfig/errors_test.go
  internal/dataplane/sendconfig/inmemory.go
  internal/dataplane/sendconfig/inmemory_test.go
  internal/dataplane/sendconfig/sendconfig.go
  internal/dataplane/sendconfig/strategy.go
  internal/konnect/config_synchronizer_test.go
  internal/metrics/prometheus.go
  internal/metrics/prometheus_test.go
  test/envtest/metrics_envtest_test.go
  test/kongintegration/dbmode_update_strategy_test.go
  test/kongintegration/inmemory_update_strategy_test.go
  test/kongintegration/kong_client_golden_tests_outputs_test.go
  test/kongintegration/kongupstreampolicy_test.go
Labels: area/feature, area/metrics, size/L

#6644 refactor: use plugin annotation types from kubernetes-configuration
  internal/annotations/annotations.go
  internal/annotations/annotations_test.go
  internal/dataplane/fallback/graph_dependencies_common.go
  internal/dataplane/kongstate/customentity.go
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/kongstate_test.go
  internal/util/objectmeta.go
Labels: area/maintenance, refactor, size/L

#6665 fix: fix panic when handling KongConsumer without username
  CHANGELOG.md
  examples/kong-consumer-key-auth.yaml
  internal/dataplane/deckgen/consumer_cmp.go
  internal/dataplane/deckgen/consumer_cmp_test.go
  internal/dataplane/deckgen/generate.go
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/kongstate_test.go
  internal/dataplane/testdata/golden/consumer-group-example-ee/default_golden.yaml
  internal/dataplane/testdata/golden/kongconsumer-with-custom-id/default_golden.yaml
  internal/dataplane/testdata/golden/kongconsumer-with-custom-id/expression-routes-on_golden.yaml
  internal/dataplane/testdata/golden/kongconsumer-with-custom-id/expression-routes-on_settings.yaml
  internal/dataplane/testdata/golden/kongconsumer-with-custom-id/in.yaml
Labels: size/L, fix

#6627 chore: generate api docs from kubernetes-configuration repo
  docs/api-reference.md
  docs/incubator-api-reference.md
  go.mod
  go.sum
  scripts/apidocs-gen/config.yaml
  scripts/apidocs-gen/generate.sh
  scripts/apidocs-gen/template/gv_details.tpl
  scripts/apidocs-gen/template/type.tpl
Labels: area/docs, size/M, area/CRD

#6674 chore: remove unused code
  internal/admission/validation/consumers/credentials/validation.go
  internal/admission/validation/consumers/credentials/validation_test.go
Labels: size/M

#6683 chore: generate kustomization files for crds
  Makefile
  config/crd/incubator/kustomization.yaml
  config/crd/kustomization.yaml
  renovate.json
  scripts/generate-crd-kustomize.sh
Labels: area/maintenance, size/M

#6673 chore: add more logs data when unparsable Gateway API error is received
  internal/dataplane/deckgen/deckgen.go
  internal/dataplane/sendconfig/inmemory_error_handling.go
  internal/dataplane/sendconfig/inmemory_error_handling_test.go
Labels: area/maintenance, size/L

#6684 chore(Makefile): fix target debug.skaffold
  config/variants/multi-gw/debug/kustomization.yaml
Labels: area/maintenance, size/XS

#6686 chore: let renovate handle kconf go.mod updates
  .github/dependabot.yml
  .github/workflows/regenerate_on_deps_bump.yaml
  renovate.json
Labels: dependencies, area/maintenance, size/M

#6687 fix(log): false positive `No targets found to create upstream ...`
  CHANGELOG.md
  internal/dataplane/translator/translate_upstreams.go
Labels: area/maintenance, size/S, fix

#6690 feat: handle CP refs in Consumer, ConsumerGroup and Vault reconcilers
  CHANGELOG.md
  hack/generators/controllers/networking/main.go
  internal/controllers/configuration/zz_generated_controllers.go
  internal/controllers/utils/control_plane_reference.go
  internal/controllers/utils/control_plane_reference_test.go
  test/envtest/consts.go
  test/envtest/control_plane_reference_test.go
  test/envtest/konglicense_controller_test.go
Labels: area/feature, size/L

#6693 tests: fix TestAdmissionWebhook by using Eventually()
  test/envtest/admission_webhook_envtest_test.go
Labels: area/tests, test-flake, size/S

#6689 fix: fix Kong client's status check
  CHANGELOG.md
  internal/adminapi/kong.go
  internal/adminapi/kong_test.go
  internal/dataplane/configfetcher/config_fetcher.go
  internal/dataplane/configfetcher/config_fetcher_test.go
Labels: size/L

#6692 fix(log): do not log errors when parentRef kind is not Gateway
  CHANGELOG.md
  internal/controllers/gateway/route_predicate_test.go
  internal/controllers/gateway/route_predicates.go
Labels: size/L

#6701 chore: use generated ValidatingWebhookConfiguration in integration tests
  test/envtest/admission_webhook.go
  test/envtest/admission_webhook_envtest_test.go
  test/helpers/webhook/webhook.go
  test/integration/admission_webhook_helpers_test.go
  test/integration/gateway_webhook_test.go
  test/integration/httproute_webhook_test.go
  test/integration/ingress_webhook_test.go
  test/integration/kongingress_webhook_test.go
Labels: area/debt, area/tests, area/maintenance, size/L

#6695 chore: add KONG_CUSTOM_DOMAIN handling with sdk-konnect-go 0.1.7
  .github/workflows/cleanup.yaml
  go.mod
  go.sum
  hack/cleanup/konnect_control_planes.go
Labels: area/ci, size/S, area/konnect

#6657 chore: bump go-kong to v0.56.0
  CHANGELOG.md
  Dockerfile
  Dockerfile.debug
  go.mod
  go.sum
  internal/controllers/gateway/route_utils.go
  internal/dataplane/kongstate/kongstate.go
  third_party/go.mod
  third_party/go.sum
Labels: size/L

#6719 chore: update changelog for 2.12.7
  CHANGELOG.md
Labels: size/XS

#6721 chore(generators): make file naming uniform zz_generated.*
  .gitattributes
  Makefile
  hack/generators/cache-stores/templates.go
  hack/generators/controllers/networking/main.go
  internal/controllers/configuration/zz_generated.controllers.go
  internal/store/zz_generated.cache_stores.go
  internal/store/zz_generated.cache_stores_test.go
  test/consts/zz_generated.gateway.go
Labels: area/maintenance, size/S

#6729 feat: improve robustness of extracting comma-delimited annotations
  CHANGELOG.md
  internal/annotations/annotations.go
  internal/annotations/annotations_test.go
  internal/dataplane/kongstate/route.go
Labels: area/maintenance, size/L

#6742 chore: sync 2.12.7 changelog
  CHANGELOG.md
Labels: size/XS

#6743 chore(ci): use pull_request instead of pull_request_target
  .github/workflows/_conformance_tests.yaml
  .github/workflows/_docker_build.yaml
  .github/workflows/_e2e_tests.yaml
  .github/workflows/_envtest_tests.yaml
  .github/workflows/_integration_tests.yaml
  .github/workflows/_kongintegration_tests.yaml
  .github/workflows/_linters.yaml
  .github/workflows/_test_reports.yaml
  .github/workflows/_unit_tests.yaml
  .github/workflows/backport.yaml
  .github/workflows/check_pr_labels.yaml
  .github/workflows/checks.yaml
  .github/workflows/e2e_trigger_via_label.yaml
Labels: area/ci, size/M

#6746 chore(HTTPRoute): change level from ERROR to DEBUG for missing backend and enhance status
  CHANGELOG.md
  internal/controllers/gateway/httproute_controller.go
  internal/dataplane/translator/backendref.go
Labels: area/debt, size/M
