Repository Kong/kubernetes-ingress-controller, pull requests merged in 2024-02, with the labels that each got.

#5515 Release checklist update - support policy markdown has new location
  .github/ISSUE_TEMPLATE/release.yaml
Labels: size/XS

#5519 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: size/XS

#5562 tests: pin Kuma version in E2E tests
  .github/test_dependencies.yaml
  go.mod
  go.sum
  test/e2e/helpers_test.go
  test/e2e/kuma_test.go
Labels: area/tests, dependencies, size/L

#5514 feat: implement KongLicense controller and inject to translator
  CHANGELOG.md
  config/crd/bases/configuration.konghq.com_konglicenses.yaml
  config/crd/kustomization.yaml
  config/rbac/role.yaml
  docs/cli-arguments.md
  internal/controllers/configuration/konglicense_controller.go
  internal/manager/config.go
  internal/manager/run.go
  internal/manager/setup.go
  pkg/apis/configuration/v1alpha1/kong_license_types.go
  pkg/clientset/typed/configuration/v1alpha1/configuration_client.go
  pkg/clientset/typed/configuration/v1alpha1/fake/fake_configuration_client.go
  pkg/clientset/typed/configuration/v1alpha1/fake/fake_konglicense.go
  pkg/clientset/typed/configuration/v1alpha1/konglicense.go
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
  test/integration/isolated/license_test.go
  test/integration/isolated/skip.go
  test/internal/helpers/kong.go
  test/internal/testlabels/labels.go
Labels: area/feature, release/required, size/XL, area/CRD

#5573 feat: enable Konnect config dumps sanitization by default
  CHANGELOG.md
  FEATURE_GATES.md
  internal/manager/featuregates/feature_gates.go
  test/envtest/telemetry_test.go
Labels: size/S

#5569 test: Add unit tests and envtest tests for KongLicense controller
  .github/workflows/_integration_tests.yaml
  internal/controllers/configuration/konglicense_controller_test.go
  test/envtest/konglicense_controller_test.go
Labels: area/tests, size/L, area/CRD

#5581 fix: don't populate fields disallowed for expressions router in Konnect
  CHANGELOG.md
  go.mod
  go.sum
  test/kongintegration/translator_golden_tests_outputs_test.go
Labels: size/S, fix

#5582 chore: prepare release 3.1.0
  CHANGELOG.md
  LICENSES
  config/image/oss/kustomization.yaml
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
Labels: size/XXL, backport release/3.1.x

#5580 test(perf): Reduce time consumption by using batch writing.
  .github/workflows/_performance_tests.yaml
  .github/workflows/performance_nightly.yaml
  .github/workflows/performance_targeted.yaml
  test/e2e/performance_basic_test.go
Labels: size/L

#5588 chore: use depth 0 when checking out repo in performance tests
  .github/workflows/performance_targeted.yaml
  .github/workflows/performance_trigger_via_label.yaml
Labels: area/ci, area/maintenance, size/XS

#5587 fix: typo in performance nightly workflow
  .github/workflows/performance_nightly.yaml
Labels: area/tests, size/XS

#5609 chore(refactor): make KongLicense controller importable
  .golangci.yaml
  Dockerfile
  Dockerfile.debug
  Makefile
  controllers/license/konglicense_controller.go
  controllers/license/konglicense_controller_test.go
  go.mod
  go.sum
  internal/manager/setup.go
  test/envtest/konglicense_controller_test.go
Labels: refactor, size/M

#5589 chore: link to guides in KIC 3.1 highlights
  CHANGELOG.md
Labels: size/S

#5611 chore(docs): split CRDs and other types into sections in reference
  docs/api-reference.md
  docs/incubator-api-reference.md
  scripts/apidocs-gen/post-process-for-konghq.sh
  scripts/apidocs-gen/template/gv_details.tpl
  scripts/apidocs-gen/template/type.tpl
Labels: area/docs, size/S

#5637 chore(docs): update release template with bumping charts' deps
  .github/ISSUE_TEMPLATE/release.yaml
Labels: area/docs, size/XS

#5636 feat: add path segment field and not operator in atc translator
  internal/dataplane/translator/atc/expression_test.go
  internal/dataplane/translator/atc/field.go
  internal/dataplane/translator/atc/matcher.go
  internal/dataplane/translator/atc/predicate.go
Labels: size/L

#5640 fix: do not translate licenses if Kong gateway is not enterprise edition
  CHANGELOG.md
  internal/dataplane/translator/translator.go
  internal/dataplane/translator/translator_test.go
  internal/manager/run.go
Labels: size/M

#5641 chore(ci) fix CLI doc generator
  scripts/cli-arguments-docs-gen/post-process-for-konghq.sh
Labels: size/XS

#5618 feat(license): add ability to validate KongLicense
  controllers/license/konglicense_controller.go
  internal/manager/setup.go
  test/envtest/konglicense_controller_test.go
Labels: size/L

#5643 test(integration): add postgres in isolated integration tests
  .github/workflows/_integration_tests.yaml
  Makefile
  test/integration/isolated/license_test.go
  test/integration/isolated/skip.go
  test/integration/isolated/suite_test.go
Labels: area/tests, size/S

#5642 fix(controllers) skip routes bound to excluded GWs
  CHANGELOG.md
  internal/controllers/gateway/route_utils.go
  internal/controllers/gateway/route_utils_test.go
Labels: size/L

#5659 chore: generate validating webhook config using controller-gen
  Makefile
  config/webhook/manifests.yaml
  internal/admission/handler.go
  test/envtest/admission_webhook.go
  test/envtest/admission_webhook_envtest_test.go
Labels: size/L, area/admission, backport release/3.1.x

#5663 chore: improve naming in package certificate
  test/helpers/certificate/certificate.go
Labels: area/maintenance, size/S

#5662 feat: managed gateways config pushed when accepted
  CHANGELOG.md
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gateway_controller_test.go
  internal/controllers/gateway/gateway_utils.go
  internal/controllers/gateway/gatewayclass_controller.go
Labels: size/L, backport release/3.1.x

#5665 backport PRs to release/3.1.x
  .github/test_dependencies.yaml
  CHANGELOG.md
  Makefile
  config/webhook/manifests.yaml
  internal/admission/handler.go
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gateway_controller_test.go
  internal/controllers/gateway/gateway_utils.go
  internal/controllers/gateway/gatewayclass_controller.go
  internal/controllers/gateway/route_utils.go
  internal/controllers/gateway/route_utils_test.go
  test/envtest/admission_webhook.go
  test/envtest/admission_webhook_envtest_test.go
  test/envtest/kong.go
  test/envtest/log.go
  test/envtest/run.go
  test/integration/webhook_test.go
  test/kongintegration/containers/kong.go
Labels: size/XXL

#5669 fix: notBefore and notAfter changed in CA test
  test/helpers/certificate/certificate.go
Labels: size/XS

#5668 chore: prepare release 3.1.1
  CHANGELOG.md
Labels: size/S, backport release/3.1.x
