Repository Kong/kubernetes-ingress-controller, pull requests merged in 2024-05, with the labels that each got.

#5969 fix: add GH_TOKEN in editing issue labels
  .github/workflows/validate_kong_image_trigger_via_label.yaml
Labels: size/XS

#5970 chore: switch log level for Konnect sync backoff to info
  internal/dataplane/kong_client.go
Labels: size/XS

#5895 feat: implement rewrite path prefix filter for HTTPRoute in traditional router mode
  .github/workflows/_integration_tests.yaml
  CHANGELOG.md
  examples/gateway-httproute-rewrite-path.yaml
  go.mod
  internal/admission/validation/gateway/httproute.go
  internal/admission/validation/gateway/httproute_test.go
  internal/dataplane/translator/subtranslator/httproute.go
  internal/dataplane/translator/subtranslator/httproute_atc.go
  internal/dataplane/translator/subtranslator/httproute_test.go
  internal/dataplane/translator/testdata/golden/httproute-url-rewrite-path-prefix/default_golden.yaml
  internal/dataplane/translator/testdata/golden/httproute-url-rewrite-path-prefix/in.yaml
  internal/dataplane/translator/translate_httproute.go
  internal/dataplane/translator/translate_httproute_test.go
  test/conformance/gateway_conformance_test.go
  test/integration/isolated/examples_httproute_rewrite_test.go
  third_party/go.mod
Labels: area/feature, area/gateway-api, size/XL

#5972 feat(validation): reject Ingress, Service and KongConsumer with many plugins of the same type attached
  CHANGELOG.md
  internal/admission/handler.go
  internal/admission/handler_test.go
  internal/admission/server_test.go
  internal/admission/validation/ingress/ingress.go
  internal/admission/validation/ingress/ingress_test.go
  internal/admission/validation/kongplugin/kongplugin.go
  internal/admission/validator.go
  internal/admission/validator_test.go
  internal/util/builder/ingress.go
Labels: area/feature, size/L, area/admission

#5940 feat: implement rewrite path prefix filter for HTTPRoute in expressions router mode
  CHANGELOG.md
  internal/dataplane/translator/subtranslator/httproute.go
  internal/dataplane/translator/subtranslator/httproute_test.go
  internal/dataplane/translator/testdata/golden/httproute-url-rewrite-path-prefix/expression-routes-on_golden.yaml
  internal/dataplane/translator/testdata/golden/httproute-url-rewrite-path-prefix/expression-routes-on_settings.yaml
  test/conformance/gateway_conformance_test.go
  test/integration/isolated/examples_httproute_rewrite_test.go
Labels: area/gateway-api, size/L

#5977 feat: introduce konghq.com/headers-separator annotation and make parsing more robust
  CHANGELOG.md
  internal/annotations/annotations.go
  internal/annotations/annotations_test.go
Labels: size/M

#5971 chore: add checkout step to each job in trigger kong image test workflow
  .github/workflows/validate_kong_image_trigger_via_label.yaml
Labels: area/ci, size/S

#5993 feat: take cache snapshot before building configuration
  CHANGELOG.md
  Makefile
  hack/generators/cache-stores-snapshot/main.go
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_test.go
  internal/dataplane/sendconfig/kong.go
  internal/dataplane/translator/translator.go
  internal/dataplane/translator/translator_test.go
  internal/manager/featuregates/feature_gates.go
  internal/manager/run.go
  internal/store/cache_stores.go
  internal/store/cache_stores_snapshot_test.go
  internal/store/fake_store.go
  internal/store/store.go
  internal/store/store_test.go
  internal/store/zz_generated_cache_stores_snapshot.go
  test/envtest/telemetry_test.go
Labels: area/feature, size/L

#5983 suggestion: inject uuid generator
  internal/dataplane/kong_client.go
  internal/dataplane/kongstate/consumer.go
  internal/dataplane/kongstate/consumer_test.go
  internal/dataplane/kongstate/credentials.go
  internal/dataplane/kongstate/credentials_test.go
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/kongstate_test.go
  internal/dataplane/kongstate/plugin_test.go
  internal/util/uuid.go
  test/mocks/uuid.go
Labels: size/M

#5982 feat: define KongCustomEntity CRD
  CHANGELOG.md
  config/crd/bases/configuration.konghq.com_kongcustomentities.yaml
  docs/api-reference.md
  pkg/apis/configuration/v1alpha1/kong_custom_entity_types.go
  pkg/apis/configuration/v1alpha1/zz_generated.deepcopy.go
  pkg/clientset/typed/configuration/v1alpha1/configuration_client.go
  pkg/clientset/typed/configuration/v1alpha1/fake/fake_configuration_client.go
  pkg/clientset/typed/configuration/v1alpha1/fake/fake_kongcustomentity.go
  pkg/clientset/typed/configuration/v1alpha1/generated_expansion.go
  pkg/clientset/typed/configuration/v1alpha1/kongcustomentity.go
Labels: size/L, area/CRD

#5979 feat(validation): reject HTTPRoute and KongConsumerGroup with many plugins of the same type attached
  CHANGELOG.md
  internal/admission/validation/gateway/httproute.go
  internal/admission/validation/gateway/httproute_test.go
  internal/admission/validation/ingress/ingress_test.go
  internal/admission/validator.go
  internal/admission/validator_test.go
  internal/manager/setup_test.go
Labels: area/feature, size/L, area/admission

#5964 fix(konnect) avoid collisions when redacting
  CHANGELOG.md
  internal/dataplane/kong_client.go
  internal/dataplane/kongstate/consumer.go
  internal/dataplane/kongstate/consumer_test.go
  internal/dataplane/kongstate/credentials.go
  internal/dataplane/kongstate/credentials_test.go
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/kongstate_test.go
  internal/util/uuid.go
  test/mocks/uuid.go
Labels: size/M, area/konnect, backport release/3.1.x

#5952 feat(httproute): handle URLRewrite filter's hostname rewrite
  CHANGELOG.md
  internal/dataplane/translator/subtranslator/httproute.go
  internal/dataplane/translator/subtranslator/httproute_atc_test.go
  internal/dataplane/translator/subtranslator/httproute_test.go
  internal/dataplane/translator/translate_httproute_test.go
  test/conformance/gateway_conformance_test.go
Labels: area/gateway-api, size/XL

#5935 chore(dep): group update k8s.io to v0.30.0 and controller-runtime to v0.18.2
  config/crd/bases/configuration.konghq.com_tcpingresses.yaml
  config/crd/bases/configuration.konghq.com_udpingresses.yaml
  controllers/license/konglicense_controller.go
  go.mod
  go.sum
  hack/generators/controllers/networking/main.go
  internal/controllers/configuration/kongadminapi_controller.go
  internal/controllers/configuration/kongupstreampolicy_controller.go
  internal/controllers/configuration/secret_controller.go
  internal/controllers/configuration/zz_generated_controllers.go
  internal/controllers/crds/dynamic_controller.go
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gatewayclass_controller.go
  internal/controllers/gateway/grpcroute_controller.go
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/referencegrant_controller.go
  internal/controllers/gateway/tcproute_controller.go
  internal/controllers/gateway/tlsroute_controller.go
  internal/controllers/gateway/udproute_controller.go
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
Labels: dependencies, size/XXL

#5990 backport(3.1.x): support license with DB backed Kong gateways (#5648)
  CHANGELOG.md
  go.mod
  go.sum
  internal/dataplane/configfetcher/kongrawstate_test.go
  internal/dataplane/sendconfig/dbmode.go
  internal/dataplane/sendconfig/strategy.go
  test/integration/isolated/suite_test.go
Labels: size/M

#5918 feat: bump GWAPI v1.1 and support for GRPCRoute v1
  .github/workflows/_linters.yaml
  CHANGELOG.md
  docs/cli-arguments.md
  go.mod
  go.sum
  internal/controllers/gateway/grpcroute_controller.go
  internal/dataplane/kongstate/upstream.go
  internal/dataplane/translator/translate_grpcroute_test.go
  internal/gatewayapi/aliases.go
  internal/gatewayapi/typemeta.go
  internal/manager/config.go
  internal/manager/controllerdef.go
  internal/store/fake_store.go
  test/conformance/gateway_conformance_test.go
  test/conformance/suite_test.go
  test/consts/zz_generated_gateway.go
  test/envtest/telemetry_test.go
  test/integration/isolated/grpc_test.go
Labels: size/L

#6016 chore: fix mise install in Makefile
  Makefile
Labels: size/XS

#6024 chore(refactor): generate code only for listing stores
  hack/generators/cache-stores-snapshot/main.go
  internal/store/cache_stores_snapshot.go
  internal/store/zz_generated_cache_all_stores.go
  internal/store/zz_generated_cache_stores_snapshot.go
Labels: refactor, size/M

#6027 prepare changelog for 3.0.3
  CHANGELOG.md
Labels: size/S

#6017 feat: make a new snapshot of the store only when it's needed
  internal/store/cache_stores_snapshot.go
  internal/store/cache_stores_snapshot_test.go
Labels: area/feature, size/L

#6028 chore: make store.CacheStores methods generated
  hack/generators/cache-stores-snapshot/main.go
  hack/generators/cache-stores/main.go
  hack/generators/cache-stores/spec.go
  hack/generators/cache-stores/templates.go
  internal/store/cache_key_funcs.go
  internal/store/cache_key_funcs_test.go
  internal/store/cache_stores.go
  internal/store/cache_stores_snapshot.go
  internal/store/cache_stores_test.go
  internal/store/fake_store.go
  internal/store/fake_store_test.go
  internal/store/zz_generated_cache_all_stores.go
  internal/store/zz_generated_cache_stores.go
  internal/store/zz_generated_cache_stores_test.go
Labels: refactor, size/XL

#6029 fix: replace c.listAllStores() with c.ListAllStores()
  internal/store/cache_stores_snapshot.go
Labels: size/XS

#6030 chore(ci): remove warning for deprecated megacheck linter
  .golangci.yaml
Labels: size/XS

#6025 [Backport release/3.1.x] deduplicate nil-weight targets (#5946)
  CHANGELOG.md
  internal/dataplane/translator/translator.go
  test/integration/ingress_test.go
Labels: size/S

#6006 fetch Kong entity schema and validate KongCustomEntity resources
  .github/workflows/_envtest_tests.yaml
  CHANGELOG.md
  config/webhook/manifests.yaml
  go.mod
  go.sum
  internal/admission/adminapi_provider.go
  internal/admission/errors.go
  internal/admission/handler.go
  internal/admission/server_test.go
  internal/admission/validator.go
  internal/admission/validator_test.go
  internal/dataplane/kongstate/customentity.go
  internal/dataplane/kongstate/customentity_test.go
  test/envtest/admission_webhook_envtest_test.go
  test/kongintegration/containers/kong.go
Labels: size/XL, area/CRD, area/admission

#6040 Revert "chore(deps): update istio/istioctl docker tag to v1.22.0"
  .github/test_dependencies.yaml
Labels: area/ci, size/XS

#5965 feat(plugins) allow cross-namespace plugin references
  .golangci.yaml
  CHANGELOG.md
  Makefile
  examples/cross-namespace-plugin-grant.yaml
  internal/annotations/annotations.go
  internal/annotations/annotations_test.go
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/kongstate_test.go
  internal/dataplane/translator/backendref.go
  internal/dataplane/translator/translate_utils.go
  internal/dataplane/translator/translate_utils_test.go
  internal/dataplane/translator/wrappers_refchecker.go
  internal/dataplane/translator/wrappers_refchecker_test.go
  internal/gatewayapi/contraints.go
  internal/gatewayapi/references.go
  test/integration/plugin_test.go
Labels: size/XL

#6050 chore: fix outdated TODO links
  internal/admission/validation/gateway/httproute.go
  internal/admission/validation/gateway/httproute_test.go
  internal/dataplane/fallback/graph_dependencies_kong.go
Labels: area/maintenance, size/S

#6048 feat(dataplane) include licenses with fallback
  CHANGELOG.md
  internal/dataplane/configfetcher/config_fetcher.go
  internal/dataplane/configfetcher/kongrawstate.go
  internal/dataplane/configfetcher/kongrawstate_test.go
  internal/dataplane/translator/translator.go
  internal/license/agent.go
  internal/manager/run.go
  internal/manager/setup.go
Labels: size/L

#6047 feat: generate fallback cache snapshot excluding affected objects
  CHANGELOG.md
  internal/dataplane/fallback/cache_to_graph.go
  internal/dataplane/fallback/cache_to_graph_test.go
  internal/dataplane/fallback/fallback.go
  internal/dataplane/fallback/fallback_test.go
  internal/dataplane/fallback/graph.go
  internal/dataplane/fallback/graph_test.go
  internal/dataplane/fallback/helpers_test.go
Labels: area/feature, size/XXL

#6059 feat: resolve dependencies for Service, KongConsumer and KongConsumerGroup, improve for plugins
  internal/dataplane/fallback/graph_dependencies.go
  internal/dataplane/fallback/graph_dependencies_common.go
  internal/dataplane/fallback/graph_dependencies_kong.go
  internal/dataplane/fallback/graph_dependencies_kong_test.go
  internal/dataplane/fallback/graph_dependencies_service.go
  internal/dataplane/fallback/graph_dependencies_service_test.go
Labels: area/feature, size/L

#6062 feat: resolve dependencies for KongPlugin and KongClusterPlugin
  internal/dataplane/fallback/graph_dependencies_common.go
  internal/dataplane/fallback/graph_dependencies_kong.go
  internal/dataplane/fallback/graph_dependencies_kong_test.go
  internal/dataplane/fallback/helpers_test.go
Labels: area/feature, size/L

#6065 feat: resolve dependencies for KongServiceFacade and improve for Service
  internal/annotations/annotations.go
  internal/dataplane/fallback/graph_dependencies_common.go
  internal/dataplane/fallback/graph_dependencies_kong.go
  internal/dataplane/fallback/graph_dependencies_kong_test.go
  internal/dataplane/fallback/graph_dependencies_service.go
  internal/dataplane/fallback/graph_dependencies_service_test.go
  internal/dataplane/fallback/helpers_test.go
Labels: area/feature, size/L

#6063 chore: simplify UpdateStrategy.Update signature
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_test.go
  internal/dataplane/sendconfig/backoff_strategy.go
  internal/dataplane/sendconfig/backoff_strategy_test.go
  internal/dataplane/sendconfig/dbmode.go
  internal/dataplane/sendconfig/errors.go
  internal/dataplane/sendconfig/errors_test.go
  internal/dataplane/sendconfig/inmemory.go
  internal/dataplane/sendconfig/inmemory_error_handling.go
  internal/dataplane/sendconfig/sendconfig.go
  internal/dataplane/sendconfig/strategy.go
  test/kongintegration/inmemory_update_strategy_test.go
  test/kongintegration/kongupstreampolicy_test.go
  test/kongintegration/translator_golden_tests_outputs_test.go
Labels: area/maintenance, size/L

#6066 feat: resolve dependencies for UDPIngress and TCPIngress
  internal/dataplane/fallback/graph_dependencies_kong.go
  internal/dataplane/fallback/graph_dependencies_kong_test.go
  internal/dataplane/fallback/helpers_test.go
Labels: area/feature, size/L

#6071 feat: generate and push fallback config on update failure
  .github/workflows/_integration_tests.yaml
  CHANGELOG.md
  config/variants/multi-gw/debug/manager_debug.yaml
  internal/dataplane/fallback/fallback.go
  internal/dataplane/fallback/fallback_test.go
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_test.go
  internal/manager/run.go
Labels: area/feature, size/XL

#6075 review suggestion: add unit test
  internal/dataplane/kong_client_test.go
Labels: size/M

#6073 fix(diag) correct redaction toggle
  CHANGELOG.md
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_test.go
Labels: size/M

#6079 fix(gwapi): only clear status of Gateway API *Routes reconciled by KIC's gateway(s)
  CHANGELOG.md
  internal/controllers/gateway/grpcroute_controller.go
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/route_parent_status.go
  internal/controllers/gateway/route_predicates.go
  internal/controllers/gateway/route_utils.go
  internal/controllers/gateway/route_utils_test.go
  internal/controllers/gateway/tcproute_controller.go
  internal/controllers/gateway/tlsroute_controller.go
  internal/controllers/gateway/udproute_controller.go
  internal/gatewayapi/aliases.go
  test/envtest/httproute_controller_test.go
  test/internal/helpers/gatewayapi.go
Labels: area/gateway-api, size/XL

#6092 feat: use TakeSnapshotIfChanged to avoid taking redundant snapshot
  internal/dataplane/fallback/fallback.go
  internal/dataplane/fallback/fallback_test.go
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_test.go
  internal/store/cache_stores_snapshot.go
Labels: area/feature, size/L

#6098 feat: backfill broken objects from last valid cache state
  CHANGELOG.md
  FEATURE_GATES.md
  docs/cli-arguments.md
  internal/dataplane/fallback/fallback.go
  internal/dataplane/fallback/fallback_test.go
  internal/dataplane/fallback/graph.go
  internal/dataplane/fallback/graph_test.go
  internal/dataplane/fallback/helpers_test.go
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_test.go
  internal/dataplane/sendconfig/kong.go
  internal/manager/config.go
  internal/store/cache_stores_snapshot.go
Labels: size/XL

#6099 feat: emit fallback configuration events
  CHANGELOG.md
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_test.go
  test/mocks/events_recorder.go
Labels: size/L

#6097 fix(gwapi): fix missing predicates for gateway-to-reconcile
  internal/controllers/configuration/kongupstreampolicy_utils.go
  internal/controllers/controller.go
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gateway_utils.go
  internal/controllers/gateway/gateway_utils_test.go
  internal/controllers/gateway/grpcroute_controller.go
  internal/controllers/gateway/httproute_controller.go
  internal/controllers/gateway/route_utils.go
  internal/controllers/gateway/route_utils_test.go
  internal/controllers/gateway/tcproute_controller.go
  internal/controllers/gateway/tlsroute_controller.go
  internal/controllers/gateway/udproute_controller.go
  internal/controllers/namespacedname.go
  internal/controllers/namespacedname_test.go
  internal/manager/controllerdef.go
  test/envtest/gateway_envtest_test.go
  test/envtest/k8s_objects_status_envtest_test.go
  test/envtest/setup.go
  test/envtest/specific_gateway_envtest_test.go
Labels: area/gateway-api, size/XL

#6113 deps: bump sigs.k8s.io/e2e-framework to v0.4.0
  go.mod
  go.sum
Labels: area/tests, size/S, area/dependency-mgmt

#6114 conformance: enable HTTPRoutePathRewrite test
  test/conformance/gateway_conformance_test.go
Labels: area/gateway-api, size/XS, kind/conformance
