Repository Kong/kubernetes-ingress-controller, pull requests merged in 2024-03, with the labels that each got.

#5686 fix: do not include DELETE in any webhook operations
  config/webhook/manifests.yaml
  internal/admission/handler.go
Labels: size/S, area/admission

#5688 Backport "fix: do not translate licenses if Kong gateway is not enterprise edition (#5640)" to 3.1.x
  CHANGELOG.md
  internal/dataplane/translator/translator.go
  internal/dataplane/translator/translator_test.go
  internal/manager/run.go
Labels: bug, area/kong, size/M

#5689 chore(docs): Move PR #5640 out of 3.1.1 changelogs
  CHANGELOG.md
Labels: area/docs, size/S

#5694 prepare release 3.1.2: update CHANGELOG for kic 3.1.2
  CHANGELOG.md
Labels: size/XS, backport release/3.1.x

#5682 [WIP] fix(#5658): handle edge cases for tag filtering detection
  CHANGELOG.md
  internal/adminapi/konnect.go
  internal/dataplane/sendconfig/kong.go
  internal/manager/run.go
Labels: size/M

#5711 tests: fix e2e tests by installing incubator CRDs
  test/consts/consts.go
  test/e2e/helpers_test.go
  test/internal/testenv/feature_gates.go
Labels: area/tests, size/S

#5718 ci: do not fetch all history on CI
  .github/workflows/_conformance_tests.yaml
  .github/workflows/_docker_build.yaml
  .github/workflows/_e2e_tests.yaml
  .github/workflows/_envtest_tests.yaml
  .github/workflows/_integration_tests.yaml
  .github/workflows/_kongintegration_tests.yaml
  .github/workflows/_linters.yaml
  .github/workflows/_performance_tests.yaml
  .github/workflows/_test_reports.yaml
  .github/workflows/_unit_tests.yaml
  .github/workflows/check_fixed_issues_references.yaml
  .github/workflows/checks.yaml
  .github/workflows/cleanup.yaml
  .github/workflows/conformance_tests_report.yaml
  .github/workflows/performance_targeted.yaml
  .github/workflows/performance_trigger_via_label.yaml
  .github/workflows/release_docs.yaml
  .github/workflows/test_nightly.yaml
Labels: area/ci, size/M

#5524 Update timeout for .github/workflows/license.yaml
  .github/workflows/license.yaml
Labels: size/XS

#5720 ci: fix main's up-to-date job by increasing fetch-depth
  .github/workflows/checks.yaml
Labels: area/ci, size/XS

#5719 chore(tests): simplify TestExampleUDPRoute
  examples/gateway-udproute.yaml
  test/e2e/helpers_gateway_test.go
  test/integration/examples_test.go
  test/integration/isolated/examples_udproute_test.go
  test/integration/isolated/tcproute_test.go
  test/integration/tcproute_test.go
  test/tcp_utils.go
Labels: area/tests, area/maintenance, size/L

#5722 ci: fix main's up-to-date job by setting fetch-depth to 0
  .github/workflows/checks.yaml
Labels: area/ci, size/XS

#5723 chore(tests): rename TestUDPRoute to TestUDPRouteEssentials and make similar to TestTCPRouteEssentials
  test/integration/isolated/examples_udproute_test.go
  test/integration/isolated/resolver.go
  test/integration/isolated/tcproute_test.go
  test/integration/isolated/udproute_test.go
Labels: area/tests, area/maintenance, size/XXL

#5735 refactor: bump KTF to v0.46.0 and adjust code accordingly
  go.mod
  go.sum
  internal/util/test/controller_manager.go
  test/e2e/helpers_test.go
  test/e2e/istio_test.go
  test/e2e/upgrade_test.go
  test/integration/consumer_group_test.go
  test/integration/consumer_test.go
  test/integration/examples_test.go
  test/integration/gateway_test.go
  test/integration/httproute_test.go
  test/integration/ingress_https_test.go
  test/integration/ingress_regex_match_test.go
  test/integration/ingress_test.go
  test/integration/isolated/ctx.go
  test/integration/isolated/examples_grpc_test.go
  test/integration/isolated/examples_kong_service_facade_test.go
  test/integration/isolated/examples_udproute_test.go
  test/integration/isolated/grpc_test.go
  test/integration/isolated/ingress_test.go
  test/integration/isolated/suite_test.go
  test/integration/isolated/tcproute_test.go
  test/integration/isolated/udproute_test.go
  test/integration/kongingress_test.go
  test/integration/plugin_test.go
  test/integration/suite_test.go
  test/integration/tcpingress_test.go
  test/integration/tcproute_test.go
  test/integration/tlsroute_test.go
  test/integration/udpingress_test.go
  test/integration/utils_test.go
  test/integration/vault_test.go
Labels: dependencies, area/maintenance, size/XL

#5737 fix(webhook): do not require rsa_public_key field in credentials secrets when working with jwt HMAC algorigthms
  CHANGELOG.md
  internal/admission/validation/consumers/credentials/validation.go
  internal/admission/validation/consumers/credentials/validation_test.go
Labels: size/M

#5745 chore(tests): improve helpers - pass `t *testing.T`
  test/integration/isolated/tcproute_test.go
  test/integration/isolated/udpingress_test.go
  test/integration/isolated/udproute_test.go
Labels: area/tests, area/maintenance, size/M

#5747 chore(tests): do not rely on Redis in TestTCPIngressTLSPassthrough
  test/integration/tcpingress_test.go
Labels: area/tests, area/maintenance, size/L

#5724 chore(tests): migrate to isolated and simplify TestUDPIngressExample
  examples/udpingress.yaml
  internal/util/test/controller_manager.go
  test/integration/examples_test.go
  test/integration/isolated/examples_udpingress_test.go
  test/internal/testlabels/labels.go
Labels: area/tests, area/maintenance, size/L

#5750 chore(tests): migrate to isolated and simplify TestUDPIngressTCPIngressCollision
  go.mod
  go.sum
  test/integration/isolated/udpingress_tcpingress_collision_test.go
  test/integration/isolated/udpingress_test.go
  test/integration/udpingress_test.go
  test/internal/testlabels/labels.go
Labels: area/tests, area/maintenance, size/XL

#5755 chore(tests): reuse assertion functions for TCP and UDP in isolated tests
  test/integration/isolated/assertion_helpers.go
  test/integration/isolated/tcproute_test.go
  test/integration/isolated/udpingress_tcpingress_collision_test.go
  test/integration/isolated/udpingress_test.go
  test/integration/isolated/udproute_test.go
Labels: area/maintenance, refactor, size/L

#5733 chore: update timeout for GitHub workflows
  .github/workflows/_conformance_tests.yaml
  .github/workflows/_docker_build.yaml
  .github/workflows/_e2e_tests.yaml
  .github/workflows/_envtest_tests.yaml
  .github/workflows/_integration_tests.yaml
  .github/workflows/_kongintegration_tests.yaml
  .github/workflows/_linters.yaml
  .github/workflows/_performance_tests.yaml
  .github/workflows/_test_reports.yaml
  .github/workflows/_unit_tests.yaml
  .github/workflows/backport.yaml
  .github/workflows/benchmarks.yaml
  .github/workflows/check_fixed_issues_references.yaml
  .github/workflows/check_pr_labels.yaml
  .github/workflows/checks.yaml
  .github/workflows/cleanup.yaml
  .github/workflows/codeql.yaml
  .github/workflows/conformance_tests_report.yaml
  .github/workflows/e2e_nightly.yaml
  .github/workflows/e2e_targeted.yaml
  .github/workflows/e2e_trigger_via_label.yaml
  .github/workflows/nightly.yaml
  .github/workflows/performance_nightly.yaml
  .github/workflows/performance_targeted.yaml
  .github/workflows/performance_trigger_via_label.yaml
  .github/workflows/regenerate_on_deps_bump.yaml
  .github/workflows/release.yaml
  .github/workflows/release_docs.yaml
  .github/workflows/validate_kong_image.yaml
Labels: area/ci, area/maintenance, size/M

#5756 chore: downgrade Kong EE dependency used in envtests
  .github/test_dependencies.yaml
Labels: size/XS

#5751 feat(build): use mise to manage third party tools
  .github/workflows/_conformance_tests.yaml
  .github/workflows/_e2e_tests.yaml
  .github/workflows/_envtest_tests.yaml
  .github/workflows/_integration_tests.yaml
  .github/workflows/_kongintegration_tests.yaml
  .github/workflows/_linters.yaml
  .github/workflows/_performance_tests.yaml
  .github/workflows/_unit_tests.yaml
  .github/workflows/benchmarks.yaml
  .github/workflows/checks.yaml
  .mise.toml
  .tools_versions.yaml
  Makefile
  renovate.json
  scripts/build-single-manifests.sh
  third_party/client-gen.go
  third_party/controller-gen.go
  third_party/crd-ref-docs.go
  third_party/go-junit-report.go
  third_party/go.mod
  third_party/go.sum
  third_party/golangci-lint.go
  third_party/gotestsum.go
  third_party/kustomize.go
  third_party/setup-envtest.go
  third_party/skaffold/go.mod
  third_party/skaffold/go.sum
  third_party/skaffold/skaffold.go
Labels: area/ci, dependencies, size/XXL

#5753 fix: set proper User-Agent for request made to Kong and Konnect
  .golangci.yaml
  CHANGELOG.md
  internal/adminapi/kong.go
  internal/adminapi/konnect.go
  internal/dataplane/kong_client_test.go
  internal/konnect/controlplanes/client.go
  internal/konnect/controlplanes/client_test.go
  internal/konnect/controlplanesconfig/client.go
  internal/konnect/controlplanesconfig/client_test.go
  internal/konnect/license/client.go
  internal/konnect/license/client_test.go
  internal/konnect/nodes/client.go
  internal/konnect/nodes/client_test.go
  internal/konnect/roles/client.go
  internal/konnect/roles/client_test.go
  internal/konnect/useragent/user_agent_round_tripper.go
  internal/manager/config.go
  internal/manager/metadata/metadata.go
  test/e2e/all_in_one_test.go
  test/e2e/konnect_test.go
  test/internal/helpers/kong.go
  test/kongintegration/expression_router_test.go
  test/kongintegration/inmemory_update_strategy_test.go
  test/kongintegration/kongupstreampolicy_test.go
  test/kongintegration/translator_golden_tests_outputs_test.go
Labels: area/maintenance, size/L

#5764 fix: do not require namespaces when parsing errors about cluster scoped resources
  internal/dataplane/sendconfig/inmemory_error_handling.go
  internal/dataplane/sendconfig/inmemory_error_handling_test.go
Labels: size/M

#5763 feat: log an error when configuration fails to get applied and `KongConfigurationApplyFailed` is emitted
  internal/dataplane/kong_client.go
Labels: size/S

#5771 Revert "ci: manage staticcheck with mise"
  .tools_versions.yaml
  Makefile
  third_party/go.mod
  third_party/go.sum
  third_party/staticcheck.go
Labels: size/S

#5768 build: add GOCACHE to Dockerfile and skaffold
  .github/workflows/_docker_build.yaml
  Dockerfile
  Dockerfile.debug
  Makefile
  skaffold.yaml
Labels: area/maintenance, size/M

#5772 ci: manage staticcheck with mise
  .tools_versions.yaml
  Makefile
  third_party/go.mod
  third_party/go.sum
  third_party/staticcheck.go
Labels: size/S

#5779 fix(ci): fix nightly build by adding missing GOCACHE and GOPATH build params
  .github/workflows/nightly.yaml
Labels: area/ci, size/S

#5781 ci: remove GHA environment for nightly build
  .github/workflows/nightly.yaml
Labels: area/ci, size/XS

#5782 chore(tests): improve logging in tests
  test/integration/tlsroute_test.go
  test/internal/helpers/http.go
Labels: area/tests, area/maintenance, size/M
