Repository Kong/kubernetes-ingress-controller, pull requests merged in 2024-10, with the labels that each got.

#6086 Add INFO log for admissions which aren't allowed
  CHANGELOG.md
  internal/admission/handler.go
Labels: size/S

#6564 chore: simplify tools installation and management with mise
  .dockerignore
  .github/dependabot.yml
  .github/workflows/_linters.yaml
  .github/workflows/checks.yaml
  .gitignore
  .mise.toml
  .tools_versions.yaml
  Makefile
  third_party/dlv.go
  third_party/go.mod
  third_party/go.sum
  third_party/looppointer.go
Labels: dependencies, area/maintenance, size/L

#6571 chore(deps): bump gateway-api from 1.1.0 to 1.2.0 and adjust code
  CHANGELOG.md
  go.mod
  go.sum
  internal/dataplane/translator/subtranslator/grpcroute_atc.go
  internal/dataplane/translator/subtranslator/grpcroute_atc_test.go
  internal/gatewayapi/aliases.go
  test/conformance/gateway_conformance_test.go
  test/consts/zz_generated_gateway.go
Labels: dependencies, area/maintenance, size/M

#6575 chore: cover credentials in KongClient golden tests
  internal/dataplane/testdata/golden/credentials/default_golden.yaml
  internal/dataplane/testdata/golden/credentials/in.yaml
Labels: area/tests, size/L
