Repository Kong/kubernetes-ingress-controller, pull requests merged in 2025-04, with the labels that each got.

#7293 fix(kong_client): return error in fetching listeners when no ready kong clients
  CHANGELOG.md
  internal/controllers/gateway/gateway_controller.go
  internal/dataplane/kong_client.go
Labels: size/M

#7306 fix: fix the FallbackConfiguration object report
  CHANGELOG.md
  examples/ingress-broken-plugin-fallback.yaml
  internal/dataplane/kong_client.go
  test/integration/isolated/examples_ingress_fallback_test.go
Labels: size/L

#7269 fix(translator): Generate regex match for prefix match if replacePrefixMatch URLRewrite filter in the rule in translating HTTPRoute match to routes when expression router enabled
  CHANGELOG.md
  internal/dataplane/translator/subtranslator/httproute.go
  internal/dataplane/translator/subtranslator/httproute_atc.go
  internal/dataplane/translator/subtranslator/httproute_atc_test.go
  internal/dataplane/translator/subtranslator/httproute_test.go
Labels: size/L

#7310 chore: re-enable metrics envtest
  test/envtest/metrics_envtest_test.go
  test/envtest/run.go
Labels: area/tests, size/L

#7325 chore(ci): fix FOSSA
  .github/workflows/license.yaml
Labels: area/ci, size/XS

#7323 prepare release 3.4.4
  CHANGELOG.md
Labels: size/XS

#7328 chore(ci): fix release workflow DockerHub login
  .github/workflows/release.yaml
Labels: area/ci, size/S

#7332 test(e2e): Do not remove CP roles in cleanups of konnect tests in release/2.12.x
  test/e2e/konnect_test.go
Labels: size/S

#7333 chore(ci): fix release workflow 2.12.x
  .github/workflows/release.yaml
Labels: size/S

#7337 chore(ci): fix token permissions in release workflow 2.12.x
  .github/workflows/release.yaml
Labels: area/ci, size/M

#7359 chore(makefile): Update Makefile
  Makefile
Labels: size/XS

#7362 chore(ci): run checks on merge_group event
  .github/workflows/checks.yaml
Labels: area/ci, size/XS

#7346 fix(validation): Override route by annotation in translation of ingresses and httproutes for validation
  CHANGELOG.md
  internal/admission/validation/gateway/httproute.go
  internal/admission/validation/ingress/ingress.go
  internal/admission/validation/ingress/ingress_test.go
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/route.go
  internal/dataplane/kongstate/route_test.go
Labels: size/M
