Repository Kong/kubernetes-ingress-controller, pull requests merged in 2025-01, with the labels that each got.

#6910 chore: prepare 3.4.1
  CHANGELOG.md
Labels: size/XS

#6920 [Backport release/2.12.x] chore(ci): use pull_request instead of pull_request_target
  .github/workflows/check_pr_labels.yaml
Labels: size/XS

#6919 [Backport release/3.2.x] chore(ci): use pull_request instead of pull_request_target
  .github/workflows/backport.yaml
  .github/workflows/check_pr_labels.yaml
  .github/workflows/e2e_trigger_via_label.yaml
Labels: size/S

#6918 [Backport release/3.3.x] chore(ci): use pull_request instead of pull_request_target
  .github/workflows/backport.yaml
  .github/workflows/check_pr_labels.yaml
  .github/workflows/e2e_trigger_via_label.yaml
Labels: size/S

#6921 ci(github): use pull_request for backport
  .github/workflows/backport.yaml
Labels: size/XS

#6923 chore: update changelog for 3.4.1
  CHANGELOG.md
Labels: size/S

#6925 chore(ci): use pull_request instead of pull_request_target (#6743)
  .github/workflows/backport.yaml
  .github/workflows/check_pr_labels.yaml
  .github/workflows/e2e_trigger_via_label.yaml
Labels: size/S

#6926 chore(ci): use pull_request instead of pull_request_target (#6743)
  .github/workflows/backport.yaml
  .github/workflows/check_pr_labels.yaml
  .github/workflows/e2e_trigger_via_label.yaml
Labels: size/S

#6924 Chore: Use hash to pin actions
  .github/workflows/_conformance_tests.yaml
  .github/workflows/_docker_build.yaml
  .github/workflows/_e2e_tests.yaml
  .github/workflows/_envtest_tests.yaml
  .github/workflows/_integration_tests.yaml
  .github/workflows/_kongintegration_tests.yaml
  .github/workflows/_linters.yaml
  .github/workflows/_performance_tests.yaml
  .github/workflows/_permission_check.yaml
  .github/workflows/_test_reports.yaml
  .github/workflows/_unit_tests.yaml
  .github/workflows/backport.yaml
  .github/workflows/benchmarks.yaml
  .github/workflows/check_fixed_issues_references.yaml
  .github/workflows/check_pr_labels.yaml
  .github/workflows/checks.yaml
  .github/workflows/conformance_tests_report.yaml
  .github/workflows/e2e_nightly.yaml
  .github/workflows/license.yaml
  .github/workflows/nightly.yaml
  .github/workflows/performance_nightly.yaml
  .github/workflows/performance_targeted.yaml
  .github/workflows/regenerate_on_deps_bump.yaml
  .github/workflows/release.yaml
  .github/workflows/release_docs.yaml
  .github/workflows/test_nightly.yaml
  .github/workflows/validate_kong_image_trigger_via_label.yaml
Labels: size/L, backport release/2.12.x, backport release/3.3.x, backport release/3.4.x

#6928 chore(ci): use pull_request instead of pull_request_target (#6743)
  .github/workflows/backport.yaml
  .github/workflows/check_pr_labels.yaml
Labels: size/XS

#6930 chore(ci): use pull_request instead of pull_request_target (#6743)
  .github/workflows/check_pr_labels.yaml
Labels: size/XS

#6933 chore(ci): use pull_request instead of pull_request_target (#6743)
  .github/workflows/check_pr_labels.yaml
Labels: size/XS

#6932 chore(ci): use pull_request instead of pull_request_target (#6743)
  .github/workflows/check_pr_labels.yaml
Labels: size/XS

#6931 chore(ci): use pull_request instead of pull_request_target (#6743)
  .github/workflows/check_pr_labels.yaml
Labels: size/XS

#6903 Fix: Proxy do not listen http2 in request redirect tests
  test/integration/isolated/httproute_filter_request_redirect_test.go
Labels: size/XS

#6885 chore: don't use KonnectClient in ClientsProvider
  internal/adminapi/konnect.go
  internal/clients/config_status.go
  internal/clients/manager.go
  internal/clients/manager_test.go
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_test.go
  internal/dataplane/sendconfig/dbmode.go
  internal/dataplane/sendconfig/strategy.go
  internal/konnect/config_synchronizer.go
  internal/konnect/config_synchronizer_test.go
  internal/konnect/node_agent.go
  internal/konnect/node_agent_test.go
  internal/manager/run.go
  internal/manager/setup.go
  internal/util/clock/ticker.go
  test/kongintegration/dbmode_update_strategy_test.go
  test/kongintegration/kong_client_golden_tests_outputs_test.go
  test/mocks/config_status_notifier.go
  test/mocks/konnect_client_factory.go
  test/mocks/konnect_kongstate_updater.go
Labels: size/XXL, area/konnect

#6954 chore(ci): run go mod tidy during regeneration
  .github/workflows/regenerate_on_deps_bump.yaml
Labels: area/ci, area/maintenance, size/XS, area/dependency-mgmt

#6956 chore(ci): add go.mod and go.sum to commit for regenerate
  .github/workflows/regenerate_on_deps_bump.yaml
Labels: area/ci, area/maintenance, size/XS, area/dependency-mgmt

#6958 chore(ci): ensure used GitHub action versions are pinned by SHA
  .github/workflows/_conformance_tests.yaml
  .github/workflows/_docker_build.yaml
  .github/workflows/_e2e_tests.yaml
  .github/workflows/_envtest_tests.yaml
  .github/workflows/_integration_tests.yaml
  .github/workflows/_kongintegration_tests.yaml
  .github/workflows/_linters.yaml
  .github/workflows/_performance_tests.yaml
  .github/workflows/_test_reports.yaml
  .github/workflows/_unit_tests.yaml
  .github/workflows/benchmarks.yaml
  .github/workflows/check_fixed_issues_references.yaml
  .github/workflows/checks.yaml
  .github/workflows/cleanup.yaml
  .github/workflows/codeql.yaml
  .github/workflows/conformance_tests_report.yaml
  .github/workflows/e2e_targeted.yaml
  .github/workflows/e2e_trigger_via_label.yaml
  .github/workflows/license.yaml
  .github/workflows/nightly.yaml
  .github/workflows/performance_nightly.yaml
  .github/workflows/performance_targeted.yaml
  .github/workflows/performance_trigger_via_label.yaml
  .github/workflows/regenerate_on_deps_bump.yaml
  .github/workflows/release.yaml
  .github/workflows/release_docs.yaml
  .github/workflows/test_nightly.yaml
  .github/workflows/validate_kong_image.yaml
  .github/workflows/validate_kong_image_trigger_via_label.yaml
Labels: area/ci, size/L

#6937 pin third party workflows by hashes (#6924)
  .github/workflows/_conformance_tests.yaml
  .github/workflows/_docker_build.yaml
  .github/workflows/_e2e_tests.yaml
  .github/workflows/_envtest_tests.yaml
  .github/workflows/_integration_tests.yaml
  .github/workflows/_kongintegration_tests.yaml
  .github/workflows/_linters.yaml
  .github/workflows/_performance_tests.yaml
  .github/workflows/_permission_check.yaml
  .github/workflows/_test_reports.yaml
  .github/workflows/_unit_tests.yaml
  .github/workflows/backport.yaml
  .github/workflows/benchmarks.yaml
  .github/workflows/check_fixed_issues_references.yaml
  .github/workflows/check_pr_labels.yaml
  .github/workflows/checks.yaml
  .github/workflows/conformance_tests_report.yaml
  .github/workflows/e2e_nightly.yaml
  .github/workflows/license.yaml
  .github/workflows/nightly.yaml
  .github/workflows/performance_nightly.yaml
  .github/workflows/performance_targeted.yaml
  .github/workflows/regenerate_on_deps_bump.yaml
  .github/workflows/release.yaml
  .github/workflows/release_docs.yaml
  .github/workflows/test_nightly.yaml
  .github/workflows/validate_kong_image_trigger_via_label.yaml
Labels: size/L

#6957 ci: add scorecard
  .github/workflows/scorecard.yml
Labels: area/ci, size/M

#6939 pin 3rd party actions by hashes
  .github/workflows/_docker_build.yaml
  .github/workflows/_e2e_tests.yaml
  .github/workflows/_integration_tests.yaml
  .github/workflows/_test_reports.yaml
  .github/workflows/backport.yaml
  .github/workflows/benchmarks.yaml
  .github/workflows/check_pr_labels.yaml
  .github/workflows/e2e_nightly.yaml
  .github/workflows/license.yaml
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
  .github/workflows/release_docs.yaml
  .github/workflows/test_nightly.yaml
Labels: size/M

#6960 chore(dependabot): group testcontainers updates
  .github/dependabot.yml
Labels: area/ci, size/XS

#6970 chore(dependabot): group actions/* updates
  .github/dependabot.yml
Labels: area/ci, size/XS

#6969 chore: add Dockerfile pins
  .github/actions/redhat-opdev-preflight-action/Dockerfile
  Dockerfile
  Dockerfile.debug
  renovate.json
Labels: area/ci, size/S

#6961 chore(ci): harden GITHUB_TOKEN permissions
  .github/workflows/_conformance_tests.yaml
  .github/workflows/_docker_build.yaml
  .github/workflows/_e2e_tests.yaml
  .github/workflows/_envtest_tests.yaml
  .github/workflows/_integration_tests.yaml
  .github/workflows/_kongintegration_tests.yaml
  .github/workflows/_linters.yaml
  .github/workflows/_performance_tests.yaml
  .github/workflows/_permission_check.yaml
  .github/workflows/_test_reports.yaml
  .github/workflows/_unit_tests.yaml
  .github/workflows/backport.yaml
  .github/workflows/benchmarks.yaml
  .github/workflows/check_fixed_issues_references.yaml
  .github/workflows/check_pr_labels.yaml
  .github/workflows/checks.yaml
  .github/workflows/cleanup.yaml
  .github/workflows/codeql.yaml
  .github/workflows/conformance_tests_report.yaml
  .github/workflows/e2e_nightly.yaml
  .github/workflows/e2e_targeted.yaml
  .github/workflows/e2e_trigger_via_label.yaml
  .github/workflows/license.yaml
  .github/workflows/nightly.yaml
  .github/workflows/performance_nightly.yaml
  .github/workflows/performance_targeted.yaml
  .github/workflows/performance_trigger_via_label.yaml
  .github/workflows/regenerate_on_deps_bump.yaml
  .github/workflows/release.yaml
  .github/workflows/release_docs.yaml
  .github/workflows/test_nightly.yaml
  .github/workflows/validate_kong_image.yaml
  .github/workflows/validate_kong_image_trigger_via_label.yaml
Labels: area/ci, size/L

#6975 chore: update SECURITY.md
  SECURITY.md
Labels: size/M

#6741 chore(refactor): remove redundant code for HTTPRoute translation
  internal/admission/validation/gateway/httproute.go
  internal/dataplane/translator/subtranslator/httproute.go
  internal/dataplane/translator/subtranslator/httproute_atc.go
  internal/dataplane/translator/subtranslator/httproute_atc_test.go
  internal/dataplane/translator/translate_httproute.go
  internal/dataplane/translator/translate_httproute_test.go
  internal/store/fake_store.go
  internal/store/fake_store_test.go
Labels: area/maintenance, release/not-required, nice-to-have, refactor, size/XL

#6978 chore: pin actions to digests
  .github/workflows/_conformance_tests.yaml
  .github/workflows/_docker_build.yaml
  .github/workflows/_e2e_tests.yaml
  .github/workflows/_envtest_tests.yaml
  .github/workflows/_integration_tests.yaml
  .github/workflows/_kongintegration_tests.yaml
  .github/workflows/_linters.yaml
  .github/workflows/_performance_tests.yaml
  .github/workflows/_test_reports.yaml
  .github/workflows/_unit_tests.yaml
  .github/workflows/benchmarks.yaml
  .github/workflows/check_fixed_issues_references.yaml
  .github/workflows/checks.yaml
  .github/workflows/cleanup.yaml
  .github/workflows/codeql.yaml
  .github/workflows/conformance_tests_report.yaml
  .github/workflows/e2e_targeted.yaml
  .github/workflows/e2e_trigger_via_label.yaml
  .github/workflows/license.yaml
  .github/workflows/nightly.yaml
  .github/workflows/performance_nightly.yaml
  .github/workflows/performance_targeted.yaml
  .github/workflows/performance_trigger_via_label.yaml
  .github/workflows/regenerate_on_deps_bump.yaml
  .github/workflows/release.yaml
  .github/workflows/release_docs.yaml
  .github/workflows/test_nightly.yaml
  .github/workflows/validate_kong_image.yaml
  .github/workflows/validate_kong_image_trigger_via_label.yaml
Labels: area/ci, github_actions, size/L

#6979 chore: pin actions to digests
  .github/workflows/_conformance_tests.yaml
  .github/workflows/_docker_build.yaml
  .github/workflows/_e2e_tests.yaml
  .github/workflows/_envtest_tests.yaml
  .github/workflows/_integration_tests.yaml
  .github/workflows/_kongintegration_tests.yaml
  .github/workflows/_linters.yaml
  .github/workflows/_performance_tests.yaml
  .github/workflows/_test_reports.yaml
  .github/workflows/_unit_tests.yaml
  .github/workflows/benchmarks.yaml
  .github/workflows/check_fixed_issues_references.yaml
  .github/workflows/checks.yaml
  .github/workflows/cleanup.yaml
  .github/workflows/codeql.yaml
  .github/workflows/conformance_tests_report.yaml
  .github/workflows/e2e_targeted.yaml
  .github/workflows/e2e_trigger_via_label.yaml
  .github/workflows/license.yaml
  .github/workflows/nightly.yaml
  .github/workflows/performance_nightly.yaml
  .github/workflows/performance_targeted.yaml
  .github/workflows/performance_trigger_via_label.yaml
  .github/workflows/regenerate_on_deps_bump.yaml
  .github/workflows/release.yaml
  .github/workflows/release_docs.yaml
  .github/workflows/test_nightly.yaml
  .github/workflows/validate_kong_image.yaml
  .github/workflows/validate_kong_image_trigger_via_label.yaml
Labels: area/ci, github_actions, size/L

#6983 chore: pin actions to digests
  .github/workflows/_conformance_tests.yaml
  .github/workflows/_docker_build.yaml
  .github/workflows/_e2e_tests.yaml
  .github/workflows/_envtest_tests.yaml
  .github/workflows/_integration_tests.yaml
  .github/workflows/_linters.yaml
  .github/workflows/_test_reports.yaml
  .github/workflows/_unit_tests.yaml
  .github/workflows/benchmarks.yaml
  .github/workflows/cleanup.yaml
  .github/workflows/codeql.yaml
  .github/workflows/conformance_tests_report.yaml
  .github/workflows/e2e_targeted.yaml
  .github/workflows/e2e_trigger_via_label.yaml
  .github/workflows/license.yaml
  .github/workflows/nightly.yaml
  .github/workflows/pr_checks.yaml
  .github/workflows/release.yaml
  .github/workflows/release_docs.yaml
  .github/workflows/test_nightly.yaml
  .github/workflows/validate_kong_image.yaml
Labels: area/ci, github_actions, size/L

#6980 chore: pin actions to digests
  .github/workflows/_conformance_tests.yaml
  .github/workflows/_docker_build.yaml
  .github/workflows/_e2e_tests.yaml
  .github/workflows/_envtest_tests.yaml
  .github/workflows/_integration_tests.yaml
  .github/workflows/_kongintegration_tests.yaml
  .github/workflows/_linters.yaml
  .github/workflows/_performance_tests.yaml
  .github/workflows/_test_reports.yaml
  .github/workflows/_unit_tests.yaml
  .github/workflows/backport.yaml
  .github/workflows/benchmarks.yaml
  .github/workflows/check_fixed_issues_references.yaml
  .github/workflows/check_pr_labels.yaml
  .github/workflows/checks.yaml
  .github/workflows/cleanup.yaml
  .github/workflows/codeql.yaml
  .github/workflows/conformance_tests_report.yaml
  .github/workflows/e2e_nightly.yaml
  .github/workflows/e2e_targeted.yaml
  .github/workflows/e2e_trigger_via_label.yaml
  .github/workflows/license.yaml
  .github/workflows/nightly.yaml
  .github/workflows/performance_nightly.yaml
  .github/workflows/performance_targeted.yaml
  .github/workflows/performance_trigger_via_label.yaml
  .github/workflows/regenerate_on_deps_bump.yaml
  .github/workflows/release.yaml
  .github/workflows/release_docs.yaml
  .github/workflows/test_nightly.yaml
  .github/workflows/validate_kong_image.yaml
  .github/workflows/validate_kong_image_trigger_via_label.yaml
Labels: area/ci, github_actions, size/L

#6982 chore: pin actions to digests
  .github/workflows/_conformance_tests.yaml
  .github/workflows/_docker_build.yaml
  .github/workflows/_e2e_tests.yaml
  .github/workflows/_envtest_tests.yaml
  .github/workflows/_integration_tests.yaml
  .github/workflows/_kongintegration_tests.yaml
  .github/workflows/_linters.yaml
  .github/workflows/_test_reports.yaml
  .github/workflows/_unit_tests.yaml
  .github/workflows/backport.yaml
  .github/workflows/benchmarks.yaml
  .github/workflows/check_fixed_issues_references.yaml
  .github/workflows/check_pr_labels.yaml
  .github/workflows/checks.yaml
  .github/workflows/cleanup.yaml
  .github/workflows/codeql.yaml
  .github/workflows/conformance_tests_report.yaml
  .github/workflows/e2e_nightly.yaml
  .github/workflows/e2e_targeted.yaml
  .github/workflows/e2e_trigger_via_label.yaml
  .github/workflows/license.yaml
  .github/workflows/nightly.yaml
  .github/workflows/regenerate_on_deps_bump.yaml
  .github/workflows/release.yaml
  .github/workflows/release_docs.yaml
  .github/workflows/test_nightly.yaml
  .github/workflows/validate_kong_image.yaml
Labels: area/ci, github_actions, size/L

#6981 chore: pin actions to digests
  .github/workflows/_conformance_tests.yaml
  .github/workflows/_docker_build.yaml
  .github/workflows/_e2e_tests.yaml
  .github/workflows/_envtest_tests.yaml
  .github/workflows/_integration_tests.yaml
  .github/workflows/_kongintegration_tests.yaml
  .github/workflows/_linters.yaml
  .github/workflows/_performance_tests.yaml
  .github/workflows/_test_reports.yaml
  .github/workflows/_unit_tests.yaml
  .github/workflows/backport.yaml
  .github/workflows/benchmarks.yaml
  .github/workflows/check_fixed_issues_references.yaml
  .github/workflows/check_pr_labels.yaml
  .github/workflows/checks.yaml
  .github/workflows/cleanup.yaml
  .github/workflows/codeql.yaml
  .github/workflows/conformance_tests_report.yaml
  .github/workflows/e2e_nightly.yaml
  .github/workflows/e2e_targeted.yaml
  .github/workflows/e2e_trigger_via_label.yaml
  .github/workflows/license.yaml
  .github/workflows/nightly.yaml
  .github/workflows/performance_targeted.yaml
  .github/workflows/performance_trigger_via_label.yaml
  .github/workflows/regenerate_on_deps_bump.yaml
  .github/workflows/release.yaml
  .github/workflows/release_docs.yaml
  .github/workflows/test_nightly.yaml
  .github/workflows/validate_kong_image.yaml
Labels: area/ci, github_actions, size/L

#6987 chore: pin actions to digests
  .github/workflows/check_pr_labels.yaml
  .github/workflows/cleanup.yaml
  .github/workflows/codeql.yaml
  .github/workflows/e2e.yaml
  .github/workflows/e2e_targeted.yaml
  .github/workflows/license.yaml
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
  .github/workflows/release_docs.yaml
  .github/workflows/test.yaml
  .github/workflows/test_nightly.yaml
Labels: area/ci, github_actions, size/L

#6991 chore: pin actions to digests
  .github/workflows/cleanup.yaml
  .github/workflows/codeql.yaml
  .github/workflows/e2e.yaml
  .github/workflows/e2e_targeted.yaml
  .github/workflows/license.yaml
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
Labels: area/ci, github_actions, size/L

#6988 chore: pin actions to digests
  .github/workflows/automerge-dependabot.yaml
  .github/workflows/check_pr_labels.yaml
  .github/workflows/cleanup.yaml
  .github/workflows/codeql.yaml
  .github/workflows/e2e.yaml
  .github/workflows/e2e_targeted.yaml
  .github/workflows/kong3.0_compatibility.yaml
  .github/workflows/license.yaml
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  .github/workflows/test_nightly.yaml
Labels: area/ci, github_actions, size/L

#6989 chore: pin actions to digests
  .github/workflows/automerge-dependabot.yaml
  .github/workflows/check_pr_labels.yaml
  .github/workflows/codeql.yaml
  .github/workflows/e2e_targeted.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  .github/workflows/test_nightly.yaml
Labels: area/ci, github_actions, size/L

#6995 chore: pin actions to digests
  .github/workflows/cleanup.yaml
  .github/workflows/codeql.yaml
  .github/workflows/e2e.yaml
  .github/workflows/license.yaml
  .github/workflows/release-testing.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
Labels: area/ci, github_actions, size/L

#6994 chore: pin actions to digests
  .github/workflows/cleanup.yaml
  .github/workflows/codeql.yaml
  .github/workflows/e2e.yaml
  .github/workflows/license.yaml
  .github/workflows/release-testing.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
Labels: area/ci, github_actions, size/L

#6992 chore: pin actions to digests
  .github/workflows/cleanup.yaml
  .github/workflows/codeql.yaml
  .github/workflows/e2e.yaml
  .github/workflows/e2e_targeted.yaml
  .github/workflows/license.yaml
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
Labels: area/ci, github_actions, size/L

#6990 chore: pin actions to digests
  .github/workflows/cleanup.yaml
  .github/workflows/codeql.yaml
  .github/workflows/e2e.yaml
  .github/workflows/e2e_targeted.yaml
  .github/workflows/license.yaml
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
Labels: area/ci, github_actions, size/L

#6986 chore: pin actions to digests
  .github/workflows/_conformance_tests.yaml
  .github/workflows/_docker_build.yaml
  .github/workflows/_e2e_tests.yaml
  .github/workflows/_integration_tests.yaml
  .github/workflows/_linters.yaml
  .github/workflows/_test_reports.yaml
  .github/workflows/_unit_tests.yaml
  .github/workflows/check_pr_labels.yaml
  .github/workflows/cleanup.yaml
  .github/workflows/codeql.yaml
  .github/workflows/e2e_targeted.yaml
  .github/workflows/e2e_trigger_via_label.yaml
  .github/workflows/license.yaml
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
  .github/workflows/release_docs.yaml
  .github/workflows/test_nightly.yaml
Labels: area/ci, github_actions, size/L

#6985 chore: pin actions to digests
  .github/workflows/_conformance_tests.yaml
  .github/workflows/_docker_build.yaml
  .github/workflows/_e2e_tests.yaml
  .github/workflows/_integration_tests.yaml
  .github/workflows/_linters.yaml
  .github/workflows/_test_reports.yaml
  .github/workflows/_unit_tests.yaml
  .github/workflows/backport.yaml
  .github/workflows/check_pr_labels.yaml
  .github/workflows/cleanup.yaml
  .github/workflows/codeql.yaml
  .github/workflows/e2e_nightly.yaml
  .github/workflows/e2e_targeted.yaml
  .github/workflows/e2e_trigger_via_label.yaml
  .github/workflows/license.yaml
  .github/workflows/nightly.yaml
  .github/workflows/pr_checks.yaml
  .github/workflows/release.yaml
  .github/workflows/release_docs.yaml
  .github/workflows/test_nightly.yaml
  .github/workflows/validate_kong_image.yaml
Labels: area/ci, github_actions, size/L

#6984 chore: pin actions to digests
  .github/workflows/_conformance_tests.yaml
  .github/workflows/_docker_build.yaml
  .github/workflows/_e2e_tests.yaml
  .github/workflows/_envtest_tests.yaml
  .github/workflows/_integration_tests.yaml
  .github/workflows/_linters.yaml
  .github/workflows/_test_reports.yaml
  .github/workflows/_unit_tests.yaml
  .github/workflows/backport.yaml
  .github/workflows/benchmarks.yaml
  .github/workflows/check_pr_labels.yaml
  .github/workflows/cleanup.yaml
  .github/workflows/codeql.yaml
  .github/workflows/e2e_nightly.yaml
  .github/workflows/e2e_targeted.yaml
  .github/workflows/e2e_trigger_via_label.yaml
  .github/workflows/license.yaml
  .github/workflows/nightly.yaml
  .github/workflows/pr_checks.yaml
  .github/workflows/release.yaml
  .github/workflows/release_docs.yaml
  .github/workflows/test_nightly.yaml
  .github/workflows/validate_kong_image.yaml
Labels: area/ci, github_actions, size/L

#6883 chore: update release template
  .github/ISSUE_TEMPLATE/release.yaml
Labels: size/XS

#7023 chore(build): use mise installed yq in Makefile
  Makefile
  renovate.json
Labels: area/ci, size/M

#7033 feat: deprecate `--gateway-discovery-dns-strategy` - make discovery always work
  CHANGELOG.md
  docs/cli-arguments.md
  internal/adminapi/client.go
  internal/adminapi/client_test.go
  internal/adminapi/endpoints.go
  internal/adminapi/endpoints_test.go
  internal/adminapi/kong.go
  internal/adminapi/kong_test.go
  internal/adminapi/konnect.go
  internal/dataplane/configfetcher/config_fetcher_test.go
  internal/dataplane/kong_client.go
  internal/konnect/config_synchronizer_test.go
  internal/manager/config.go
  internal/manager/config/types/dnsstrategy.go
  internal/manager/config_validation.go
  internal/manager/config_validation_test.go
  internal/manager/run.go
  internal/manager/setup.go
  scripts/cli-arguments-docs-gen/main.go
  test/e2e/all_in_one_test.go
  test/e2e/konnect_test.go
  test/envtest/adminapi_discoverer_envtest_test.go
  test/envtest/kongadminapi_controller_envtest_test.go
  test/internal/helpers/kong.go
  test/kongintegration/dbmode_update_strategy_test.go
  test/kongintegration/expression_router_test.go
  test/kongintegration/inmemory_update_strategy_test.go
  test/kongintegration/kong_client_golden_tests_outputs_test.go
  test/kongintegration/kongupstreampolicy_test.go
Labels: area/maintenance, size/XL

#7065 chore: merge main into feat/kic-as-library
  CHANGELOG.md
  docs/cli-arguments.md
  go.mod
  go.sum
  internal/adminapi/client.go
  internal/adminapi/client_test.go
  internal/adminapi/endpoints.go
  internal/adminapi/endpoints_test.go
  internal/adminapi/kong.go
  internal/adminapi/kong_test.go
  internal/adminapi/konnect.go
  internal/dataplane/configfetcher/config_fetcher_test.go
  internal/dataplane/kong_client.go
  internal/konnect/config_synchronizer_test.go
  internal/manager/config.go
  internal/manager/config/types/dnsstrategy.go
  internal/manager/config_validation.go
  internal/manager/config_validation_test.go
  internal/manager/run.go
  internal/manager/setup.go
  scripts/cli-arguments-docs-gen/main.go
  test/e2e/all_in_one_test.go
  test/e2e/konnect_test.go
  test/envtest/adminapi_discoverer_envtest_test.go
  test/envtest/kongadminapi_controller_envtest_test.go
  test/internal/helpers/kong.go
  test/kongintegration/dbmode_update_strategy_test.go
  test/kongintegration/expression_router_test.go
  test/kongintegration/inmemory_update_strategy_test.go
  test/kongintegration/kong_client_golden_tests_outputs_test.go
  test/kongintegration/kongupstreampolicy_test.go
Labels: size/XL
