Repository Kong/kubernetes-ingress-controller, pull requests merged in 2025-05, with the labels that each got.

#7388 chore(ci): remove redundant check permission workflow
  .github/workflows/_permission_check.yaml
  .github/workflows/checks.yaml
  .github/workflows/e2e_trigger_via_label.yaml
Labels: area/ci, area/maintenance, size/M

#7410 fix(kongstate): Fill ID for plugins
  CHANGELOG.md
  go.mod
  go.sum
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/testdata/golden/fallback-config-kong-custom-entities-ee/default_golden.yaml
  internal/dataplane/testdata/golden/kong-custom-entity-ee/default_golden.yaml
  internal/dataplane/testdata/golden/kong-service-facade/expression-routes-on_golden.yaml
  internal/dataplane/testdata/golden/kong-service-facade/feature-flag-on_golden.yaml
  internal/dataplane/testdata/golden/kongplugin-instance-name/default_golden.yaml
  internal/dataplane/translator/translator_test.go
Labels: size/M

#7380 fix(sendconfig): Do not skip when SHA is not changed if the update is performed by a fallback
  CHANGELOG.md
  internal/dataplane/sendconfig/sendconfig.go
  test/integration/consumer_group_test.go
Labels: size/S

#7419 chore(release): update changelog for release 3.4.5
  CHANGELOG.md
Labels: area/docs, size/XS

#7432 test(envtest): Ignore goroutine leaks in controller-runtime
  test/envtest/manager_envtest_test.go
Labels: size/XS

#7439 chore(ci): update kind k8s minor versions
  .github/test_dependencies.yaml
Labels: area/ci, area/tests, size/XS

#7446 Fix(sendconfig): Keep ID of existing plugins
  CHANGELOG.md
  internal/dataplane/sendconfig/dbmode.go
  internal/dataplane/sendconfig/dbmode_test.go
Labels: size/L
