Repository Kong/kubernetes-ingress-controller, pull requests merged in 2025-06, with the labels that each got.

#7467 chore: update DOCKERHUB tokens
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
  .github/workflows/test_nightly.yaml
Labels: size/S

#7466 feat: add basic sticky-sessions support
  CHANGELOG.md
  docs/cli-arguments.md
  examples/drain_support.yaml
  internal/cmd/rootcmd/config/cli.go
  internal/dataplane/kong_client_golden_test.go
  internal/dataplane/translator/translate_upstreams.go
  internal/dataplane/translator/translate_upstreams_drain_support_test.go
  internal/dataplane/translator/translator.go
  internal/dataplane/translator/translator_test.go
  internal/manager/consts/consts.go
  internal/manager/run.go
  internal/util/types.go
  pkg/manager/config/config.go
  test/integration/isolated/drain_support_test.go
Labels: size/XXL

#7488 feat(konnect): Store of konnect licenses to secrets
  CHANGELOG.md
  Makefile
  config/rbac/role.yaml
  docs/cli-arguments.md
  internal/cmd/rootcmd/config/cli.go
  internal/konnect/license/client.go
  internal/konnect/license/client_test.go
  internal/konnect/license/storage.go
  internal/konnect/license/storage_test.go
  internal/labels/labels.go
  internal/manager/setup.go
  pkg/manager/config/konnect.go
  pkg/manager/config_test.go
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
Labels: area/feature, size/L, area/konnect

#7517 fix(attachedRoutes): fixed count in case of HTTPRoute with multiple parentRefs
  CHANGELOG.md
  internal/controllers/gateway/gateway_utils.go
  internal/controllers/gateway/gateway_utils_test.go
Labels: size/L, backport release/3.4.x

#7522 backport(#7517): fixed count in case of HTTPRoute with multiple parentRefs
  CHANGELOG.md
  internal/controllers/gateway/gateway_utils.go
  internal/controllers/gateway/gateway_utils_test.go
Labels: size/L

#7512 update manifest for drain support and upgrade kcfg dep
  config/crd/incubator/kustomization.yaml
  config/crd/kustomization.yaml
  docs/api-reference.md
  examples/drain_support.yaml
  go.mod
  go.sum
  internal/controllers/utils/control_plane_reference_test.go
  internal/diagnostics/server_test.go
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
  test/envtest/control_plane_reference_test.go
  test/integration/kongingress_webhook_test.go
Labels: release/required, size/M

#7528 chore(changelog): update changelog for releasing KIC 3.4.7
  CHANGELOG.md
Labels: size/XS

#7533 update kcfg dependency and add translate logic
  CHANGELOG.md
  Makefile
  config/crd/incubator/kustomization.yaml
  config/crd/kustomization.yaml
  docs/api-reference.md
  go.mod
  go.sum
  internal/dataplane/kongstate/kongupstreampolicy.go
  internal/dataplane/kongstate/upstream.go
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
  test/envtest/crds_envtest_test.go
Labels: release/required, size/M

#7556 fix(tests): make envtests for K8s events generation robust
  test/envtest/configerrorevent_envtest_test.go
Labels: area/tests, area/maintenance, size/L, fix

#7543 ci(docs): release docs to developer.konghq.com
  .github/workflows/release_docs.yaml
Labels: size/S

#7538 feat(translator): Generate KongConfigurationTranslationFailed event when algorithm=sticky-sessions and kong version < 3.11
  .github/test_dependencies.yaml
  CHANGELOG.md
  config/crd/incubator/kustomization.yaml
  config/crd/kustomization.yaml
  go.mod
  go.sum
  internal/dataplane/kong_client_golden_test.go
  internal/dataplane/kongstate/kongstate.go
  internal/dataplane/kongstate/kongstate_test.go
  internal/dataplane/translator/translate_upstreams.go
  internal/dataplane/translator/translator.go
  internal/dataplane/translator/translator_test.go
  internal/manager/run.go
  internal/versions/versions.go
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
  test/envtest/configerrorevent_envtest_test.go
  test/envtest/kong.go
  test/envtest/run.go
Labels: size/L
