Repository Kong/kubernetes-ingress-controller, pull requests merged in 2025-02, with the labels that each got.

#7072 chore: ensure logger is passed down
  internal/clients/manager.go
  internal/clients/manager_test.go
  internal/cmd/rootcmd/run.go
  internal/manager/run.go
  internal/manager/setup.go
  internal/manager/telemetry/reports.go
Labels: size/M

#7071 chore: decouple health/readiness server from manager
  internal/cmd/rootcmd/run.go
  internal/manager/health/health_check.go
  internal/manager/health/health_check_test.go
  internal/manager/run.go
  internal/util/test/controller_manager.go
  pkg/manager/manager.go
  test/envtest/crds_envtest_test.go
  test/envtest/run.go
Labels: area/feature, refactor, size/L

#7080 chore: use `pkg/manager` instead of `internal/manager` everywhere
  .golangci.yaml
  internal/adminapi/kong.go
  internal/admission/validation/gateway/httproute_test.go
  internal/admission/validator_test.go
  internal/cmd/rootcmd/config/cli.go
  internal/cmd/rootcmd/config/cli_validation.go
  internal/cmd/rootcmd/config/cli_validation_test.go
  internal/cmd/rootcmd/rootcmd.go
  internal/cmd/rootcmd/run.go
  internal/controllers/configuration/kongupstreampolicy_utils_test.go
  internal/controllers/gateway/route_predicate_test.go
  internal/controllers/reference/indexer.go
  internal/dataplane/translator/translator_test.go
  internal/health/health_check.go
  internal/health/health_check_test.go
  internal/konnect/controlplanes/client_test.go
  internal/konnect/license/client_test.go
  internal/konnect/nodes/client_test.go
  internal/konnect/useragent/user_agent_round_tripper.go
  internal/logging/logging.go
  internal/logging/setup.go
  internal/manager/run.go
  internal/manager/setup.go
  internal/manager/telemetry/reports.go
  internal/manager/utils/kubeconfig.go
  internal/store/cache_stores.go
  internal/util/types_test.go
  pkg/manager/config.go
  pkg/manager/manager.go
  pkg/manager/scheme/scheme.go
  pkg/metadata/metadata.go
  pkg/metadata/metadata_test.go
  scripts/cli-arguments-docs-gen/main.go
  test/conformance/gateway_conformance_test.go
  test/conformance/suite_test.go
  test/e2e/istio_test.go
  test/envtest/crds_envtest_test.go
  test/envtest/run.go
  test/envtest/setup.go
  test/helpers/k8s_meta.go
  test/integration/admission_webhook_helpers_test.go
  test/integration/isolated/suite_test.go
  test/integration/suite_test.go
  test/integration/translation_failures_test.go
  test/mocks/events_recorder.go
  test/util/controller_manager.go
  test/util/crds.go
  test/util/gomod.go
  test/util/kustomize_consts.go
  test/util/name.go
  test/util/rbacs.go
  test/util/webhooks.go
Labels: refactor, size/L

#7083 test(integration): accept "connection reset by peer" error in error check where no routes matches in case TestTLSPassThrough
  test/integration/tlsroute_test.go
Labels: area/tests, size/XS

#7086 test(integration): change all error checks in TestTLSPassThrough
  test/integration/tlsroute_test.go
Labels: area/tests, size/S

#7079 chore: decouple diagnostics server from collector and handlers
  internal/dataplane/kong_client.go
  internal/dataplane/kong_client_golden_test.go
  internal/dataplane/kong_client_test.go
  internal/dataplane/sendconfig/dbmode.go
  internal/dataplane/sendconfig/sendconfig.go
  internal/dataplane/sendconfig/strategy.go
  internal/diagnostics/collector.go
  internal/diagnostics/collector_test.go
  internal/diagnostics/diff.go
  internal/diagnostics/diff_test.go
  internal/diagnostics/http_handler.go
  internal/diagnostics/http_handler_test.go
  internal/diagnostics/mapping.go
  internal/diagnostics/server.go
  internal/diagnostics/server_test.go
  internal/diagnostics/types.go
  internal/manager/run.go
  test/envtest/control_plane_reference_test.go
  test/envtest/crds_envtest_test.go
  test/envtest/ingress_test.go
  test/envtest/kongupstreampolicy_test.go
  test/envtest/manager_debugendpoints_test.go
  test/mocks/update_strategy_resolver.go
Labels: area/maintenance, size/XXL

#7089 feat: implement multi-instance manager
  go.mod
  pkg/manager/multiinstance/errors.go
  pkg/manager/multiinstance/instance.go
  pkg/manager/multiinstance/manager.go
  pkg/manager/multiinstance/manager_test.go
Labels: size/L

#7087 chore(ci): update kong OSS nightly repo
  .github/workflows/e2e_nightly.yaml
Labels: area/ci, size/XS

#7073 [release/2.12.x] chore(deps): bump GKE version in e2e tests
  .github/workflows/_e2e_tests.yaml
Labels: size/XS

#7092 feat: allow dynamically exposing diagnostics for multiple instances
  internal/manager/run.go
  pkg/manager/config/config.go
  pkg/manager/manager.go
  pkg/manager/multiinstance/diagnostics.go
  pkg/manager/multiinstance/instance.go
  pkg/manager/multiinstance/manager.go
  pkg/manager/multiinstance/manager_test.go
  pkg/manager/multiinstance/mocks_test.go
  test/envtest/multiinstance_manager_diagnostics_test.go
  test/envtest/run.go
Labels: size/L

#7098 feat: expose pprof endpoints from multiinstance diagnostics server
  go.mod
  pkg/manager/multiinstance/diagnostics.go
  pkg/manager/multiinstance/manager.go
  test/envtest/multiinstance_manager_diagnostics_test.go
Labels: size/M

#7100 chore: extract starting telemetry from `internal/manager`
  internal/cmd/rootcmd/run.go
  internal/konnect/node_agent.go
  internal/konnect/node_agent_test.go
  internal/manager/id.go
  internal/manager/run.go
  pkg/manager/id.go
  pkg/manager/manager.go
  pkg/telemetry/reports.go
  test/envtest/run.go
Labels: refactor, size/L

#7105 fix(manager): Run `AddToScheme` only once in `scheme.Get`
  CHANGELOG.md
  internal/admission/validation/gateway/httproute_test.go
  internal/admission/validator_test.go
  internal/controllers/configuration/kongupstreampolicy_utils_test.go
  internal/controllers/gateway/route_predicate_test.go
  internal/controllers/reference/indexer.go
  internal/dataplane/translator/translator_test.go
  internal/manager/run.go
  internal/manager/scheme/scheme.go
  internal/manager/setup.go
  internal/store/cache_stores.go
  internal/util/types_test.go
  test/helpers/k8s_meta.go
  test/mocks/events_recorder.go
Labels: size/L, backport release/3.4.x, backport feat/kic-as-library

#7108 feat: associate KIC instance with Kubernetes event via annotation
  .golangci.yaml
  internal/manager/consts/consts.go
  internal/manager/record.go
  internal/manager/run.go
  test/envtest/configerrorevent_envtest_test.go
Labels: area/feature, size/M

#7113 feat: report not only version but project name too to konnect
  internal/manager/run.go
  pkg/metadata/metadata.go
Labels: size/XS

#7097 chore: remove configmaps policy rule from leader election role
  config/rbac/leader_election_role.yaml
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
Labels: size/S, backport release/3.4.x

#7116 [Backport to release/3.4.x] fix(manager): Run AddToScheme only once in scheme.Get
  CHANGELOG.md
  internal/admission/validation/gateway/httproute_test.go
  internal/admission/validator_test.go
  internal/controllers/configuration/kongupstreampolicy_utils_test.go
  internal/controllers/gateway/route_predicate_test.go
  internal/controllers/reference/indexer.go
  internal/dataplane/translator/translator_test.go
  internal/manager/run.go
  internal/manager/scheme/scheme.go
  internal/manager/setup.go
  internal/store/cache_stores.go
  internal/util/types_test.go
  test/helpers/k8s_meta.go
  test/mocks/events_recorder.go
Labels: size/L

#7121 chore: do not run goroutines in manager.New
  internal/admission/server.go
  internal/clients/manager.go
  internal/clients/manager_test.go
  internal/controllers/configuration/kongadminapi_controller.go
  internal/konnect/node_agent.go
  internal/konnect/node_agent_test.go
  internal/manager/run.go
  internal/manager/setup.go
  test/envtest/kongadminapi_controller_envtest_test.go
Labels: size/L

#7125 chore: ensure no gouroutines leak after cancelling manager
  .golangci.yaml
  internal/admission/server.go
  internal/diagnostics/server.go
  internal/manager/consts/consts.go
  internal/manager/run.go
  internal/manager/setup.go
  test/envtest/admission_webhook_envtest_test.go
  test/envtest/manager_envtest_test.go
  test/envtest/run.go
Labels: size/L

#7135 [Backport release/3.4.x] chore(ci): harden GITHUB_TOKEN permissions (#6961)
  .github/workflows/_conformance_tests.yaml
  .github/workflows/_docker_build.yaml
  .github/workflows/_e2e_tests.yaml
  .github/workflows/_envtest_tests.yaml
  .github/workflows/_integration_tests.yaml
  .github/workflows/_kongintegration_tests.yaml
  .github/workflows/_linters.yaml
  .github/workflows/_performance_tests.yaml
  .github/workflows/_permission_check.yaml
  .github/workflows/_test_reports.yaml
  .github/workflows/_unit_tests.yaml
  .github/workflows/backport.yaml
  .github/workflows/benchmarks.yaml
  .github/workflows/check_fixed_issues_references.yaml
  .github/workflows/check_pr_labels.yaml
  .github/workflows/checks.yaml
  .github/workflows/cleanup.yaml
  .github/workflows/codeql.yaml
  .github/workflows/conformance_tests_report.yaml
  .github/workflows/e2e_nightly.yaml
  .github/workflows/e2e_targeted.yaml
  .github/workflows/e2e_trigger_via_label.yaml
  .github/workflows/license.yaml
  .github/workflows/nightly.yaml
  .github/workflows/performance_nightly.yaml
  .github/workflows/performance_targeted.yaml
  .github/workflows/performance_trigger_via_label.yaml
  .github/workflows/regenerate_on_deps_bump.yaml
  .github/workflows/release.yaml
  .github/workflows/release_docs.yaml
  .github/workflows/test_nightly.yaml
  .github/workflows/validate_kong_image.yaml
  .github/workflows/validate_kong_image_trigger_via_label.yaml
Labels: size/L

#7142 bump golang.org/x/net to 0.33.0 in release/3.4.x
  go.mod
  go.sum
Labels: size/XS

#7138 chore: update with `main` branch
  .github/test_dependencies.yaml
  .github/workflows/_docker_build.yaml
  .github/workflows/_test_reports.yaml
  .github/workflows/checks.yaml
  .github/workflows/e2e_nightly.yaml
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
  .tools_versions.yaml
  CHANGELOG.md
  Dockerfile
  Dockerfile.debug
  config/rbac/leader_election_role.yaml
  go.mod
  go.sum
  internal/admission/validation/gateway/httproute_test.go
  internal/admission/validator_test.go
  internal/controllers/configuration/kongupstreampolicy_utils_test.go
  internal/controllers/gateway/route_predicate_test.go
  internal/controllers/reference/indexer.go
  internal/dataplane/translator/translator_test.go
  internal/manager/run.go
  internal/manager/setup.go
  internal/store/cache_stores.go
  internal/util/types_test.go
  pkg/manager/scheme/scheme.go
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
  test/envtest/httproute_controller_test.go
  test/helpers/k8s_meta.go
  test/integration/tlsroute_test.go
  test/mocks/events_recorder.go
Labels: area/maintenance, size/L

#7144 fix: map `KongConsumer` to respective `KongConsumerGroup` in Konnect
  CHANGELOG.md
  internal/dataplane/kongstate/consumer.go
  internal/dataplane/kongstate/consumer_test.go
Labels: size/S, area/konnect, fix

#7146 chore(doc): update changelog for 3.4.2
  CHANGELOG.md
Labels: area/docs, size/S

#7145 chore(linter): replace deprecated `tenv` with `usetesting`
  .golangci.yaml
  test/e2e/helpers_test.go
Labels: area/ci, area/maintenance, size/S

#7177 chore(release): prepare 3.4.3 release
  CHANGELOG.md
Labels: size/XS
