Repository Kong/kubernetes-ingress-controller, pull requests merged in 2025-07, with the labels that each got.

#7520 fix(konnect): Do not mark pod ready when no konnect licenses available
  CHANGELOG.md
  internal/manager/run.go
Labels: size/M

#7573 chore(dep): update kubernetes-configuration to v1.5.1
  config/crd/incubator/kustomization.yaml
  config/crd/kustomization.yaml
  docs/api-reference.md
  go.mod
  go.sum
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
Labels: size/XS

#7575 prepare changelog for 3.5.0
  CHANGELOG.md
Labels: size/M

#7572 test(e2e): Add postStart hook to set open file limit to at least 4096
  config/base/kong-ingress-dbless.yaml
  config/variants/multi-gw/base/gateway_deployment.yaml
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
Labels: area/tests, size/S, backport release/3.4.x

#7577 chore: update kic image to 3.5
  config/image/oss/kustomization.yaml
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
Labels: size/XS

#7582 Fix(validation): Use whitelist to check HTTPRoute filters in validation webhook
  CHANGELOG.md
  internal/admission/validation/gateway/httproute.go
  internal/admission/validation/gateway/httproute_test.go
  internal/dataplane/translator/subtranslator/httproute.go
Labels: size/M

#7583 fix: fix KongUpstreamPolicy hash on translation
  CHANGELOG.md
  Makefile
  config/crd/incubator/kustomization.yaml
  config/crd/kustomization.yaml
  docs/api-reference.md
  go.mod
  go.sum
  internal/dataplane/kongstate/kongupstreampolicy.go
  internal/dataplane/kongstate/kongupstreampolicy_test.go
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
  test/envtest/crds_envtest_test.go
Labels: size/L

#7590 [backport: 3.4.x] fix: fix KongUpstreamPolicy hash on translation
  CHANGELOG.md
  Makefile
  config/crd/incubator/kustomization.yaml
  config/crd/kustomization.yaml
  go.mod
  go.sum
  internal/dataplane/kongstate/kongupstreampolicy.go
  internal/dataplane/kongstate/kongupstreampolicy_test.go
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
  test/envtest/crds_envtest_test.go
Labels: size/L

#7596 fix(ci): fix release docs workflow
  .github/workflows/release_docs.yaml
  Makefile
  docs/api-reference.md
  docs/cli-arguments.md
  scripts/apidocs-gen/post-process-for-konghq.sh
  scripts/cli-arguments-docs-gen/main.go
  scripts/cli-arguments-docs-gen/post-process-for-konghq.sh
Labels: size/XL

#7600 [backport release/3.4.x] chore(deps): bump golang from 1.24.4 to 1.24.5
  Dockerfile
  Dockerfile.debug
Labels: size/XS

#7602 chore: 3.4.8 changelog
  CHANGELOG.md
Labels: size/S

#7605 chore: fix 3.4.8 changelog
  CHANGELOG.md
Labels: size/XS

#7620 fix integration EE tests with Kong 3.11
  .github/test_dependencies.yaml
  test/kongintegration/inmemory_update_strategy_test.go
  test/kongintegration/kongupstreampolicy_test.go
Labels: size/M

#7628 chore: fix CLI args docs generation
  docs/api-reference.md
  docs/cli-arguments.md
  scripts/apidocs-gen/post-process-for-konghq.sh
  scripts/cli-arguments-docs-gen/main.go
Labels: size/L

#7648 fix(konnect): Use correct label value of secret to store license
  CHANGELOG.md
  internal/konnect/license/client.go
  internal/labels/labels.go
  test/e2e/konnect_test.go
  test/e2e/utils_test.go
Labels: size/S, backport release/3.5.x
