Repository Kong/kubernetes-ingress-controller, pull requests merged in 2025-03, with the labels that each got.

#7192 chore(logs): feature gate are logged always in the same order
  internal/manager/run.go
  pkg/manager/config/feature_gates.go
Labels: area/maintenance, size/S

#7191 chore(deps): bump kcfg to v1.2.0-rc.1
  .golangci.yaml
  config/crd/incubator/kustomization.yaml
  config/crd/kustomization.yaml
  go.mod
  go.sum
  internal/controllers/utils/control_plane_reference.go
  internal/controllers/utils/control_plane_reference_test.go
  test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
  test/e2e/manifests/all-in-one-dbless-konnect.yaml
  test/e2e/manifests/all-in-one-dbless.yaml
  test/e2e/manifests/all-in-one-postgres-enterprise.yaml
  test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
  test/e2e/manifests/all-in-one-postgres.yaml
  test/envtest/control_plane_reference_test.go
Labels: size/M

#7198 chore: make multimanager implement Runnable interface
  pkg/manager/multiinstance/manager.go
  pkg/manager/multiinstance/manager_test.go
  test/envtest/multiinstance_manager_diagnostics_test.go
Labels: size/S

#7185 chore(tests): migrate TestTLSRouteExample to isolated
  examples/gateway-tlsroute.yaml
  test/integration/examples_test.go
  test/integration/isolated/assertion_helpers.go
  test/integration/isolated/examples_tlsroute_test.go
  test/integration/tcpingress_test.go
  test/integration/tlsroute_test.go
  test/internal/testlabels/labels.go
  test/tcp_utils.go
Labels: area/tests, area/maintenance, size/L

#7199 fix: respect Admin API init retry options
  internal/manager/setup.go
Labels: size/S

#7227 test(helpers): remove cleanup of roles after deleting Konnect CPs
  test/internal/helpers/konnect/control_plane.go
Labels: size/M

#7226 fix(admission): ignore unsupported credential types in validating secrets
  CHANGELOG.md
  internal/admission/handler.go
  internal/admission/handler_test.go
  internal/admission/validation/consumers/credentials/validation.go
  internal/admission/validation/consumers/credentials/validation_test.go
  internal/admission/validation/consumers/credentials/vars.go
  internal/controllers/configuration/secret_controller.go
  test/envtest/admission_webhook_envtest_test.go
Labels: size/L

#7147 fix(translator): Only log error for duplicate SNI when the certificate ID are not the same
  internal/dataplane/translator/translate_certs.go
Labels: size/XS

#7236 fix: fix the wrong error return value
  internal/controllers/reference/reference.go
Labels: area/maintenance, size/XS, fix

#7237 fix: GatewayReconciler will fall into a loop and cannot converge to stable state
  CHANGELOG.md
  internal/controllers/gateway/gateway_controller.go
  internal/controllers/gateway/gateway_utils.go
  internal/controllers/gateway/gateway_utils_test.go
Labels: size/L, fix

#7233 fix(kong_client): Do not check Kong gateway status by /status endpoint if workspace is given
  CHANGELOG.md
  internal/adminapi/kong.go
  test/mocks/admin_api_handler.go
Labels: size/M, backport release/2.12.x

#7283 Do not check Kong gateway status by /status endpoint if workspace is given (#7233)
  internal/adminapi/kong.go
  internal/adminapi/kong_test.go
  test/mocks/admin_api_handler.go
Labels: size/M
